projgeomcpp: SomeClass Class Reference
SomeClass Class Reference
SomeClass description.
#include <SomeClass.h>
Public Member Functions
SomeClass ()
Creates empty SomeClass.
~SomeClass ()
void set (int x)
Sets the value.
int get ()
get the value
Public Member Functions inherited from BaseClass
BaseClass ()
~BaseClass ()
void freePtr ()
Public Attributes
Data * mParent
Public Attributes inherited from BaseClass
int * mPointer
Private Attributes
int mVal {0}
Stores the value.
std::vector< Data > mData
std::vector< std::string > mStrings
Detailed Description
SomeClass description.
This is a test class ment to show how to create, build, use and document classes from other files.
Warning
beware, this is how warning looks like.
Definition at line 51 of file SomeClass.h.
Constructor & Destructor Documentation
SomeClass()
SomeClass::SomeClass ()
Creates empty SomeClass.
Definition at line 4 of file SomeClass.cpp.
~SomeClass()
SomeClass::~SomeClass ()
Definition at line 6 of file SomeClass.cpp.
Member Function Documentation
get()
int SomeClass::get ()
get the value
Returns
current value
Definition at line 13 of file SomeClass.cpp.
References get(), mVal, set(), and TEST_CASE().
Referenced by get(), and main().
set()
void SomeClass::set (int x)
Sets the value.
Parameters
x input value
Definition at line 8 of file SomeClass.cpp.
References mVal.
Referenced by get(), and main().
Member Data Documentation
mData
std::vector<Data> SomeClass::mData private
Definition at line 54 of file SomeClass.h.
mParent
Data* SomeClass::mParent
Definition at line 61 of file SomeClass.h.
mStrings
std::vector<std::string> SomeClass::mStrings private
Definition at line 55 of file SomeClass.h.
mVal
int SomeClass::mVal {0} private
Stores the value.
Definition at line 53 of file SomeClass.h.
Referenced by get(), and set().
The documentation for this class was generated from the following files:
source/SomeClass.h
source/SomeClass.cpp