projgeomcpp: source/unittest/test_ck_plane.cpp File Reference
test_ck_plane.cpp File Reference
#include <boost/multiprecision/cpp_int.hpp>
#include <catch.hpp>
#include <iostream>
#include "pgcpp/ck_plane.hpp"
#include "pgcpp/persp_plane.hpp"
#include "pgcpp/pg_common.hpp"
#include "pgcpp/pg_line.hpp"
#include "pgcpp/pg_point.hpp"
Classes
struct myck< P, L >
Functions
auto ApproxEqual (const auto &a, const auto &b) -> bool
template<typename PG >
void chk_ck (const PG &myck)
chk_ck (myck< pg_point< cpp_int >>())
chk_ck (myck< pg_line< cpp_int >>())
chk_ck (ellck< pg_point< cpp_int >>())
chk_ck (ellck< pg_line< cpp_int >>())
chk_ck (hyck< pg_point< cpp_int >>())
chk_ck (hyck< pg_line< cpp_int >>())
chk_ck (P)
chk_ck (myck< pg_line< double >>())
chk_ck (ellck< pg_point< float >>())
chk_ck (ellck< pg_line< float >>())
chk_ck (hyck< pg_point< double >>())
chk_ck (hyck< pg_line< double >>())
Variables
static auto Zero = Approx(0).margin(0.01)
auto Ire = pg_point<cpp_int>{0, 1, 1}
auto Iim = pg_point<cpp_int>{1, 0, 0}
auto l_inf = pg_line<cpp_int>{0, -1, 1}
auto P = persp_euclid_plane{std::move(Ire), std::move(Iim), std::move(l_inf)}
Function Documentation
ApproxEqual()
auto ApproxEqual (const auto & a, const auto & b) -> bool inline
Parameters
a
b
Returns
true
false
Definition at line 25 of file test_ck_plane.cpp.
References Zero.
Referenced by chk_ck().
chk_ck() [1/13]
template<typename PG > void chk_ck (const PG & myck)
Definition at line 31 of file test_ck_plane.cpp.
References a1, a2, a3, ApproxEqual(), CHECK(), fun::check_sine_law(), fun::coincident(), fun::cross(), fun::tri_dual(), triangle, and Zero.
Referenced by myck< P, L >::measure().
chk_ck() [2/13]
chk_ck (myck< pg_point< cpp_int >> ())
chk_ck() [3/13]
chk_ck (myck< pg_line< cpp_int >> ())
chk_ck() [4/13]
chk_ck (ellck< pg_point< cpp_int >> ())
chk_ck() [5/13]
chk_ck (ellck< pg_line< cpp_int >> ())
chk_ck() [6/13]
chk_ck (hyck< pg_point< cpp_int >> ())
chk_ck() [7/13]
chk_ck (hyck< pg_line< cpp_int >> ())
chk_ck() [8/13]
chk_ck (P)
chk_ck() [9/13]
chk_ck (myck< pg_line< double >> ())
chk_ck() [10/13]
chk_ck (ellck< pg_point< float >> ())
chk_ck() [11/13]
chk_ck (ellck< pg_line< float >> ())
chk_ck() [12/13]
chk_ck (hyck< pg_point< double >> ())
chk_ck() [13/13]
chk_ck (hyck< pg_line< double >> ())
Variable Documentation
Iim
auto Iim = pg_point<cpp_int>{1, 0, 0}
Definition at line 124 of file test_ck_plane.cpp.
Referenced by fun::persp_euclid_plane< P, L >::persp_euclid_plane().
Ire
auto Ire = pg_point<cpp_int>{0, 1, 1}
Definition at line 123 of file test_ck_plane.cpp.
Referenced by fun::persp_euclid_plane< P, L >::persp_euclid_plane().
l_inf
auto l_inf = pg_line<cpp_int>{0, -1, 1}
Definition at line 125 of file test_ck_plane.cpp.
P
auto P = persp_euclid_plane{std::move(Ire), std::move(Iim), std::move(l_inf)}
Definition at line 127 of file test_ck_plane.cpp.
Referenced by myck< P, L >::perp().
Zero
auto Zero = Approx(0).margin(0.01) static
Definition at line 15 of file test_ck_plane.cpp.
Referenced by ApproxEqual(), and chk_ck().