projgeomcpp: source/unittest/test_proj_plane.cpp File Reference
test_proj_plane.cpp File Reference
#include <catch.hpp>
#include <complex>
#include <iostream>
#include "pgcpp/pg_line.hpp"
#include "pgcpp/pg_point.hpp"
#include "pgcpp/proj_plane.hpp"
Functions
TEST_CASE ("Projective Point", "[proj_plane]")
TEST_CASE ("Projective Line", "[proj_plane]")
CHECK (l_nan==l_nan)
CHECK (p_nan==l *l)
CHECK (incident(l_nan, p))
CHECK (incident(p_nan, l))
CHECK (incident(p_nan, l_nan))
Variables
auto l = pg_line{-2, 3, 1}
auto l_nan = pg_line{0, 0, 0}
auto p_nan = pg_point{0, 0, 0}
Function Documentation
CHECK() [1/5]
CHECK (l_nan = =l_nan)
Referenced by chk_ck(), chk_cyclic(), chk_degenerate(), chk_euclid(), chk_tri(), and TEST_CASE().
CHECK() [2/5]
CHECK (p_nan = =l *l)
CHECK() [3/5]
CHECK (incident(l_nan, p))
CHECK() [4/5]
CHECK (incident(p_nan, l))
CHECK() [5/5]
CHECK (incident(p_nan, l_nan))
TEST_CASE() [1/2]
TEST_CASE ("Projective Point" , "" [proj_plane])
Definition at line 13 of file test_proj_plane.cpp.
References CHECK(), l, and fun::plucker().
Referenced by TEST_CASE().
TEST_CASE() [2/2]
TEST_CASE ("Projective Line" , "" [proj_plane])
Definition at line 40 of file test_proj_plane.cpp.
References CHECK(), l, fun::plucker(), and TEST_CASE().
Variable Documentation
l
auto l = pg_line{-2, 3, 1}
Definition at line 68 of file test_proj_plane.cpp.
Referenced by fun::ck< P, L, myck >::altitude(), fun::fB(), fun::is_parallel(), fun::persp_euclid_plane< P, L >::is_parallel(), fun::is_perpendicular(), fun::ck< P, L, myck >::is_perpendicular(), and TEST_CASE().
l_nan
auto l_nan = pg_line{0, 0, 0}
Definition at line 70 of file test_proj_plane.cpp.
p_nan
auto p_nan = pg_point{0, 0, 0}
Definition at line 71 of file test_proj_plane.cpp.