projgeomcpp: source/unittest/test_ell_plane.cpp File Reference
test_ell_plane.cpp File Reference
#include <boost/multiprecision/cpp_int.hpp>
#include <catch.hpp>
#include <iostream>
#include "pgcpp/ck_plane.hpp"
#include "pgcpp/pg_line.hpp"
#include "pgcpp/pg_point.hpp"
Functions
auto ApproxEqual (const auto &a, const auto &b) -> bool
template<typename PG >
void chk_tri (const PG &myck)
TEST_CASE ("Elliptic/Hyperbolic plane", "[ell_plane]")
chk_tri (ellck< pg_line< double >>())
chk_tri (hyck< pg_point< double >>())
chk_tri (hyck< pg_line< double >>())
Variables
static auto Zero = Approx(0).margin(0.01)
Function Documentation
ApproxEqual()
auto ApproxEqual (const auto & a, const auto & b) -> bool inline
Parameters
a
b
Returns
true
false
Definition at line 23 of file test_ell_plane.cpp.
References Zero.
Referenced by chk_tri().
chk_tri() [1/4]
template<typename PG > void chk_tri (const PG & myck)
Template Parameters
PG
Parameters
myck
Definition at line 35 of file test_ell_plane.cpp.
References a1, a2, a3, ApproxEqual(), CHECK(), fun::check_cross_law(), fun::check_cross_TQF(), fun::cross(), fun::plucker(), fun::tri_dual(), triangle, and Zero.
Referenced by TEST_CASE().
chk_tri() [2/4]
chk_tri (ellck< pg_line< double >> ())
chk_tri() [3/4]
chk_tri (hyck< pg_point< double >> ())
chk_tri() [4/4]
chk_tri (hyck< pg_line< double >> ())
TEST_CASE()
TEST_CASE ("Elliptic/Hyperbolic plane" , "" [ell_plane])
Definition at line 80 of file test_ell_plane.cpp.
References chk_tri().
Referenced by chk_cyclic(), chk_degenerate(), SomeClass::get(), and myck< P, L >::measure().
Variable Documentation
Zero
auto Zero = Approx(0).margin(0.01) static
Definition at line 13 of file test_ell_plane.cpp.
Referenced by ApproxEqual(), and chk_tri().