CkPttnCpp: itertest::SolidInt Class Reference
itertest::SolidInt Class Reference
#include <helpers.hpp>
Public Member Functions
constexpr SolidInt (int n)
constexpr int getint () const
SolidInt ()=delete
SolidInt (const SolidInt &)=delete
SolidInt & operator= (const SolidInt &)=delete
SolidInt & operator= (SolidInt &&)=delete
SolidInt (SolidInt &&)=delete
Private Attributes
const int i
Detailed Description
Definition at line 16 of file helpers.hpp.
Constructor & Destructor Documentation
SolidInt() [1/4]
constexpr itertest::SolidInt::SolidInt (int n) inline
Definition at line 21 of file helpers.hpp.
SolidInt() [2/4]
itertest::SolidInt::SolidInt () delete
Referenced by getint().
SolidInt() [3/4]
itertest::SolidInt::SolidInt (const SolidInt &) delete
SolidInt() [4/4]
itertest::SolidInt::SolidInt (SolidInt &&) delete
Member Function Documentation
getint()
constexpr int itertest::SolidInt::getint () const inline
Definition at line 23 of file helpers.hpp.
References i, operator=(), and SolidInt().
Referenced by itertest::operator<(), and TEST_CASE().
operator=() [1/2]
SolidInt& itertest::SolidInt::operator= (const SolidInt &) delete
Referenced by itertest::BasicIterable< T >::BasicIterable(), and getint().
operator=() [2/2]
SolidInt& itertest::SolidInt::operator= (SolidInt &&) delete
Member Data Documentation
i
const int itertest::SolidInt::i private
Definition at line 18 of file helpers.hpp.
Referenced by itertest::BasicIterable< T >::BasicIterable(), and getint().
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/helpers.hpp