CkPttnCpp: iter::impl::DerefHolder< T > Class Template Reference
iter::impl::DerefHolder< T > Class Template Reference
#include <iterbase.hpp>
Public Types
using reference = TPlain &
using pointer = TPlain *
Public Member Functions
DerefHolder ()=default
reference get ()
pointer get_ptr ()
void reset (T &&item)
operator bool () const
Private Types
using TPlain = std::remove_reference_t< T >
Private Attributes
std::optional< TPlain > item_p
Detailed Description
template<typename T>
class iter::impl::DerefHolder< T >
Definition at line 272 of file iterbase.hpp.
Member Typedef Documentation
pointer
template<typename T> using iter::impl::DerefHolder< T >::pointer = TPlain*
Definition at line 283 of file iterbase.hpp.
reference
template<typename T> using iter::impl::DerefHolder< T >::reference = TPlain&
Definition at line 282 of file iterbase.hpp.
TPlain
template<typename T> using iter::impl::DerefHolder< T >::TPlain = std::remove_reference_t<T> private
Definition at line 277 of file iterbase.hpp.
Constructor & Destructor Documentation
DerefHolder()
template<typename T> iter::impl::DerefHolder< T >::DerefHolder () default
Member Function Documentation
get()
template<typename T> reference iter::impl::DerefHolder< T >::get () inline
Definition at line 287 of file iterbase.hpp.
Referenced by iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::check_current(), iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::get(), iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::next_key(), iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::operator*(), iter::impl::Dropper< FilterFunc, Container >::Iterator< ContainerT >::operator*(), iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT >::operator*(), iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::set_key_group_pair(), iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT >::skip_failures(), iter::impl::Dropper< FilterFunc, Container >::Iterator< ContainerT >::skip_passes(), TEST_CASE(), and iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::update_sub_iterable().
get_ptr()
template<typename T> pointer iter::impl::DerefHolder< T >::get_ptr () inline
Definition at line 291 of file iterbase.hpp.
Referenced by iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::get_ptr(), iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::operator->(), iter::impl::Dropper< FilterFunc, Container >::Iterator< ContainerT >::operator->(), iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT >::operator->(), and TEST_CASE().
operator bool()
template<typename T> iter::impl::DerefHolder< T >::operator bool () const inline explicit
Definition at line 299 of file iterbase.hpp.
reset()
template<typename T> void iter::impl::DerefHolder< T >::reset (T && item) inline
Definition at line 295 of file iterbase.hpp.
Referenced by iter::impl::Dropper< FilterFunc, Container >::Iterator< ContainerT >::inc_sub_iter(), iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::inc_sub_iter(), iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT >::inc_sub_iter(), iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::increment_iterator(), iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::Iterator(), iter::impl::Dropper< FilterFunc, Container >::Iterator< ContainerT >::Iterator(), iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::Iterator(), iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT >::Iterator(), TEST_CASE(), and iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::update_sub_iterable().
Member Data Documentation
item_p
template<typename T> std::optional<TPlain> iter::impl::DerefHolder< T >::item_p private
Definition at line 279 of file iterbase.hpp.
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/internal/iterbase.hpp