CkPttnCpp: iter::impl::IterIterWrapper< Container > Class Template Reference
iter::impl::IterIterWrapper< Container > Class Template Reference
#include <iteratoriterator.hpp>
Classes
struct ConstAtTypeOrVoid
struct ConstAtTypeOrVoid< U, std::void_t< decltype(*std::declval< const U & >().at(0))> >
struct ConstIndexTypeOrVoid
struct ConstIndexTypeOrVoid< U, std::void_t< decltype(*std::declval< const U & >()[0])> >
Public Member Functions
IterIterWrapper ()=default
IterIterWrapper (size_type sz)
IterIterWrapper (size_type sz, const contained_iter &val)
auto at (size_type pos) -> decltype(*container.at(pos))
auto at (size_type pos) const -> const_at_type_or_void_t
auto operator[] (size_type pos) noexcept(noexcept(*container[pos])) -> decltype(*container[pos])
auto operator[] (size_type pos) const noexcept(noexcept(*container[pos])) -> const_index_type_or_void_t
bool empty () const noexcept
size_type size () const noexcept
iterator begin () noexcept
iterator end () noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
reverse_iterator rbegin () noexcept
reverse_iterator rend () noexcept
const_reverse_iterator rbegin () const noexcept
const_reverse_iterator rend () const noexcept
const_reverse_iterator crbegin () const noexcept
const_reverse_iterator crend () const noexcept
Container & get () noexcept
const Container & get () const noexcept
Private Types
using contained_iter = typename Container::value_type
using size_type = typename Container::size_type
using iterator = IteratorIterator< typename Container::iterator >
using const_iterator = IteratorIterator< typename Container::const_iterator >
using reverse_iterator = IteratorIterator< typename Container::reverse_iterator >
using const_reverse_iterator = IteratorIterator< typename Container::const_reverse_iterator >
using const_at_type_or_void_t = typename ConstAtTypeOrVoid<>::type
using const_index_type_or_void_t = typename ConstIndexTypeOrVoid<>::type
Private Attributes
Container container
Detailed Description
template<typename Container>
class iter::impl::IterIterWrapper< Container >
Definition at line 144 of file iteratoriterator.hpp.
Member Typedef Documentation
const_at_type_or_void_t
template<typename Container> using iter::impl::IterIterWrapper< Container >::const_at_type_or_void_t = typename ConstAtTypeOrVoid<>::type private
Definition at line 166 of file iteratoriterator.hpp.
const_index_type_or_void_t
template<typename Container> using iter::impl::IterIterWrapper< Container >::const_index_type_or_void_t = typename ConstIndexTypeOrVoid<>::type private
Definition at line 176 of file iteratoriterator.hpp.
const_iterator
template<typename Container> using iter::impl::IterIterWrapper< Container >::const_iterator = IteratorIterator<typename Container::const_iterator> private
Definition at line 152 of file iteratoriterator.hpp.
const_reverse_iterator
template<typename Container> using iter::impl::IterIterWrapper< Container >::const_reverse_iterator = IteratorIterator<typename Container::const_reverse_iterator> private
Definition at line 156 of file iteratoriterator.hpp.
contained_iter
template<typename Container> using iter::impl::IterIterWrapper< Container >::contained_iter = typename Container::value_type private
Definition at line 148 of file iteratoriterator.hpp.
iterator
template<typename Container> using iter::impl::IterIterWrapper< Container >::iterator = IteratorIterator<typename Container::iterator> private
Definition at line 150 of file iteratoriterator.hpp.
reverse_iterator
template<typename Container> using iter::impl::IterIterWrapper< Container >::reverse_iterator = IteratorIterator<typename Container::reverse_iterator> private
Definition at line 154 of file iteratoriterator.hpp.
size_type
template<typename Container> using iter::impl::IterIterWrapper< Container >::size_type = typename Container::size_type private
Definition at line 149 of file iteratoriterator.hpp.
Constructor & Destructor Documentation
IterIterWrapper() [1/3]
template<typename Container> iter::impl::IterIterWrapper< Container >::IterIterWrapper () default
IterIterWrapper() [2/3]
template<typename Container> iter::impl::IterIterWrapper< Container >::IterIterWrapper (size_type sz) inline explicit
Definition at line 181 of file iteratoriterator.hpp.
IterIterWrapper() [3/3]
template<typename Container> iter::impl::IterIterWrapper< Container >::IterIterWrapper (size_type sz, const contained_iter & val) inline
Definition at line 183 of file iteratoriterator.hpp.
Member Function Documentation
at() [1/2]
template<typename Container> auto iter::impl::IterIterWrapper< Container >::at (size_type pos) -> decltype(*container.at(pos)) inline
Definition at line 186 of file iteratoriterator.hpp.
at() [2/2]
template<typename Container> auto iter::impl::IterIterWrapper< Container >::at (size_type pos) const -> const_at_type_or_void_t inline
Definition at line 190 of file iteratoriterator.hpp.
begin() [1/2]
template<typename Container> iterator iter::impl::IterIterWrapper< Container >::begin () inline noexcept
Definition at line 212 of file iteratoriterator.hpp.
Referenced by iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< Container >::begin(), iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >::begin(), and TEST_CASE().
begin() [2/2]
template<typename Container> const_iterator iter::impl::IterIterWrapper< Container >::begin () const inline noexcept
Definition at line 220 of file iteratoriterator.hpp.
cbegin()
template<typename Container> const_iterator iter::impl::IterIterWrapper< Container >::cbegin () const inline noexcept
Definition at line 228 of file iteratoriterator.hpp.
cend()
template<typename Container> const_iterator iter::impl::IterIterWrapper< Container >::cend () const inline noexcept
Definition at line 232 of file iteratoriterator.hpp.
crbegin()
template<typename Container> const_reverse_iterator iter::impl::IterIterWrapper< Container >::crbegin () const inline noexcept
Definition at line 252 of file iteratoriterator.hpp.
crend()
template<typename Container> const_reverse_iterator iter::impl::IterIterWrapper< Container >::crend () const inline noexcept
Definition at line 256 of file iteratoriterator.hpp.
empty()
template<typename Container> bool iter::impl::IterIterWrapper< Container >::empty () const inline noexcept
Definition at line 204 of file iteratoriterator.hpp.
Referenced by iter::impl::Chunker< Container >::Iterator< ContainerT >::done(), iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >::populate_const_sorted_iters(), and iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >::populate_sorted_iters().
end() [1/2]
template<typename Container> iterator iter::impl::IterIterWrapper< Container >::end () inline noexcept
Definition at line 216 of file iteratoriterator.hpp.
Referenced by iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< Container >::end(), and iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >::end().
end() [2/2]
template<typename Container> const_iterator iter::impl::IterIterWrapper< Container >::end () const inline noexcept
Definition at line 224 of file iteratoriterator.hpp.
get() [1/2]
template<typename Container> Container& iter::impl::IterIterWrapper< Container >::get () inline noexcept
Definition at line 263 of file iteratoriterator.hpp.
Referenced by iter::impl::WindowSlider< Container >::Iterator< ContainerT >::Iterator(), iter::impl::Combinator< Container >::Iterator< ContainerT >::Iterator(), iter::impl::Permuter< Container >::Iterator< ContainerT >::Iterator(), iter::impl::Chunker< Container >::Iterator< ContainerT >::Iterator(), iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::operator++(), iter::impl::Permuter< Container >::Iterator< ContainerT >::operator++(), iter::impl::Combinator< Container >::Iterator< ContainerT >::operator++(), iter::impl::WindowSlider< Container >::Iterator< ContainerT >::operator++(), iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >::populate_const_sorted_iters(), iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >::populate_sorted_iters(), iter::impl::Chunker< Container >::Iterator< ContainerT >::refill_chunk(), iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< Container >::SortedItersHolder(), and TEST_CASE().
get() [2/2]
template<typename Container> const Container& iter::impl::IterIterWrapper< Container >::get () const inline noexcept
Definition at line 267 of file iteratoriterator.hpp.
operator[]() [1/2]
template<typename Container> auto iter::impl::IterIterWrapper< Container >::operator[] (size_type pos) -> decltype(*container[pos]) inline noexcept
Definition at line 194 of file iteratoriterator.hpp.
operator[]() [2/2]
template<typename Container> auto iter::impl::IterIterWrapper< Container >::operator[] (size_type pos) const -> const_index_type_or_void_t inline noexcept
Definition at line 199 of file iteratoriterator.hpp.
rbegin() [1/2]
template<typename Container> reverse_iterator iter::impl::IterIterWrapper< Container >::rbegin () inline noexcept
Definition at line 236 of file iteratoriterator.hpp.
Referenced by TEST_CASE().
rbegin() [2/2]
template<typename Container> const_reverse_iterator iter::impl::IterIterWrapper< Container >::rbegin () const inline noexcept
Definition at line 244 of file iteratoriterator.hpp.
rend() [1/2]
template<typename Container> reverse_iterator iter::impl::IterIterWrapper< Container >::rend () inline noexcept
Definition at line 240 of file iteratoriterator.hpp.
Referenced by TEST_CASE().
rend() [2/2]
template<typename Container> const_reverse_iterator iter::impl::IterIterWrapper< Container >::rend () const inline noexcept
Definition at line 248 of file iteratoriterator.hpp.
size()
template<typename Container> size_type iter::impl::IterIterWrapper< Container >::size () const inline noexcept
Definition at line 208 of file iteratoriterator.hpp.
Member Data Documentation
container
template<typename Container> Container iter::impl::IterIterWrapper< Container >::container private
Definition at line 146 of file iteratoriterator.hpp.
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/internal/iteratoriterator.hpp