CkPttnCpp: iter::impl::Permuter< Container > Class Template Reference
iter::impl::Permuter< Container > Class Template Reference
#include <permutations.hpp>
Classes
class Iterator
Public Member Functions
Permuter (Permuter &&)=default
Iterator< Container > begin ()
Iterator< Container > end ()
Iterator< AsConst< Container > > begin () const
Iterator< AsConst< Container > > end () const
Private Types
template<typename T >
using IndexVector = std::vector< IteratorWrapper< T > >
template<typename T >
using Permutable = IterIterWrapper< IndexVector< T > >
Private Member Functions
Permuter (Container &&container)
Private Attributes
friend PermutationsFn
Container container_
Detailed Description
template<typename Container>
class iter::impl::Permuter< Container >
Definition at line 17 of file permutations.hpp.
Member Typedef Documentation
IndexVector
template<typename Container > template<typename T > using iter::impl::Permuter< Container >::IndexVector = std::vector<IteratorWrapper<T> > private
Definition at line 30 of file permutations.hpp.
Permutable
template<typename Container > template<typename T > using iter::impl::Permuter< Container >::Permutable = IterIterWrapper<IndexVector<T> > private
Definition at line 32 of file permutations.hpp.
Constructor & Destructor Documentation
Permuter() [1/2]
template<typename Container > iter::impl::Permuter< Container >::Permuter (Container && container) inline private
Definition at line 34 of file permutations.hpp.
Permuter() [2/2]
template<typename Container > iter::impl::Permuter< Container >::Permuter (Permuter< Container > &&) default
Member Function Documentation
begin() [1/2]
template<typename Container > Iterator<Container> iter::impl::Permuter< Container >::begin () inline
Definition at line 109 of file permutations.hpp.
References iter::impl::get_iters::get_begin(), and iter::impl::get_iters::get_end().
begin() [2/2]
template<typename Container > Iterator<AsConst<Container> > iter::impl::Permuter< Container >::begin () const inline
Definition at line 117 of file permutations.hpp.
References iter::impl::get_iters::get_begin(), and iter::impl::get_iters::get_end().
end() [1/2]
template<typename Container > Iterator<Container> iter::impl::Permuter< Container >::end () inline
Definition at line 113 of file permutations.hpp.
References iter::impl::get_iters::get_end().
end() [2/2]
template<typename Container > Iterator<AsConst<Container> > iter::impl::Permuter< Container >::end () const inline
Definition at line 122 of file permutations.hpp.
References iter::impl::get_iters::get_end().
Member Data Documentation
container_
template<typename Container > Container iter::impl::Permuter< Container >::container_ private
Definition at line 27 of file permutations.hpp.
PermutationsFn
template<typename Container > friend iter::impl::Permuter< Container >::PermutationsFn private
Definition at line 26 of file permutations.hpp.
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/permutations.hpp