CkPttnCpp: iter::impl::Chunker< Container >::Iterator< ContainerT > Class Template Reference
iter::impl::Chunker< Container >::Iterator< ContainerT > Class Template Reference
#include <chunked.hpp>
Public Types
using iterator_category = std::input_iterator_tag
using value_type = DerefVec< ContainerT >
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
Public Member Functions
Iterator (IteratorWrapper< ContainerT > &&sub_iter, IteratorWrapper< ContainerT > &&sub_end, std::size_t s)
Iterator & operator++ ()
Iterator operator++ (int)
template<typename T >
bool operator!= (const Iterator< T > &other) const
template<typename T >
bool operator== (const Iterator< T > &other) const
DerefVec< ContainerT > & operator* ()
DerefVec< ContainerT > * operator-> ()
Private Member Functions
bool done () const
void refill_chunk ()
Private Attributes
IteratorWrapper< ContainerT > sub_iter_
IteratorWrapper< ContainerT > sub_end_
DerefVec< ContainerT > chunk_
std::size_t chunk_size_ = 0
Friends
template<typename >
class Iterator
Detailed Description
template<typename Container>
template<typename ContainerT>
class iter::impl::Chunker< Container >::Iterator< ContainerT >
Definition at line 44 of file chunked.hpp.
Member Typedef Documentation
difference_type
template<typename Container > template<typename ContainerT> using iter::impl::Chunker< Container >::Iterator< ContainerT >::difference_type = std::ptrdiff_t
Definition at line 70 of file chunked.hpp.
iterator_category
template<typename Container > template<typename ContainerT> using iter::impl::Chunker< Container >::Iterator< ContainerT >::iterator_category = std::input_iterator_tag
Definition at line 68 of file chunked.hpp.
pointer
template<typename Container > template<typename ContainerT> using iter::impl::Chunker< Container >::Iterator< ContainerT >::pointer = value_type*
Definition at line 71 of file chunked.hpp.
reference
template<typename Container > template<typename ContainerT> using iter::impl::Chunker< Container >::Iterator< ContainerT >::reference = value_type&
Definition at line 72 of file chunked.hpp.
value_type
template<typename Container > template<typename ContainerT> using iter::impl::Chunker< Container >::Iterator< ContainerT >::value_type = DerefVec<ContainerT>
Definition at line 69 of file chunked.hpp.
Constructor & Destructor Documentation
Iterator()
template<typename Container > template<typename ContainerT> iter::impl::Chunker< Container >::Iterator< ContainerT >::Iterator (IteratorWrapper< ContainerT > && sub_iter, IteratorWrapper< ContainerT > && sub_end, std::size_t s) inline
Definition at line 74 of file chunked.hpp.
References iter::impl::IterIterWrapper< Container >::get(), and iter::impl::Chunker< Container >::Iterator< ContainerT >::refill_chunk().
Member Function Documentation
done()
template<typename Container > template<typename ContainerT> bool iter::impl::Chunker< Container >::Iterator< ContainerT >::done () const inline private
Definition at line 53 of file chunked.hpp.
References iter::impl::IterIterWrapper< Container >::empty().
Referenced by iter::impl::Chunker< Container >::Iterator< ContainerT >::operator==().
operator!=()
template<typename Container > template<typename ContainerT> template<typename T > bool iter::impl::Chunker< Container >::Iterator< ContainerT >::operator!= (const Iterator< T > & other) const inline
Definition at line 95 of file chunked.hpp.
operator*()
template<typename Container > template<typename ContainerT> DerefVec<ContainerT>& iter::impl::Chunker< Container >::Iterator< ContainerT >::operator* () inline
Definition at line 105 of file chunked.hpp.
References iter::impl::Chunker< Container >::Iterator< ContainerT >::chunk_.
operator++() [1/2]
template<typename Container > template<typename ContainerT> Iterator& iter::impl::Chunker< Container >::Iterator< ContainerT >::operator++ () inline
Definition at line 83 of file chunked.hpp.
References iter::impl::Chunker< Container >::Iterator< ContainerT >::refill_chunk().
operator++() [2/2]
template<typename Container > template<typename ContainerT> Iterator iter::impl::Chunker< Container >::Iterator< ContainerT >::operator++ (int) inline
Definition at line 88 of file chunked.hpp.
operator->()
template<typename Container > template<typename ContainerT> DerefVec<ContainerT>* iter::impl::Chunker< Container >::Iterator< ContainerT >::operator-> () inline
Definition at line 109 of file chunked.hpp.
References iter::impl::Chunker< Container >::Iterator< ContainerT >::chunk_.
operator==()
template<typename Container > template<typename ContainerT> template<typename T > bool iter::impl::Chunker< Container >::Iterator< ContainerT >::operator== (const Iterator< T > & other) const inline
Definition at line 100 of file chunked.hpp.
References iter::impl::Chunker< Container >::Iterator< ContainerT >::done(), and iter::impl::Chunker< Container >::Iterator< ContainerT >::sub_iter_.
refill_chunk()
template<typename Container > template<typename ContainerT> void iter::impl::Chunker< Container >::Iterator< ContainerT >::refill_chunk () inline private
Definition at line 57 of file chunked.hpp.
References iter::impl::IterIterWrapper< Container >::get(), i, and iter::impl::Chunker< Container >::Iterator< ContainerT >::sub_iter_.
Referenced by iter::impl::Chunker< Container >::Iterator< ContainerT >::Iterator(), and iter::impl::Chunker< Container >::Iterator< ContainerT >::operator++().
Friends And Related Function Documentation
Iterator
template<typename Container > template<typename ContainerT> template<typename > friend class Iterator friend
Definition at line 47 of file chunked.hpp.
Member Data Documentation
chunk_
template<typename Container > template<typename ContainerT> DerefVec<ContainerT> iter::impl::Chunker< Container >::Iterator< ContainerT >::chunk_ private
Definition at line 50 of file chunked.hpp.
Referenced by iter::impl::Chunker< Container >::Iterator< ContainerT >::operator*(), and iter::impl::Chunker< Container >::Iterator< ContainerT >::operator->().
chunk_size_
template<typename Container > template<typename ContainerT> std::size_t iter::impl::Chunker< Container >::Iterator< ContainerT >::chunk_size_ = 0 private
Definition at line 51 of file chunked.hpp.
sub_end_
template<typename Container > template<typename ContainerT> IteratorWrapper<ContainerT> iter::impl::Chunker< Container >::Iterator< ContainerT >::sub_end_ private
Definition at line 49 of file chunked.hpp.
sub_iter_
template<typename Container > template<typename ContainerT> IteratorWrapper<ContainerT> iter::impl::Chunker< Container >::Iterator< ContainerT >::sub_iter_ private
Definition at line 48 of file chunked.hpp.
Referenced by iter::impl::Chunker< Container >::Iterator< ContainerT >::operator==(), and iter::impl::Chunker< Container >::Iterator< ContainerT >::refill_chunk().
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/chunked.hpp