CkPttnCpp: iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT > Class Template Reference
iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT > Class Template Reference
#include <compress.hpp>
Public Types
using iterator_category = std::input_iterator_tag
using value_type = iterator_traits_deref< ContainerT >
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
Public Member Functions
Iterator (IteratorWrapper< ContainerT > &&cont_iter, IteratorWrapper< ContainerT > &&cont_end, IteratorWrapper< SelectorT > &&sel_iter, IteratorWrapper< SelectorT > &&sel_end)
iterator_deref< ContainerT > operator* ()
iterator_arrow< ContainerT > operator-> ()
Iterator & operator++ ()
Iterator operator++ (int)
template<typename T , typename U >
bool operator!= (const Iterator< T, U > &other) const
template<typename T , typename U >
bool operator== (const Iterator< T, U > &other) const
Private Member Functions
void increment_iterators ()
void skip_failures ()
Private Attributes
IteratorWrapper< ContainerT > sub_iter_
IteratorWrapper< ContainerT > sub_end_
IteratorWrapper< SelectorT > selector_iter_
IteratorWrapper< SelectorT > selector_end_
Friends
template<typename , typename >
class Iterator
Detailed Description
template<typename Container, typename Selector>
template<typename ContainerT, typename SelectorT>
class iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >
Definition at line 36 of file compress.hpp.
Member Typedef Documentation
difference_type
template<typename Container, typename Selector> template<typename ContainerT, typename SelectorT> using iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::difference_type = std::ptrdiff_t
Definition at line 61 of file compress.hpp.
iterator_category
template<typename Container, typename Selector> template<typename ContainerT, typename SelectorT> using iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::iterator_category = std::input_iterator_tag
Definition at line 59 of file compress.hpp.
pointer
template<typename Container, typename Selector> template<typename ContainerT, typename SelectorT> using iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::pointer = value_type*
Definition at line 62 of file compress.hpp.
reference
template<typename Container, typename Selector> template<typename ContainerT, typename SelectorT> using iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::reference = value_type&
Definition at line 63 of file compress.hpp.
value_type
template<typename Container, typename Selector> template<typename ContainerT, typename SelectorT> using iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::value_type = iterator_traits_deref<ContainerT>
Definition at line 60 of file compress.hpp.
Constructor & Destructor Documentation
Iterator()
template<typename Container, typename Selector> template<typename ContainerT, typename SelectorT> iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::Iterator (IteratorWrapper< ContainerT > && cont_iter, IteratorWrapper< ContainerT > && cont_end, IteratorWrapper< SelectorT > && sel_iter, IteratorWrapper< SelectorT > && sel_end) inline
Definition at line 65 of file compress.hpp.
References iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::skip_failures().
Member Function Documentation
increment_iterators()
template<typename Container, typename Selector> template<typename ContainerT, typename SelectorT> void iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::increment_iterators () inline private
Definition at line 46 of file compress.hpp.
References iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::selector_iter_, and iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::sub_iter_.
Referenced by iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::operator++(), and iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::skip_failures().
operator!=()
template<typename Container, typename Selector> template<typename ContainerT, typename SelectorT> template<typename T , typename U > bool iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::operator!= (const Iterator< T, U > & other) const inline
Definition at line 97 of file compress.hpp.
References iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::selector_iter_, and iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::sub_iter_.
operator*()
template<typename Container, typename Selector> template<typename ContainerT, typename SelectorT> iterator_deref<ContainerT> iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::operator* () inline
Definition at line 76 of file compress.hpp.
References iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::sub_iter_.
operator++() [1/2]
template<typename Container, typename Selector> template<typename ContainerT, typename SelectorT> Iterator& iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::operator++ () inline
Definition at line 84 of file compress.hpp.
References iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::increment_iterators(), and iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::skip_failures().
operator++() [2/2]
template<typename Container, typename Selector> template<typename ContainerT, typename SelectorT> Iterator iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::operator++ (int) inline
Definition at line 90 of file compress.hpp.
operator->()
template<typename Container, typename Selector> template<typename ContainerT, typename SelectorT> iterator_arrow<ContainerT> iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::operator-> () inline
Definition at line 80 of file compress.hpp.
References iter::impl::apply_arrow().
operator==()
template<typename Container, typename Selector> template<typename ContainerT, typename SelectorT> template<typename T , typename U > bool iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::operator== (const Iterator< T, U > & other) const inline
Definition at line 103 of file compress.hpp.
skip_failures()
template<typename Container, typename Selector> template<typename ContainerT, typename SelectorT> void iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::skip_failures () inline private
Definition at line 51 of file compress.hpp.
References iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::increment_iterators().
Referenced by iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::Iterator(), and iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::operator++().
Friends And Related Function Documentation
Iterator
template<typename Container, typename Selector> template<typename ContainerT, typename SelectorT> template<typename , typename > friend class Iterator friend
Definition at line 39 of file compress.hpp.
Member Data Documentation
selector_end_
template<typename Container, typename Selector> template<typename ContainerT, typename SelectorT> IteratorWrapper<SelectorT> iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::selector_end_ private
Definition at line 44 of file compress.hpp.
selector_iter_
template<typename Container, typename Selector> template<typename ContainerT, typename SelectorT> IteratorWrapper<SelectorT> iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::selector_iter_ private
Definition at line 43 of file compress.hpp.
Referenced by iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::increment_iterators(), and iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::operator!=().
sub_end_
template<typename Container, typename Selector> template<typename ContainerT, typename SelectorT> IteratorWrapper<ContainerT> iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::sub_end_ private
Definition at line 41 of file compress.hpp.
sub_iter_
template<typename Container, typename Selector> template<typename ContainerT, typename SelectorT> IteratorWrapper<ContainerT> iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::sub_iter_ private
Definition at line 40 of file compress.hpp.
Referenced by iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::increment_iterators(), iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::operator!=(), and iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::operator*().
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/compress.hpp