CkPttnCpp: iter::impl::Taker< FilterFunc, Container > Class Template Reference
iter::impl::Taker< FilterFunc, Container > Class Template Reference
#include <takewhile.hpp>
Classes
class Iterator
Public Member Functions
Taker (Taker &&)=default
Iterator< Container > begin ()
Iterator< Container > end ()
Iterator< AsConst< Container > > begin () const
Iterator< AsConst< Container > > end () const
Private Member Functions
Taker (FilterFunc filter_func, Container &&container)
Private Attributes
Container container_
FilterFunc filter_func_
friend TakeWhileFn
Detailed Description
template<typename FilterFunc, typename Container>
class iter::impl::Taker< FilterFunc, Container >
Definition at line 15 of file takewhile.hpp.
Constructor & Destructor Documentation
Taker() [1/2]
template<typename FilterFunc , typename Container > iter::impl::Taker< FilterFunc, Container >::Taker (FilterFunc filter_func, Container && container) inline private
Definition at line 30 of file takewhile.hpp.
Taker() [2/2]
template<typename FilterFunc , typename Container > iter::impl::Taker< FilterFunc, Container >::Taker (Taker< FilterFunc, Container > &&) default
Member Function Documentation
begin() [1/2]
template<typename FilterFunc , typename Container > Iterator<Container> iter::impl::Taker< FilterFunc, Container >::begin () inline
Definition at line 110 of file takewhile.hpp.
References iter::impl::get_iters::get_begin(), and iter::impl::get_iters::get_end().
begin() [2/2]
template<typename FilterFunc , typename Container > Iterator<AsConst<Container> > iter::impl::Taker< FilterFunc, Container >::begin () const inline
Definition at line 118 of file takewhile.hpp.
References iter::impl::get_iters::get_begin(), and iter::impl::get_iters::get_end().
end() [1/2]
template<typename FilterFunc , typename Container > Iterator<Container> iter::impl::Taker< FilterFunc, Container >::end () inline
Definition at line 114 of file takewhile.hpp.
References iter::impl::get_iters::get_end().
end() [2/2]
template<typename FilterFunc , typename Container > Iterator<AsConst<Container> > iter::impl::Taker< FilterFunc, Container >::end () const inline
Definition at line 123 of file takewhile.hpp.
References iter::impl::get_iters::get_end().
Member Data Documentation
container_
template<typename FilterFunc , typename Container > Container iter::impl::Taker< FilterFunc, Container >::container_ private
Definition at line 25 of file takewhile.hpp.
filter_func_
template<typename FilterFunc , typename Container > FilterFunc iter::impl::Taker< FilterFunc, Container >::filter_func_ mutable private
Definition at line 26 of file takewhile.hpp.
TakeWhileFn
template<typename FilterFunc , typename Container > friend iter::impl::Taker< FilterFunc, Container >::TakeWhileFn private
Definition at line 28 of file takewhile.hpp.
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/takewhile.hpp