CkPttnCpp: iter::impl::Compressed< Container, Selector > Class Template Reference
iter::impl::Compressed< Container, Selector > Class Template Reference
#include <compress.hpp>
Classes
class Iterator
Public Member Functions
Compressed (Compressed &&)=default
Iterator< Container, Selector > begin ()
Iterator< Container, Selector > end ()
Iterator< AsConst< Container >, AsConst< Selector > > begin () const
Iterator< AsConst< Container >, AsConst< Selector > > end () const
Private Member Functions
Compressed (Container &&in_container, Selector &&in_selectors)
Private Attributes
Container container_
Selector selectors_
Friends
Compressed iter::compress (Container &&, Selector &&)
Detailed Description
template<typename Container, typename Selector>
class iter::impl::Compressed< Container, Selector >
Definition at line 13 of file compress.hpp.
Constructor & Destructor Documentation
Compressed() [1/2]
template<typename Container, typename Selector> iter::impl::Compressed< Container, Selector >::Compressed (Container && in_container, Selector && in_selectors) inline private
Definition at line 29 of file compress.hpp.
Compressed() [2/2]
template<typename Container, typename Selector> iter::impl::Compressed< Container, Selector >::Compressed (Compressed< Container, Selector > &&) default
Member Function Documentation
begin() [1/2]
template<typename Container, typename Selector> Iterator<Container, Selector> iter::impl::Compressed< Container, Selector >::begin () inline
Definition at line 108 of file compress.hpp.
References iter::impl::get_iters::get_begin(), and iter::impl::get_iters::get_end().
begin() [2/2]
template<typename Container, typename Selector> Iterator<AsConst<Container>, AsConst<Selector> > iter::impl::Compressed< Container, Selector >::begin () const inline
Definition at line 118 of file compress.hpp.
References iter::impl::get_iters::get_begin(), and iter::impl::get_iters::get_end().
end() [1/2]
template<typename Container, typename Selector> Iterator<Container, Selector> iter::impl::Compressed< Container, Selector >::end () inline
Definition at line 113 of file compress.hpp.
References iter::impl::get_iters::get_end().
end() [2/2]
template<typename Container, typename Selector> Iterator<AsConst<Container>, AsConst<Selector> > iter::impl::Compressed< Container, Selector >::end () const inline
Definition at line 125 of file compress.hpp.
References iter::compress(), iter::impl::Compressed< Container, Selector >::container_, iter::impl::get_iters::get_end(), and iter::impl::Compressed< Container, Selector >::selectors_.
Friends And Related Function Documentation
iter::compress
template<typename Container, typename Selector> Compressed iter::compress (Container && , Selector &&) friend
Member Data Documentation
container_
template<typename Container, typename Selector> Container iter::impl::Compressed< Container, Selector >::container_ private
Definition at line 23 of file compress.hpp.
Referenced by iter::impl::Compressed< Container, Selector >::end().
selectors_
template<typename Container, typename Selector> Selector iter::impl::Compressed< Container, Selector >::selectors_ private
Definition at line 24 of file compress.hpp.
Referenced by iter::impl::Compressed< Container, Selector >::end().
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/compress.hpp