CkPttnCpp: iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT > Class Template Reference
iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT > Class Template Reference
#include <filter.hpp>
Public Types
using iterator_category = std::input_iterator_tag
using value_type = iterator_traits_deref< ContainerT >
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
Public Member Functions
Iterator (IteratorWrapper< ContainerT > &&sub_iter, IteratorWrapper< ContainerT > &&sub_end, FilterFunc &filter_func)
Holder::reference operator* ()
Holder::pointer operator-> ()
Iterator & operator++ ()
Iterator operator++ (int)
template<typename T >
bool operator!= (const Iterator< T > &other) const
template<typename T >
bool operator== (const Iterator< T > &other) const
Private Types
using Holder = DerefHolder< iterator_deref< ContainerT > >
Private Member Functions
void inc_sub_iter ()
void skip_failures ()
Private Attributes
IteratorWrapper< ContainerT > sub_iter_
IteratorWrapper< ContainerT > sub_end_
Holder item_
FilterFunc * filter_func_
Friends
template<typename >
class Iterator
Detailed Description
template<typename FilterFunc, typename Container>
template<typename ContainerT>
class iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT >
Definition at line 48 of file filter.hpp.
Member Typedef Documentation
difference_type
template<typename FilterFunc, typename Container> template<typename ContainerT> using iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT >::difference_type = std::ptrdiff_t
Definition at line 77 of file filter.hpp.
Holder
template<typename FilterFunc, typename Container> template<typename ContainerT> using iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT >::Holder = DerefHolder<iterator_deref<ContainerT> > private
Definition at line 52 of file filter.hpp.
iterator_category
template<typename FilterFunc, typename Container> template<typename ContainerT> using iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT >::iterator_category = std::input_iterator_tag
Definition at line 75 of file filter.hpp.
pointer
template<typename FilterFunc, typename Container> template<typename ContainerT> using iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT >::pointer = value_type*
Definition at line 78 of file filter.hpp.
reference
template<typename FilterFunc, typename Container> template<typename ContainerT> using iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT >::reference = value_type&
Definition at line 79 of file filter.hpp.
value_type
template<typename FilterFunc, typename Container> template<typename ContainerT> using iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT >::value_type = iterator_traits_deref<ContainerT>
Definition at line 76 of file filter.hpp.
Constructor & Destructor Documentation
Iterator()
template<typename FilterFunc, typename Container> template<typename ContainerT> iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT >::Iterator (IteratorWrapper< ContainerT > && sub_iter, IteratorWrapper< ContainerT > && sub_end, FilterFunc & filter_func) inline
Definition at line 81 of file filter.hpp.
References iter::impl::DerefHolder< T >::reset().
Member Function Documentation
inc_sub_iter()
template<typename FilterFunc, typename Container> template<typename ContainerT> void iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT >::inc_sub_iter () inline private
Definition at line 58 of file filter.hpp.
References iter::impl::DerefHolder< T >::reset().
operator!=()
template<typename FilterFunc, typename Container> template<typename ContainerT> template<typename T > bool iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT >::operator!= (const Iterator< T > & other) const inline
Definition at line 113 of file filter.hpp.
References iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT >::sub_iter_.
operator*()
template<typename FilterFunc, typename Container> template<typename ContainerT> Holder::reference iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT >::operator* () inline
Definition at line 92 of file filter.hpp.
References iter::impl::DerefHolder< T >::get().
operator++() [1/2]
template<typename FilterFunc, typename Container> template<typename ContainerT> Iterator& iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT >::operator++ () inline
Definition at line 100 of file filter.hpp.
operator++() [2/2]
template<typename FilterFunc, typename Container> template<typename ContainerT> Iterator iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT >::operator++ (int) inline
Definition at line 106 of file filter.hpp.
operator->()
template<typename FilterFunc, typename Container> template<typename ContainerT> Holder::pointer iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT >::operator-> () inline
Definition at line 96 of file filter.hpp.
References iter::impl::DerefHolder< T >::get_ptr().
operator==()
template<typename FilterFunc, typename Container> template<typename ContainerT> template<typename T > bool iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT >::operator== (const Iterator< T > & other) const inline
Definition at line 118 of file filter.hpp.
skip_failures()
template<typename FilterFunc, typename Container> template<typename ContainerT> void iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT >::skip_failures () inline private
Definition at line 67 of file filter.hpp.
References iter::impl::DerefHolder< T >::get().
Friends And Related Function Documentation
Iterator
template<typename FilterFunc, typename Container> template<typename ContainerT> template<typename > friend class Iterator friend
Definition at line 51 of file filter.hpp.
Member Data Documentation
filter_func_
template<typename FilterFunc, typename Container> template<typename ContainerT> FilterFunc* iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT >::filter_func_ private
Definition at line 56 of file filter.hpp.
item_
template<typename FilterFunc, typename Container> template<typename ContainerT> Holder iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT >::item_ private
Definition at line 55 of file filter.hpp.
sub_end_
template<typename FilterFunc, typename Container> template<typename ContainerT> IteratorWrapper<ContainerT> iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT >::sub_end_ private
Definition at line 54 of file filter.hpp.
sub_iter_
template<typename FilterFunc, typename Container> template<typename ContainerT> IteratorWrapper<ContainerT> iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT >::sub_iter_ private
Definition at line 53 of file filter.hpp.
Referenced by iter::impl::Filtered< FilterFunc, Container >::Iterator< ContainerT >::operator!=().
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/filter.hpp