CkPttnCpp: iter::impl::StarMapper< Func, Container > Class Template Reference
iter::impl::StarMapper< Func, Container > Class Template Reference
#include <starmap.hpp>
Classes
class Iterator
Public Member Functions
Iterator< Container > begin ()
Iterator< Container > end ()
Iterator< AsConst< Container > > begin () const
Iterator< AsConst< Container > > end () const
Private Types
using StarIterDeref = std::remove_reference_t< decltype(std::apply(func_, std::declval< iterator_deref< Container > >()))>
Private Member Functions
StarMapper (Func f, Container &&c)
Private Attributes
Func func_
Container container_
friend StarMapFn
Detailed Description
template<typename Func, typename Container>
class iter::impl::StarMapper< Func, Container >
Definition at line 18 of file starmap.hpp.
Member Typedef Documentation
StarIterDeref
template<typename Func , typename Container > using iter::impl::StarMapper< Func, Container >::StarIterDeref = std::remove_reference_t<decltype(std::apply(func_, std::declval<iterator_deref<Container> >()))> private
Definition at line 38 of file starmap.hpp.
Constructor & Destructor Documentation
StarMapper()
template<typename Func , typename Container > iter::impl::StarMapper< Func, Container >::StarMapper (Func f, Container && c) inline private
Definition at line 40 of file starmap.hpp.
Member Function Documentation
begin() [1/2]
template<typename Func , typename Container > Iterator<Container> iter::impl::StarMapper< Func, Container >::begin () inline
Definition at line 94 of file starmap.hpp.
References iter::impl::StarMapper< Func, Container >::Iterator< ContainerT >::func_, and iter::impl::get_iters::get_begin().
begin() [2/2]
template<typename Func , typename Container > Iterator<AsConst<Container> > iter::impl::StarMapper< Func, Container >::begin () const inline
Definition at line 102 of file starmap.hpp.
References iter::impl::StarMapper< Func, Container >::Iterator< ContainerT >::func_, and iter::impl::get_iters::get_begin().
end() [1/2]
template<typename Func , typename Container > Iterator<Container> iter::impl::StarMapper< Func, Container >::end () inline
Definition at line 98 of file starmap.hpp.
References iter::impl::StarMapper< Func, Container >::Iterator< ContainerT >::func_, and iter::impl::get_iters::get_end().
end() [2/2]
template<typename Func , typename Container > Iterator<AsConst<Container> > iter::impl::StarMapper< Func, Container >::end () const inline
Definition at line 106 of file starmap.hpp.
References iter::impl::StarMapper< Func, Container >::Iterator< ContainerT >::func_, and iter::impl::get_iters::get_end().
Member Data Documentation
container_
template<typename Func , typename Container > Container iter::impl::StarMapper< Func, Container >::container_ private
Definition at line 35 of file starmap.hpp.
func_
template<typename Func , typename Container > Func iter::impl::StarMapper< Func, Container >::func_ mutable private
Definition at line 34 of file starmap.hpp.
StarMapFn
template<typename Func , typename Container > friend iter::impl::StarMapper< Func, Container >::StarMapFn private
Definition at line 43 of file starmap.hpp.
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/starmap.hpp