CkPttnCpp: iter::impl::GroupProducer< Container, KeyFunc > Class Template Reference
iter::impl::GroupProducer< Container, KeyFunc > Class Template Reference
#include <groupby.hpp>
Classes
class Group
class Iterator
Public Member Functions
GroupProducer (GroupProducer &&)=default
Iterator< Container > begin ()
Iterator< Container > end ()
Iterator< AsConst< Container > > begin () const
Iterator< AsConst< Container > > end () const
Private Types
template<typename T >
using key_func_ret = std::invoke_result_t< KeyFunc, iterator_deref< T > >
template<typename T >
using KeyGroupPair = std::pair< key_func_ret< T >, Group< T > >
template<typename T >
using Holder = DerefHolder< iterator_deref< T > >
Private Member Functions
GroupProducer (Container &&container, KeyFunc key_func)
Private Attributes
Container container_
KeyFunc key_func_
friend GroupByFn
Detailed Description
template<typename Container, typename KeyFunc>
class iter::impl::GroupProducer< Container, KeyFunc >
Definition at line 19 of file groupby.hpp.
Member Typedef Documentation
Holder
template<typename Container , typename KeyFunc > template<typename T > using iter::impl::GroupProducer< Container, KeyFunc >::Holder = DerefHolder<iterator_deref<T> > private
Definition at line 59 of file groupby.hpp.
key_func_ret
template<typename Container , typename KeyFunc > template<typename T > using iter::impl::GroupProducer< Container, KeyFunc >::key_func_ret = std::invoke_result_t<KeyFunc, iterator_deref<T> > private
Definition at line 42 of file groupby.hpp.
KeyGroupPair
template<typename Container , typename KeyFunc > template<typename T > using iter::impl::GroupProducer< Container, KeyFunc >::KeyGroupPair = std::pair<key_func_ret<T>, Group<T> > private
Definition at line 57 of file groupby.hpp.
Constructor & Destructor Documentation
GroupProducer() [1/2]
template<typename Container , typename KeyFunc > iter::impl::GroupProducer< Container, KeyFunc >::GroupProducer (Container && container, KeyFunc key_func) inline private
Definition at line 44 of file groupby.hpp.
GroupProducer() [2/2]
template<typename Container , typename KeyFunc > iter::impl::GroupProducer< Container, KeyFunc >::GroupProducer (GroupProducer< Container, KeyFunc > &&) default
Member Function Documentation
begin() [1/2]
template<typename Container , typename KeyFunc > Iterator<Container> iter::impl::GroupProducer< Container, KeyFunc >::begin () inline
Definition at line 279 of file groupby.hpp.
References iter::impl::get_iters::get_begin(), and iter::impl::get_iters::get_end().
begin() [2/2]
template<typename Container , typename KeyFunc > Iterator<AsConst<Container> > iter::impl::GroupProducer< Container, KeyFunc >::begin () const inline
Definition at line 287 of file groupby.hpp.
References iter::impl::get_iters::get_begin(), and iter::impl::get_iters::get_end().
end() [1/2]
template<typename Container , typename KeyFunc > Iterator<Container> iter::impl::GroupProducer< Container, KeyFunc >::end () inline
Definition at line 283 of file groupby.hpp.
References iter::impl::get_iters::get_end().
end() [2/2]
template<typename Container , typename KeyFunc > Iterator<AsConst<Container> > iter::impl::GroupProducer< Container, KeyFunc >::end () const inline
Definition at line 292 of file groupby.hpp.
References iter::impl::get_iters::get_end().
Member Data Documentation
container_
template<typename Container , typename KeyFunc > Container iter::impl::GroupProducer< Container, KeyFunc >::container_ private
Definition at line 36 of file groupby.hpp.
GroupByFn
template<typename Container , typename KeyFunc > friend iter::impl::GroupProducer< Container, KeyFunc >::GroupByFn private
Definition at line 39 of file groupby.hpp.
key_func_
template<typename Container , typename KeyFunc > KeyFunc iter::impl::GroupProducer< Container, KeyFunc >::key_func_ mutable private
Definition at line 37 of file groupby.hpp.
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/groupby.hpp