CkPttnCpp: itertest::BasicIterable< T > Class Template Reference
itertest::BasicIterable< T > Class Template Reference
#include <helpers.hpp>
Classes
class Iterator
Public Member Functions
BasicIterable (std::initializer_list< T > il)
BasicIterable & operator= (BasicIterable &&)=delete
BasicIterable & operator= (const BasicIterable &)=delete
BasicIterable (const BasicIterable &)=delete
BasicIterable (BasicIterable &&other)
bool was_moved_from () const
bool was_copied_from () const
~BasicIterable ()
Private Attributes
T * data
std::size_t size
bool was_moved_from_ = false
bool was_copied_from_ = false
Friends
BasicIterable::Iterator< T > begin (BasicIterable &b)
BasicIterable::Iterator< T > end (BasicIterable &b)
Detailed Description
template<typename T>
class itertest::BasicIterable< T >
Definition at line 108 of file helpers.hpp.
Constructor & Destructor Documentation
BasicIterable() [1/3]
template<typename T > itertest::BasicIterable< T >::BasicIterable (std::initializer_list< T > il) inline
Definition at line 116 of file helpers.hpp.
References NS1::begin(), NS1::end(), itertest::SolidInt::i, itertest::SolidInt::operator=(), itertest::BasicIterable< T >::size, and itertest::BasicIterable< T >::was_copied_from_.
BasicIterable() [2/3]
template<typename T > itertest::BasicIterable< T >::BasicIterable (const BasicIterable< T > &) delete
BasicIterable() [3/3]
template<typename T > itertest::BasicIterable< T >::BasicIterable (BasicIterable< T > && other) inline
Definition at line 143 of file helpers.hpp.
References itertest::BasicIterable< T >::data, itertest::BasicIterable< T >::size, and itertest::BasicIterable< T >::was_moved_from_.
~BasicIterable()
template<typename T > itertest::BasicIterable< T >::~BasicIterable () inline
Definition at line 156 of file helpers.hpp.
Member Function Documentation
operator=() [1/2]
template<typename T > BasicIterable& itertest::BasicIterable< T >::operator= (BasicIterable< T > &&) delete
operator=() [2/2]
template<typename T > BasicIterable& itertest::BasicIterable< T >::operator= (const BasicIterable< T > &) delete
was_copied_from()
template<typename T > bool itertest::BasicIterable< T >::was_copied_from () const inline
Definition at line 152 of file helpers.hpp.
was_moved_from()
template<typename T > bool itertest::BasicIterable< T >::was_moved_from () const inline
Definition at line 148 of file helpers.hpp.
Friends And Related Function Documentation
begin
template<typename T > BasicIterable::Iterator<T> begin (BasicIterable< T > & b) friend
Definition at line 184 of file helpers.hpp.
end
template<typename T > BasicIterable::Iterator<T> end (BasicIterable< T > & b) friend
Definition at line 188 of file helpers.hpp.
Member Data Documentation
data
template<typename T > T* itertest::BasicIterable< T >::data private
Definition at line 110 of file helpers.hpp.
Referenced by itertest::BasicIterable< T >::BasicIterable().
size
template<typename T > std::size_t itertest::BasicIterable< T >::size private
Definition at line 111 of file helpers.hpp.
Referenced by itertest::BasicIterable< T >::BasicIterable().
was_copied_from_
template<typename T > bool itertest::BasicIterable< T >::was_copied_from_ = false mutable private
Definition at line 113 of file helpers.hpp.
Referenced by itertest::BasicIterable< T >::BasicIterable().
was_moved_from_
template<typename T > bool itertest::BasicIterable< T >::was_moved_from_ = false private
Definition at line 112 of file helpers.hpp.
Referenced by itertest::BasicIterable< T >::BasicIterable().
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/helpers.hpp