CkPttnCpp: iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> > Class Template Reference
iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> > Class Template Reference
Public Types
using IterIterWrap = IterIterWrapper< std::vector< iterator_type< ContainerT > >>
using ItIt = iterator_type< IterIterWrap >
using ConstIterIterWrap = IterIterWrapper< std::vector< iterator_type< AsConst< ContainerT > >> >
using ConstItIt = iterator_type< ConstIterIterWrap >
Public Member Functions
SortedItersHolder (ContainerT &&container, CompareFunc compare_func)
ItIt begin ()
ItIt end ()
ConstItIt begin () const
ConstItIt end () const
Private Member Functions
void populate_sorted_iters () const =delete
void populate_sorted_iters ()
void populate_const_sorted_iters ()=delete
void populate_const_sorted_iters () const
Private Attributes
ContainerT container_
CompareFunc compare_func_
IterIterWrap sorted_iters_
ConstIterIterWrap const_sorted_iters_
Detailed Description
template<typename Container, typename CompareFunc>
template<typename ContainerT>
class iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >
Definition at line 64 of file sorted.hpp.
Member Typedef Documentation
ConstIterIterWrap
template<typename Container , typename CompareFunc > template<typename ContainerT > using iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >::ConstIterIterWrap = IterIterWrapper<std::vector<iterator_type<AsConst<ContainerT> >> >
Definition at line 72 of file sorted.hpp.
ConstItIt
template<typename Container , typename CompareFunc > template<typename ContainerT > using iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >::ConstItIt = iterator_type<ConstIterIterWrap>
Definition at line 73 of file sorted.hpp.
IterIterWrap
template<typename Container , typename CompareFunc > template<typename ContainerT > using iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >::IterIterWrap = IterIterWrapper<std::vector<iterator_type<ContainerT> >>
Definition at line 68 of file sorted.hpp.
ItIt
template<typename Container , typename CompareFunc > template<typename ContainerT > using iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >::ItIt = iterator_type<IterIterWrap>
Definition at line 69 of file sorted.hpp.
Constructor & Destructor Documentation
SortedItersHolder()
template<typename Container , typename CompareFunc > template<typename ContainerT > iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >::SortedItersHolder (ContainerT && container, CompareFunc compare_func) inline
Definition at line 120 of file sorted.hpp.
Member Function Documentation
begin() [1/2]
template<typename Container , typename CompareFunc > template<typename ContainerT > ItIt iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >::begin () inline
Definition at line 124 of file sorted.hpp.
References iter::impl::IterIterWrapper< Container >::begin().
begin() [2/2]
template<typename Container , typename CompareFunc > template<typename ContainerT > ConstItIt iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >::begin () const inline
Definition at line 134 of file sorted.hpp.
References iter::impl::IterIterWrapper< Container >::begin().
end() [1/2]
template<typename Container , typename CompareFunc > template<typename ContainerT > ItIt iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >::end () inline
Definition at line 129 of file sorted.hpp.
References iter::impl::IterIterWrapper< Container >::end().
end() [2/2]
template<typename Container , typename CompareFunc > template<typename ContainerT > ConstItIt iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >::end () const inline
Definition at line 139 of file sorted.hpp.
References iter::impl::IterIterWrapper< Container >::end().
populate_const_sorted_iters() [1/2]
template<typename Container , typename CompareFunc > template<typename ContainerT > void iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >::populate_const_sorted_iters () private delete
populate_const_sorted_iters() [2/2]
template<typename Container , typename CompareFunc > template<typename ContainerT > void iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >::populate_const_sorted_iters () const inline private
Definition at line 101 of file sorted.hpp.
References iter::impl::IterIterWrapper< Container >::empty(), iter::impl::IterIterWrapper< Container >::get(), iter::impl::get_iters::get_begin(), and iter::impl::get_iters::get_end().
populate_sorted_iters() [1/2]
template<typename Container , typename CompareFunc > template<typename ContainerT > void iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >::populate_sorted_iters () const private delete
populate_sorted_iters() [2/2]
template<typename Container , typename CompareFunc > template<typename ContainerT > void iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >::populate_sorted_iters () inline private
Definition at line 82 of file sorted.hpp.
References iter::impl::IterIterWrapper< Container >::empty(), iter::impl::IterIterWrapper< Container >::get(), iter::impl::get_iters::get_begin(), and iter::impl::get_iters::get_end().
Member Data Documentation
compare_func_
template<typename Container , typename CompareFunc > template<typename ContainerT > CompareFunc iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >::compare_func_ mutable private
Definition at line 77 of file sorted.hpp.
const_sorted_iters_
template<typename Container , typename CompareFunc > template<typename ContainerT > ConstIterIterWrap iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >::const_sorted_iters_ mutable private
Definition at line 79 of file sorted.hpp.
container_
template<typename Container , typename CompareFunc > template<typename ContainerT > ContainerT iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >::container_ private
Definition at line 76 of file sorted.hpp.
sorted_iters_
template<typename Container , typename CompareFunc > template<typename ContainerT > IterIterWrap iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >::sorted_iters_ private
Definition at line 78 of file sorted.hpp.
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/sorted.hpp