CkPttnCpp: iter::impl::Powersetter< Container >::Iterator< ContainerT > Class Template Reference
iter::impl::Powersetter< Container >::Iterator< ContainerT > Class Template Reference
#include <powerset.hpp>
Public Types
using iterator_category = std::input_iterator_tag
using value_type = CombinatorType< ContainerT >
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
Public Member Functions
Iterator (ContainerT &container, std::size_t sz)
Iterator & operator++ ()
Iterator operator++ (int)
iterator_deref< CombinatorType< ContainerT > > operator* ()
iterator_arrow< CombinatorType< ContainerT > > operator-> ()
bool operator!= (const Iterator &other) const
bool operator== (const Iterator &other) const
Private Attributes
std::remove_reference_t< ContainerT > * container_p_
std::size_t set_size_ {}
std::shared_ptr< CombinatorType< ContainerT > > comb_
iterator_type< CombinatorType< ContainerT > > comb_iter_
iterator_type< CombinatorType< ContainerT > > comb_end_
Detailed Description
template<typename Container>
template<typename ContainerT>
class iter::impl::Powersetter< Container >::Iterator< ContainerT >
Definition at line 40 of file powerset.hpp.
Member Typedef Documentation
difference_type
template<typename Container > template<typename ContainerT> using iter::impl::Powersetter< Container >::Iterator< ContainerT >::difference_type = std::ptrdiff_t
Definition at line 54 of file powerset.hpp.
iterator_category
template<typename Container > template<typename ContainerT> using iter::impl::Powersetter< Container >::Iterator< ContainerT >::iterator_category = std::input_iterator_tag
Definition at line 52 of file powerset.hpp.
pointer
template<typename Container > template<typename ContainerT> using iter::impl::Powersetter< Container >::Iterator< ContainerT >::pointer = value_type*
Definition at line 55 of file powerset.hpp.
reference
template<typename Container > template<typename ContainerT> using iter::impl::Powersetter< Container >::Iterator< ContainerT >::reference = value_type&
Definition at line 56 of file powerset.hpp.
value_type
template<typename Container > template<typename ContainerT> using iter::impl::Powersetter< Container >::Iterator< ContainerT >::value_type = CombinatorType<ContainerT>
Definition at line 53 of file powerset.hpp.
Constructor & Destructor Documentation
Iterator()
template<typename Container > template<typename ContainerT> iter::impl::Powersetter< Container >::Iterator< ContainerT >::Iterator (ContainerT & container, std::size_t sz) inline
Definition at line 58 of file powerset.hpp.
References iter::combinations, iter::impl::get_iters::get_begin(), iter::impl::get_iters::get_end(), and iter::impl::Powersetter< Container >::Iterator< ContainerT >::set_size_.
Member Function Documentation
operator!=()
template<typename Container > template<typename ContainerT> bool iter::impl::Powersetter< Container >::Iterator< ContainerT >::operator!= (const Iterator< ContainerT > & other) const inline
Definition at line 93 of file powerset.hpp.
Referenced by iter::impl::Powersetter< Container >::Iterator< ContainerT >::operator==().
operator*()
template<typename Container > template<typename ContainerT> iterator_deref<CombinatorType<ContainerT> > iter::impl::Powersetter< Container >::Iterator< ContainerT >::operator* () inline
Definition at line 85 of file powerset.hpp.
References iter::impl::Powersetter< Container >::Iterator< ContainerT >::comb_iter_.
operator++() [1/2]
template<typename Container > template<typename ContainerT> Iterator& iter::impl::Powersetter< Container >::Iterator< ContainerT >::operator++ () inline
Definition at line 66 of file powerset.hpp.
References iter::impl::Powersetter< Container >::Iterator< ContainerT >::comb_iter_, iter::combinations, iter::impl::get_iters::get_begin(), iter::impl::get_iters::get_end(), and iter::impl::Powersetter< Container >::Iterator< ContainerT >::set_size_.
operator++() [2/2]
template<typename Container > template<typename ContainerT> Iterator iter::impl::Powersetter< Container >::Iterator< ContainerT >::operator++ (int) inline
Definition at line 79 of file powerset.hpp.
operator->()
template<typename Container > template<typename ContainerT> iterator_arrow<CombinatorType<ContainerT> > iter::impl::Powersetter< Container >::Iterator< ContainerT >::operator-> () inline
Definition at line 89 of file powerset.hpp.
References iter::impl::apply_arrow().
operator==()
template<typename Container > template<typename ContainerT> bool iter::impl::Powersetter< Container >::Iterator< ContainerT >::operator== (const Iterator< ContainerT > & other) const inline
Definition at line 97 of file powerset.hpp.
References iter::impl::Powersetter< Container >::Iterator< ContainerT >::comb_iter_, iter::impl::Powersetter< Container >::Iterator< ContainerT >::operator!=(), and iter::impl::Powersetter< Container >::Iterator< ContainerT >::set_size_.
Member Data Documentation
comb_
template<typename Container > template<typename ContainerT> std::shared_ptr<CombinatorType<ContainerT> > iter::impl::Powersetter< Container >::Iterator< ContainerT >::comb_ private
Definition at line 47 of file powerset.hpp.
comb_end_
template<typename Container > template<typename ContainerT> iterator_type<CombinatorType<ContainerT> > iter::impl::Powersetter< Container >::Iterator< ContainerT >::comb_end_ private
Definition at line 49 of file powerset.hpp.
comb_iter_
template<typename Container > template<typename ContainerT> iterator_type<CombinatorType<ContainerT> > iter::impl::Powersetter< Container >::Iterator< ContainerT >::comb_iter_ private
Definition at line 48 of file powerset.hpp.
Referenced by iter::impl::Powersetter< Container >::Iterator< ContainerT >::operator*(), iter::impl::Powersetter< Container >::Iterator< ContainerT >::operator++(), and iter::impl::Powersetter< Container >::Iterator< ContainerT >::operator==().
container_p_
template<typename Container > template<typename ContainerT> std::remove_reference_t<ContainerT>* iter::impl::Powersetter< Container >::Iterator< ContainerT >::container_p_ private
Definition at line 45 of file powerset.hpp.
set_size_
template<typename Container > template<typename ContainerT> std::size_t iter::impl::Powersetter< Container >::Iterator< ContainerT >::set_size_ {} private
Definition at line 46 of file powerset.hpp.
Referenced by iter::impl::Powersetter< Container >::Iterator< ContainerT >::Iterator(), iter::impl::Powersetter< Container >::Iterator< ContainerT >::operator++(), and iter::impl::Powersetter< Container >::Iterator< ContainerT >::operator==().
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/powerset.hpp