CkPttnCpp: iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT > Class Template Reference
iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT > Class Template Reference
#include <takewhile.hpp>
Public Types
using iterator_category = std::input_iterator_tag
using value_type = iterator_traits_deref< ContainerT >
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
Public Member Functions
Iterator (IteratorWrapper< ContainerT > &&sub_iter, IteratorWrapper< ContainerT > &&sub_end, FilterFunc &filter_func)
Holder::reference operator* ()
Holder::pointer operator-> ()
Iterator & operator++ ()
Iterator operator++ (int)
template<typename T >
bool operator!= (const Iterator< T > &other) const
template<typename T >
bool operator== (const Iterator< T > &other) const
Private Types
using Holder = DerefHolder< iterator_deref< ContainerT > >
Private Member Functions
void inc_sub_iter ()
void check_current ()
Private Attributes
IteratorWrapper< ContainerT > sub_iter_
IteratorWrapper< ContainerT > sub_end_
Holder item_
FilterFunc * filter_func_
Friends
template<typename >
class Iterator
Detailed Description
template<typename FilterFunc, typename Container>
template<typename ContainerT>
class iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >
Definition at line 38 of file takewhile.hpp.
Member Typedef Documentation
difference_type
template<typename FilterFunc , typename Container > template<typename ContainerT> using iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::difference_type = std::ptrdiff_t
Definition at line 64 of file takewhile.hpp.
Holder
template<typename FilterFunc , typename Container > template<typename ContainerT> using iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::Holder = DerefHolder<iterator_deref<ContainerT> > private
Definition at line 42 of file takewhile.hpp.
iterator_category
template<typename FilterFunc , typename Container > template<typename ContainerT> using iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::iterator_category = std::input_iterator_tag
Definition at line 62 of file takewhile.hpp.
pointer
template<typename FilterFunc , typename Container > template<typename ContainerT> using iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::pointer = value_type*
Definition at line 65 of file takewhile.hpp.
reference
template<typename FilterFunc , typename Container > template<typename ContainerT> using iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::reference = value_type&
Definition at line 66 of file takewhile.hpp.
value_type
template<typename FilterFunc , typename Container > template<typename ContainerT> using iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::value_type = iterator_traits_deref<ContainerT>
Definition at line 63 of file takewhile.hpp.
Constructor & Destructor Documentation
Iterator()
template<typename FilterFunc , typename Container > template<typename ContainerT> iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::Iterator (IteratorWrapper< ContainerT > && sub_iter, IteratorWrapper< ContainerT > && sub_end, FilterFunc & filter_func) inline
Definition at line 68 of file takewhile.hpp.
References iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::check_current(), iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::filter_func_, and iter::impl::DerefHolder< T >::reset().
Member Function Documentation
check_current()
template<typename FilterFunc , typename Container > template<typename ContainerT> void iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::check_current () inline private
Definition at line 55 of file takewhile.hpp.
References iter::impl::DerefHolder< T >::get(), and iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::sub_end_.
Referenced by iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::Iterator(), and iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::operator++().
inc_sub_iter()
template<typename FilterFunc , typename Container > template<typename ContainerT> void iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::inc_sub_iter () inline private
Definition at line 48 of file takewhile.hpp.
References iter::impl::DerefHolder< T >::reset(), and iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::sub_iter_.
Referenced by iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::operator++().
operator!=()
template<typename FilterFunc , typename Container > template<typename ContainerT> template<typename T > bool iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::operator!= (const Iterator< T > & other) const inline
Definition at line 100 of file takewhile.hpp.
References iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::sub_iter_.
operator*()
template<typename FilterFunc , typename Container > template<typename ContainerT> Holder::reference iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::operator* () inline
Definition at line 79 of file takewhile.hpp.
References iter::impl::DerefHolder< T >::get().
operator++() [1/2]
template<typename FilterFunc , typename Container > template<typename ContainerT> Iterator& iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::operator++ () inline
Definition at line 87 of file takewhile.hpp.
References iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::check_current(), and iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::inc_sub_iter().
operator++() [2/2]
template<typename FilterFunc , typename Container > template<typename ContainerT> Iterator iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::operator++ (int) inline
Definition at line 93 of file takewhile.hpp.
operator->()
template<typename FilterFunc , typename Container > template<typename ContainerT> Holder::pointer iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::operator-> () inline
Definition at line 83 of file takewhile.hpp.
References iter::impl::DerefHolder< T >::get_ptr().
operator==()
template<typename FilterFunc , typename Container > template<typename ContainerT> template<typename T > bool iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::operator== (const Iterator< T > & other) const inline
Definition at line 105 of file takewhile.hpp.
Friends And Related Function Documentation
Iterator
template<typename FilterFunc , typename Container > template<typename ContainerT> template<typename > friend class Iterator friend
Definition at line 41 of file takewhile.hpp.
Member Data Documentation
filter_func_
template<typename FilterFunc , typename Container > template<typename ContainerT> FilterFunc* iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::filter_func_ private
Definition at line 46 of file takewhile.hpp.
Referenced by iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::Iterator().
item_
template<typename FilterFunc , typename Container > template<typename ContainerT> Holder iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::item_ private
Definition at line 45 of file takewhile.hpp.
sub_end_
template<typename FilterFunc , typename Container > template<typename ContainerT> IteratorWrapper<ContainerT> iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::sub_end_ private
Definition at line 44 of file takewhile.hpp.
Referenced by iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::check_current().
sub_iter_
template<typename FilterFunc , typename Container > template<typename ContainerT> IteratorWrapper<ContainerT> iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::sub_iter_ private
Definition at line 43 of file takewhile.hpp.
Referenced by iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::inc_sub_iter(), and iter::impl::Taker< FilterFunc, Container >::Iterator< ContainerT >::operator!=().
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/takewhile.hpp