CkPttnCpp: iter::impl::Zipped< TupleType, Is > Class Template Reference
iter::impl::Zipped< TupleType, Is > Class Template Reference
#include <zip.hpp>
Classes
class Iterator
Public Member Functions
Zipped (Zipped &&)=default
Iterator< TupleType, iterator_tuple_type, iterator_deref_tuple > begin ()
Iterator< TupleType, iterator_tuple_type, iterator_deref_tuple > end ()
Iterator< AsConst< TupleType >, const_iterator_tuple_type, const_iterator_deref_tuple > begin () const
Iterator< AsConst< TupleType >, const_iterator_tuple_type, const_iterator_deref_tuple > end () const
Private Member Functions
Zipped (TupleType &&containers)
Private Attributes
TupleType containers_
Friends
Zipped iter::impl::zip_impl (TupleType &&, std::index_sequence< Is... >)
Detailed Description
template<typename TupleType, std::size_t... Is>
class iter::impl::Zipped< TupleType, Is >
Definition at line 15 of file zip.hpp.
Constructor & Destructor Documentation
Zipped() [1/2]
template<typename TupleType , std::size_t... Is> iter::impl::Zipped< TupleType, Is >::Zipped (TupleType && containers) inline private
Definition at line 32 of file zip.hpp.
Zipped() [2/2]
template<typename TupleType , std::size_t... Is> iter::impl::Zipped< TupleType, Is >::Zipped (Zipped< TupleType, Is > &&) default
Member Function Documentation
begin() [1/2]
template<typename TupleType , std::size_t... Is> Iterator<TupleType, iterator_tuple_type, iterator_deref_tuple> iter::impl::Zipped< TupleType, Is >::begin () inline
Definition at line 99 of file zip.hpp.
References iter::impl::get_iters::get_begin().
begin() [2/2]
template<typename TupleType , std::size_t... Is> Iterator<AsConst<TupleType>, const_iterator_tuple_type, const_iterator_deref_tuple> iter::impl::Zipped< TupleType, Is >::begin () const inline
Definition at line 109 of file zip.hpp.
References iter::impl::get_iters::get_begin().
end() [1/2]
template<typename TupleType , std::size_t... Is> Iterator<TupleType, iterator_tuple_type, iterator_deref_tuple> iter::impl::Zipped< TupleType, Is >::end () inline
Definition at line 103 of file zip.hpp.
References iter::impl::get_iters::get_end().
end() [2/2]
template<typename TupleType , std::size_t... Is> Iterator<AsConst<TupleType>, const_iterator_tuple_type, const_iterator_deref_tuple> iter::impl::Zipped< TupleType, Is >::end () const inline
Definition at line 115 of file zip.hpp.
References iter::impl::get_iters::get_end(), and iter::impl::zip_impl().
Friends And Related Function Documentation
iter::impl::zip_impl
template<typename TupleType , std::size_t... Is> Zipped iter::impl::zip_impl (TupleType && , std::index_sequence< Is... >) friend
Member Data Documentation
containers_
template<typename TupleType , std::size_t... Is> TupleType iter::impl::Zipped< TupleType, Is >::containers_ private
Definition at line 28 of file zip.hpp.
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/zip.hpp