CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_range.cpp File Reference
test_range.cpp File Reference
#include "range.hpp"
#include <algorithm>
#include <iterator>
#include <vector>
#include "catch.hpp"
#include "helpers.hpp"
Typedefs
using Vec = const std::vector< int >
using FVec = const std::vector< double >
Functions
TEST_CASE ("range: works with only stop", "[range]")
TEST_CASE ("range: works with start and stop", "[range]")
TEST_CASE ("range: works with positive step > 1", "[range]")
TEST_CASE ("range(0) is empty", "[range]")
TEST_CASE ("range: postfix++", "[range]")
TEST_CASE ("start > stop produces empty range", "[range]")
TEST_CASE ("start < stop and step < 0 produces empty range", "[range]")
TEST_CASE ("range: with only a negative stop is empty", "[range]")
TEST_CASE ("range: works with negative step", "[range]")
TEST_CASE ("range: stops short when step doesn't divide stop-start", "[range]")
TEST_CASE ("range: stops short when step > stop-start", "[range]")
TEST_CASE ("range: step size of 0 gives an empty range", "[range]")
TEST_CASE ("range: can create constexpr ranges", "[range]")
TEST_CASE ("range: const iterators compare to non-const iterators", "[range]")
TEST_CASE ("range: works with a variable start, stop, and step", "[range]")
TEST_CASE ("range: forward iterator checks", "[range]")
TEST_CASE ("range: forward iterator with double, checks", "[range]")
TEST_CASE ("range: using doubles", "[range]")
TEST_CASE ("range: using doubles with start and stop", "[range]")
TEST_CASE ("range: using doubles with start, stop and step", "[range]")
TEST_CASE ("range: using doubles with negative", "[range]")
TEST_CASE ("range: using doubles with uneven step", "[range]")
TEST_CASE ("range: using doubles detects empty ranges", "[range]")
TEST_CASE ("range: iterator meets forward iterator requirements", "[range]")
Typedef Documentation
FVec
using FVec = const std::vector<double>
Definition at line 212 of file test_range.cpp.
Vec
using Vec = const std::vector<int>
Definition at line 10 of file test_range.cpp.
Function Documentation
TEST_CASE() [1/24]
TEST_CASE ("range: works with only stop" , "" [range])
Definition at line 13 of file test_range.cpp.
References NS1::begin(), NS1::end(), and iter::range().
Referenced by for(), and TEST_CASE().
TEST_CASE() [2/24]
TEST_CASE ("range: works with start and stop" , "" [range])
Definition at line 21 of file test_range.cpp.
References NS1::begin(), NS1::end(), and iter::range().
TEST_CASE() [3/24]
TEST_CASE ("range: works with positive step, 1" , "" [range])
Definition at line 29 of file test_range.cpp.
References NS1::begin(), NS1::end(), and iter::range().
TEST_CASE() [4/24]
TEST_CASE ("range(0) is empty" , "" [range])
Definition at line 37 of file test_range.cpp.
References NS1::begin(), NS1::end(), and iter::range().
TEST_CASE() [5/24]
TEST_CASE ("range: postfix++" , "" [range])
Definition at line 42 of file test_range.cpp.
References NS1::begin(), and iter::range().
TEST_CASE() [6/24]
TEST_CASE (" start, stop produces empty range" , "" [range])
Definition at line 49 of file test_range.cpp.
References NS1::begin(), NS1::end(), and iter::range().
TEST_CASE() [7/24]
TEST_CASE ()
Definition at line 55 of file test_range.cpp.
References NS1::begin(), NS1::end(), and iter::range().
TEST_CASE() [8/24]
TEST_CASE ("range: with only a negative stop is empty" , "" [range])
Definition at line 61 of file test_range.cpp.
References NS1::begin(), NS1::end(), and iter::range().
TEST_CASE() [9/24]
TEST_CASE ("range: works with negative step" , "" [range])
Definition at line 68 of file test_range.cpp.
References NS1::begin(), NS1::end(), and iter::range().
TEST_CASE() [10/24]
TEST_CASE ("range: stops short when step doesn't divide stop-start" , "" [range])
Definition at line 76 of file test_range.cpp.
References NS1::begin(), NS1::end(), and iter::range().
TEST_CASE() [11/24]
TEST_CASE ("range: stops short when step, stop-start" , "" [range])
Definition at line 84 of file test_range.cpp.
References NS1::begin(), NS1::end(), and iter::range().
TEST_CASE() [12/24]
TEST_CASE ("range: step size of 0 gives an empty range" , "" [range])
Definition at line 90 of file test_range.cpp.
References NS1::begin(), NS1::end(), and iter::range().
TEST_CASE() [13/24]
TEST_CASE ("range: can create constexpr ranges" , "" [range])
Definition at line 97 of file test_range.cpp.
References i, and iter::range().
TEST_CASE() [14/24]
TEST_CASE ("range: const iterators compare to non-const iterators" , "" [range])
Definition at line 115 of file test_range.cpp.
References NS1::begin(), NS1::end(), and iter::range().
TEST_CASE() [15/24]
TEST_CASE ("range: works with a variable start, stop , and step" , "" [range])
Definition at line 121 of file test_range.cpp.
References NS1::begin(), NS1::end(), and iter::range().
TEST_CASE() [16/24]
TEST_CASE ("range: forward iterator checks" , "" [range])
Definition at line 173 of file test_range.cpp.
References NS1::begin(), NS1::end(), and iter::range().
TEST_CASE() [17/24]
TEST_CASE ("range: forward iterator with double, checks" , "" [range])
Definition at line 195 of file test_range.cpp.
References NS1::begin(), NS1::end(), and iter::range().
TEST_CASE() [18/24]
TEST_CASE ("range: using doubles" , "" [range])
Definition at line 214 of file test_range.cpp.
References NS1::begin(), NS1::end(), and iter::range().
TEST_CASE() [19/24]
TEST_CASE ("range: using doubles with start and stop" , "" [range])
Definition at line 221 of file test_range.cpp.
References NS1::begin(), NS1::end(), and iter::range().
TEST_CASE() [20/24]
TEST_CASE ("range: using doubles with start, stop and step" , "" [range])
Definition at line 228 of file test_range.cpp.
References NS1::begin(), NS1::end(), and iter::range().
TEST_CASE() [21/24]
TEST_CASE ("range: using doubles with negative" , "" [range])
Definition at line 235 of file test_range.cpp.
References NS1::begin(), NS1::end(), and iter::range().
TEST_CASE() [22/24]
TEST_CASE ("range: using doubles with uneven step" , "" [range])
Definition at line 242 of file test_range.cpp.
References NS1::begin(), NS1::end(), and iter::range().
TEST_CASE() [23/24]
TEST_CASE ("range: using doubles detects empty ranges" , "" [range])
Definition at line 249 of file test_range.cpp.
References NS1::begin(), NS1::end(), and iter::range().
TEST_CASE() [24/24]
TEST_CASE ("range: iterator meets forward iterator requirements" , "" [range])
Definition at line 257 of file test_range.cpp.
References NS1::begin(), and iter::range().