CkPttnCpp: iter::impl::get_iters Namespace Reference
iter::impl::get_iters Namespace Reference
Functions
template<typename T , std::size_t N>
T * get_begin_impl (T(&array)[N], int)
template<typename T , typename I = decltype(std::declval<T&>().begin())>
I get_begin_impl (T &r, int)
template<typename T , typename I = decltype(begin(std::declval<T&>()))>
I get_begin_impl (T &r, long)
template<typename T >
auto get_begin (T &t) -> decltype(get_begin_impl(std::declval< T &>(), 42))
template<typename T , std::size_t N>
T * get_end_impl (T(&array)[N], int)
template<typename T , typename I = decltype(std::declval<T&>().end())>
I get_end_impl (T &r, int)
template<typename T , typename I = decltype(end(std::declval<T&>()))>
I get_end_impl (T &r, long)
template<typename T >
auto get_end (T &t) -> decltype(get_end_impl(std::declval< T &>(), 42))
Function Documentation
get_begin()
template<typename T > auto iter::impl::get_iters::get_begin (T & t) -> decltype(get_begin_impl(std::declval<T&>(), 42))
Definition at line 48 of file iterbase.hpp.
References get_begin_impl().
Referenced by iter::impl::Cycler< Container >::begin(), iter::impl::StarMapper< Func, Container >::begin(), iter::impl::Sliced< Container, DifferenceType >::begin(), iter::impl::WindowSlider< Container >::begin(), iter::impl::Zipped< TupleType, Is >::begin(), iter::impl::Accumulator< Container, AccumulateFunc >::begin(), iter::impl::Compressed< Container, Selector >::begin(), iter::impl::Permuter< Container >::begin(), iter::impl::Dropper< FilterFunc, Container >::begin(), iter::impl::Taker< FilterFunc, Container >::begin(), iter::impl::ZippedLongest< TupleType, Is >::begin(), iter::impl::Chunker< Container >::begin(), iter::impl::Enumerable< Container, Index >::begin(), iter::impl::Filtered< PredicateFlipper< FilterFunc >, Container >::begin(), iter::impl::Chained< TupType, Is >::begin(), iter::impl::Productor< TupleType, Is >::begin(), iter::impl::GroupProducer< Container, KeyFunc >::begin(), iter::impl::ChainedFromIterable< Container >::begin(), iter::impl::dumb_size(), get_end(), iter::impl::Combinator< Container >::Iterator< ContainerT >::Iterator(), iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::Iterator(), iter::impl::Powersetter< Container >::Iterator< ContainerT >::Iterator(), iter::impl::Permuter< Container >::Iterator< ContainerT >::Iterator(), iter::impl::UniqueJustseenFn::operator()(), iter::impl::Powersetter< Container >::Iterator< ContainerT >::operator++(), iter::impl::Permuter< Container >::Iterator< ContainerT >::operator++(), iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >::populate_const_sorted_iters(), iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >::populate_sorted_iters(), iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< Container >::SortedItersHolder(), TEST_CASE(), and iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::update_sub_iterable().
get_begin_impl() [1/3]
template<typename T , std::size_t N> T* iter::impl::get_iters::get_begin_impl (T(&) array[N], int)
Definition at line 31 of file iterbase.hpp.
Referenced by get_begin().
get_begin_impl() [2/3]
template<typename T , typename I = decltype(std::declval<T&>().begin())> I iter::impl::get_iters::get_begin_impl (T & r, int)
Definition at line 37 of file iterbase.hpp.
get_begin_impl() [3/3]
template<typename T , typename I = decltype(begin(std::declval<T&>()))> I iter::impl::get_iters::get_begin_impl (T & r, long)
Definition at line 43 of file iterbase.hpp.
References NS1::begin().
get_end()
template<typename T > auto iter::impl::get_iters::get_end (T & t) -> decltype(get_end_impl(std::declval<T&>(), 42))
Definition at line 71 of file iterbase.hpp.
References get_begin(), and get_end_impl().
Referenced by iter::impl::Cycler< Container >::begin(), iter::impl::Sliced< Container, DifferenceType >::begin(), iter::impl::WindowSlider< Container >::begin(), iter::impl::Accumulator< Container, AccumulateFunc >::begin(), iter::impl::Compressed< Container, Selector >::begin(), iter::impl::Dropper< FilterFunc, Container >::begin(), iter::impl::Permuter< Container >::begin(), iter::impl::Taker< FilterFunc, Container >::begin(), iter::impl::ZippedLongest< TupleType, Is >::begin(), iter::impl::Chunker< Container >::begin(), iter::impl::Filtered< PredicateFlipper< FilterFunc >, Container >::begin(), iter::impl::Productor< TupleType, Is >::begin(), iter::impl::Chained< TupType, Is >::begin(), iter::impl::GroupProducer< Container, KeyFunc >::begin(), iter::impl::ChainedFromIterable< Container >::begin(), iter::impl::dumb_size(), iter::impl::Cycler< Container >::end(), iter::impl::StarMapper< Func, Container >::end(), iter::impl::Zipped< TupleType, Is >::end(), iter::impl::Accumulator< Container, AccumulateFunc >::end(), iter::impl::Sliced< Container, DifferenceType >::end(), iter::impl::WindowSlider< Container >::end(), iter::impl::Dropper< FilterFunc, Container >::end(), iter::impl::Permuter< Container >::end(), iter::impl::Compressed< Container, Selector >::end(), iter::impl::Taker< FilterFunc, Container >::end(), iter::impl::ZippedLongest< TupleType, Is >::end(), iter::impl::Chunker< Container >::end(), iter::impl::Enumerable< Container, Index >::end(), iter::impl::Filtered< PredicateFlipper< FilterFunc >, Container >::end(), iter::impl::Chained< TupType, Is >::end(), iter::impl::Productor< TupleType, Is >::end(), iter::impl::GroupProducer< Container, KeyFunc >::end(), iter::impl::ChainedFromIterable< Container >::end(), iter::impl::Combinator< Container >::Iterator< ContainerT >::Iterator(), iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::Iterator(), iter::impl::Powersetter< Container >::Iterator< ContainerT >::Iterator(), iter::impl::Permuter< Container >::Iterator< ContainerT >::Iterator(), iter::impl::Powersetter< Container >::Iterator< ContainerT >::operator++(), iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::operator++(), iter::impl::Permuter< Container >::Iterator< ContainerT >::operator++(), iter::impl::Combinator< Container >::Iterator< ContainerT >::operator++(), iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >::populate_const_sorted_iters(), iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >::populate_sorted_iters(), iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< Container >::SortedItersHolder(), and iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::update_sub_iterable().
get_end_impl() [1/3]
template<typename T , std::size_t N> T* iter::impl::get_iters::get_end_impl (T(&) array[N], int)
Definition at line 54 of file iterbase.hpp.
Referenced by get_end().
get_end_impl() [2/3]
template<typename T , typename I = decltype(std::declval<T&>().end())> I iter::impl::get_iters::get_end_impl (T & r, int)
Definition at line 60 of file iterbase.hpp.
get_end_impl() [3/3]
template<typename T , typename I = decltype(end(std::declval<T&>()))> I iter::impl::get_iters::get_end_impl (T & r, long)
Definition at line 66 of file iterbase.hpp.
References NS1::end().