CkPttnCpp: DifferentTypes::iterator Struct Reference
DifferentTypes::iterator Struct Reference
Public Member Functions
iterator ()
iterator (int i)
bool operator!= (const iterator &other) const
bool operator!= (const end_iterator &) const
iterator & operator++ ()
const int & operator* () const
const int & value () const
Public Attributes
std::vector< int > value_
Detailed Description
Definition at line 39 of file test_iterator_wrapper.cpp.
Constructor & Destructor Documentation
iterator() [1/2]
DifferentTypes::iterator::iterator () inline
Definition at line 40 of file test_iterator_wrapper.cpp.
iterator() [2/2]
DifferentTypes::iterator::iterator (int i) inline
Definition at line 43 of file test_iterator_wrapper.cpp.
Member Function Documentation
operator!=() [1/2]
bool DifferentTypes::iterator::operator!= (const iterator & other) const inline
Definition at line 45 of file test_iterator_wrapper.cpp.
References value().
operator!=() [2/2]
bool DifferentTypes::iterator::operator!= (const end_iterator &) const inline
Definition at line 48 of file test_iterator_wrapper.cpp.
operator*()
const int& DifferentTypes::iterator::operator* () const inline
Definition at line 55 of file test_iterator_wrapper.cpp.
operator++()
iterator& DifferentTypes::iterator::operator++ () inline
Definition at line 51 of file test_iterator_wrapper.cpp.
References SameTypes::iterator::value_.
value()
const int& DifferentTypes::iterator::value () const inline
Definition at line 59 of file test_iterator_wrapper.cpp.
References SameTypes::iterator::value_.
Referenced by operator!=(), and DifferentTypes::end_iterator::operator!=().
Member Data Documentation
value_
std::vector<int> DifferentTypes::iterator::value_
Definition at line 62 of file test_iterator_wrapper.cpp.
The documentation for this struct was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_iterator_wrapper.cpp