CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_sliding_window.cpp File Reference
test_sliding_window.cpp File Reference
#include <sliding_window.hpp>
#include <array>
#include <string>
#include <utility>
#include <vector>
#include "catch.hpp"
#include "helpers.hpp"
Typedefs
using Vec = const std::vector< int >
template<typename T >
using ImpT = decltype(sliding_window(std::declval< T >(), 1))
Functions
TEST_CASE ("sliding_window: window of size 3", "[sliding_window]")
TEST_CASE ("sliding_window: const iteration", "[sliding_window][const]")
TEST_CASE ("sliding_window: const iterators can be compared to non-const iterators", "[sliding_window][const]")
TEST_CASE ("sliding_window: Works with different begin and end types", "[sliding_window]")
TEST_CASE ("sliding window: oversized window is empty", "[sliding_window]")
TEST_CASE ("sliding window: window size == len(iterable)", "[sliding_window]")
TEST_CASE ("sliding window: empty iterable is empty", "[sliding_window]")
TEST_CASE ("sliding window: window size of 1", "[sliding_window]")
TEST_CASE ("sliding window: window size of 0", "[sliding_window]")
TEST_CASE ("sliding window: moves rvalues and binds to lvalues", "[sliding_window]")
TEST_CASE ("sliding window: doesn't copy elements", "[sliding_window]")
TEST_CASE ("sliding_window: iterator meets requirements", "[sliding_window]")
TEST_CASE ("sliding_window: has correct ctor and assign ops", "[sliding_window]")
Typedef Documentation
ImpT
template<typename T > using ImpT = decltype(sliding_window(std::declval<T>(), 1))
Definition at line 129 of file test_sliding_window.cpp.
Vec
using Vec = const std::vector<int>
Definition at line 12 of file test_sliding_window.cpp.
Function Documentation
TEST_CASE() [1/13]
TEST_CASE ("sliding_window: window of size 3" , "" [sliding_window])
Definition at line 14 of file test_sliding_window.cpp.
References NS1::begin(), NS1::end(), and iter::sliding_window.
TEST_CASE() [2/13]
TEST_CASE ("sliding_window: const iteration" , "" [sliding_window][const ])
Definition at line 31 of file test_sliding_window.cpp.
References NS1::begin(), NS1::end(), and iter::sliding_window.
TEST_CASE() [3/13]
TEST_CASE ("sliding_window: const iterators can be compared to non-const iterators" , "" [sliding_window][const ])
Definition at line 42 of file test_sliding_window.cpp.
References NS1::begin(), NS1::end(), and iter::sliding_window.
TEST_CASE() [4/13]
TEST_CASE ("sliding_window: Works with different begin and end types" , "" [sliding_window])
Definition at line 50 of file test_sliding_window.cpp.
References NS1::begin(), NS1::end(), and iter::sliding_window.
TEST_CASE() [5/13]
TEST_CASE ("sliding window: oversized window is empty" , "" [sliding_window])
Definition at line 62 of file test_sliding_window.cpp.
References NS1::begin(), NS1::end(), and iter::sliding_window.
TEST_CASE() [6/13]
TEST_CASE ()
Definition at line 68 of file test_sliding_window.cpp.
References NS1::begin(), NS1::end(), and iter::sliding_window.
TEST_CASE() [7/13]
TEST_CASE ("sliding window: empty iterable is empty" , "" [sliding_window])
Definition at line 81 of file test_sliding_window.cpp.
References NS1::begin(), NS1::end(), and iter::sliding_window.
TEST_CASE() [8/13]
TEST_CASE ("sliding window: window size of 1" , "" [sliding_window])
Definition at line 87 of file test_sliding_window.cpp.
References NS1::begin(), NS1::end(), and iter::sliding_window.
TEST_CASE() [9/13]
TEST_CASE ("sliding window: window size of 0" , "" [sliding_window])
Definition at line 100 of file test_sliding_window.cpp.
References NS1::begin(), NS1::end(), and iter::sliding_window.
TEST_CASE() [10/13]
TEST_CASE ("sliding window: moves rvalues and binds to lvalues" , "" [sliding_window])
Definition at line 106 of file test_sliding_window.cpp.
References iter::sliding_window.
TEST_CASE() [11/13]
TEST_CASE ("sliding window: doesn't copy elements" , "" [sliding_window])
Definition at line 115 of file test_sliding_window.cpp.
References NS1::begin(), i, and iter::sliding_window.
TEST_CASE() [12/13]
TEST_CASE ("sliding_window: iterator meets requirements" , "" [sliding_window])
Definition at line 122 of file test_sliding_window.cpp.
References NS1::begin(), and iter::sliding_window.
TEST_CASE() [13/13]
TEST_CASE ("sliding_window: has correct ctor and assign ops" , "" [sliding_window])
Definition at line 130 of file test_sliding_window.cpp.