CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_powerset.cpp File Reference
test_powerset.cpp File Reference
#include <powerset.hpp>
#include "helpers.hpp"
#include <iterator>
#include <set>
#include <string>
#include <vector>
#include "catch.hpp"
Macros
#define CHAR_RANGE_DEFAULT_CONSTRUCTIBLE
Typedefs
using IntPermSet = std::multiset< std::multiset< int > >
template<typename T >
using ImpT = decltype(powerset(std::declval< T >()))
Functions
TEST_CASE ("powerset: basic test, [1, 2, 3]", "[powerset]")
TEST_CASE ("powerset: const iteration", "[powerset][const]")
TEST_CASE ("powerset: Works with different begin and end types", "[powerset]")
TEST_CASE ("powerset: empty sequence gives only empty set", "[powerset]")
TEST_CASE ("powerset: iterators can be compared", "[powerset]")
TEST_CASE ("powerset: iterator copy ctor is correct", "[powerset]")
TEST_CASE ("powerset: binds to lvalues, moves rvalues", "[powerset]")
TEST_CASE ("powerset: doesn't move or copy elements of iterable", "[powerset]")
TEST_CASE ("powerset: iterator meets requirements", "[powerset]")
TEST_CASE ("powerset: has correct ctor and assign ops", "[powerset]")
Macro Definition Documentation
CHAR_RANGE_DEFAULT_CONSTRUCTIBLE
#define CHAR_RANGE_DEFAULT_CONSTRUCTIBLE
Definition at line 3 of file test_powerset.cpp.
Typedef Documentation
ImpT
template<typename T > using ImpT = decltype(powerset(std::declval<T>()))
Definition at line 155 of file test_powerset.cpp.
IntPermSet
using IntPermSet = std::multiset<std::multiset<int> >
Definition at line 15 of file test_powerset.cpp.
Function Documentation
TEST_CASE() [1/10]
TEST_CASE ("powerset: basic test, [1, 2, 3] " , "" [powerset])
Definition at line 17 of file test_powerset.cpp.
References NS1::begin(), NS1::end(), and iter::powerset.
Referenced by TEST_CASE().
TEST_CASE() [2/10]
TEST_CASE ("powerset: const iteration" , "" [powerset][const ])
Definition at line 36 of file test_powerset.cpp.
References NS1::begin(), NS1::end(), iter::powerset, and TEST_CASE().
TEST_CASE() [3/10]
TEST_CASE ("powerset: Works with different begin and end types" , "" [powerset])
Definition at line 59 of file test_powerset.cpp.
References NS1::begin(), NS1::end(), and iter::powerset.
TEST_CASE() [4/10]
TEST_CASE ("powerset: empty sequence gives only empty set" , "" [powerset])
Definition at line 72 of file test_powerset.cpp.
References NS1::begin(), NS1::end(), and iter::powerset.
TEST_CASE() [5/10]
TEST_CASE ("powerset: iterators can be compared" , "" [powerset])
Definition at line 81 of file test_powerset.cpp.
References NS1::begin(), NS1::end(), and iter::powerset.
TEST_CASE() [6/10]
TEST_CASE ("powerset: iterator copy ctor is correct" , "" [powerset])
Definition at line 113 of file test_powerset.cpp.
References NS1::begin(), NS1::end(), and iter::powerset.
TEST_CASE() [7/10]
TEST_CASE ("powerset: binds to lvalues, moves rvalues" , "" [powerset])
Definition at line 125 of file test_powerset.cpp.
References iter::powerset.
TEST_CASE() [8/10]
TEST_CASE ("powerset: doesn't move or copy elements of iterable" , "" [powerset])
Definition at line 137 of file test_powerset.cpp.
References i, and iter::powerset.
TEST_CASE() [9/10]
TEST_CASE ("powerset: iterator meets requirements" , "" [powerset])
Definition at line 146 of file test_powerset.cpp.
References NS1::begin(), and iter::powerset.
TEST_CASE() [10/10]
TEST_CASE ("powerset: has correct ctor and assign ops" , "" [powerset])
Definition at line 156 of file test_powerset.cpp.