CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_reversed.cpp File Reference
test_reversed.cpp File Reference
#include <reversed.hpp>
#include <array>
#include <string>
#include <utility>
#include <vector>
#include "catch.hpp"
#include "helpers.hpp"
Macros
#define DECLARE_REVERSE_ITERATOR
Typedefs
using Vec = const std::vector< int >
template<typename T >
using ImpT = decltype(reversed(std::declval< T >()))
Functions
TEST_CASE ("reversed: can reverse a vector", "[reversed]")
TEST_CASE ("reversed: const iteration", "[reversed][const]")
TEST_CASE ("reversed: const iterators can be compared to non-const iterators", "[reversed][const]")
TEST_CASE ("reversed: can reverse an array", "[reversed]")
TEST_CASE ("reversed: empty when iterable is empty", "[reversed]")
TEST_CASE ("reversed: moves rvalues and binds to lvalues", "[reversed]")
TEST_CASE ("reversed: doesn't move or copy elements of array", "[reversed]")
TEST_CASE ("reversed: with iterable doesn't move or copy elems", "[reversed]")
TEST_CASE ("reversed: iterator meets requirements", "[reversed]")
TEST_CASE ("reversed: has correct ctor and assign ops", "[reversed]")
Macro Definition Documentation
DECLARE_REVERSE_ITERATOR
#define DECLARE_REVERSE_ITERATOR
Definition at line 10 of file test_reversed.cpp.
Typedef Documentation
ImpT
template<typename T > using ImpT = decltype(reversed(std::declval<T>()))
Definition at line 111 of file test_reversed.cpp.
Vec
using Vec = const std::vector<int>
Definition at line 15 of file test_reversed.cpp.
Function Documentation
TEST_CASE() [1/10]
TEST_CASE ("reversed: can reverse a vector" , "" [reversed])
Definition at line 17 of file test_reversed.cpp.
References NS1::begin(), NS1::end(), and iter::reversed.
Referenced by TEST_CASE().
TEST_CASE() [2/10]
TEST_CASE ("reversed: const iteration" , "" [reversed][const ])
Definition at line 34 of file test_reversed.cpp.
References NS1::begin(), NS1::end(), and iter::reversed.
TEST_CASE() [3/10]
TEST_CASE ("reversed: const iterators can be compared to non-const iterators" , "" [reversed][const ])
Definition at line 42 of file test_reversed.cpp.
References NS1::begin(), NS1::end(), iter::reversed, and TEST_CASE().
TEST_CASE() [4/10]
TEST_CASE ("reversed: can reverse an array" , "" [reversed])
Definition at line 60 of file test_reversed.cpp.
References NS1::begin(), NS1::end(), and iter::reversed.
TEST_CASE() [5/10]
TEST_CASE ("reversed: empty when iterable is empty" , "" [reversed])
Definition at line 70 of file test_reversed.cpp.
References NS1::begin(), NS1::end(), and iter::reversed.
TEST_CASE() [6/10]
TEST_CASE ("reversed: moves rvalues and binds to lvalues" , "" [reversed])
Definition at line 76 of file test_reversed.cpp.
References iter::reversed.
TEST_CASE() [7/10]
TEST_CASE ("reversed: doesn't move or copy elements of array" , "" [reversed])
Definition at line 86 of file test_reversed.cpp.
References i, and iter::reversed.
TEST_CASE() [8/10]
TEST_CASE ("reversed: with iterable doesn't move or copy elems" , "" [reversed])
Definition at line 93 of file test_reversed.cpp.
References i, and iter::reversed.
TEST_CASE() [9/10]
TEST_CASE ("reversed: iterator meets requirements" , "" [reversed])
Definition at line 100 of file test_reversed.cpp.
References NS1::begin(), and iter::reversed.
TEST_CASE() [10/10]
TEST_CASE ("reversed: has correct ctor and assign ops" , "" [reversed])
Definition at line 112 of file test_reversed.cpp.