CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_enumerate.cpp File Reference
test_enumerate.cpp File Reference
#include <enumerate.hpp>
#include "helpers.hpp"
#include <iterator>
#include <sstream>
#include <string>
#include <utility>
#include <vector>
#include "catch.hpp"
Namespaces
Catch
Typedefs
using Vec = std::vector< std::pair< std::size_t, char > >
template<typename T >
using ImpT = decltype(enumerate(std::declval< T >()))
Functions
template<typename A , typename B >
std::string Catch::toString (const std::pair< A, B > &p)
TEST_CASE ("Basic Functioning enumerate", "[enumerate]")
TEST_CASE ("const enumerate", "[enumerate][const]")
TEST_CASE ("enumerate: can modify underlying sequence", "[enumerate]")
TEST_CASE ("enumerate: const iterators can be compared", "[enumerate][const]")
TEST_CASE ("enumerate: has .index, .element, .first, and .second")
TEST_CASE ("Empty enumerate", "[enumerate]")
TEST_CASE ("Postfix ++ enumerate", "[enumerate]")
TEST_CASE ("enumerate: structured bindings", "[enumerate]")
TEST_CASE ("enumerate: with starting value", "[enumerate]")
TEST_CASE ("Modifications through enumerate affect container", "[enumerate]")
TEST_CASE ("enumerate with static array works", "[enumerate]")
TEST_CASE ("binds reference when it should", "[enumerate]")
TEST_CASE ("moves rvalues into enumerable object", "[enumerate]")
TEST_CASE ("enumerate: operator->", "[enumerate]")
TEST_CASE ("enumerate: index and element", "[enumerate]")
TEST_CASE ("enumerate: index and element through arrow", "[enumerate]")
TEST_CASE ("Works with const iterable", "[enumerate]")
TEST_CASE ("Doesn't move or copy elements of iterable", "[enumerate]")
TEST_CASE ("enumerate: iterator meets requirements", "[enumerate]")
TEST_CASE ("enumerate: works with pipe", "[enumerate]")
TEST_CASE ("enumerate: works index and pipe", "[enumerate]")
TEST_CASE ("enumerate: Works with different begin and end types", "[enumerate]")
TEST_CASE ("enumerate: has correct ctor and assign ops", "[enumerate]")
Typedef Documentation
ImpT
template<typename T > using ImpT = decltype(enumerate(std::declval<T>()))
Definition at line 256 of file test_enumerate.cpp.
Vec
using Vec = std::vector<std::pair<std::size_t, char> >
Definition at line 22 of file test_enumerate.cpp.
Function Documentation
TEST_CASE() [1/23]
TEST_CASE ("Basic Functioning enumerate" , "" [enumerate])
Definition at line 28 of file test_enumerate.cpp.
References NS1::begin(), NS1::end(), and iter::enumerate.
TEST_CASE() [2/23]
TEST_CASE ("const enumerate" , "" [enumerate][const ])
Definition at line 37 of file test_enumerate.cpp.
References NS1::begin(), NS1::end(), and iter::enumerate.
TEST_CASE() [3/23]
TEST_CASE ("enumerate: can modify underlying sequence" , "" [enumerate])
Definition at line 59 of file test_enumerate.cpp.
References iter::enumerate, and i.
TEST_CASE() [4/23]
TEST_CASE ("enumerate: const iterators can be compared" , "" [enumerate][const ])
Definition at line 67 of file test_enumerate.cpp.
References NS1::begin(), NS1::end(), and iter::enumerate.
TEST_CASE() [5/23]
TEST_CASE ("enumerate: has . index, . element, . first, and .second")
Definition at line 73 of file test_enumerate.cpp.
References NS1::begin(), and iter::enumerate.
TEST_CASE() [6/23]
TEST_CASE ("Empty enumerate" , "" [enumerate])
Definition at line 81 of file test_enumerate.cpp.
References NS1::begin(), NS1::end(), and iter::enumerate.
TEST_CASE() [7/23]
TEST_CASE ("Postfix ++ enumerate" , "" [enumerate])
Definition at line 87 of file test_enumerate.cpp.
References NS1::begin(), and iter::enumerate.
TEST_CASE() [8/23]
TEST_CASE ("enumerate: structured bindings" , "" [enumerate])
Definition at line 95 of file test_enumerate.cpp.
References NS1::begin(), iter::enumerate, and i.
TEST_CASE() [9/23]
TEST_CASE ("enumerate: with starting value" , "" [enumerate])
Definition at line 112 of file test_enumerate.cpp.
References NS1::begin(), NS1::end(), and iter::enumerate.
TEST_CASE() [10/23]
TEST_CASE ("Modifications through enumerate affect container" , "" [enumerate])
Definition at line 121 of file test_enumerate.cpp.
References iter::enumerate.
TEST_CASE() [11/23]
TEST_CASE ("enumerate with static array works" , "" [enumerate])
Definition at line 131 of file test_enumerate.cpp.
References NS1::begin(), NS1::end(), and iter::enumerate.
TEST_CASE() [12/23]
TEST_CASE ("binds reference when it should" , "" [enumerate])
Definition at line 151 of file test_enumerate.cpp.
References iter::enumerate.
TEST_CASE() [13/23]
TEST_CASE ("moves rvalues into enumerable object" , "" [enumerate])
Definition at line 158 of file test_enumerate.cpp.
References iter::enumerate.
TEST_CASE() [14/23]
TEST_CASE ("enumerate: operator->" , "" [enumerate])
Definition at line 165 of file test_enumerate.cpp.
References NS1::begin(), and iter::enumerate.
TEST_CASE() [15/23]
TEST_CASE ("enumerate: index and element" , "" [enumerate])
Definition at line 173 of file test_enumerate.cpp.
References NS1::begin(), and iter::enumerate.
TEST_CASE() [16/23]
TEST_CASE ("enumerate: index and element through arrow" , "" [enumerate])
Definition at line 188 of file test_enumerate.cpp.
References NS1::begin(), NS1::end(), and iter::enumerate.
TEST_CASE() [17/23]
TEST_CASE ("Works with const iterable" , "" [enumerate])
Definition at line 207 of file test_enumerate.cpp.
References NS1::begin(), NS1::end(), and iter::enumerate.
TEST_CASE() [18/23]
TEST_CASE ("Doesn't move or copy elements of iterable" , "" [enumerate])
Definition at line 215 of file test_enumerate.cpp.
References iter::enumerate, and i.
TEST_CASE() [19/23]
TEST_CASE ("enumerate: iterator meets requirements" , "" [enumerate])
Definition at line 222 of file test_enumerate.cpp.
References NS1::begin(), and iter::enumerate.
TEST_CASE() [20/23]
TEST_CASE ("enumerate: works with pipe" , "" [enumerate])
Definition at line 228 of file test_enumerate.cpp.
References NS1::begin(), NS1::end(), and iter::enumerate.
TEST_CASE() [21/23]
TEST_CASE ("enumerate: works index and pipe" , "" [enumerate])
Definition at line 237 of file test_enumerate.cpp.
References NS1::begin(), NS1::end(), and iter::enumerate.
TEST_CASE() [22/23]
TEST_CASE ("enumerate: Works with different begin and end types" , "" [enumerate])
Definition at line 246 of file test_enumerate.cpp.
References iter::enumerate.
TEST_CASE() [23/23]
TEST_CASE ("enumerate: has correct ctor and assign ops" , "" [enumerate])
Definition at line 257 of file test_enumerate.cpp.