CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_unique_everseen.cpp File Reference
test_unique_everseen.cpp File Reference
#include <unique_everseen.hpp>
#include "helpers.hpp"
#include <iterator>
#include <string>
#include <vector>
#include "catch.hpp"
Typedefs
using Vec = const std::vector< int >
template<typename T >
using ImpT = decltype(unique_everseen(std::declval< T >()))
Functions
TEST_CASE ("unique everseen: adjacent repeating values", "[unique_everseen]")
TEST_CASE ("unique everseen: const iteration", "[unique_everseen][const]")
TEST_CASE ("unique everseen: const iterators can be compared to non-const iterators", "[unique_everseen][const]")
TEST_CASE ("unique everseen: nonadjacent repeating values", "[unique_everseen]")
TEST_CASE ("unique everseen: moves rvalues, binds to lvalues", "[unique_everseen]")
TEST_CASE ("unique everseen: Works with different begin and end types", "[unique_everseen]")
TEST_CASE ("unique_everseen: iterator meets requirements", "[unique_everseen]")
TEST_CASE ("unique_everseen: has correct ctor and assign ops", "[unique_everseen]")
Typedef Documentation
ImpT
template<typename T > using ImpT = decltype(unique_everseen(std::declval<T>()))
Definition at line 82 of file test_unique_everseen.cpp.
Vec
using Vec = const std::vector<int>
Definition at line 13 of file test_unique_everseen.cpp.
Function Documentation
TEST_CASE() [1/8]
TEST_CASE ("unique everseen: adjacent repeating values" , "" [unique_everseen])
Definition at line 15 of file test_unique_everseen.cpp.
References NS1::begin(), NS1::end(), and iter::unique_everseen.
TEST_CASE() [2/8]
TEST_CASE ("unique everseen: const iteration" , "" [unique_everseen][const ])
Definition at line 23 of file test_unique_everseen.cpp.
References NS1::begin(), NS1::end(), and iter::unique_everseen.
TEST_CASE() [3/8]
TEST_CASE ("unique everseen: const iterators can be compared to non-const iterators" , "" [unique_everseen][const ])
Definition at line 31 of file test_unique_everseen.cpp.
References NS1::begin(), NS1::end(), and iter::unique_everseen.
TEST_CASE() [4/8]
TEST_CASE ("unique everseen: nonadjacent repeating values" , "" [unique_everseen])
Definition at line 39 of file test_unique_everseen.cpp.
References NS1::begin(), NS1::end(), and iter::unique_everseen.
TEST_CASE() [5/8]
TEST_CASE ("unique everseen: moves rvalues, binds to lvalues" , "" [unique_everseen])
Definition at line 55 of file test_unique_everseen.cpp.
References iter::unique_everseen.
TEST_CASE() [6/8]
TEST_CASE ("unique everseen: Works with different begin and end types" , "" [unique_everseen])
Definition at line 65 of file test_unique_everseen.cpp.
References iter::unique_everseen.
TEST_CASE() [7/8]
TEST_CASE ("unique_everseen: iterator meets requirements" , "" [unique_everseen])
Definition at line 75 of file test_unique_everseen.cpp.
References NS1::begin(), and iter::unique_everseen.
TEST_CASE() [8/8]
TEST_CASE ("unique_everseen: has correct ctor and assign ops" , "" [unique_everseen])
Definition at line 83 of file test_unique_everseen.cpp.