CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_chain.cpp File Reference
test_chain.cpp File Reference
#include <chain.hpp>
#include "helpers.hpp"
#include <iterator>
#include <list>
#include <string>
#include <utility>
#include <vector>
#include "catch.hpp"
Typedefs
using Vec = const std::vector< char >
template<typename... Ts>
using ImpT = decltype(chain(std::declval< Ts >()...))
template<typename T >
using ImpT2 = decltype(chain.from_iterable(std::declval< T >()))
Functions
TEST_CASE ("chain: three strings", "[chain]")
TEST_CASE ("chain: const iteration", "[chain][const]")
TEST_CASE ("chain: with different container types", "[chain]")
TEST_CASE ("chain: where one container has different begin and end types", "[chain]")
TEST_CASE ("chain: handles empty containers", "[chain]")
TEST_CASE ("chain: with only empty containers", "[chain]")
TEST_CASE ("chain: doesn't move or copy elements of iterable", "[chain]")
TEST_CASE ("chain: binds reference to lvalue and moves rvalue", "[chain]")
TEST_CASE ("chain: operator==", "[chain]")
TEST_CASE ("chain: postfix ++", "[chain]")
TEST_CASE ("chain: iterator meets requirements", "[chain]")
TEST_CASE ("chain: has correct ctor and assign ops", "[chain]")
TEST_CASE ("chain.from_iterable: basic test", "[chain.from_iterable]")
TEST_CASE ("chain.from_iterable: const iteration", "[chain.from_iterable][const]")
TEST_CASE ("chain.from_iterable: const iterators can be compared to non-const " "iterators", "[chain.from_iterable][const]")
TEST_CASE ("chain.fromm_iterable: Works with different begin and end types", "[chain.from_iterable]")
TEST_CASE ("chain.from_iterable: Works with empty subiterable", "[chain.from_iterable]")
TEST_CASE ("chain.from_iterable: iterators cant be copy constructed " "and assigned", "[chain.from_iterable]")
TEST_CASE ("chain.from_iterable: postfix ++", "[chain.from_iterable]")
TEST_CASE ("chain.from_iterable: operator->", "[chain.from_iterable]")
TEST_CASE ("chain.from_iterable: moves rvalues and binds ref to lvalues", "[chain.from_iterable]")
TEST_CASE ("chain.from_iterable: empty", "[chain.from_iterable]")
TEST_CASE ("chain.from_iterable: iterator meets requirements", "[chain.from_iterable]")
TEST_CASE ("chain.from_iterable: has correct ctor and assign ops", "[chain.from_iterable]")
Typedef Documentation
ImpT
template<typename... Ts> using ImpT = decltype(chain(std::declval<Ts>()...))
Definition at line 185 of file test_chain.cpp.
ImpT2
template<typename T > using ImpT2 = decltype(chain.from_iterable(std::declval<T>()))
Definition at line 309 of file test_chain.cpp.
Vec
using Vec = const std::vector<char>
Definition at line 15 of file test_chain.cpp.
Function Documentation
TEST_CASE() [1/24]
TEST_CASE ("chain: three strings" , "" [chain])
Definition at line 17 of file test_chain.cpp.
References NS1::begin(), and NS1::end().
Referenced by TEST_CASE().
TEST_CASE() [2/24]
TEST_CASE ("chain: const iteration" , "" [chain][const ])
Definition at line 29 of file test_chain.cpp.
References NS1::begin(), NS1::end(), and TEST_CASE().
TEST_CASE() [3/24]
TEST_CASE ("chain: with different container types" , "" [chain])
Definition at line 49 of file test_chain.cpp.
References NS1::begin(), and NS1::end().
TEST_CASE() [4/24]
TEST_CASE ("chain: where one container has different begin and end types" , "" [chain])
Definition at line 61 of file test_chain.cpp.
References NS1::begin(), and NS1::end().
TEST_CASE() [5/24]
TEST_CASE ("chain: handles empty containers" , "" [chain])
Definition at line 74 of file test_chain.cpp.
References NS1::begin(), and NS1::end().
TEST_CASE() [6/24]
TEST_CASE ("chain: with only empty containers" , "" [chain])
Definition at line 124 of file test_chain.cpp.
References NS1::begin(), and NS1::end().
TEST_CASE() [7/24]
TEST_CASE ("chain: doesn't move or copy elements of iterable" , "" [chain])
Definition at line 142 of file test_chain.cpp.
References i.
TEST_CASE() [8/24]
TEST_CASE ("chain: binds reference to lvalue and moves rvalue" , "" [chain])
Definition at line 149 of file test_chain.cpp.
TEST_CASE() [9/24]
TEST_CASE ()
Definition at line 164 of file test_chain.cpp.
References NS1::begin(), and NS1::end().
TEST_CASE() [10/24]
TEST_CASE ("chain: postfix ++" , "" [chain])
Definition at line 170 of file test_chain.cpp.
References NS1::begin().
TEST_CASE() [11/24]
TEST_CASE ("chain: iterator meets requirements" , "" [chain])
Definition at line 178 of file test_chain.cpp.
References NS1::begin().
TEST_CASE() [12/24]
TEST_CASE ("chain: has correct ctor and assign ops" , "" [chain])
Definition at line 186 of file test_chain.cpp.
TEST_CASE() [13/24]
TEST_CASE ("chain.from_iterable: basic test" , "" [chain.from_iterable])
Definition at line 191 of file test_chain.cpp.
References NS1::begin(), and NS1::end().
TEST_CASE() [14/24]
TEST_CASE ("chain.from_iterable: const iteration" , "" [chain.from_iterable][const ])
Definition at line 207 of file test_chain.cpp.
References NS1::begin(), and NS1::end().
TEST_CASE() [15/24]
TEST_CASE ("chain.from_iterable: const iterators can be compared to non-const " "iterators" , "" [chain.from_iterable][const ])
Definition at line 217 of file test_chain.cpp.
References NS1::begin(), and NS1::end().
TEST_CASE() [16/24]
TEST_CASE ("chain.fromm_iterable: Works with different begin and end types" , "" [chain.from_iterable])
Definition at line 227 of file test_chain.cpp.
References NS1::begin(), and NS1::end().
TEST_CASE() [17/24]
TEST_CASE ("chain.from_iterable: Works with empty subiterable" , "" [chain.from_iterable])
Definition at line 236 of file test_chain.cpp.
References NS1::begin(), and NS1::end().
TEST_CASE() [18/24]
TEST_CASE ("chain.from_iterable: iterators cant be copy constructed " "and assigned" , "" [chain.from_iterable])
Definition at line 246 of file test_chain.cpp.
References NS1::begin(), and NS1::end().
TEST_CASE() [19/24]
TEST_CASE ("chain.from_iterable: postfix ++" , "" [chain.from_iterable])
Definition at line 267 of file test_chain.cpp.
References NS1::begin().
TEST_CASE() [20/24]
TEST_CASE ("chain.from_iterable: operator->" , "" [chain.from_iterable])
Definition at line 275 of file test_chain.cpp.
References NS1::begin().
TEST_CASE() [21/24]
TEST_CASE ("chain.from_iterable: moves rvalues and binds ref to lvalues" , "" [chain.from_iterable])
Definition at line 282 of file test_chain.cpp.
TEST_CASE() [22/24]
TEST_CASE ("chain.from_iterable: empty" , "" [chain.from_iterable])
Definition at line 295 of file test_chain.cpp.
References NS1::begin(), and NS1::end().
TEST_CASE() [23/24]
TEST_CASE ("chain.from_iterable: iterator meets requirements" , "" [chain.from_iterable])
Definition at line 301 of file test_chain.cpp.
References NS1::begin().
TEST_CASE() [24/24]
TEST_CASE ("chain.from_iterable: has correct ctor and assign ops" , "" [chain.from_iterable])
Definition at line 310 of file test_chain.cpp.