CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_zip_longest.cpp File Reference
test_zip_longest.cpp File Reference
#include <zip_longest.hpp>
#include "helpers.hpp"
#include <iostream>
#include <iterator>
#include <sstream>
#include <string>
#include <tuple>
#include <utility>
#include <vector>
#include "catch.hpp"
Namespaces
boost
Typedefs
template<typename... Ts>
using const_opt_tuple = std::tuple< boost::optional< const Ts & >... >
template<typename... Ts>
using ImpT = decltype(zip_longest(std::declval< Ts >()...))
Functions
template<typename T >
std::ostream & boost::operator<< (std::ostream &out, const optional< T > &opt)
TEST_CASE ("zip longest: correctly detects longest at any position", "[zip_longest]")
TEST_CASE ("zip_longest: three sequences, one sequence has different begin and end", "[zip_longest]")
TEST_CASE ("zip_longest: const iteration", "[zip_longest][const]")
TEST_CASE ("zip_longest: const iterators can be compared to non-const iterators", "[zip_longest][const]")
TEST_CASE ("zip longest: when all are empty, terminates right away", "[zip_longest]")
TEST_CASE ("zip longest: can modify zipped sequences", "[zip_longest]")
TEST_CASE ("zip longest: empty zip_longest() is empty", "[zip_longest]")
TEST_CASE ("zip_longest: binds to lvalues, moves rvalues", "[zip_longest]")
TEST_CASE ("zip_longest: doesn't move or copy elements", "[zip_longest]")
TEST_CASE ("zip_longest: iterator meets requirements", "[zip_longest]")
TEST_CASE ("zip_longest: has correct ctor and assign ops", "[zip_longest]")
Typedef Documentation
const_opt_tuple
template<typename... Ts> using const_opt_tuple = std::tuple<boost::optional<const Ts&>...>
Definition at line 31 of file test_zip_longest.cpp.
ImpT
template<typename... Ts> using ImpT = decltype(zip_longest(std::declval<Ts>()...))
Definition at line 184 of file test_zip_longest.cpp.
Function Documentation
TEST_CASE() [1/11]
TEST_CASE ("zip longest: correctly detects longest at any position" , "" [zip_longest])
Definition at line 33 of file test_zip_longest.cpp.
References NS1::begin(), NS1::end(), and iter::zip_longest().
TEST_CASE() [2/11]
TEST_CASE ("zip_longest: three sequences, one sequence has different begin and end" , "" [zip_longest])
Definition at line 82 of file test_zip_longest.cpp.
References i, and iter::zip_longest().
TEST_CASE() [3/11]
TEST_CASE ("zip_longest: const iteration" , "" [zip_longest][const ])
Definition at line 100 of file test_zip_longest.cpp.
References iter::zip_longest().
TEST_CASE() [4/11]
TEST_CASE ("zip_longest: const iterators can be compared to non-const iterators" , "" [zip_longest][const ])
Definition at line 117 of file test_zip_longest.cpp.
References NS1::begin(), NS1::end(), and iter::zip_longest().
TEST_CASE() [5/11]
TEST_CASE ("zip longest: when all are empty, terminates right away" , "" [zip_longest])
Definition at line 126 of file test_zip_longest.cpp.
References NS1::begin(), NS1::end(), and iter::zip_longest().
TEST_CASE() [6/11]
TEST_CASE ("zip longest: can modify zipped sequences" , "" [zip_longest])
Definition at line 136 of file test_zip_longest.cpp.
References iter::zip_longest().
TEST_CASE() [7/11]
TEST_CASE ("zip longest: empty zip_longest() is empty" , "" [zip_longest])
Definition at line 149 of file test_zip_longest.cpp.
References NS1::begin(), NS1::end(), and iter::zip_longest().
TEST_CASE() [8/11]
TEST_CASE ("zip_longest: binds to lvalues, moves rvalues" , "" [zip_longest])
Definition at line 155 of file test_zip_longest.cpp.
References iter::zip_longest().
TEST_CASE() [9/11]
TEST_CASE ("zip_longest: doesn't move or copy elements" , "" [zip_longest])
Definition at line 168 of file test_zip_longest.cpp.
References iter::zip_longest().
TEST_CASE() [10/11]
TEST_CASE ("zip_longest: iterator meets requirements" , "" [zip_longest])
Definition at line 175 of file test_zip_longest.cpp.
References NS1::begin(), and iter::zip_longest().
TEST_CASE() [11/11]
TEST_CASE ("zip_longest: has correct ctor and assign ops" , "" [zip_longest])
Definition at line 185 of file test_zip_longest.cpp.