CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_compress.cpp File Reference
test_compress.cpp File Reference
#include <compress.hpp>
#include "helpers.hpp"
#include <iterator>
#include <string>
#include <utility>
#include <vector>
#include "catch.hpp"
Classes
struct BoolLike
Typedefs
using Vec = const std::vector< int >
template<typename T , typename U >
using ImpT = decltype(compress(std::declval< T >(), std::declval< U >()))
Functions
TEST_CASE ("compress: alternating", "[compress]")
TEST_CASE ("compress: const iteration ", "[compress][const]")
TEST_CASE ("compress: const iterators can be compared to non-const iterators", "[compress][const]")
TEST_CASE ("compress: consecutive falses", "[compress]")
TEST_CASE ("compress: consecutive trues", "[compress]")
TEST_CASE ("compress: all true", "[compress]")
TEST_CASE ("compress: all false", "[compress]")
TEST_CASE ("compress: operator->", "[compress")
TEST_CASE ("compress: binds to lvalues, moves rvalues", "[compress]")
TEST_CASE ("compress: workds with truthy and falsey values", "[compress]")
TEST_CASE ("compress: terminates on shorter selectors", "[compress]")
TEST_CASE ("compress: terminates on shorter data", "[compress]")
TEST_CASE ("compress: nothing on empty selectors", "[compress]")
TEST_CASE ("compress: nothing on empty data", "[compress]")
TEST_CASE ("compress: iterator meets requirements", "[compress]")
TEST_CASE ("compress: Works with different begin and end types", "[compress]")
TEST_CASE ("compress: has correct ctor and assign ops", "[compress]")
Typedef Documentation
ImpT
template<typename T , typename U > using ImpT = decltype(compress(std::declval<T>(), std::declval<U>()))
Definition at line 164 of file test_compress.cpp.
Vec
using Vec = const std::vector<int>
Definition at line 14 of file test_compress.cpp.
Function Documentation
TEST_CASE() [1/17]
TEST_CASE ("compress: alternating" , "" [compress])
Definition at line 16 of file test_compress.cpp.
References NS1::begin(), iter::compress(), and NS1::end().
TEST_CASE() [2/17]
TEST_CASE ("compress: const iteration " , "" [compress][const ])
Definition at line 26 of file test_compress.cpp.
References NS1::begin(), iter::compress(), and NS1::end().
TEST_CASE() [3/17]
TEST_CASE ("compress: const iterators can be compared to non-const iterators" , "" [compress][const ])
Definition at line 36 of file test_compress.cpp.
References NS1::begin(), iter::compress(), and NS1::end().
TEST_CASE() [4/17]
TEST_CASE ("compress: consecutive falses" , "" [compress])
Definition at line 43 of file test_compress.cpp.
References NS1::begin(), iter::compress(), and NS1::end().
TEST_CASE() [5/17]
TEST_CASE ("compress: consecutive trues" , "" [compress])
Definition at line 53 of file test_compress.cpp.
References NS1::begin(), iter::compress(), and NS1::end().
TEST_CASE() [6/17]
TEST_CASE ("compress: all true" , "" [compress])
Definition at line 63 of file test_compress.cpp.
References NS1::begin(), iter::compress(), and NS1::end().
TEST_CASE() [7/17]
TEST_CASE ("compress: all false" , "" [compress])
Definition at line 72 of file test_compress.cpp.
References NS1::begin(), iter::compress(), and NS1::end().
TEST_CASE() [8/17]
TEST_CASE ("compress: operator->" , "[compress")
Definition at line 79 of file test_compress.cpp.
References NS1::begin(), and iter::compress().
TEST_CASE() [9/17]
TEST_CASE ("compress: binds to lvalues, moves rvalues" , "" [compress])
Definition at line 87 of file test_compress.cpp.
References iter::compress().
TEST_CASE() [10/17]
TEST_CASE ("compress: workds with truthy and falsey values" , "" [compress])
Definition at line 108 of file test_compress.cpp.
References NS1::begin(), iter::compress(), and NS1::end().
TEST_CASE() [11/17]
TEST_CASE ("compress: terminates on shorter selectors" , "" [compress])
Definition at line 120 of file test_compress.cpp.
References NS1::begin(), iter::compress(), and NS1::end().
TEST_CASE() [12/17]
TEST_CASE ("compress: terminates on shorter data" , "" [compress])
Definition at line 127 of file test_compress.cpp.
References NS1::begin(), iter::compress(), and NS1::end().
TEST_CASE() [13/17]
TEST_CASE ("compress: nothing on empty selectors" , "" [compress])
Definition at line 134 of file test_compress.cpp.
References NS1::begin(), iter::compress(), and NS1::end().
TEST_CASE() [14/17]
TEST_CASE ("compress: nothing on empty data" , "" [compress])
Definition at line 141 of file test_compress.cpp.
References NS1::begin(), iter::compress(), and NS1::end().
TEST_CASE() [15/17]
TEST_CASE ("compress: iterator meets requirements" , "" [compress])
Definition at line 148 of file test_compress.cpp.
References NS1::begin(), and iter::compress().
TEST_CASE() [16/17]
TEST_CASE ("compress: Works with different begin and end types" , "" [compress])
Definition at line 155 of file test_compress.cpp.
References iter::compress().
TEST_CASE() [17/17]
TEST_CASE ("compress: has correct ctor and assign ops" , "" [compress])
Definition at line 165 of file test_compress.cpp.