CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_permutations.cpp File Reference
test_permutations.cpp File Reference
#include <permutations.hpp>
#include "helpers.hpp"
#include <iterator>
#include <set>
#include <string>
#include <vector>
#include "catch.hpp"
Namespaces
itertest
Typedefs
using IntPermSet = std::multiset< std::vector< int > >
template<typename T >
using ImpT = decltype(permutations(std::declval< T >()))
Functions
TEST_CASE ("permutations: basic test, 3 element sequence", "[permutations]")
TEST_CASE ("permutations: const iteration", "[permutations][const]")
TEST_CASE ("permutations: const iterators can be compared to non-const iteration", "[permutations][const]")
TEST_CASE ("permutations: Works with different begin and end types", "[permutations]")
TEST_CASE ("permutations: empty sequence has one empy permutation", "[permutations]")
TEST_CASE ("permutations: iterators can be compared", "[permutations]")
TEST_CASE ("permutations: binds to lvalues, moves rvalues", "[permutations]")
bool itertest::operator< (const SolidInt &lhs, const SolidInt &rhs)
TEST_CASE ("permutations doesn't move or copy elements of iterable", "[permutations]")
TEST_CASE ("permutations: iterator meets requirements", "[permutations]")
TEST_CASE ("permutations: has correct ctor and assign ops", "[permutations]")
Typedef Documentation
ImpT
template<typename T > using ImpT = decltype(permutations(std::declval<T>()))
Definition at line 134 of file test_permutations.cpp.
IntPermSet
using IntPermSet = std::multiset<std::vector<int> >
Definition at line 13 of file test_permutations.cpp.
Function Documentation
TEST_CASE() [1/10]
TEST_CASE ("permutations: basic test, 3 element sequence" , "" [permutations])
Definition at line 15 of file test_permutations.cpp.
References NS1::begin(), NS1::end(), and iter::permutations.
TEST_CASE() [2/10]
TEST_CASE ("permutations: const iteration" , "" [permutations][const ])
Definition at line 35 of file test_permutations.cpp.
References NS1::begin(), NS1::end(), and iter::permutations.
TEST_CASE() [3/10]
TEST_CASE ("permutations: const iterators can be compared to non-const iteration" , "" [permutations][const ])
Definition at line 48 of file test_permutations.cpp.
References NS1::begin(), NS1::end(), and iter::permutations.
TEST_CASE() [4/10]
TEST_CASE ("permutations: Works with different begin and end types" , "" [permutations])
Definition at line 56 of file test_permutations.cpp.
References NS1::begin(), NS1::end(), and iter::permutations.
TEST_CASE() [5/10]
TEST_CASE ("permutations: empty sequence has one empy permutation" , "" [permutations])
Definition at line 70 of file test_permutations.cpp.
References NS1::begin(), NS1::end(), and iter::permutations.
TEST_CASE() [6/10]
TEST_CASE ("permutations: iterators can be compared" , "" [permutations])
Definition at line 80 of file test_permutations.cpp.
References NS1::begin(), NS1::end(), and iter::permutations.
TEST_CASE() [7/10]
TEST_CASE ("permutations: binds to lvalues, moves rvalues" , "" [permutations])
Definition at line 98 of file test_permutations.cpp.
References iter::permutations.
TEST_CASE() [8/10]
TEST_CASE ("permutations doesn't move or copy elements of iterable" , "" [permutations])
Definition at line 117 of file test_permutations.cpp.
References iter::permutations.
TEST_CASE() [9/10]
TEST_CASE ("permutations: iterator meets requirements" , "" [permutations])
Definition at line 125 of file test_permutations.cpp.
References NS1::begin(), and iter::permutations.
TEST_CASE() [10/10]
TEST_CASE ("permutations: has correct ctor and assign ops" , "" [permutations])
Definition at line 135 of file test_permutations.cpp.