CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_iteratoriterator.cpp File Reference
test_iteratoriterator.cpp File Reference
#include <internal/iteratoriterator.hpp>
#include <string>
#include <vector>
#include <utility>
#include "catch.hpp"
Functions
TEST_CASE ("Iterator over a vector of vector iterators", "[iteratoriterator]")
TEST_CASE ("IteratorIterator operator->", "[iteratoriterator]")
TEST_CASE ("Iterate over a vector of string iterators", "[iteratoriterator]")
TEST_CASE ("IteratorIterator supports mutable RandomAccessIterator operators", "[iteratoriterator]")
TEST_CASE ("IterIterWrapper supports several SequenceContainer methodes", "[iteratoriterator]")
Function Documentation
TEST_CASE() [1/5]
TEST_CASE ("Iterator over a vector of vector iterators" , "" [iteratoriterator])
Definition at line 11 of file test_iteratoriterator.cpp.
References NS1::begin(), NS1::end(), iter::impl::IterIterWrapper< Container >::get(), iter::impl::IterIterWrapper< Container >::rbegin(), and iter::impl::IterIterWrapper< Container >::rend().
TEST_CASE() [2/5]
TEST_CASE ("IteratorIterator operator->" , "" [iteratoriterator])
Definition at line 46 of file test_iteratoriterator.cpp.
References NS1::begin(), NS1::end(), and iter::impl::IterIterWrapper< Container >::get().
TEST_CASE() [3/5]
TEST_CASE ("Iterate over a vector of string iterators" , "" [iteratoriterator])
Definition at line 57 of file test_iteratoriterator.cpp.
References NS1::begin().
TEST_CASE() [4/5]
TEST_CASE ("IteratorIterator supports mutable RandomAccessIterator operators" , "" [iteratoriterator])
Definition at line 66 of file test_iteratoriterator.cpp.
References NS1::begin(), iter::impl::IterIterWrapper< Container >::begin(), NS1::end(), and iter::impl::IterIterWrapper< Container >::get().
TEST_CASE() [5/5]
TEST_CASE ("IterIterWrapper supports several SequenceContainer methodes" , "" [iteratoriterator])
Definition at line 139 of file test_iteratoriterator.cpp.
References NS1::begin(), NS1::end(), and iter::impl::IterIterWrapper< Container >::get().