CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_unique_justseen.cpp File Reference
test_unique_justseen.cpp File Reference
#include <unique_justseen.hpp>
#include "helpers.hpp"
#include <iterator>
#include <string>
#include <vector>
#include "catch.hpp"
Typedefs
using Vec = std::vector< int >
template<typename T >
using ImpT = decltype(unique_justseen(std::declval< T >()))
Functions
TEST_CASE ("unique justseen: adjacent repeating values", "[unique_justseen]")
TEST_CASE ("unique justseen: const iteration", "[unique_justseen][const]")
TEST_CASE ("unique justseen: const iterator can be compared to non-const iterators", "[unique_justseen][const]")
TEST_CASE ("unique justseen: some repeating values", "[unique_justseen]")
TEST_CASE ("unique justseen: Works with different begin and end types", "[unique_justseen]")
TEST_CASE ("unique justseen: doesn't omit non-adjacent duplicates", "[unique_justseen]")
TEST_CASE ("unique justseen: moves and binds correctly", "[unique_justseen]")
TEST_CASE ("unique_justseen: iterator meets requirements", "[unique_justseen]")
TEST_CASE ("unique_justseen: has correct ctor and assign ops", "[unique_justseen]")
Typedef Documentation
ImpT
template<typename T > using ImpT = decltype(unique_justseen(std::declval<T>()))
Definition at line 88 of file test_unique_justseen.cpp.
Vec
using Vec = std::vector<int>
Definition at line 13 of file test_unique_justseen.cpp.
Function Documentation
TEST_CASE() [1/9]
TEST_CASE ("unique justseen: adjacent repeating values" , "" [unique_justseen])
Definition at line 15 of file test_unique_justseen.cpp.
References NS1::begin(), NS1::end(), and iter::unique_justseen.
TEST_CASE() [2/9]
TEST_CASE ("unique justseen: const iteration" , "" [unique_justseen][const ])
Definition at line 23 of file test_unique_justseen.cpp.
References NS1::begin(), NS1::end(), and iter::unique_justseen.
TEST_CASE() [3/9]
TEST_CASE ("unique justseen: const iterator can be compared to non-const iterators" , "" [unique_justseen][const ])
Definition at line 31 of file test_unique_justseen.cpp.
References NS1::begin(), and iter::unique_justseen.
TEST_CASE() [4/9]
TEST_CASE ("unique justseen: some repeating values" , "" [unique_justseen])
Definition at line 39 of file test_unique_justseen.cpp.
References NS1::begin(), NS1::end(), and iter::unique_justseen.
TEST_CASE() [5/9]
TEST_CASE ("unique justseen: Works with different begin and end types" , "" [unique_justseen])
Definition at line 54 of file test_unique_justseen.cpp.
References iter::unique_justseen.
TEST_CASE() [6/9]
TEST_CASE ("unique justseen: doesn't omit non-adjacent duplicates" , "" [unique_justseen])
Definition at line 64 of file test_unique_justseen.cpp.
References NS1::begin(), NS1::end(), and iter::unique_justseen.
TEST_CASE() [7/9]
TEST_CASE ("unique justseen: moves and binds correctly" , "" [unique_justseen])
Definition at line 72 of file test_unique_justseen.cpp.
References iter::unique_justseen.
TEST_CASE() [8/9]
TEST_CASE ("unique_justseen: iterator meets requirements" , "" [unique_justseen])
Definition at line 81 of file test_unique_justseen.cpp.
References NS1::begin(), and iter::unique_justseen.
TEST_CASE() [9/9]
TEST_CASE ("unique_justseen: has correct ctor and assign ops" , "" [unique_justseen])
Definition at line 89 of file test_unique_justseen.cpp.