CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_iterbase.cpp File Reference
test_iterbase.cpp File Reference
#include <enumerate.hpp>
#include <internal/iterbase.hpp>
#include <iterator>
#include <list>
#include <string>
#include <type_traits>
#include <vector>
#include "catch.hpp"
#include "helpers.hpp"
Classes
struct NS1::Dummy
Namespaces
NS1
Typedefs
using IVec = std::vector< int >
template<typename T >
using hrai = it::has_random_access_iter< T >
Functions
TEST_CASE ("Detects random access iterators correctly", "[iterbase]")
TEST_CASE ("Detects correct iterator types", "[iterbase]")
TEST_CASE ("advance, next, size", "[iterbase]")
TEST_CASE ("are_same", "[iterbase]")
TEST_CASE ("DerefHolder lvalue reference", "[iterbase]")
TEST_CASE ("DerefHolder non-reference", "[iterbase]")
TEST_CASE ("get_begin returns correct type", "[iterbase]")
template<typename T >
auto NS1::begin (T &t)
template<typename T >
auto NS1::end (T &t)
TEST_CASE ("Detects is_iterable with ADL conflicts", "[iterbase]")
Typedef Documentation
hrai
template<typename T > using hrai = it::has_random_access_iter<T>
Definition at line 21 of file test_iterbase.cpp.
IVec
using IVec = std::vector<int>
Definition at line 18 of file test_iterbase.cpp.
Function Documentation
TEST_CASE() [1/8]
TEST_CASE ("Detects random access iterators correctly" , "" [iterbase])
Definition at line 22 of file test_iterbase.cpp.
References iter::enumerate.
TEST_CASE() [2/8]
TEST_CASE ("Detects correct iterator types" , "" [iterbase])
Definition at line 32 of file test_iterbase.cpp.
TEST_CASE() [3/8]
TEST_CASE (" advance, next , size" , "" [iterbase])
Definition at line 47 of file test_iterbase.cpp.
References iter::impl::apply_arrow(), NS1::begin(), iter::impl::dumb_advance_unsafe(), iter::impl::dumb_next(), and iter::impl::dumb_size().
TEST_CASE() [4/8]
TEST_CASE ("are_same" , "" [iterbase])
Definition at line 58 of file test_iterbase.cpp.
TEST_CASE() [5/8]
TEST_CASE ("DerefHolder lvalue reference" , "" [iterbase])
Definition at line 65 of file test_iterbase.cpp.
References iter::impl::DerefHolder< T >::get(), iter::impl::DerefHolder< T >::get_ptr(), and iter::impl::DerefHolder< T >::reset().
TEST_CASE() [6/8]
TEST_CASE ("DerefHolder non-reference" , "" [iterbase])
Definition at line 80 of file test_iterbase.cpp.
References iter::impl::DerefHolder< T >::get(), and iter::impl::DerefHolder< T >::reset().
TEST_CASE() [7/8]
TEST_CASE ("get_begin returns correct type" , "" [iterbase])
Definition at line 93 of file test_iterbase.cpp.
References iter::impl::get_iters::get_begin().
TEST_CASE() [8/8]
TEST_CASE ("Detects is_iterable with ADL conflicts" , "" [iterbase])
Definition at line 121 of file test_iterbase.cpp.
References iter::impl::is_iterable.