CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_chunked.cpp File Reference
test_chunked.cpp File Reference
#include <chunked.hpp>
#include <array>
#include <string>
#include <utility>
#include <vector>
#include "catch.hpp"
#include "helpers.hpp"
Typedefs
using Vec = std::vector< int >
using ResVec = std::vector< Vec >
template<typename T >
using ImpT = decltype(chunked(std::declval< T >(), 1))
Functions
TEST_CASE ("chunked: basic test", "[chunked]")
TEST_CASE ("chunked: const chunked", "[chunked][const]")
TEST_CASE ("chunked: const iterators can be compared to non-const iterators", "[chunked][const]")
TEST_CASE ("chunked: len(iterable) % groupsize != 0", "[chunked]")
TEST_CASE ("chunked: iterators can be compared", "[chunked]")
TEST_CASE ("chunked: size 0 is empty", "[chunked]")
TEST_CASE ("chunked: Works with different begin and end types", "[chunked]")
TEST_CASE ("chunked: empty iterable gives empty chunked", "[chunked]")
TEST_CASE ("chunked: iterator meets requirements", "[chunked]")
TEST_CASE ("chunked: has correct ctor and assign ops", "[chunked]")
Typedef Documentation
ImpT
template<typename T > using ImpT = decltype(chunked(std::declval<T>(), 1))
Definition at line 107 of file test_chunked.cpp.
ResVec
using ResVec = std::vector<Vec>
Definition at line 13 of file test_chunked.cpp.
Vec
using Vec = std::vector<int>
Definition at line 12 of file test_chunked.cpp.
Function Documentation
TEST_CASE() [1/10]
TEST_CASE ("chunked: basic test" , "" [chunked])
Definition at line 15 of file test_chunked.cpp.
References NS1::begin(), iter::chunked, and NS1::end().
TEST_CASE() [2/10]
TEST_CASE ("chunked: const chunked" , "" [chunked][const ])
Definition at line 34 of file test_chunked.cpp.
References NS1::begin(), iter::chunked, and NS1::end().
TEST_CASE() [3/10]
TEST_CASE ("chunked: const iterators can be compared to non-const iterators" , "" [chunked][const ])
Definition at line 48 of file test_chunked.cpp.
References NS1::begin(), iter::chunked, and NS1::end().
TEST_CASE() [4/10]
TEST_CASE ()
Definition at line 55 of file test_chunked.cpp.
References NS1::begin(), iter::chunked, and NS1::end().
TEST_CASE() [5/10]
TEST_CASE ("chunked: iterators can be compared" , "" [chunked])
Definition at line 67 of file test_chunked.cpp.
References NS1::begin(), and iter::chunked.
TEST_CASE() [6/10]
TEST_CASE ("chunked: size 0 is empty" , "" [chunked])
Definition at line 78 of file test_chunked.cpp.
References NS1::begin(), iter::chunked, and NS1::end().
TEST_CASE() [7/10]
TEST_CASE ("chunked: Works with different begin and end types" , "" [chunked])
Definition at line 84 of file test_chunked.cpp.
References NS1::begin(), iter::chunked, and NS1::end().
TEST_CASE() [8/10]
TEST_CASE ("chunked: empty iterable gives empty chunked" , "" [chunked])
Definition at line 94 of file test_chunked.cpp.
References NS1::begin(), iter::chunked, and NS1::end().
TEST_CASE() [9/10]
TEST_CASE ("chunked: iterator meets requirements" , "" [chunked])
Definition at line 100 of file test_chunked.cpp.
References NS1::begin(), and iter::chunked.
TEST_CASE() [10/10]
TEST_CASE ("chunked: has correct ctor and assign ops" , "" [chunked])
Definition at line 108 of file test_chunked.cpp.