CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_sorted.cpp File Reference
test_sorted.cpp File Reference
#include <sorted.hpp>
#include <array>
#include <set>
#include <string>
#include <unordered_set>
#include <utility>
#include <vector>
#include "catch.hpp"
#include "helpers.hpp"
Typedefs
using Vec = const std::vector< int >
template<typename T >
using ImpT = decltype(sorted(std::declval< T >()))
Functions
TEST_CASE ("sorted: iterates through a vector in sorted order", "[sorted]")
TEST_CASE ("sorted: handles pointer to member function", "[sorted]")
TEST_CASE ("sorted: const iteration", "[sorted][const]")
TEST_CASE ("sorted: const iterators can be compared to non-const iterators", "[sorted][const][!hide]")
TEST_CASE ("sorted: can modify elements through sorted", "[sorted]")
char inc_vowels (char c)
TEST_CASE ("sorted: Works with different begin and end types", "[sorted]")
TEST_CASE ("sorted: can iterate over unordered container", "[sorted]")
TEST_CASE ("sorted: empty when iterable is empty", "[sorted]")
TEST_CASE ("sorted: works with different callable types", "[sorted]")
TEST_CASE ("sorted: moves rvalues and binds to lvalues", "[sorted]")
TEST_CASE ("sorted: doesn't move or copy elements of iterable", "[sorted]")
TEST_CASE ("sorted: has correct ctor and assign ops", "[sorted]")
TEST_CASE ("sorted: iterator meets requirements", "[sorted]")
Typedef Documentation
ImpT
template<typename T > using ImpT = decltype(sorted(std::declval<T>()))
Definition at line 229 of file test_sorted.cpp.
Vec
using Vec = const std::vector<int>
Definition at line 15 of file test_sorted.cpp.
Function Documentation
inc_vowels()
char inc_vowels (char c)
Definition at line 66 of file test_sorted.cpp.
Referenced by TEST_CASE().
TEST_CASE() [1/13]
TEST_CASE ("sorted: iterates through a vector in sorted order" , "" [sorted])
Definition at line 17 of file test_sorted.cpp.
References NS1::begin(), NS1::end(), and iter::sorted.
TEST_CASE() [2/13]
TEST_CASE ("sorted: handles pointer to member function" , "" [sorted])
Definition at line 32 of file test_sorted.cpp.
References NS1::begin(), NS1::end(), and iter::sorted.
TEST_CASE() [3/13]
TEST_CASE ("sorted: const iteration" , "" [sorted][const ])
Definition at line 41 of file test_sorted.cpp.
References NS1::begin(), NS1::end(), and iter::sorted.
TEST_CASE() [4/13]
TEST_CASE ("sorted: const iterators can be compared to non-const iterators" , "" [sorted][const ][!hide])
Definition at line 50 of file test_sorted.cpp.
References NS1::begin(), and iter::sorted.
TEST_CASE() [5/13]
TEST_CASE ("sorted: can modify elements through sorted" , "" [sorted])
Definition at line 57 of file test_sorted.cpp.
References iter::sorted.
TEST_CASE() [6/13]
TEST_CASE ("sorted: Works with different begin and end types" , "" [sorted])
Definition at line 70 of file test_sorted.cpp.
References inc_vowels(), and iter::sorted.
TEST_CASE() [7/13]
TEST_CASE ("sorted: can iterate over unordered container" , "" [sorted])
Definition at line 80 of file test_sorted.cpp.
References NS1::begin(), NS1::end(), and iter::sorted.
TEST_CASE() [8/13]
TEST_CASE ("sorted: empty when iterable is empty" , "" [sorted])
Definition at line 89 of file test_sorted.cpp.
References NS1::begin(), NS1::end(), and iter::sorted.
TEST_CASE() [9/13]
TEST_CASE ("sorted: works with different callable types" , "" [sorted])
Definition at line 107 of file test_sorted.cpp.
References NS1::begin(), NS1::end(), i, and iter::sorted.
TEST_CASE() [10/13]
TEST_CASE ("sorted: moves rvalues and binds to lvalues" , "" [sorted])
Definition at line 209 of file test_sorted.cpp.
References iter::sorted.
TEST_CASE() [11/13]
TEST_CASE ("sorted: doesn't move or copy elements of iterable" , "" [sorted])
Definition at line 218 of file test_sorted.cpp.
References i, and iter::sorted.
TEST_CASE() [12/13]
TEST_CASE ("sorted: has correct ctor and assign ops" , "" [sorted])
Definition at line 230 of file test_sorted.cpp.
TEST_CASE() [13/13]
TEST_CASE ("sorted: iterator meets requirements" , "" [sorted])
Definition at line 235 of file test_sorted.cpp.
References NS1::begin(), and iter::sorted.