CkPttnCpp: lib/test/src/test_netlist.cpp File Reference
test_netlist.cpp File Reference
#include <catch.hpp>
#include <ckpttncpp/netlist.hpp>
#include <py2cpp/py2cpp.hpp>
#include <utility>
#include <vector>
Functions
auto create_dwarf () -> SimpleNetlist
Create a test netlist object.
auto create_test_netlist () -> SimpleNetlist
Create a test netlist object.
TEST_CASE ("Test Netlist", "[test_netlist]")
TEST_CASE ("Test dwarf", "[test_dwarf]")
Function Documentation
create_dwarf()
auto create_dwarf () -> SimpleNetlist
Create a test netlist object.
Returns
Netlist
Definition at line 18 of file test_netlist.cpp.
References Netlist< nodeview_t, nodemap_t >::module_weight.
Referenced by TEST_CASE().
create_test_netlist()
auto create_test_netlist () -> SimpleNetlist
Create a test netlist object.
Returns
Netlist
Definition at line 78 of file test_netlist.cpp.
References Netlist< nodeview_t, nodemap_t >::module_weight, and R.
Referenced by TEST_CASE().
TEST_CASE() [1/2]
TEST_CASE ("Test Netlist" , "" [test_netlist])
Definition at line 112 of file test_netlist.cpp.
References CHECK(), and create_test_netlist().
TEST_CASE() [2/2]
TEST_CASE ("Test dwarf" , "" [test_dwarf])
Definition at line 124 of file test_netlist.cpp.
References CHECK(), and create_dwarf().