CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_mixed.cpp File Reference
test_mixed.cpp File Reference
#include "itertools.hpp"
#include "catch.hpp"
#include <iostream>
#include <vector>
Classes
class MyUnMovable
Functions
TEST_CASE ("filtering doesn't dereference multiple times", "[imap][filter]")
TEST_CASE ("dropwhile doesn't dereference multiple times", "[imap][dropwhile]")
TEST_CASE ("takewhile doesn't dereference multiple times", "[imap][takewhile]")
TEST_CASE ("sorted(chain.from_iterable)", "[sorted][chain.from_iterable]")
TEST_CASE ("filter into enumerate with pipe", "[filter][enumerate]")
TEST_CASE ("chain.from_iterable: accept imap result that yields rvalues", "[chain.from_iterable][imap]")
Function Documentation
TEST_CASE() [1/6]
TEST_CASE ("filtering doesn't dereference multiple times" , "" [imap][filter])
Definition at line 50 of file test_mixed.cpp.
References iter::filter, MyUnMovable::get_val(), and iter::imap.
TEST_CASE() [2/6]
TEST_CASE ("dropwhile doesn't dereference multiple times" , "" [imap][dropwhile])
Definition at line 77 of file test_mixed.cpp.
References NS1::begin(), iter::dropwhile, NS1::end(), MyUnMovable::get_val(), and iter::imap.
TEST_CASE() [3/6]
TEST_CASE ("takewhile doesn't dereference multiple times" , "" [imap][takewhile])
Definition at line 101 of file test_mixed.cpp.
References NS1::begin(), NS1::end(), MyUnMovable::get_val(), iter::imap, and iter::takewhile.
TEST_CASE() [4/6]
TEST_CASE ("sorted(chain.from_iterable)" , "" [sorted][chain.from_iterable])
Definition at line 125 of file test_mixed.cpp.
References iter::sorted.
TEST_CASE() [5/6]
TEST_CASE ("filter into enumerate with pipe" , "" [filter][enumerate])
Definition at line 130 of file test_mixed.cpp.
References NS1::begin(), NS1::end(), iter::enumerate, iter::filter, MyUnMovable::get_val(), and iter::imap.
TEST_CASE() [6/6]
TEST_CASE ("chain.from_iterable: accept imap result that yields rvalues" , "" [chain.from_iterable][imap])
Definition at line 147 of file test_mixed.cpp.
References NS1::begin(), NS1::end(), and iter::imap.