CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_cycle.cpp File Reference
test_cycle.cpp File Reference
#include <cycle.hpp>
#include "helpers.hpp"
#include <iterator>
#include <string>
#include <vector>
#include "catch.hpp"
Typedefs
template<typename T >
using ImpT = decltype(cycle(std::declval< T >()))
Functions
TEST_CASE ("cycle: iterate twice", "[cycle]")
TEST_CASE ("cycle: const iteration, iterate twice", "[cycle][const]")
TEST_CASE ("cycle: const iterators can be compared to non-const iterators", "[cycle][const]")
TEST_CASE ("cycle: Works with different begin and end types", "[cycle]")
TEST_CASE ("cycle: with pipe", "[cycle]")
TEST_CASE ("cycle: empty cycle terminates", "[cycle]")
TEST_CASE ("cycle: binds to lvalues, moves rvalues", "[cycle]")
TEST_CASE ("cycle: doesn't move or copy elements of iterable", "[cycle]")
TEST_CASE ("cycle: iterator meets requirements", "[cycle]")
TEST_CASE ("cycle: arrow works", "[cycle]")
TEST_CASE ("cycle: has correct ctor and assign ops", "[cycle]")
Typedef Documentation
ImpT
template<typename T > using ImpT = decltype(cycle(std::declval<T>()))
Definition at line 128 of file test_cycle.cpp.
Function Documentation
TEST_CASE() [1/11]
TEST_CASE ("cycle: iterate twice" , "" [cycle])
Definition at line 13 of file test_cycle.cpp.
References NS1::begin(), count, iter::cycle, NS1::end(), and i.
TEST_CASE() [2/11]
TEST_CASE ("cycle: const iteration, iterate twice" , "" [cycle][const ])
Definition at line 30 of file test_cycle.cpp.
References NS1::begin(), count, iter::cycle, NS1::end(), and i.
TEST_CASE() [3/11]
TEST_CASE ("cycle: const iterators can be compared to non-const iterators" , "" [cycle][const ])
Definition at line 48 of file test_cycle.cpp.
References NS1::begin(), iter::cycle, and NS1::end().
TEST_CASE() [4/11]
TEST_CASE ("cycle: Works with different begin and end types" , "" [cycle])
Definition at line 55 of file test_cycle.cpp.
References count, iter::cycle, and i.
TEST_CASE() [5/11]
TEST_CASE ("cycle: with pipe" , "" [cycle])
Definition at line 72 of file test_cycle.cpp.
References NS1::begin(), count, iter::cycle, NS1::end(), and i.
TEST_CASE() [6/11]
TEST_CASE ("cycle: empty cycle terminates" , "" [cycle])
Definition at line 89 of file test_cycle.cpp.
References NS1::begin(), iter::cycle, and NS1::end().
TEST_CASE() [7/11]
TEST_CASE ("cycle: binds to lvalues, moves rvalues" , "" [cycle])
Definition at line 96 of file test_cycle.cpp.
References iter::cycle.
TEST_CASE() [8/11]
TEST_CASE ("cycle: doesn't move or copy elements of iterable" , "" [cycle])
Definition at line 108 of file test_cycle.cpp.
References NS1::begin(), and iter::cycle.
TEST_CASE() [9/11]
TEST_CASE ("cycle: iterator meets requirements" , "" [cycle])
Definition at line 114 of file test_cycle.cpp.
References NS1::begin(), and iter::cycle.
TEST_CASE() [10/11]
TEST_CASE ("cycle: arrow works" , "" [cycle])
Definition at line 120 of file test_cycle.cpp.
References NS1::begin(), and iter::cycle.
TEST_CASE() [11/11]
TEST_CASE ("cycle: has correct ctor and assign ops" , "" [cycle])
Definition at line 129 of file test_cycle.cpp.