CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_combinations.cpp File Reference
test_combinations.cpp File Reference
#include "helpers.hpp"
#include <combinations.hpp>
#include <iterator>
#include <set>
#include <string>
#include <vector>
#include "catch.hpp"
Macros
#define DEFINE_DEFAULT_ITERATOR_CTOR
#define CHAR_RANGE_DEFAULT_CONSTRUCTIBLE
Typedefs
using CharCombSet = std::vector< std::vector< char > >
template<typename T >
using ImpT = decltype(combinations(std::declval< T >(), 1))
Functions
TEST_CASE ("combinations: Simple combination of 4", "[combinations]")
TEST_CASE ("combinations: const iteration", "[combinations][const]")
TEST_CASE ("combinations: const iterators can be compared to non-const iterators", "[combinations][const]")
TEST_CASE ("combinations: Works with different begin and end types", "[combinations]")
TEST_CASE ("combinations: iterators can be compared", "[combinations]")
TEST_CASE ("combinations: operator->", "[combinations]")
TEST_CASE ("combinations: size too large gives no results", "[combinations]")
TEST_CASE ("combinations: size 0 gives nothing", "[combinations]")
TEST_CASE ("combinations: iterable without operator*() const", "[combinations]")
TEST_CASE ("combinations: binds to lvalues, moves rvalues", "[combinations]")
TEST_CASE ("combinations: doesn't move or copy elements of iterable", "[combinations]")
TEST_CASE ("combinations: iterator meets requirements", "[combinations]")
TEST_CASE ("combinations: has correct ctor and assign ops", "[combinations]")
Macro Definition Documentation
CHAR_RANGE_DEFAULT_CONSTRUCTIBLE
#define CHAR_RANGE_DEFAULT_CONSTRUCTIBLE
Definition at line 2 of file test_combinations.cpp.
DEFINE_DEFAULT_ITERATOR_CTOR
#define DEFINE_DEFAULT_ITERATOR_CTOR
Definition at line 1 of file test_combinations.cpp.
Typedef Documentation
CharCombSet
using CharCombSet = std::vector<std::vector<char> >
Definition at line 19 of file test_combinations.cpp.
ImpT
template<typename T > using ImpT = decltype(combinations(std::declval<T>(), 1))
Definition at line 142 of file test_combinations.cpp.
Function Documentation
TEST_CASE() [1/13]
TEST_CASE ("combinations: Simple combination of 4" , "" [combinations])
Definition at line 21 of file test_combinations.cpp.
References NS1::begin(), iter::combinations, and NS1::end().
TEST_CASE() [2/13]
TEST_CASE ("combinations: const iteration" , "" [combinations][const ])
Definition at line 40 of file test_combinations.cpp.
References NS1::begin(), iter::combinations, and NS1::end().
TEST_CASE() [3/13]
TEST_CASE ("combinations: const iterators can be compared to non-const iterators" , "" [combinations][const ])
Definition at line 53 of file test_combinations.cpp.
References NS1::begin(), iter::combinations, and NS1::end().
TEST_CASE() [4/13]
TEST_CASE ("combinations: Works with different begin and end types" , "" [combinations])
Definition at line 62 of file test_combinations.cpp.
References NS1::begin(), iter::combinations, and NS1::end().
TEST_CASE() [5/13]
TEST_CASE ("combinations: iterators can be compared" , "" [combinations])
Definition at line 74 of file test_combinations.cpp.
References NS1::begin(), and iter::combinations.
TEST_CASE() [6/13]
TEST_CASE ("combinations: operator->" , "" [combinations])
Definition at line 85 of file test_combinations.cpp.
References NS1::begin(), and iter::combinations.
TEST_CASE() [7/13]
TEST_CASE ("combinations: size too large gives no results" , "" [combinations])
Definition at line 92 of file test_combinations.cpp.
References NS1::begin(), iter::combinations, and NS1::end().
TEST_CASE() [8/13]
TEST_CASE ("combinations: size 0 gives nothing" , "" [combinations])
Definition at line 98 of file test_combinations.cpp.
References NS1::begin(), iter::combinations, and NS1::end().
TEST_CASE() [9/13]
TEST_CASE ("combinations: iterable without operator*() const" , "" [combinations])
Definition at line 104 of file test_combinations.cpp.
References NS1::begin(), and iter::combinations.
TEST_CASE() [10/13]
TEST_CASE ("combinations: binds to lvalues, moves rvalues" , "" [combinations])
Definition at line 113 of file test_combinations.cpp.
References iter::combinations.
TEST_CASE() [11/13]
TEST_CASE ("combinations: doesn't move or copy elements of iterable" , "" [combinations])
Definition at line 125 of file test_combinations.cpp.
References iter::combinations, and i.
TEST_CASE() [12/13]
TEST_CASE ("combinations: iterator meets requirements" , "" [combinations])
Definition at line 133 of file test_combinations.cpp.
References NS1::begin(), and iter::combinations.
TEST_CASE() [13/13]
TEST_CASE ("combinations: has correct ctor and assign ops" , "" [combinations])
Definition at line 143 of file test_combinations.cpp.