projgeomcpp: Version::Version Struct Reference
Version::Version Struct Reference
#include <version.h>
Public Member Functions
Version ()
Creates empty Version object.
Version (long long version)
Converts number to version object.
long long asNumber () const
Returns version in one big number with format:
std::string asShortStr () const
Returns version string with version in format:
std::string asLongStr () const
Returns Version + Date + Build machine.
bool operator< (const Version &other)
bool operator> (const Version &other)
bool operator<= (const Version &other)
bool operator>= (const Version &other)
bool operator== (const Version &other)
bool operator!= (const Version &other)
Public Attributes
int major {0}
int minor {0}
int patch {0}
std::string type {""}
Type of build.
std::string datetime {""}
Get time of build in format like: Feb 20 2016 14:38:27.
std::string machine {""}
Machine where it was built.
Detailed Description
Definition at line 8 of file version.h.
Constructor & Destructor Documentation
Version() [1/2]
Version::Version::Version ()
Creates empty Version object.
Version() [2/2]
Version::Version::Version (long long version)
Converts number to version object.
Parameters
version - number in format MMMMmmmmpppp (M-Major, m-minor, p-patch)
Returns
Version object
Member Function Documentation
asLongStr()
std::string Version::Version::asLongStr () const
Returns Version + Date + Build machine.
Will produce result similar to: 1.2.6 beta / Feb 20 2016 14:42:41 / buildMachine
Referenced by main(), and printHelp().
asNumber()
long long Version::Version::asNumber () const
Returns version in one big number with format:
MMMMmmmmpppp (M-Major, m-minor, p-patch)
So 1.2.3 will be 100020003 (leading zeroes are not displayed)
Returns
long integer with version
Referenced by printHelp().
asShortStr()
std::string Version::Version::asShortStr () const
Returns version string with version in format:
Major.Minor.Patch VersionType
1.2.3 beta
Referenced by printHelp().
operator!=()
bool Version::Version::operator!= (const Version & other)
operator<()
bool Version::Version::operator< (const Version & other)
operator<=()
bool Version::Version::operator<= (const Version & other)
operator==()
bool Version::Version::operator== (const Version & other)
operator>()
bool Version::Version::operator> (const Version & other)
operator>=()
bool Version::Version::operator>= (const Version & other)
Member Data Documentation
datetime
std::string Version::Version::datetime {""}
Get time of build in format like: Feb 20 2016 14:38:27.
Definition at line 30 of file version.h.
machine
std::string Version::Version::machine {""}
Machine where it was built.
Definition at line 33 of file version.h.
major
int Version::Version::major {0}
Definition at line 22 of file version.h.
minor
int Version::Version::minor {0}
Definition at line 23 of file version.h.
patch
int Version::Version::patch {0}
Definition at line 24 of file version.h.
type
std::string Version::Version::type {""}
Type of build.
Definition at line 27 of file version.h.
The documentation for this struct was generated from the following file:
source/version.h