EllCpp: lib/bench/BM_lowpass.cpp File Reference
BM_lowpass.cpp File Reference
#include "benchmark/benchmark.h"
#include <iostream>
#include <tuple>
#include <cmath>
#include <complex>
#include <ellcpp/cutting_plane.hpp>
#include <ellcpp/ell.hpp>
#include <ellcpp/oracles/lowpass_oracle.hpp>
#include <ellcpp/utility.hpp>
#include <limits>
#include <xtensor-blas/xlinalg.hpp>
#include <xtensor/xview.hpp>
Typedefs
using Arr = xt::xarray< double, xt::layout_type::row_major >
Functions
static auto run_lowpass (bool use_parallel_cut)
static void BM_Lowpass_single_cut (benchmark::State &state)
static void BM_Lowpass_parallel_cut (benchmark::State &state)
BENCHMARK (BM_Lowpass_single_cut)
BENCHMARK (BM_Lowpass_parallel_cut)
BENCHMARK_MAIN ()
Variables
static const auto PI = std::acos(-1)
static const auto N = 48
static const auto wpass = 0.12 * PI
static const auto wstop = 0.20 * PI
static const auto delta0_wpass = 0.125
static const auto delta0_wstop = 0.125
static const auto delta = 20 * std::log10(1 + delta0_wpass)
static const auto delta2 = 20 * std::log10(delta0_wstop)
static const auto m = 15 * N
static const auto w = Arr {xt::linspace<double>(0, PI, m)}
static Arr An = 2 * xt::cos(xt::linalg::outer(w, xt::arange(1, N)))
static Arr A = xt::concatenate(xt::xtuple(xt::ones<double>({m, 1}), An), 1)
static const auto ind_p = xt::where(w <= wpass)[0]
static const auto Lp = std::pow(10, -delta / 20)
static const auto Up = std::pow(10, +delta / 20)
static const auto Ap = Arr {xt::view(A, xt::range(0, ind_p.size()), xt::all())}
static auto ind_s = xt::where(wstop <= w)[0]
static const auto Sp = std::pow(10, delta2 / 20)
static Arr As = xt::view(A, xt::range(ind_s[0], _), xt::all())
static auto ind_beg = ind_p[ind_p.size() - 1]
static auto ind_end = ind_s[0]
static Arr Anr = xt::view(A, xt::range(ind_beg + 1, ind_end), xt::all())
static const auto Lpsq = Lp * Lp
static const auto Upsq = Up * Up
static const auto Spsq = Sp * Sp
Typedef Documentation
Arr
using Arr = xt::xarray<double, xt::layout_type::row_major>
Definition at line 18 of file BM_lowpass.cpp.
Function Documentation
BENCHMARK() [1/2]
BENCHMARK (BM_Lowpass_single_cut)
Referenced by BM_Lowpass_parallel_cut().
BENCHMARK() [2/2]
BENCHMARK (BM_Lowpass_parallel_cut)
BENCHMARK_MAIN()
BENCHMARK_MAIN ()
Referenced by BM_Lowpass_parallel_cut().
BM_Lowpass_parallel_cut()
static void BM_Lowpass_parallel_cut (benchmark::State & state) static
Definition at line 130 of file BM_lowpass.cpp.
References BENCHMARK(), BENCHMARK_MAIN(), BM_Lowpass_single_cut(), and run_lowpass().
BM_Lowpass_single_cut()
static void BM_Lowpass_single_cut (benchmark::State & state) static
Definition at line 122 of file BM_lowpass.cpp.
References run_lowpass().
Referenced by BM_Lowpass_parallel_cut().
run_lowpass()
static auto run_lowpass (bool use_parallel_cut) static
Definition at line 104 of file BM_lowpass.cpp.
References Ap, cutting_plane_dc(), E, Lpsq, N, P, Spsq, Upsq, and zeros().
Referenced by BM_Lowpass_parallel_cut(), and BM_Lowpass_single_cut().
Variable Documentation
A
Arr A = xt::concatenate(xt::xtuple(xt::ones<double>({m, 1}), An), 1) static
Definition at line 73 of file BM_lowpass.cpp.
Referenced by create_2d_isotropic(), create_test_case1(), create_test_case2(), create_test_case_timing(), chol_ext< Allow_semidefinite >::factorize(), lmi_old_oracle::operator()(), profit_rb_oracle::profit_rb_oracle(), chol_ext< Allow_semidefinite >::sym_quad(), and TEST_CASE().
An
Arr An = 2 * xt::cos(xt::linalg::outer(w, xt::arange(1, N))) static
Definition at line 72 of file BM_lowpass.cpp.
Anr
Arr Anr = xt::view(A, xt::range(ind_beg + 1, ind_end), xt::all()) static
Definition at line 95 of file BM_lowpass.cpp.
Referenced by lowpass_oracle::lowpass_oracle().
Ap
const auto Ap = Arr {xt::view(A, xt::range(0, ind_p.size()), xt::all())} static
Definition at line 79 of file BM_lowpass.cpp.
Referenced by run_lowpass().
As
Arr As = xt::view(A, xt::range(ind_s[0], _), xt::all()) static
Definition at line 86 of file BM_lowpass.cpp.
Referenced by lowpass_oracle::lowpass_oracle().
delta
const auto delta = 20 * std::log10(1 + delta0_wpass) static
Definition at line 59 of file BM_lowpass.cpp.
Referenced by ellipsoid::update().
delta0_wpass
const auto delta0_wpass = 0.125 static
Definition at line 56 of file BM_lowpass.cpp.
delta0_wstop
const auto delta0_wstop = 0.125 static
Definition at line 57 of file BM_lowpass.cpp.
delta2
const auto delta2 = 20 * std::log10(delta0_wstop) static
Definition at line 61 of file BM_lowpass.cpp.
ind_beg
auto ind_beg = ind_p[ind_p.size() - 1] static
Definition at line 93 of file BM_lowpass.cpp.
ind_end
auto ind_end = ind_s[0] static
Definition at line 94 of file BM_lowpass.cpp.
ind_p
const auto ind_p = xt::where(w <= wpass)[0] static
Definition at line 76 of file BM_lowpass.cpp.
ind_s
auto ind_s = xt::where(wstop <= w)[0] static
Definition at line 82 of file BM_lowpass.cpp.
Lp
const auto Lp = std::pow(10, -delta / 20) static
Definition at line 77 of file BM_lowpass.cpp.
Lpsq
const auto Lpsq = Lp * Lp static
Definition at line 97 of file BM_lowpass.cpp.
Referenced by lowpass_oracle::lowpass_oracle(), and run_lowpass().
m
const auto m = 15 * N static
Definition at line 67 of file BM_lowpass.cpp.
Referenced by mle_oracle::operator()(), operator*(), operator+(), operator/(), py::operator<(), sqrt(), and chol_ext< Allow_semidefinite >::witness().
N
const auto N = 48 static
Definition at line 53 of file BM_lowpass.cpp.
Referenced by xn::DiGraphS< nodeview_t, adjlist_t >::add_edges_from(), xn::Graph< nodeview_t, adjlist_t >::add_edges_from(), chol_ext< Allow_semidefinite >::chol_ext(), create_2d_isotropic(), do_case(), posynomial< _Tp >::log_exp_fvalue_with_gradient(), posynomial< _Tp >::log_exp_gradient(), posynomial< _Tp >::lse(), posynomial< _Tp >::lse_gradient(), lowpass_oracle::operator()(), run_lowpass(), and TEST_CASE().
PI
const auto PI = std::acos(-1) static
Definition at line 19 of file BM_lowpass.cpp.
Sp
const auto Sp = std::pow(10, delta2 / 20) static
Definition at line 83 of file BM_lowpass.cpp.
Spsq
const auto Spsq = Sp * Sp static
Definition at line 99 of file BM_lowpass.cpp.
Referenced by lowpass_oracle::lowpass_oracle(), lowpass_oracle::operator()(), and run_lowpass().
Up
const auto Up = std::pow(10, +delta / 20) static
Definition at line 78 of file BM_lowpass.cpp.
Upsq
const auto Upsq = Up * Up static
Definition at line 98 of file BM_lowpass.cpp.
Referenced by lowpass_oracle::lowpass_oracle(), and run_lowpass().
w
const auto w = Arr {xt::linspace<double>(0, PI, m)} static
Definition at line 68 of file BM_lowpass.cpp.
wpass
const auto wpass = 0.12 * PI static
Definition at line 54 of file BM_lowpass.cpp.
wstop
const auto wstop = 0.20 * PI static
Definition at line 55 of file BM_lowpass.cpp.