EllCpp: gp_base< _Tp > Class Template Reference
gp_base< _Tp > Class Template Reference
#include <gp_solve.hpp>
Public Member Functions
gp_base ()
~gp_base ()
Info4EM< Vec > operator() (const Vec &x) const
template<>
Info4EM< Vec > operator() (const Vec &x) const
template<>
Info4EM< Vec > operator() (const Vec &x) const
Protected Attributes
std::vector< posynomial< _Tp > > _M
Private Types
using Vec = std::valarray< double >
Detailed Description
template<typename _Tp>
class gp_base< _Tp >
Definition at line 10 of file gp_solve.hpp.
Member Typedef Documentation
Vec
template<typename _Tp > using gp_base< _Tp >::Vec = std::valarray<double> private
Definition at line 12 of file gp_solve.hpp.
Constructor & Destructor Documentation
gp_base()
template<typename _Tp > gp_base< _Tp >::gp_base () inline
Definition at line 15 of file gp_solve.hpp.
~gp_base()
template<typename _Tp > gp_base< _Tp >::~gp_base () inline
Definition at line 16 of file gp_solve.hpp.
References gp_base< _Tp >::operator()().
Member Function Documentation
operator()() [1/3]
template<> Info4EM< Vec > gp_base< double >::operator() (const Vec & x) const
Definition at line 6 of file gp_solve.cpp.
operator()() [2/3]
template<typename _Tp > Info4EM<Vec> gp_base< _Tp >::operator() (const Vec & x) const
Referenced by gp_base< _Tp >::~gp_base().
operator()() [3/3]
template<> Info4EM< Vec > gp_base< aaf >::operator() (const Vec & x) const
Definition at line 80 of file rgp_yalaa.cpp.
References posynomial< _Tp >::_M, posynomial< _Tp >::lse(), posynomial< _Tp >::lse_gradient(), max(), and P.
Member Data Documentation
_M
template<typename _Tp > std::vector<posynomial<_Tp> > gp_base< _Tp >::_M protected
Definition at line 21 of file gp_solve.hpp.
The documentation for this class was generated from the following file:
lib/include/ellip/gp_solve.hpp