EllCpp: ell Class Reference
ell Class Reference
Ellipsoid Search Space.
#include <ell.hpp>
Public Types
using Arr = xt::xarray< double, xt::layout_type::row_major >
Public Member Functions
ell (const Arr &val, Arr &&x)
Construct a new ell object.
ell (const Arr &val, const Arr &x)
Construct a new ell object.
ell (const double &alpha, const Arr &x)
Construct a new ell object.
ell (const double &alpha, Arr &&x)
Construct a new ell object.
ell (const ell &E)=default
Construct a new ell object.
auto xc () const -> Arr
copy the whole array anyway
void set_xc (const Arr &xc)
Set the xc object.
template<typename T >
std::tuple< int, double > update (const std::tuple< Arr, T > &cut)
Update ellipsoid core function using the cut(s)
Public Attributes
bool _use_parallel_cut = true
bool _no_defer_trick = false
Private Member Functions
auto __calc_ll_core (const double &b0, const double &b1) -> int
Calculate new ellipsoid under Parallel Cut.
auto __calc_ll_cc (const double &b1, const double &t1) -> void
Calculate new ellipsoid under Parallel Cut, one of them is central.
auto __calc_dc (const double &b0) -> int
Calculate new ellipsoid under Deep Cut.
auto __calc_cc (const double &tau) -> void
Calculate new ellipsoid under Central Cut.
Private Attributes
double _rho = 0.
double _sigma = 0.
double _delta = 0.
double _tsq = 0.
size_t _n
double _c1
double _kappa
Arr _xc
Arr _Q
Detailed Description
Ellipsoid Search Space.
ell = {x | (x − xc)' Q^−1 (x − xc) ​≤ κ}
Definition at line 13 of file ell.hpp.
Member Typedef Documentation
Arr
using ell::Arr = xt::xarray<double, xt::layout_type::row_major>
Definition at line 16 of file ell.hpp.
Constructor & Destructor Documentation
ell() [1/5]
ell::ell (const Arr & val, Arr && x) inline
Construct a new ell object.
Template Parameters
T
Parameters
val
x
Definition at line 44 of file ell.hpp.
Referenced by ell().
ell() [2/5]
ell::ell (const Arr & val, const Arr & x) inline
Construct a new ell object.
Template Parameters
T
Parameters
val
x
Definition at line 60 of file ell.hpp.
ell() [3/5]
ell::ell (const double & alpha, const Arr & x) inline
Construct a new ell object.
Template Parameters
T
Parameters
val
x
Definition at line 76 of file ell.hpp.
ell() [4/5]
ell::ell (const double & alpha, Arr && x) inline
Construct a new ell object.
Template Parameters
T
Parameters
val
x
Definition at line 92 of file ell.hpp.
References E, and ell().
ell() [5/5]
ell::ell (const ell & E) default
Construct a new ell object.
Parameters
E
Member Function Documentation
__calc_cc()
void ell::__calc_cc (const double & tau) -> void private
Calculate new ellipsoid under Central Cut.
Central Cut.
g' (x − xc​) ≤ 0
Parameters
tau
Returns
void
Parameters
tau
Returns
int
Definition at line 107 of file ell.cpp.
References _c1, _delta, _n, _rho, and _sigma.
Referenced by __calc_dc(), and set_xc().
__calc_dc()
int ell::__calc_dc (const double & beta) -> int private
Calculate new ellipsoid under Deep Cut.
Deep Cut.
g' (x − xc​) + β0 ​≤ 0
Parameters
b0
Returns
int
Parameters
beta
Returns
int
Definition at line 74 of file ell.cpp.
References __calc_cc(), _c1, _delta, _n, _rho, _sigma, _tsq, and sqrt().
Referenced by __calc_ll_core(), set_xc(), and update().
__calc_ll_cc()
void ell::__calc_ll_cc (const double & b1, const double & b1sq) -> void private
Calculate new ellipsoid under Parallel Cut, one of them is central.
g' (x − xc​) ​≤ 0 g' (x − xc​) + β1 ​≥ 0
Parameters
b1
t1
Returns
void
Parameters
b1
b1sq
Returns
void
Definition at line 58 of file ell.cpp.
References _c1, _delta, _n, _rho, _sigma, _tsq, and sqrt().
Referenced by __calc_ll_core(), and set_xc().
__calc_ll_core()
int ell::__calc_ll_core (const double & b0, const double & b1) -> int private
Calculate new ellipsoid under Parallel Cut.
g' (x − xc​) + β0 ​≤ 0 g' (x − xc​) + β1 ​≥ 0
Parameters
b0
b1
Returns
int
Parameters
b0
b1
Returns
int
Definition at line 14 of file ell.cpp.
References __calc_dc(), __calc_ll_cc(), _c1, _delta, _n, _rho, _sigma, _tsq, _use_parallel_cut, and sqrt().
Referenced by set_xc(), and update().
set_xc()
void ell::set_xc (const Arr & xc) inline
Set the xc object.
Parameters
xc
Definition at line 124 of file ell.hpp.
References __calc_cc(), __calc_dc(), __calc_ll_cc(), __calc_ll_core(), update(), and xc().
update()
template<typename T > template std::tuple< int, double > ell::update (const std::tuple< Arr, T > & cut)
Update ellipsoid core function using the cut(s)
Update ellipsoid core function using the cut g' * (x - xc) + beta <= 0.
Template Parameters
T
Parameters
cut cutting-plane
Returns
std::tuple<int, double>
Template Parameters
T
Parameters
g
beta
Returns
std::tuple<int, double>
Definition at line 125 of file ell.cpp.
References __calc_dc(), __calc_ll_core(), _delta, _kappa, _no_defer_trick, _Q, _rho, _sigma, _tsq, and _xc.
Referenced by set_xc().
xc()
auto ell::xc () const -> Arr inline
copy the whole array anyway
Returns
const Arr&
Definition at line 114 of file ell.hpp.
References _xc.
Referenced by set_xc().
Member Data Documentation
_c1
double ell::_c1 private
Definition at line 31 of file ell.hpp.
Referenced by __calc_cc(), __calc_dc(), __calc_ll_cc(), and __calc_ll_core().
_delta
double ell::_delta = 0. private
Definition at line 27 of file ell.hpp.
Referenced by __calc_cc(), __calc_dc(), __calc_ll_cc(), __calc_ll_core(), and update().
_kappa
double ell::_kappa private
Definition at line 32 of file ell.hpp.
Referenced by update().
_n
size_t ell::_n private
Definition at line 30 of file ell.hpp.
Referenced by __calc_cc(), __calc_dc(), __calc_ll_cc(), and __calc_ll_core().
_no_defer_trick
bool ell::_no_defer_trick = false
Definition at line 22 of file ell.hpp.
Referenced by update().
_Q
Arr ell::_Q private
Definition at line 34 of file ell.hpp.
Referenced by update().
_rho
double ell::_rho = 0. private
Definition at line 25 of file ell.hpp.
Referenced by __calc_cc(), __calc_dc(), __calc_ll_cc(), __calc_ll_core(), and update().
_sigma
double ell::_sigma = 0. private
Definition at line 26 of file ell.hpp.
Referenced by __calc_cc(), __calc_dc(), __calc_ll_cc(), __calc_ll_core(), and update().
_tsq
double ell::_tsq = 0. private
Definition at line 28 of file ell.hpp.
Referenced by __calc_dc(), __calc_ll_cc(), __calc_ll_core(), and update().
_use_parallel_cut
bool ell::_use_parallel_cut = true
Definition at line 21 of file ell.hpp.
Referenced by __calc_ll_core().
_xc
Arr ell::_xc private
Definition at line 33 of file ell.hpp.
Referenced by update(), and xc().
The documentation for this class was generated from the following files:
lib/include/ellcpp/ell.hpp
lib/src/ell.cpp