EllCpp: chol_ext< Allow_semidefinite > Class Template Reference
chol_ext< Allow_semidefinite > Class Template Reference
Cholesky factorization for LMI.
#include <chol_ext.hpp>
Public Member Functions
chol_ext (size_t N)
Construct a new chol ext object.
void factorize (const Mat &A)
Perform Cholesky Factorization.
template<typename Fn >
void factor (Fn getA)
Perform Cholesky Factorization (Lazy evaluation)
auto is_spd () const -> bool
Is $A$ symmetric positive definite (spd)
auto witness () -> double
witness that certifies $A$ is not symmetric positive definite (spd)
auto sym_quad (const Vec &A) const -> double
Calculate v'*{A}(p,p)*v.
auto sqrt () -> Mat
Public Attributes
Rng p {0, 0}
the rows where the process starts and stops
Vec v
witness vector
Private Types
using Arr = xt::xarray< double, xt::layout_type::row_major >
using Vec = Arr
using Mat = Arr
using Rng = std::pair< size_t, size_t >
Private Attributes
size_t n
dimension
Mat T
temporary storage
Detailed Description
template<bool Allow_semidefinite = false>
class chol_ext< Allow_semidefinite >
Cholesky factorization for LMI.
LDL^T square-root-free version
Option allow semidefinite
A matrix $A in R^{m x m}$ is positive definite iff v' A v > 0 for all v in R^n.
O($p^2 n$) per iteration, independent of $m$
Definition at line 18 of file chol_ext.hpp.
Member Typedef Documentation
Arr
template<bool Allow_semidefinite = false> using chol_ext< Allow_semidefinite >::Arr = xt::xarray<double, xt::layout_type::row_major> private
Definition at line 20 of file chol_ext.hpp.
Mat
template<bool Allow_semidefinite = false> using chol_ext< Allow_semidefinite >::Mat = Arr private
Definition at line 22 of file chol_ext.hpp.
Rng
template<bool Allow_semidefinite = false> using chol_ext< Allow_semidefinite >::Rng = std::pair<size_t, size_t> private
Definition at line 23 of file chol_ext.hpp.
Vec
template<bool Allow_semidefinite = false> using chol_ext< Allow_semidefinite >::Vec = Arr private
Definition at line 21 of file chol_ext.hpp.
Constructor & Destructor Documentation
chol_ext()
template<bool Allow_semidefinite = false> chol_ext< Allow_semidefinite >::chol_ext (size_t N) inline explicit
Construct a new chol ext object.
Parameters
N dimension
Definition at line 39 of file chol_ext.hpp.
References N, and zeros().
Member Function Documentation
factor()
template<bool Allow_semidefinite = false> template<typename Fn > void chol_ext< Allow_semidefinite >::factor (Fn getA) inline
Perform Cholesky Factorization (Lazy evaluation)
Template Parameters
Fn
Parameters
getA function to access the elements of A
See also: factorize()
Definition at line 70 of file chol_ext.hpp.
References chol_ext< Allow_semidefinite >::n, chol_ext< Allow_semidefinite >::p, and chol_ext< Allow_semidefinite >::T.
Referenced by chol_ext< Allow_semidefinite >::factorize(), lmi0_oracle::operator()(), lmi_oracle::operator()(), and qmi_oracle::operator()().
factorize()
template<bool Allow_semidefinite = false> void chol_ext< Allow_semidefinite >::factorize (const Mat & A) inline
Perform Cholesky Factorization.
Parameters
A Symmetric Matrix
If $A$ is positive definite, then $p$ is zero. If it is not, then $p$ is a positive integer, such that $v = R^−1 e_p$ is a certificate vector to make $v'*A[:p,:p]*v < 0$
Definition at line 56 of file chol_ext.hpp.
References A, and chol_ext< Allow_semidefinite >::factor().
Referenced by lmi_old_oracle::operator()(), and TEST_CASE().
is_spd()
template<bool Allow_semidefinite = false> auto chol_ext< Allow_semidefinite >::is_spd () const -> bool inline
Is $A$ symmetric positive definite (spd)
Returns
true
false
Definition at line 121 of file chol_ext.hpp.
References chol_ext< Allow_semidefinite >::p.
Referenced by lmi0_oracle::operator()(), lmi_oracle::operator()(), lmi_old_oracle::operator()(), qmi_oracle::operator()(), chol_ext< Allow_semidefinite >::sqrt(), and chol_ext< Allow_semidefinite >::witness().
sqrt()
template<bool Allow_semidefinite = false> auto chol_ext< Allow_semidefinite >::sqrt () -> Mat inline
Definition at line 178 of file chol_ext.hpp.
References chol_ext< Allow_semidefinite >::is_spd(), chol_ext< Allow_semidefinite >::n, sqrt(), chol_ext< Allow_semidefinite >::T, and zeros().
Referenced by mle_oracle::operator()().
sym_quad()
template<bool Allow_semidefinite = false> auto chol_ext< Allow_semidefinite >::sym_quad (const Vec & A) const -> double inline
Calculate v'*{A}(p,p)*v.
Parameters
v
A
Returns
double
Definition at line 161 of file chol_ext.hpp.
References A, chol_ext< Allow_semidefinite >::p, and chol_ext< Allow_semidefinite >::v.
Referenced by lmi0_oracle::operator()(), lmi_oracle::operator()(), and lmi_old_oracle::operator()().
witness()
template<bool Allow_semidefinite = false> auto chol_ext< Allow_semidefinite >::witness () -> double inline
witness that certifies $A$ is not symmetric positive definite (spd)
Returns
auto
Definition at line 132 of file chol_ext.hpp.
References chol_ext< Allow_semidefinite >::is_spd(), m, chol_ext< Allow_semidefinite >::n, chol_ext< Allow_semidefinite >::p, chol_ext< Allow_semidefinite >::T, and chol_ext< Allow_semidefinite >::v.
Referenced by lmi0_oracle::operator()(), lmi_oracle::operator()(), lmi_old_oracle::operator()(), and qmi_oracle::operator()().
Member Data Documentation
n
template<bool Allow_semidefinite = false> size_t chol_ext< Allow_semidefinite >::n private
dimension
Definition at line 30 of file chol_ext.hpp.
Referenced by chol_ext< Allow_semidefinite >::factor(), chol_ext< Allow_semidefinite >::sqrt(), and chol_ext< Allow_semidefinite >::witness().
p
template<bool Allow_semidefinite = false> Rng chol_ext< Allow_semidefinite >::p {0, 0}
the rows where the process starts and stops
Definition at line 26 of file chol_ext.hpp.
Referenced by chol_ext< Allow_semidefinite >::factor(), chol_ext< Allow_semidefinite >::is_spd(), qmi_oracle::operator()(), lsq_oracle::operator()(), chol_ext< Allow_semidefinite >::sym_quad(), and chol_ext< Allow_semidefinite >::witness().
T
template<bool Allow_semidefinite = false> Mat chol_ext< Allow_semidefinite >::T private
temporary storage
Definition at line 31 of file chol_ext.hpp.
Referenced by chol_ext< Allow_semidefinite >::factor(), chol_ext< Allow_semidefinite >::sqrt(), and chol_ext< Allow_semidefinite >::witness().
v
template<bool Allow_semidefinite = false> Vec chol_ext< Allow_semidefinite >::v
witness vector
Definition at line 27 of file chol_ext.hpp.
Referenced by qmi_oracle::operator()(), chol_ext< Allow_semidefinite >::sym_quad(), and chol_ext< Allow_semidefinite >::witness().
The documentation for this class was generated from the following file:
lib/include/ellcpp/oracles/chol_ext.hpp