EllCpp: ell1d Class Reference
ell1d Class Reference
Ellipsoid Method for special 1D case.
#include <ell1d.hpp>
Public Types
using return_t = std::tuple< int, double >
Public Member Functions
ell1d (const double &l, const double &u)
Construct a new ell1d object.
ell1d (const ell1d &E)=default
Construct a new ell1d object.
auto xc () const -> double
void set_xc (const double &xc)
Set the xc object.
return_t update (const std::tuple< double, double > &cut)
Private Attributes
double _r
double _xc
Detailed Description
Ellipsoid Method for special 1D case.
Definition at line 11 of file ell1d.hpp.
Member Typedef Documentation
return_t
using ell1d::return_t = std::tuple<int, double>
Definition at line 14 of file ell1d.hpp.
Constructor & Destructor Documentation
ell1d() [1/2]
ell1d::ell1d (const double & l, const double & u) inline
Construct a new ell1d object.
Parameters
l
u
Definition at line 27 of file ell1d.hpp.
References E.
ell1d() [2/2]
ell1d::ell1d (const ell1d & E) default
Construct a new ell1d object.
Parameters
E
Member Function Documentation
set_xc()
void ell1d::set_xc (const double & xc) inline
Set the xc object.
Parameters
xc
Definition at line 55 of file ell1d.hpp.
References update(), and xc().
update()
ell1d::return_t ell1d::update (const std::tuple< double, double > & cut)
Parameters
g
beta
Returns
return_t
Parameters
cut
Returns
ell1d::return_t
Definition at line 11 of file ell1d.cpp.
References _r, and _xc.
Referenced by set_xc().
xc()
auto ell1d::xc () const -> double inline
Returns
double
Definition at line 45 of file ell1d.hpp.
References _xc.
Referenced by set_xc().
Member Data Documentation
_r
double ell1d::_r private
Definition at line 17 of file ell1d.hpp.
Referenced by update().
_xc
double ell1d::_xc private
Definition at line 18 of file ell1d.hpp.
Referenced by update(), and xc().
The documentation for this class was generated from the following files:
lib/include/ellcpp/ell1d.hpp
lib/src/ell1d.cpp