EllCpp: negCycleFinder< Graph > Class Template Reference
negCycleFinder< Graph > Class Template Reference
negative cycle
#include <neg_cycle.hpp>
Public Member Functions
negCycleFinder (const Graph &G)
Construct a new neg Cycle Finder object.
template<typename Container , typename WeightFn >
auto find_neg_cycle (Container &dist, const WeightFn &get_weight) -> std::vector< edge_t >
find negative cycle
Private Types
using node_t = typename Graph::node_t
using edge_t = typename Graph::edge_t
Private Member Functions
auto __find_cycle () -> node_t
Find a cycle on policy graph.
template<typename Container , typename WeightFn >
auto __relax (Container &dist, const WeightFn &get_weight) -> bool
Perform one relaxation.
auto __cycle_list (const node_t &handle) -> std::vector< edge_t >
generate a cycle list
template<typename Container , typename WeightFn >
auto __is_negative (const node_t &handle, Container &dist, const WeightFn &get_weight) -> bool
check if it is really a negative cycle
Private Attributes
py::dict< node_t, node_t > _pred {}
py::dict< node_t, edge_t > _edge {}
const Graph & _G
Detailed Description
template<typename Graph>
class negCycleFinder< Graph >
negative cycle
Negative cycle detection for (auto weighed graphs.
Template Parameters
Graph Note: Bellman-Ford's shortest-path algorithm (BF) is NOT the best way to detect negative cycles, because
BF needs a source node.
BF detect whether there is a negative cycle at the fianl stage.
BF restarts the solution (dist[u]) every time.
Definition at line 24 of file neg_cycle.hpp.
Member Typedef Documentation
edge_t
template<typename Graph> using negCycleFinder< Graph >::edge_t = typename Graph::edge_t private
Definition at line 27 of file neg_cycle.hpp.
node_t
template<typename Graph> using negCycleFinder< Graph >::node_t = typename Graph::node_t private
Definition at line 26 of file neg_cycle.hpp.
Constructor & Destructor Documentation
negCycleFinder()
template<typename Graph> negCycleFinder< Graph >::negCycleFinder (const Graph & G) inline explicit
Construct a new neg Cycle Finder object.
Parameters
G
Definition at line 41 of file neg_cycle.hpp.
Member Function Documentation
__cycle_list()
template<typename Graph> auto negCycleFinder< Graph >::__cycle_list (const node_t & handle) -> std::vector<edge_t> inline private
generate a cycle list
Parameters
handle
Returns
std::vector<edge_t>
Definition at line 154 of file neg_cycle.hpp.
References negCycleFinder< Graph >::_edge, and negCycleFinder< Graph >::_pred.
Referenced by negCycleFinder< Graph >::find_neg_cycle().
__find_cycle()
template<typename Graph> auto negCycleFinder< Graph >::__find_cycle () -> node_t inline private
Find a cycle on policy graph.
Returns
node_t a start node of the cycle
Definition at line 81 of file neg_cycle.hpp.
References negCycleFinder< Graph >::_pred.
Referenced by negCycleFinder< Graph >::find_neg_cycle().
__is_negative()
template<typename Graph> template<typename Container , typename WeightFn > auto negCycleFinder< Graph >::__is_negative (const node_t & handle, Container & dist, const WeightFn & get_weight) -> bool inline private
check if it is really a negative cycle
Template Parameters
Container
WeightFn
Parameters
handle
dist
get_weight
Returns
true
false
Definition at line 183 of file neg_cycle.hpp.
References negCycleFinder< Graph >::_edge, negCycleFinder< Graph >::_pred, and dist.
Referenced by negCycleFinder< Graph >::find_neg_cycle().
__relax()
template<typename Graph> template<typename Container , typename WeightFn > auto negCycleFinder< Graph >::__relax (Container & dist, const WeightFn & get_weight) -> bool inline private
Perform one relaxation.
Template Parameters
Container
WeightFn
Parameters
dist
get_weight
Returns
true
false
Definition at line 128 of file neg_cycle.hpp.
References negCycleFinder< Graph >::_edge, negCycleFinder< Graph >::_pred, and dist.
Referenced by negCycleFinder< Graph >::find_neg_cycle().
find_neg_cycle()
template<typename Graph> template<typename Container , typename WeightFn > auto negCycleFinder< Graph >::find_neg_cycle (Container & dist, const WeightFn & get_weight) -> std::vector<edge_t> inline
find negative cycle
Template Parameters
Container
WeightFn
Parameters
[in,out] dist
get_weight
Returns
std::vector<edge_t>
Definition at line 57 of file neg_cycle.hpp.
References negCycleFinder< Graph >::__cycle_list(), negCycleFinder< Graph >::__find_cycle(), negCycleFinder< Graph >::__is_negative(), negCycleFinder< Graph >::__relax(), negCycleFinder< Graph >::_edge, negCycleFinder< Graph >::_pred, and dist.
Referenced by network_oracle< Graph, Container, optscaling_oracle::Ratio >::operator()().
Member Data Documentation
_edge
template<typename Graph> py::dict<node_t, edge_t> negCycleFinder< Graph >::_edge {} private
Definition at line 30 of file neg_cycle.hpp.
Referenced by negCycleFinder< Graph >::__cycle_list(), negCycleFinder< Graph >::__is_negative(), negCycleFinder< Graph >::__relax(), and negCycleFinder< Graph >::find_neg_cycle().
_G
template<typename Graph> const Graph& negCycleFinder< Graph >::_G private
Definition at line 33 of file neg_cycle.hpp.
_pred
template<typename Graph> py::dict<node_t, node_t> negCycleFinder< Graph >::_pred {} private
Definition at line 29 of file neg_cycle.hpp.
Referenced by negCycleFinder< Graph >::__cycle_list(), negCycleFinder< Graph >::__find_cycle(), negCycleFinder< Graph >::__is_negative(), negCycleFinder< Graph >::__relax(), and negCycleFinder< Graph >::find_neg_cycle().
The documentation for this class was generated from the following file:
lib/include/netoptim/neg_cycle.hpp