EllCpp: qmi_oracle Class Reference
qmi_oracle Class Reference
Oracle for Quadratic Matrix Inequality.
#include <qmi_oracle.hpp>
Public Member Functions
qmi_oracle (gsl::span< const Arr > F, const Arr &F0)
Construct a new qmi oracle object.
void update (double t)
Update t.
auto operator() (const Arr &x) -> std::optional< Cut >
Public Attributes
chol_ext _Q
Private Types
using Arr = xt::xarray< double, xt::layout_type::row_major >
using Cut = std::tuple< Arr, double >
Private Attributes
double _t = 0.
size_t _nx = 0
size_t _count = 0
size_t _n
size_t _m
gsl::span< const Arr > _F
const Arr & _F0
Arr _Fx
Detailed Description
Oracle for Quadratic Matrix Inequality.
find x s.t.​ t*I - F(x)' F(x) ⪰ 0
where
F(x) = F0 - (F1 * x1 + F2 * x2 + ...)
Definition at line 19 of file qmi_oracle.hpp.
Member Typedef Documentation
Arr
using qmi_oracle::Arr = xt::xarray<double, xt::layout_type::row_major> private
Definition at line 21 of file qmi_oracle.hpp.
Cut
using qmi_oracle::Cut = std::tuple<Arr, double> private
Definition at line 22 of file qmi_oracle.hpp.
Constructor & Destructor Documentation
qmi_oracle()
qmi_oracle::qmi_oracle (gsl::span< const Arr > F, const Arr & F0) inline
Construct a new qmi oracle object.
Parameters
F
F0
Definition at line 45 of file qmi_oracle.hpp.
References _m, _Q, and zeros().
Member Function Documentation
operator()()
std::optional< Cut > qmi_oracle::operator() (const Arr & x) -> std::optional<Cut>
Parameters
x
Returns
std::optional<Cut>
Definition at line 17 of file qmi_oracle.cpp.
References _count, _F, _F0, _Fx, _nx, _Q, _t, COLUMN, chol_ext< Allow_semidefinite >::factor(), chol_ext< Allow_semidefinite >::is_spd(), chol_ext< Allow_semidefinite >::p, py::range(), ROW, chol_ext< Allow_semidefinite >::v, chol_ext< Allow_semidefinite >::witness(), and zeros().
Referenced by update().
update()
void qmi_oracle::update (double t) inline
Update t.
Parameters
t the best-so-far optimal value
Definition at line 60 of file qmi_oracle.hpp.
References operator()(), and t.
Referenced by lsq_oracle::operator()().
Member Data Documentation
_count
size_t qmi_oracle::_count = 0 private
Definition at line 27 of file qmi_oracle.hpp.
Referenced by operator()().
_F
gsl::span<const Arr> qmi_oracle::_F private
Definition at line 31 of file qmi_oracle.hpp.
Referenced by operator()().
_F0
const Arr& qmi_oracle::_F0 private
Definition at line 32 of file qmi_oracle.hpp.
Referenced by operator()().
_Fx
Arr qmi_oracle::_Fx private
Definition at line 33 of file qmi_oracle.hpp.
Referenced by operator()().
_m
size_t qmi_oracle::_m private
Definition at line 30 of file qmi_oracle.hpp.
Referenced by qmi_oracle().
_n
size_t qmi_oracle::_n private
Definition at line 29 of file qmi_oracle.hpp.
_nx
size_t qmi_oracle::_nx = 0 private
Definition at line 26 of file qmi_oracle.hpp.
Referenced by operator()().
_Q
chol_ext qmi_oracle::_Q
Definition at line 36 of file qmi_oracle.hpp.
Referenced by operator()(), lsq_oracle::operator()(), and qmi_oracle().
_t
double qmi_oracle::_t = 0. private
Definition at line 25 of file qmi_oracle.hpp.
Referenced by operator()().
The documentation for this class was generated from the following files:
lib/include/ellcpp/oracles/qmi_oracle.hpp
lib/src/qmi_oracle.cpp