EllCpp: posynomial< _Tp > Class Template Reference
posynomial< _Tp > Class Template Reference
Reference: S.P.
#include <posynomial.hpp>
Public Member Functions
posynomial (size_t n, size_t N)
Constructor.
posynomial (const monomial< _Tp > &m)
Constructor.
template<typename Up , class Map >
posynomial (const posynomial< Up > &posyn, const Map &polarity)
Constructor (for AAF -> double)
~posynomial ()
Destructor.
_Self & operator+= (const monomial< _Tp > &m)
Add and assign.
_Self & operator+= (const _Self &P)
Add and assign.
_Self & operator*= (const monomial< _Tp > &m)
Multiply and assign.
_Self & operator/= (const monomial< _Tp > &m)
Divide and assign.
_Self & operator*= (const _Tp &c)
Multiply and assign.
_Self & operator/= (const _Tp &c)
Divide and assign.
_Self operator* (const _Self &P) const
Multiply.
template<typename _Up >
_Tp lse (const _Up &y) const
Function evaluation of log(f(exp(y))).
template<typename _Up >
std::valarray< _Tp > log_exp_gradient (const _Up &y) const
Gradient of log(f(exp(y))).
template<typename _Up >
_Tp log_exp_fvalue_with_gradient (const _Up &y, std::valarray< _Tp > &g) const
function value and gradient of log(f(exp(y))).
template<typename _Up >
std::valarray< _Tp > lse_gradient (const _Up &y, _Tp &f) const
function value and gradient of log(f(exp(y))).
posynomial (const _Self &Q)
_Self & operator= (const _Self &Q)
template<>
posynomial (const posynomial< aaf > &posyn, const pmap &polarity)
Constructor (for AAF -> double)
Public Attributes
std::vector< monomial< _Tp > > _M
vector of monomials
Private Types
using Vec = std::valarray< double >
using _Self = posynomial< _Tp >
Detailed Description
template<typename _Tp>
class posynomial< _Tp >
Reference: S.P.
Boyd, S.J. Kim and L.Vandenberghe and A. Hassibi. A Tutorial on Geometric Programming. Available at http://www.standford.edu/~boyd/gp_tutorial.html Posynomial function. A sum of one or more monomials, i.e., a function of the form
f(x) = {k=1}^{K} c_k x_1^{a_{1k}} x_2^{a_{2k}} ... x_n^{a_{nk}},
where $c_k$ > 0, is called a posynomial function or, more simply, a posynomial (with $K$ terms, in the variables $x_1$, ..., $x_n$. The term `posynomial' is meant to suggest a combination of `positive' and `polynomial'.
Any monomial is also a posynomial. Posynomials are close under addition, multiplication, and positive scaling. Posynomials can be divided by monomials (with the result also a posynomial): If $f$ is a posynomial and $g$ is a monomial, then $f/g$ is a posynomial. Note that <_Tp> could be <double> or <AAF>
Definition at line 34 of file posynomial.hpp.
Member Typedef Documentation
_Self
template<typename _Tp> using posynomial< _Tp >::_Self = posynomial<_Tp> private
Definition at line 37 of file posynomial.hpp.
Vec
template<typename _Tp> using posynomial< _Tp >::Vec = std::valarray<double> private
Definition at line 36 of file posynomial.hpp.
Constructor & Destructor Documentation
posynomial() [1/5]
template<typename _Tp> posynomial< _Tp >::posynomial (size_t n, size_t N) inline explicit
Constructor.
Definition at line 41 of file posynomial.hpp.
posynomial() [2/5]
template<typename _Tp> posynomial< _Tp >::posynomial (const monomial< _Tp > & m) inline
Constructor.
Definition at line 47 of file posynomial.hpp.
posynomial() [3/5]
template<typename _Tp> template<typename Up , class Map > posynomial< _Tp >::posynomial (const posynomial< Up > & posyn, const Map & polarity) inline
Constructor (for AAF -> double)
Definition at line 54 of file posynomial.hpp.
References posynomial< _Tp >::_M.
~posynomial()
template<typename _Tp> posynomial< _Tp >::~posynomial () inline
Destructor.
Definition at line 64 of file posynomial.hpp.
posynomial() [4/5]
template<typename _Tp> posynomial< _Tp >::posynomial (const _Self & Q) inline
Definition at line 297 of file posynomial.hpp.
posynomial() [5/5]
template<> posynomial< double >::posynomial (const posynomial< aaf > & posyn, const pmap & polarity)
Constructor (for AAF -> double)
Definition at line 66 of file rgp_yalaa.cpp.
References posynomial< _Tp >::_M.
Member Function Documentation
log_exp_fvalue_with_gradient()
template<typename _Tp> template<typename _Up > _Tp posynomial< _Tp >::log_exp_fvalue_with_gradient (const _Up & y, std::valarray< _Tp > & g) const inline
function value and gradient of log(f(exp(y))).
Note that for AAF, the two quantities have to be evaluated at the same time in order to maintain the noise symbols consistency
Definition at line 206 of file posynomial.hpp.
References posynomial< _Tp >::_M, posynomial< _Tp >::lse(), n, and N.
log_exp_gradient()
template<typename _Tp> template<typename _Up > std::valarray<_Tp> posynomial< _Tp >::log_exp_gradient (const _Up & y) const inline
Gradient of log(f(exp(y))).
Precondition: call f(y) previously
Definition at line 158 of file posynomial.hpp.
References posynomial< _Tp >::_M, posynomial< _Tp >::lse(), n, and N.
lse()
template<typename _Tp> template<typename _Up > _Tp posynomial< _Tp >::lse (const _Up & y) const inline
Function evaluation of log(f(exp(y))).
Todo:
should combine the following two functions into one, and eniminate _p
Definition at line 132 of file posynomial.hpp.
References posynomial< _Tp >::_M, and N.
Referenced by posynomial< _Tp >::log_exp_fvalue_with_gradient(), posynomial< _Tp >::log_exp_gradient(), posynomial< _Tp >::lse_gradient(), and gp_base< _Tp >::operator()().
lse_gradient()
template<typename _Tp> template<typename _Up > std::valarray<_Tp> posynomial< _Tp >::lse_gradient (const _Up & y, _Tp & f) const inline
function value and gradient of log(f(exp(y))).
Definition at line 252 of file posynomial.hpp.
References posynomial< _Tp >::_M, posynomial< _Tp >::lse(), n, and N.
Referenced by gp_base< _Tp >::operator()().
operator*()
template<typename _Tp> _Self posynomial< _Tp >::operator* (const _Self & P) const inline
Multiply.
Todo:
simplify the result.
Definition at line 114 of file posynomial.hpp.
References posynomial< _Tp >::_M.
operator*=() [1/2]
template<typename _Tp> _Self& posynomial< _Tp >::operator*= (const monomial< _Tp > & m) inline
Multiply and assign.
Definition at line 82 of file posynomial.hpp.
References posynomial< _Tp >::_M.
operator*=() [2/2]
template<typename _Tp> _Self& posynomial< _Tp >::operator*= (const _Tp & c) inline
Multiply and assign.
Definition at line 98 of file posynomial.hpp.
References posynomial< _Tp >::_M.
operator+=() [1/2]
template<typename _Tp> _Self& posynomial< _Tp >::operator+= (const monomial< _Tp > & m) inline
Add and assign.
Definition at line 67 of file posynomial.hpp.
References posynomial< _Tp >::_M.
operator+=() [2/2]
template<typename _Tp> _Self& posynomial< _Tp >::operator+= (const _Self & P) inline
Add and assign.
Definition at line 74 of file posynomial.hpp.
References posynomial< _Tp >::_M.
operator/=() [1/2]
template<typename _Tp> _Self& posynomial< _Tp >::operator/= (const monomial< _Tp > & m) inline
Divide and assign.
Definition at line 90 of file posynomial.hpp.
References posynomial< _Tp >::_M.
operator/=() [2/2]
template<typename _Tp> _Self& posynomial< _Tp >::operator/= (const _Tp & c) inline
Divide and assign.
Definition at line 106 of file posynomial.hpp.
References posynomial< _Tp >::_M.
operator=()
template<typename _Tp> _Self& posynomial< _Tp >::operator= (const _Self & Q) inline
Definition at line 303 of file posynomial.hpp.
References posynomial< _Tp >::_M.
Member Data Documentation
_M
template<typename _Tp> std::vector<monomial<_Tp> > posynomial< _Tp >::_M
vector of monomials
Definition at line 294 of file posynomial.hpp.
Referenced by posynomial< _Tp >::log_exp_fvalue_with_gradient(), posynomial< _Tp >::log_exp_gradient(), posynomial< _Tp >::lse(), posynomial< _Tp >::lse_gradient(), gp_base< _Tp >::operator()(), posynomial< _Tp >::operator*(), posynomial< _Tp >::operator*=(), posynomial< _Tp >::operator+=(), posynomial< _Tp >::operator/=(), posynomial< _Tp >::operator=(), and posynomial< _Tp >::posynomial().
The documentation for this class was generated from the following file:
lib/include/ellip/posynomial.hpp