EllCpp: profit_oracle Class Reference
profit_oracle Class Reference
Oracle for a profit maximization problem.
#include <profit_oracle.hpp>
Public Member Functions
profit_oracle (double p, double A, double k, Arr a, Arr v)
Construct a new profit oracle object.
auto operator() (const Arr &y, double t) const -> std::tuple< Cut, double >
Public Attributes
Arr _a
Private Types
using Arr = xt::xarray< double, xt::layout_type::row_major >
using Cut = std::tuple< Arr, double >
Private Attributes
double _log_pA
double _log_k
Arr _v
Detailed Description
Oracle for a profit maximization problem.
This example is taken from [Aliabadi and Salahi, 2013]
max     p(A x1^α x2^β) - v1*x1 - v2*x2
s.t.    x1 ≤ k
where:
p(A x1^α x2^β): Cobb-Douglas production function
p: the market price per unit
A: the scale of production
α, β: the output elasticities
x: input quantity
v: output price
k: a given constant that restricts the quantity of x1
Definition at line 26 of file profit_oracle.hpp.
Member Typedef Documentation
Arr
using profit_oracle::Arr = xt::xarray<double, xt::layout_type::row_major> private
Definition at line 28 of file profit_oracle.hpp.
Cut
using profit_oracle::Cut = std::tuple<Arr, double> private
Definition at line 29 of file profit_oracle.hpp.
Constructor & Destructor Documentation
profit_oracle()
profit_oracle::profit_oracle (double p, double A, double k, Arr a, Arr v) inline
Construct a new profit oracle object.
Parameters
p the market price per unit
A the scale of production
k a given constant that restricts the quantity of x1
a the output elasticities
v output price
Definition at line 49 of file profit_oracle.hpp.
References operator()(), and t.
Member Function Documentation
operator()()
std::tuple< Cut, double > profit_oracle::operator() (const Arr & y, double t) const -> std::tuple<Cut, double>
Parameters
y input quantity (in log scale)
t the best-so-far optimal value
Returns
std::tuple<Cut, double> Cut and the updated best-so-far value
Parameters
y
t the best-so-far optimal value
Returns
std::tuple<Cut, double>
Definition at line 14 of file profit_oracle.cpp.
References _a, _log_k, _log_pA, and _v.
Referenced by profit_oracle(), and profit_q_oracle::profit_q_oracle().
Member Data Documentation
_a
Arr profit_oracle::_a
Definition at line 37 of file profit_oracle.hpp.
Referenced by operator()(), and profit_rb_oracle::operator()().
_log_k
double profit_oracle::_log_k private
Definition at line 33 of file profit_oracle.hpp.
Referenced by operator()().
_log_pA
double profit_oracle::_log_pA private
Definition at line 32 of file profit_oracle.hpp.
Referenced by operator()().
_v
Arr profit_oracle::_v private
Definition at line 34 of file profit_oracle.hpp.
Referenced by operator()().
The documentation for this class was generated from the following files:
lib/include/ellcpp/oracles/profit_oracle.hpp
lib/src/profit_oracle.cpp