EllCpp: lmi_oracle Class Reference
lmi_oracle Class Reference
Oracle for Linear Matrix Inequality.
#include <lmi_oracle.hpp>
Public Member Functions
lmi_oracle (gsl::span< const Arr > F, Arr &&B)
Construct a new lmi oracle object.
lmi_oracle (gsl::span< const Arr > F, const Arr &B)
Construct a new lmi oracle object.
auto operator() (const Arr &x) -> std::optional< Cut >
Private Types
using Arr = xt::xarray< double, xt::layout_type::row_major >
using Cut = std::tuple< Arr, double >
Private Attributes
gsl::span< const Arr > _F
Arr _F0
chol_ext _Q
Detailed Description
Oracle for Linear Matrix Inequality.
find x s.t.​ (B - F*x) ⪰ 0
Definition at line 15 of file lmi_oracle.hpp.
Member Typedef Documentation
Arr
using lmi_oracle::Arr = xt::xarray<double, xt::layout_type::row_major> private
Definition at line 17 of file lmi_oracle.hpp.
Cut
using lmi_oracle::Cut = std::tuple<Arr, double> private
Definition at line 18 of file lmi_oracle.hpp.
Constructor & Destructor Documentation
lmi_oracle() [1/2]
lmi_oracle::lmi_oracle (gsl::span< const Arr > F, Arr && B) inline
Construct a new lmi oracle object.
Parameters
F
B
Definition at line 32 of file lmi_oracle.hpp.
lmi_oracle() [2/2]
lmi_oracle::lmi_oracle (gsl::span< const Arr > F, const Arr & B) inline
Construct a new lmi oracle object.
Parameters
F
B
Definition at line 45 of file lmi_oracle.hpp.
References _Q, and operator()().
Member Function Documentation
operator()()
std::optional< Cut > lmi_oracle::operator() (const Arr & x) -> std::optional<Cut>
Parameters
x
Returns
std::optional<Cut>
Definition at line 14 of file lmi_oracle.cpp.
References _F, _F0, _Q, chol_ext< Allow_semidefinite >::factor(), chol_ext< Allow_semidefinite >::is_spd(), n, chol_ext< Allow_semidefinite >::sym_quad(), chol_ext< Allow_semidefinite >::witness(), and zeros().
Referenced by lmi_oracle().
Member Data Documentation
_F
gsl::span<const Arr> lmi_oracle::_F private
Definition at line 21 of file lmi_oracle.hpp.
Referenced by operator()().
_F0
Arr lmi_oracle::_F0 private
Definition at line 22 of file lmi_oracle.hpp.
Referenced by operator()().
_Q
chol_ext lmi_oracle::_Q private
Definition at line 23 of file lmi_oracle.hpp.
Referenced by lmi_oracle(), and operator()().
The documentation for this class was generated from the following files:
lib/include/ellcpp/oracles/lmi_oracle.hpp
lib/src/lmi_oracle.cpp