EllCpp: lmi_old_oracle Class Reference
lmi_old_oracle Class Reference
Oracle for Linear Matrix Inequality.
#include <lmi_old_oracle.hpp>
Public Member Functions
lmi_old_oracle (gsl::span< const Arr > F, Arr &&B)
Construct a new lmi oracle object.
lmi_old_oracle (gsl::span< const Arr > F, const Arr &B)
Construct a new lmi oracle object.
auto operator() (const Arr &x) -> std::optional< Cut >
Private Types
using Arr = xt::xarray< double, xt::layout_type::row_major >
using Cut = std::tuple< Arr, double >
Private Attributes
gsl::span< const Arr > _F
Arr _F0
chol_ext _Q
Detailed Description
Oracle for Linear Matrix Inequality.
Oracle for: F * x <= B or (B - F * x) must be a semidefinte matrix
Definition at line 17 of file lmi_old_oracle.hpp.
Member Typedef Documentation
Arr
using lmi_old_oracle::Arr = xt::xarray<double, xt::layout_type::row_major> private
Definition at line 19 of file lmi_old_oracle.hpp.
Cut
using lmi_old_oracle::Cut = std::tuple<Arr, double> private
Definition at line 20 of file lmi_old_oracle.hpp.
Constructor & Destructor Documentation
lmi_old_oracle() [1/2]
lmi_old_oracle::lmi_old_oracle (gsl::span< const Arr > F, Arr && B) inline
Construct a new lmi oracle object.
Parameters
F
B
Definition at line 34 of file lmi_old_oracle.hpp.
lmi_old_oracle() [2/2]
lmi_old_oracle::lmi_old_oracle (gsl::span< const Arr > F, const Arr & B) inline
Construct a new lmi oracle object.
Parameters
F
B
Definition at line 47 of file lmi_old_oracle.hpp.
References _Q, and operator()().
Member Function Documentation
operator()()
std::optional< Cut > lmi_old_oracle::operator() (const Arr & x) -> std::optional<Cut>
Parameters
x
Returns
std::optional<Cut>
Definition at line 15 of file lmi_old_oracle.cpp.
References _F, _F0, _Q, A, chol_ext< Allow_semidefinite >::factorize(), chol_ext< Allow_semidefinite >::is_spd(), n, chol_ext< Allow_semidefinite >::sym_quad(), chol_ext< Allow_semidefinite >::witness(), and zeros().
Referenced by lmi_old_oracle().
Member Data Documentation
_F
gsl::span<const Arr> lmi_old_oracle::_F private
Definition at line 23 of file lmi_old_oracle.hpp.
Referenced by operator()().
_F0
Arr lmi_old_oracle::_F0 private
Definition at line 24 of file lmi_old_oracle.hpp.
Referenced by operator()().
_Q
chol_ext lmi_old_oracle::_Q private
Definition at line 25 of file lmi_old_oracle.hpp.
Referenced by lmi_old_oracle(), and operator()().
The documentation for this class was generated from the following files:
lib/include/ellcpp/oracles/lmi_old_oracle.hpp
lib/src/lmi_old_oracle.cpp