EllCpp: ellipsoid Class Reference
ellipsoid Class Reference
Enclosing ellipsoid.
#include <ellipsoid.hpp>
Public Member Functions
ellipsoid (Vec &x, double rho)
Constructor.
ellipsoid (Vec &x, const Vec &r)
Constructor.
~ellipsoid ()
Vec & x ()
void update (const Vec &g)
CUTSTATUS update (const Vec &g, double beta)
Private Types
using Vec = std::valarray< double >
using Matrix = std::valarray< Vec >
Private Attributes
size_t _n
Matrix _Ae
Vec _x
Detailed Description
Enclosing ellipsoid.
Definition at line 16 of file ellipsoid.hpp.
Member Typedef Documentation
Matrix
using ellipsoid::Matrix = std::valarray<Vec> private
Definition at line 19 of file ellipsoid.hpp.
Vec
using ellipsoid::Vec = std::valarray<double> private
Definition at line 18 of file ellipsoid.hpp.
Constructor & Destructor Documentation
ellipsoid() [1/2]
ellipsoid::ellipsoid (Vec & x, double rho) inline
Constructor.
Definition at line 23 of file ellipsoid.hpp.
References _Ae, and _n.
ellipsoid() [2/2]
ellipsoid::ellipsoid (Vec & x, const Vec & r) inline
Constructor.
Definition at line 36 of file ellipsoid.hpp.
References _Ae, and _n.
~ellipsoid()
ellipsoid::~ellipsoid () inline
Definition at line 48 of file ellipsoid.hpp.
Member Function Documentation
update() [1/2]
void ellipsoid::update (const Vec & g)
Definition at line 3 of file ellipsoid.cpp.
References _Ae, _n, _x, delta, and sqrt().
Referenced by x().
update() [2/2]
CUTSTATUS ellipsoid::update (const Vec & g, double beta)
Definition at line 41 of file ellipsoid.cpp.
References _Ae, _n, _x, CUT, delta, NOEFFECT, NOSOLUTION, and sqrt().
x()
Vec& ellipsoid::x () inline
Definition at line 50 of file ellipsoid.hpp.
References _x, and update().
Referenced by ellipsoid_dc(), and ellipsoid_dc_discrete().
Member Data Documentation
_Ae
Matrix ellipsoid::_Ae private
Definition at line 61 of file ellipsoid.hpp.
Referenced by ellipsoid(), and update().
_n
size_t ellipsoid::_n private
Definition at line 60 of file ellipsoid.hpp.
Referenced by ellipsoid(), and update().
_x
Vec ellipsoid::_x private
Definition at line 62 of file ellipsoid.hpp.
Referenced by update(), and x().
The documentation for this class was generated from the following files:
lib/include/ellip/ellipsoid.hpp
lib/include/ellip/ellipsoid.cpp