EllCpp: lsq_oracle Class Reference
lsq_oracle Class Reference
min ‖ Σ(p) − Y ‖ s.t. Σ(p) ⪰ 0
Public Member Functions
lsq_oracle (const std::vector< Arr > &F, const Arr &F0)
Construct a new lsq oracle object.
std::tuple< Cut, double > operator() (const Arr &x, double t)
Private Types
using Arr = xt::xarray< double, xt::layout_type::row_major >
using shape_type = Arr::shape_type
using Cut = std::tuple< Arr, double >
Private Attributes
qmi_oracle _qmi
lmi0_oracle _lmi0
Detailed Description
min ‖ Σ(p) − Y ‖ s.t. Σ(p) ⪰ 0
where
ρ(h) = p1 Ψ1(h) + ··· + pn Ψn(h)
{Fk}i,j = Ψk(‖sj − si‖^2)
Definition at line 140 of file lsq_corr_ell.cpp.
Member Typedef Documentation
Arr
using lsq_oracle::Arr = xt::xarray<double, xt::layout_type::row_major> private
Definition at line 142 of file lsq_corr_ell.cpp.
Cut
using lsq_oracle::Cut = std::tuple<Arr, double> private
Definition at line 144 of file lsq_corr_ell.cpp.
shape_type
using lsq_oracle::shape_type = Arr::shape_type private
Definition at line 143 of file lsq_corr_ell.cpp.
Constructor & Destructor Documentation
lsq_oracle()
lsq_oracle::lsq_oracle (const std::vector< Arr > & F, const Arr & F0) inline
Construct a new lsq oracle object.
Parameters
F
F0
Definition at line 157 of file lsq_corr_ell.cpp.
Referenced by lsq_corr_poly2().
Member Function Documentation
operator()()
std::tuple<Cut, double> lsq_oracle::operator() (const Arr & x, double t) inline
Parameters
x
t the best-so-far optimal value
Returns
auto
Definition at line 170 of file lsq_corr_ell.cpp.
References _lmi0, qmi_oracle::_Q, _qmi, n, chol_ext< Allow_semidefinite >::p, py::range(), t, qmi_oracle::update(), and zeros().
Member Data Documentation
_lmi0
lmi0_oracle lsq_oracle::_lmi0 private
Definition at line 148 of file lsq_corr_ell.cpp.
Referenced by mle_oracle::mle_oracle(), operator()(), and mle_oracle::operator()().
_qmi
qmi_oracle lsq_oracle::_qmi private
Definition at line 147 of file lsq_corr_ell.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
lib/src/lsq_corr_ell.cpp