EllCpp: lib/test/src/corr_fn_ell.cpp File Reference
corr_fn_ell.cpp File Reference
#include <catch2/catch.hpp>
#include <xtensor/xarray.hpp>
Typedefs
using Arr = xt::xarray< double, xt::layout_type::row_major >
Functions
Arr create_2d_sites (size_t, size_t)
Create a 2d sites object.
Arr create_2d_isotropic (const Arr &, size_t)
Create a 2d isotropic object.
std::tuple< size_t, bool > lsq_corr_poly2 (const Arr &, const Arr &, size_t)
std::tuple< size_t, bool > mle_corr_poly (const Arr &, const Arr &, size_t)
TEST_CASE ("check create_2d_isotropic", "[corr_fn]")
TEST_CASE ("lsq_corr_fn", "[corr_fn]")
TEST_CASE ("mle_corr_fn", "[corr_fn]")
Typedef Documentation
Arr
using Arr = xt::xarray<double, xt::layout_type::row_major>
Definition at line 5 of file corr_fn_ell.cpp.
Function Documentation
create_2d_isotropic()
Arr create_2d_isotropic (const Arr & s, size_t N = 3000U)
Create a 2d isotropic object.
Parameters
s location of sites
N
Returns
Arr Biased covariance matrix
Definition at line 46 of file lsq_corr_ell.cpp.
References A, n, N, sqrt(), and zeros().
Referenced by TEST_CASE().
create_2d_sites()
Arr create_2d_sites (size_t nx = 10U, size_t ny = 8U)
Create a 2d sites object.
Parameters
nx
ny
Returns
Arr location of sites
Definition at line 27 of file lsq_corr_ell.cpp.
Referenced by TEST_CASE().
lsq_corr_poly2()
std::tuple<size_t, bool> lsq_corr_poly2 (const Arr & Y, const Arr & s, size_t m)
Parameters
Y
s
m
Returns
std::tuple<size_t, bool>
Definition at line 238 of file lsq_corr_ell.cpp.
References construct_poly_matrix(), lsq_corr_core2(), lsq_oracle::lsq_oracle(), and P.
Referenced by TEST_CASE().
mle_corr_poly()
std::tuple<size_t, bool> mle_corr_poly (const Arr & Y, const Arr & s, size_t m)
Parameters
Y
s
m
Returns
std::tuple<size_t, bool>
Definition at line 362 of file lsq_corr_ell.cpp.
References construct_poly_matrix(), mle_corr_core(), and P.
Referenced by TEST_CASE().
TEST_CASE() [1/3]
TEST_CASE ("check create_2d_isotropic" , "" [corr_fn])
Definition at line 12 of file corr_fn_ell.cpp.
References CHECK(), create_2d_isotropic(), and create_2d_sites().
TEST_CASE() [2/3]
TEST_CASE ("lsq_corr_fn" , "" [corr_fn])
Definition at line 19 of file corr_fn_ell.cpp.
References CHECK(), create_2d_isotropic(), create_2d_sites(), and lsq_corr_poly2().
TEST_CASE() [3/3]
TEST_CASE ("mle_corr_fn" , "" [corr_fn])
Definition at line 29 of file corr_fn_ell.cpp.
References CHECK(), create_2d_isotropic(), create_2d_sites(), and mle_corr_poly().