EllCpp: lib/include/ellcpp/cutting_plane.hpp File Reference
cutting_plane.hpp File Reference
#include <cmath>
#include <tuple>
Classes
struct Options
Options.
struct CInfo
CInfo.
class bsearch_adaptor< Oracle, Space >
Functions
template<typename Oracle , typename Space >
auto bsearch (Oracle &Omega, const Space &I, const Options &options=Options())
template<typename Oracle , typename Space >
auto cutting_plane_feas (Oracle &Omega, Space &S, const Options &options=Options())
Find a point in a convex set (defined through a cutting-plane oracle).
template<typename Oracle , typename Space >
auto cutting_plane_dc (Oracle &Omega, Space &S, double t, const Options &options=Options())
Cutting-plane method for solving convex problem.
template<typename Oracle , typename Space >
auto cutting_plane_q (Oracle &Omega, Space &S, double t, const Options &options=Options())
Function Documentation
bsearch()
template<typename Oracle , typename Space > auto bsearch (Oracle & Omega, const Space & I, const Options & options = Options())
Template Parameters
Oracle
Space
Parameters
Omega
I
options
Returns
auto
Definition at line 55 of file cutting_plane.hpp.
References t.
Referenced by lsq_corr_poly().
cutting_plane_dc()
template<typename Oracle , typename Space > auto cutting_plane_dc (Oracle & Omega, Space & S, double t, const Options & options = Options())
Cutting-plane method for solving convex problem.
Template Parameters
Oracle
Space
T
Parameters
[in] Omega perform assessment on x0
[in] S search Space containing x*
[in] t best-so-far optimal sol'n
[in] max_it maximum number of iterations
[in] tol error tolerance
Returns
x solution vector
niter number of iterations performed
feasible solution found or not
status how is the final cut
Definition at line 205 of file cutting_plane.hpp.
References t.
Referenced by BM_LMI_Lazy(), BM_LMI_No_Trick(), BM_LMI_old(), lsq_corr_core2(), mle_corr_core(), run_lowpass(), and TEST_CASE().
cutting_plane_feas()
template<typename Oracle , typename Space > auto cutting_plane_feas (Oracle & Omega, Space & S, const Options & options = Options())
Find a point in a convex set (defined through a cutting-plane oracle).
Template Parameters
Oracle
Space
T
Parameters
[in] Omega perform assessment on x0
[in] S search Space containing x*
[in] max_it maximum number of iterations
[in] tol error tolerance
Returns
x solution vector
niter number of iterations performed
feasible solution found or not
status how is the final cut
Definition at line 158 of file cutting_plane.hpp.
Referenced by bsearch_adaptor< Oracle, Space >::operator()(), and TEST_CASE().
cutting_plane_q()
template<typename Oracle , typename Space > auto cutting_plane_q (Oracle & Omega, Space & S, double t, const Options & options = Options())
Cutting-plane method for solving convex discrete optimization problem input oracle perform assessment on x0 S(xc) Search space containing x* t best-so-far optimal sol'n max_it maximum number of iterations tol error tolerance output x solution vector niter number of iterations performed
Template Parameters
Oracle
Space
T
Parameters
Omega
S
t the best-so-far optimal value
options
Returns
auto
Definition at line 270 of file cutting_plane.hpp.
References t, and x0.
Referenced by TEST_CASE().