EllCpp: lib/include/ellip/ellipsoid.hpp File Reference
ellipsoid.hpp File Reference
#include <cassert>
#include <valarray>
#include <limits>
Classes
class ellipsoid
Enclosing ellipsoid.
struct Info4EM< Vec >
– (Generalized) bisection method for solving convex minimization problem P:
Enumerations
enum CUTSTATUS { CUT, NOSOLUTION, NOEFFECT }
enum STATUS { FOUND, EXCEEDMAXITER, NOTFOUND }
Functions
template<class Vec >
double norm (const Vec &x)
template<class Enclosing , class Oracle , class Vec >
STATUS ellipsoid_dc_discrete (Enclosing &E, Oracle &P, Vec &best_x, double &best_f, int max_it=100, double tol=1e-4)
template<class Enclosing , class Oracle , class Vec >
STATUS ellipsoid_dc (Enclosing &E, Oracle &P, Vec &best_x, double &best_f, int max_it=100, double tol=1e-4)
template<class Enclosing , class Oracle , class Vec >
STATUS ellipsoid_algo (Enclosing &E, Oracle &P, Vec &best_x, double &best_f, int max_it=100, double tol=1e-4)
Enumeration Type Documentation
CUTSTATUS
enum CUTSTATUS
Returns
return status
Enumerator
CUT
NOSOLUTION
NOEFFECT
Definition at line 8 of file ellipsoid.hpp.
STATUS
enum STATUS
Returns
return status
Enumerator
FOUND
EXCEEDMAXITER
NOTFOUND
Definition at line 67 of file ellipsoid.hpp.
Function Documentation
ellipsoid_algo()
template<class Enclosing , class Oracle , class Vec > STATUS ellipsoid_algo (Enclosing & E, Oracle & P, Vec & best_x, double & best_f, int max_it = 100, double tol = 1e-4)
Definition at line 210 of file ellipsoid.hpp.
References Info4EM< Vec >::_f, Info4EM< Vec >::_g, Info4EM< Vec >::_is_feasible, EXCEEDMAXITER, FOUND, max(), norm(), NOTFOUND, and P.
ellipsoid_dc()
template<class Enclosing , class Oracle , class Vec > STATUS ellipsoid_dc (Enclosing & E, Oracle & P, Vec & best_x, double & best_f, int max_it = 100, double tol = 1e-4)
Definition at line 164 of file ellipsoid.hpp.
References Info4EM< Vec >::_f, Info4EM< Vec >::_g, Info4EM< Vec >::_is_feasible, CUT, EXCEEDMAXITER, FOUND, max(), norm(), NOTFOUND, P, and ellipsoid::x().
Referenced by main().
ellipsoid_dc_discrete()
template<class Enclosing , class Oracle , class Vec > STATUS ellipsoid_dc_discrete (Enclosing & E, Oracle & P, Vec & best_x, double & best_f, int max_it = 100, double tol = 1e-4)
Definition at line 120 of file ellipsoid.hpp.
References Info4EM< Vec >::_f, Info4EM< Vec >::_g, Info4EM< Vec >::_is_feasible, Info4EM< Vec >::_x, CUT, EXCEEDMAXITER, FOUND, max(), norm(), NOTFOUND, P, and ellipsoid::x().
norm()
template<class Vec > double norm (const Vec & x) inline
Definition at line 114 of file ellipsoid.hpp.
References sqrt().
Referenced by ellipsoid_algo(), ellipsoid_dc(), ellipsoid_dc_discrete(), and lsq_corr_core2().