EllCpp: lib/src/lsq_corr_ell.cpp File Reference
lsq_corr_ell.cpp File Reference
#include <ellcpp/cutting_plane.hpp>
#include <ellcpp/ell.hpp>
#include <ellcpp/oracles/lmi0_oracle.hpp>
#include <ellcpp/oracles/lmi_oracle.hpp>
#include <ellcpp/oracles/qmi_oracle.hpp>
#include <ellcpp/utility.hpp>
#include <limits>
#include <tuple>
#include <vector>
#include <xtensor-blas/xlinalg.hpp>
#include <xtensor/xmath.hpp>
#include <xtensor/xnorm.hpp>
#include <xtensor/xrandom.hpp>
Classes
class lsq_oracle
min ‖ Σ(p) − Y ‖ s.t. Σ(p) ⪰ 0
class mle_oracle
Typedefs
using Arr = xt::xarray< double, xt::layout_type::row_major >
Functions
Arr create_2d_sites (size_t nx=10U, size_t ny=8U)
Create a 2d sites object.
Arr create_2d_isotropic (const Arr &s, size_t N=3000U)
Create a 2d isotropic object.
Arr construct_distance_matrix (const Arr &s)
Construct a distance matrix object.
std::vector< Arr > construct_poly_matrix (const Arr &s, size_t m)
Construct distance matrix for polynomial.
auto lsq_corr_core2 (const Arr &Y, size_t m, lsq_oracle &P)
std::tuple< size_t, bool > lsq_corr_poly2 (const Arr &Y, const Arr &s, size_t m)
auto mle_corr_core (const Arr &, size_t m, mle_oracle &P)
std::tuple< size_t, bool > mle_corr_poly (const Arr &Y, const Arr &s, size_t m)
std::tuple< size_t, bool > lsq_corr_poly (const Arr &Y, const Arr &s, size_t m)
Typedef Documentation
Arr
using Arr = xt::xarray<double, xt::layout_type::row_major>
Definition at line 18 of file lsq_corr_ell.cpp.
Function Documentation
construct_distance_matrix()
Arr construct_distance_matrix (const Arr & s)
Construct a distance matrix object.
Parameters
s location of sites
Returns
std::vector<Arr>
Definition at line 88 of file lsq_corr_ell.cpp.
References n, sqrt(), and zeros().
Referenced by construct_poly_matrix().
construct_poly_matrix()
std::vector<Arr> construct_poly_matrix (const Arr & s, size_t m)
Construct distance matrix for polynomial.
Parameters
s location of sites
m degree of polynomial
Returns
std::vector<Arr>
Definition at line 112 of file lsq_corr_ell.cpp.
References construct_distance_matrix(), D, and n.
Referenced by lsq_corr_poly(), lsq_corr_poly2(), and mle_corr_poly().
create_2d_isotropic()
Arr create_2d_isotropic (const Arr & s, size_t N = 3000U)
Create a 2d isotropic object.
Parameters
s location of sites
N
Returns
Arr Biased covariance matrix
Definition at line 46 of file lsq_corr_ell.cpp.
References A, n, N, sqrt(), and zeros().
Referenced by TEST_CASE().
create_2d_sites()
Arr create_2d_sites (size_t nx = 10U, size_t ny = 8U)
Create a 2d sites object.
Parameters
nx
ny
Returns
Arr location of sites
Definition at line 27 of file lsq_corr_ell.cpp.
Referenced by TEST_CASE().
lsq_corr_core2()
auto lsq_corr_core2 (const Arr & Y, size_t m, lsq_oracle & P)
Parameters
Y
m
P
Returns
auto
Definition at line 213 of file lsq_corr_ell.cpp.
References cutting_plane_dc(), E, max(), norm(), py::range(), and zeros().
Referenced by lsq_corr_poly2().
lsq_corr_poly()
std::tuple<size_t, bool> lsq_corr_poly (const Arr & Y, const Arr & s, size_t m)
Parameters
Y
s
m
Returns
std::tuple<size_t, bool>
Definition at line 379 of file lsq_corr_ell.cpp.
References bsearch(), construct_poly_matrix(), E, P, and zeros().
lsq_corr_poly2()
std::tuple<size_t, bool> lsq_corr_poly2 (const Arr & Y, const Arr & s, size_t m)
Parameters
Y
s
m
Returns
std::tuple<size_t, bool>
Definition at line 238 of file lsq_corr_ell.cpp.
References construct_poly_matrix(), lsq_corr_core2(), lsq_oracle::lsq_oracle(), and P.
Referenced by TEST_CASE().
mle_corr_core()
auto mle_corr_core (const Arr & , size_t m, mle_oracle & P)
Parameters
Y
m
P
Returns
auto
Definition at line 343 of file lsq_corr_ell.cpp.
References cutting_plane_dc(), E, max(), and zeros().
Referenced by mle_corr_poly().
mle_corr_poly()
std::tuple<size_t, bool> mle_corr_poly (const Arr & Y, const Arr & s, size_t m)
Parameters
Y
s
m
Returns
std::tuple<size_t, bool>
Definition at line 362 of file lsq_corr_ell.cpp.
References construct_poly_matrix(), mle_corr_core(), and P.
Referenced by TEST_CASE().