EllCpp: py Namespace Reference
py Namespace Reference
Classes
class dict
struct key_iterator
class set
Functions
template<typename T , typename TIter = decltype(std::begin(std::declval<T>())), typename = decltype(std::end(std::declval<T>()))>
constexpr auto enumerate (T &&iterable)
template<typename T >
constexpr auto range (T start, T stop)
template<typename T >
constexpr auto range (T stop)
template<typename Key >
bool operator< (const Key &key, const set< Key > &m)
template<typename Key >
size_t len (const set< Key > &m)
template<typename Key >
set (std::initializer_list< Key >) -> set< Key >
Template Deduction Guide.
template<typename Key , typename T >
bool operator< (const Key &key, const dict< Key, T > &m)
template<typename Key , typename T >
size_t len (const dict< Key, T > &m)
template<typename Key , typename T >
dict (std::initializer_list< std::pair< const Key, T >>) -> dict< Key, T >
Template Deduction Guide.
template<class Sequence >
dict (const Sequence &S) -> dict< std::remove_cv_t< decltype(*std::begin(S))>, size_t >
Function Documentation
dict() [1/2]
template<typename Key , typename T > py::dict (std::initializer_list< std::pair< const Key, T >>) -> dict< Key, T >
Template Deduction Guide.
Template Parameters
Key
T
Referenced by py::dict< Node, Node >::dict(), and len().
dict() [2/2]
template<class Sequence > py::dict (const Sequence & S) -> dict< std::remove_cv_t< decltype(*std::begin(S))>, size_t >
enumerate()
template<typename T , typename TIter = decltype(std::begin(std::declval<T>())), typename = decltype(std::end(std::declval<T>()))> constexpr auto py::enumerate (T && iterable)
Template Parameters
T
decltype(std::begin(std::declval<T>()))
decltype(std::end(std::declval<T>()))
Parameters
iterable
Returns
constexpr auto
Definition at line 28 of file py2cpp.hpp.
References fun::operator*().
len() [1/2]
template<typename Key > size_t py::len (const set< Key > & m) inline
Template Parameters
Key
Parameters
m
Returns
size_t
Definition at line 221 of file py2cpp.hpp.
len() [2/2]
template<typename Key , typename T > size_t py::len (const dict< Key, T > & m) inline
Template Parameters
Key
T
Parameters
m
Returns
size_t
Definition at line 402 of file py2cpp.hpp.
References dict().
operator<() [1/2]
template<typename Key > bool py::operator< (const Key & key, const set< Key > & m) inline
Template Parameters
Key
Parameters
key
m
Returns
true
false
Definition at line 208 of file py2cpp.hpp.
References m.
operator<() [2/2]
template<typename Key , typename T > bool py::operator< (const Key & key, const dict< Key, T > & m) inline
Template Parameters
Key
T
Parameters
key
m
Returns
true
false
Definition at line 388 of file py2cpp.hpp.
References m.
range() [1/2]
template<typename T > constexpr auto py::range (T start, T stop) inline
Definition at line 82 of file py2cpp.hpp.
References n, and fun::operator*().
Referenced by lsq_corr_core2(), qmi_oracle::operator()(), lsq_oracle::operator()(), and range().
range() [2/2]
template<typename T > constexpr auto py::range (T stop) inline
Definition at line 115 of file py2cpp.hpp.
References range().
set()
template<typename Key > py::set (std::initializer_list< Key >) -> set< Key >
Template Deduction Guide.
Template Parameters
Key