EllCpp: lib/test/src/test_optscaling_boost.cpp File Reference
test_optscaling_boost.cpp File Reference
#include <algorithm>
#include <boost/graph/adjacency_list.hpp>
#include <boost/graph/graph_traits.hpp>
#include <boost/graph/properties.hpp>
#include <boost/property_map/property_map.hpp>
#include <catch2/catch.hpp>
#include <ellcpp/cutting_plane.hpp>
#include <ellcpp/ell.hpp>
#include <ellcpp/ell1d.hpp>
#include <ellcpp/oracles/optscaling_oracle.hpp>
#include <py2cpp/nx2bgl.hpp>
#include <utility>
#include <xtensor/xarray.hpp>
Namespaces
boost
Typedefs
using Arr = xt::xarray< double, xt::layout_type::row_major >
using graph_t = boost::adjacency_list< boost::vecS, boost::vecS, boost::directedS, boost::no_property, boost::property< boost::edge_id_tag_t, size_t > >
using Vertex = typename boost::graph_traits< graph_t >::vertex_descriptor
using edge_t = typename boost::graph_traits< graph_t >::edge_iterator
Enumerations
enum boost::edge_id_tag_t { boost::id_tag, boost::id_tag }
Functions
boost::BOOST_INSTALL_PROPERTY (edge, id_tag)
static xn::grAdaptor< graph_t > create_test_case1 ()
Create a test case1 object.
TEST_CASE ("Test Optimal Scaling (two varaibles, boost)", "[test_optscaling_boost]")
Typedef Documentation
Arr
using Arr = xt::xarray<double, xt::layout_type::row_major>
Definition at line 27 of file test_optscaling_boost.cpp.
edge_t
using edge_t = typename boost::graph_traits<graph_t>::edge_iterator
Definition at line 33 of file test_optscaling_boost.cpp.
graph_t
using graph_t = boost::adjacency_list<boost::vecS, boost::vecS, boost::directedS, boost::no_property, boost::property<boost::edge_id_tag_t, size_t> >
Definition at line 31 of file test_optscaling_boost.cpp.
Vertex
using Vertex = typename boost::graph_traits<graph_t>::vertex_descriptor
Definition at line 32 of file test_optscaling_boost.cpp.
Function Documentation
create_test_case1()
static xn::grAdaptor<graph_t> create_test_case1 () static
Create a test case1 object.
Returns
xn::grAdaptor<graph_t>
Definition at line 40 of file test_optscaling_boost.cpp.
References A, D, and E.
Referenced by TEST_CASE().
TEST_CASE()
TEST_CASE ("Test Optimal Scaling (two varaibles, boost)" , "" [test_optscaling_boost])
Definition at line 62 of file test_optscaling_boost.cpp.
References CHECK(), cost, cost_pa(), create_test_case1(), cutting_plane_dc(), dist, E, edge_id, elem, G, get_cost, boost::id_tag, max(), num_of_nodes, P, t, and x0.