EllCpp: lib/test/src/test_lmi_old.cpp File Reference
test_lmi_old.cpp File Reference
#include <catch2/catch.hpp>
#include <ellcpp/cutting_plane.hpp>
#include <ellcpp/ell.hpp>
#include <ellcpp/oracles/lmi_old_oracle.hpp>
#include <vector>
#include <xtensor-blas/xlinalg.hpp>
Classes
class my_oracle< Oracle >
my_oracle
Typedefs
using M_t = std::vector< Arr >
Functions
CHECK (ell_info.feasible)
Variables
const auto F1
const auto B1 = Arr {{33., -9.}, {-9., 26.}}
const auto F2
const auto B2 = Arr {{14., 9., 40.}, {9., 91., 10.}, {40., 10., 15.}}
auto P = my_oracle(F1, B1, F2, B2, Arr {1., -1., 1.})
auto E = ell(10., Arr {0., 0., 0.})
auto [_, ell_info]
Typedef Documentation
M_t
using M_t = std::vector<Arr>
Initial value:
{
    using Arr = xt::xarray<double, xt::layout_type::row_major>
Definition at line 75 of file test_lmi_old.cpp.
Function Documentation
CHECK()
CHECK (ell_info. feasible)
Variable Documentation
auto
auto[_, ell_info]
Initial value:
=
        cutting_plane_dc(P, E, std::numeric_limits<double>::max())
Definition at line 88 of file test_lmi_old.cpp.
B1
const auto B1 = Arr {{33., -9.}, {-9., 26.}}
Definition at line 80 of file test_lmi_old.cpp.
Referenced by BM_LMI_Lazy(), BM_LMI_No_Trick(), BM_LMI_old(), and TEST_CASE().
B2
const auto B2 = Arr {{14., 9., 40.}, {9., 91., 10.}, {40., 10., 15.}}
Definition at line 84 of file test_lmi_old.cpp.
Referenced by BM_LMI_Lazy(), BM_LMI_No_Trick(), BM_LMI_old(), my_oracle< Oracle >::my_oracle(), and TEST_CASE().
E
auto E = ell(10., Arr {0., 0., 0.})
Definition at line 87 of file test_lmi_old.cpp.
Referenced by BM_LMI_Lazy(), BM_LMI_No_Trick(), BM_LMI_old(), create_test_case1(), create_test_case2(), ell::ell(), ell1d::ell1d(), lsq_corr_core2(), lsq_corr_poly(), main(), mle_corr_core(), run_lowpass(), and TEST_CASE().
F1
const auto F1
Initial value:
= M_t {{{-7., -11.}, {-11., 3.}}, {{7., -18.}, {-18., 8.}},
        {{-2., -8.}, {-8., 1.}}}
Definition at line 78 of file test_lmi_old.cpp.
Referenced by BM_LMI_Lazy(), BM_LMI_No_Trick(), BM_LMI_old(), my_oracle< Oracle >::my_oracle(), and TEST_CASE().
F2
const auto F2
Initial value:
= M_t {{{-21., -11., 0.}, {-11., 10., 8.}, {0., 8., 5.}},
        {{0., 10., 16.}, {10., -10., -10.}, {16., -10., 3.}},
        {{-5., 2., -17.}, {2., -6., 8.}, {-17., 8., 6.}}}
Definition at line 81 of file test_lmi_old.cpp.
Referenced by BM_LMI_Lazy(), BM_LMI_No_Trick(), BM_LMI_old(), my_oracle< Oracle >::my_oracle(), and TEST_CASE().
P
auto P = my_oracle(F1, B1, F2, B2, Arr {1., -1., 1.})
Definition at line 86 of file test_lmi_old.cpp.
Referenced by BM_LMI_Lazy(), BM_LMI_No_Trick(), BM_LMI_old(), ellipsoid_algo(), ellipsoid_dc(), ellipsoid_dc_discrete(), lsq_corr_poly(), lsq_corr_poly2(), main(), mle_corr_poly(), gp_base< _Tp >::operator()(), profit_q_oracle::operator()(), run_lowpass(), and TEST_CASE().