EllCpp: lib/test/src/test_example1.cpp File Reference
test_example1.cpp File Reference
#include <catch2/catch.hpp>
#include <ellcpp/cutting_plane.hpp>
#include <ellcpp/ell.hpp>
#include <limits>
#include <tuple>
Typedefs
using Arr = xt::xarray< double, xt::layout_type::row_major >
using Cut = std::tuple< Arr, double >
Functions
std::tuple< Cut, double > my_oracle (const Arr &z, double t)
TEST_CASE ("Example 1", "[example1]")
Typedef Documentation
Arr
using Arr = xt::xarray<double, xt::layout_type::row_major>
Definition at line 8 of file test_example1.cpp.
Cut
using Cut = std::tuple<Arr, double>
Definition at line 9 of file test_example1.cpp.
Function Documentation
my_oracle()
std::tuple<Cut, double> my_oracle (const Arr & z, double t)
Parameters
z
t
Returns
std::tuple<Cut, double>
Definition at line 18 of file test_example1.cpp.
Referenced by TEST_CASE().
TEST_CASE()
TEST_CASE ("Example 1" , "" [example1])
Definition at line 48 of file test_example1.cpp.
References CHECK(), cutting_plane_dc(), E, my_oracle(), and P.