NetOptimCpp: lib/test/src/test_neg_cycle_boost.cpp File Reference
test_neg_cycle_boost.cpp File Reference
#include <boost/graph/adjacency_list.hpp>
#include <boost/graph/graph_traits.hpp>
#include <catch.hpp>
#include <netoptim/min_cycle_ratio.hpp>
#include <netoptim/neg_cycle.hpp>
#include <py2cpp/nx2bgl.hpp>
#include <utility>
Typedefs
using graph_t = boost::adjacency_list< boost::listS, boost::vecS, boost::directedS, boost::no_property, boost::property< boost::edge_weight_t, int, boost::property< boost::edge_index_t, int > >>
using Vertex = boost::graph_traits< graph_t >::vertex_descriptor
using Edge_it = boost::graph_traits< graph_t >::edge_iterator
Functions
static xn::grAdaptor< graph_t > create_test_case1 ()
static xn::grAdaptor< graph_t > create_test_case2 ()
static auto create_test_case_timing () -> xn::grAdaptor< graph_t >
auto do_case (xn::grAdaptor< graph_t > &G) -> bool
CHECK (hasNeg)
CHECK (!hasNeg)
Variables
auto hasNeg = do_case(G)
Typedef Documentation
Edge_it
using Edge_it = boost::graph_traits<graph_t>::edge_iterator
Definition at line 14 of file test_neg_cycle_boost.cpp.
graph_t
using graph_t = boost::adjacency_list< boost::listS, boost::vecS, boost::directedS, boost::no_property, boost::property<boost::edge_weight_t, int, boost::property<boost::edge_index_t, int> >>
Definition at line 12 of file test_neg_cycle_boost.cpp.
Vertex
using Vertex = boost::graph_traits<graph_t>::vertex_descriptor
Definition at line 13 of file test_neg_cycle_boost.cpp.
Function Documentation
CHECK() [1/2]
CHECK (hasNeg)
CHECK() [2/2]
CHECK (! hasNeg)
create_test_case1()
static xn::grAdaptor<graph_t> create_test_case1 () static
Definition at line 16 of file test_neg_cycle_boost.cpp.
Referenced by do_case().
create_test_case2()
static xn::grAdaptor<graph_t> create_test_case2 () static
Definition at line 35 of file test_neg_cycle_boost.cpp.
create_test_case_timing()
static auto create_test_case_timing () -> xn::grAdaptor<graph_t> static
Definition at line 54 of file test_neg_cycle_boost.cpp.
do_case()
auto do_case (xn::grAdaptor< graph_t > & G) -> bool
Definition at line 72 of file test_neg_cycle_boost.cpp.
References create_test_case1(), G, and TEST_CASE().
Variable Documentation
hasNeg
auto hasNeg = do_case(G)
Definition at line 92 of file test_neg_cycle_boost.cpp.
Referenced by TEST_CASE().