[global]
line-length = 1200

[MD013]
line-length = 1200
code-blocks = false

[MD024]
enabled = false

[MD030]
ul-single = 3
ul-multi = 3

[MD033]
enabled = false

[MD036]
fix = true

[MD041]
enabled = false

[MD046]
enabled = false

[MD057]
enabled = false

[MD075]
enabled = false
