CkPttnCpp: FMKWayGainMgr Class Reference
FMKWayGainMgr Class Reference
#include <FMKWayGainMgr.hpp>
Public Types
using Base = FMGainMgr< FMKWayGainCalc, FMKWayGainMgr >
using GainCalc_ = FMKWayGainCalc
using index_t = typename SimpleNetlist::index_t
Public Member Functions
FMKWayGainMgr (SimpleNetlist &H, uint8_t K)
Construct a new FMKWayGainMgr object.
auto init (gsl::span< const uint8_t > part) -> int
auto modify_key (node_t w, uint8_t part_w, const std::vector< int > &keys) -> void
(needed by base class)
auto update_move_v (const MoveInfoV &move_info_v, int gain) -> void
auto lock (index_t whichPart, node_t v) -> void
lock
auto lock_all (index_t, node_t v) -> void
lock_all
Public Member Functions inherited from FMGainMgr< FMKWayGainCalc, FMKWayGainMgr >
FMGainMgr (SimpleNetlist &H, uint8_t K)
Construct a new FMGainMgr object.
auto init (gsl::span< const uint8_t > part) -> int
auto is_empty_togo (uint8_t toPart) const -> bool
auto is_empty () const -> bool
auto select (gsl::span< const uint8_t > part) -> std::tuple< MoveInfoV, int >
auto select_togo (uint8_t toPart) -> std::tuple< index_t, int >
auto update_move (gsl::span< const uint8_t > part, const MoveInfoV &move_info_v) -> void
Private Member Functions
auto __set_key (index_t whichPart, node_t v, int key) -> void
Set the key object.
Private Attributes
robin< uint8_t > RR
Additional Inherited Members
Public Attributes inherited from FMGainMgr< FMKWayGainCalc, FMKWayGainMgr >
uint8_t K
Protected Attributes inherited from FMGainMgr< FMKWayGainCalc, FMKWayGainMgr >
dllink< node_t > waitinglist
SimpleNetlist & H
FMKWayGainCalc gainCalc
size_t pmax
std::vector< bpqueue< int > > gainbucket
Detailed Description
Definition at line 13 of file FMKWayGainMgr.hpp.
Member Typedef Documentation
Base
using FMKWayGainMgr::Base = FMGainMgr<FMKWayGainCalc, FMKWayGainMgr>
Definition at line 20 of file FMKWayGainMgr.hpp.
GainCalc_
using FMKWayGainMgr::GainCalc_ = FMKWayGainCalc
Definition at line 21 of file FMKWayGainMgr.hpp.
index_t
using FMKWayGainMgr::index_t = typename SimpleNetlist::index_t
Definition at line 22 of file FMKWayGainMgr.hpp.
Constructor & Destructor Documentation
FMKWayGainMgr()
FMKWayGainMgr::FMKWayGainMgr (SimpleNetlist & H, uint8_t K) inline
Construct a new FMKWayGainMgr object.
Parameters
H
K
Definition at line 30 of file FMKWayGainMgr.hpp.
References FMGainMgr< FMKWayGainCalc, FMKWayGainMgr >::H, and init().
Member Function Documentation
__set_key()
auto FMKWayGainMgr::__set_key (index_t whichPart, node_t v, int key) -> void inline private
Set the key object.
Parameters
whichPart
v
key
Definition at line 104 of file FMKWayGainMgr.hpp.
References FMGainMgr< FMKWayGainCalc, FMKWayGainMgr >::gainbucket, FMGainMgr< FMKWayGainCalc, FMKWayGainMgr >::gainCalc, and FMKWayGainCalc::vertex_list.
Referenced by update_move_v().
init()
int FMKWayGainMgr::init (gsl::span< const uint8_t > part) -> int
Parameters
part
part
Returns
int
Definition at line 10 of file FMKWayGainMgr.cpp.
References dllink< T >::append(), robin< T >::exclude(), FMGainMgr< FMKWayGainCalc, FMKWayGainMgr >::gainbucket, FMGainMgr< FMKWayGainCalc, FMKWayGainMgr >::gainCalc, FMGainMgr< FMKWayGainCalc, FMKWayGainMgr >::H, FMGainMgr< FMKWayGainCalc, FMKWayGainMgr >::init(), k, FMGainMgr< FMKWayGainCalc, FMKWayGainMgr >::K, lock_all(), Netlist< nodeview_t, nodemap_t >::module_fixed, Netlist< nodeview_t, nodemap_t >::modules, RR, FMKWayGainCalc::vertex_list, and FMGainMgr< FMKWayGainCalc, FMKWayGainMgr >::waitinglist.
Referenced by FMKWayGainMgr().
lock()
auto FMKWayGainMgr::lock (index_t whichPart, node_t v) -> void inline
lock
Parameters
whichPart
v
Definition at line 75 of file FMKWayGainMgr.hpp.
References FMGainMgr< FMKWayGainCalc, FMKWayGainMgr >::gainbucket, FMGainMgr< FMKWayGainCalc, FMKWayGainMgr >::gainCalc, and FMKWayGainCalc::vertex_list.
Referenced by lock_all().
lock_all()
auto FMKWayGainMgr::lock_all (index_t , node_t v) -> void inline
lock_all
Parameters
fromPart
v
Definition at line 88 of file FMKWayGainMgr.hpp.
References k, FMGainMgr< FMKWayGainCalc, FMKWayGainMgr >::K, and lock().
Referenced by init().
modify_key()
auto FMKWayGainMgr::modify_key (node_t w, uint8_t part_w, const std::vector< int > & keys) -> void inline
(needed by base class)
Parameters
part
w
keys
Definition at line 50 of file FMKWayGainMgr.hpp.
References robin< T >::exclude(), FMGainMgr< FMKWayGainCalc, FMKWayGainMgr >::gainbucket, FMGainMgr< FMKWayGainCalc, FMKWayGainMgr >::gainCalc, k, update_move_v(), and FMKWayGainCalc::vertex_list.
update_move_v()
void FMKWayGainMgr::update_move_v (const MoveInfoV & move_info_v, int gain) -> void
Parameters
part
move_info_v
gain
Definition at line 44 of file FMKWayGainMgr.cpp.
References __set_key(), FMGainMgr< FMKWayGainCalc, FMKWayGainMgr >::gainbucket, FMGainMgr< FMKWayGainCalc, FMKWayGainMgr >::gainCalc, k, FMGainMgr< FMKWayGainCalc, FMKWayGainMgr >::K, and FMKWayGainCalc::vertex_list.
Referenced by modify_key().
Member Data Documentation
RR
robin<uint8_t> FMKWayGainMgr::RR private
Definition at line 17 of file FMKWayGainMgr.hpp.
Referenced by init().
The documentation for this class was generated from the following files:
lib/include/ckpttncpp/FMKWayGainMgr.hpp
lib/src/FMKWayGainMgr.cpp