CkPttnCpp: iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT > Class Template Reference
iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT > Class Template Reference
#include <chain.hpp>
Public Types
using iterator_category = std::input_iterator_tag
using value_type = iterator_traits_deref< iterator_deref< ContainerT > >
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
Public Member Functions
Iterator (IteratorWrapper< ContainerT > &&top_iter, IteratorWrapper< ContainerT > &&top_end)
Iterator & operator++ ()
Iterator operator++ (int)
template<typename T >
bool operator!= (const Iterator< T > &other) const
template<typename T >
bool operator== (const Iterator< T > &other) const
iterator_deref< iterator_deref< ContainerT > > operator* ()
iterator_arrow< iterator_deref< ContainerT > > operator-> ()
Private Types
using SubContainer = iterator_deref< ContainerT >
using SubIter = IteratorWrapper< SubContainer >
Private Member Functions
void advance_while_empty_sub_iterable ()
void update_sub_iterable ()
void next_sub_iterable ()
Private Attributes
IteratorWrapper< ContainerT > top_level_iter_
IteratorWrapper< ContainerT > top_level_end_
DerefHolder< SubContainer > sub_iterable_
std::optional< SubIter > sub_iter_p_
std::optional< SubIter > sub_end_p_
Friends
template<typename >
class Iterator
Detailed Description
template<typename Container>
template<typename ContainerT>
class iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >
Definition at line 194 of file chain.hpp.
Member Typedef Documentation
difference_type
template<typename Container > template<typename ContainerT> using iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::difference_type = std::ptrdiff_t
Definition at line 234 of file chain.hpp.
iterator_category
template<typename Container > template<typename ContainerT> using iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::iterator_category = std::input_iterator_tag
Definition at line 232 of file chain.hpp.
pointer
template<typename Container > template<typename ContainerT> using iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::pointer = value_type*
Definition at line 235 of file chain.hpp.
reference
template<typename Container > template<typename ContainerT> using iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::reference = value_type&
Definition at line 236 of file chain.hpp.
SubContainer
template<typename Container > template<typename ContainerT> using iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::SubContainer = iterator_deref<ContainerT> private
Definition at line 198 of file chain.hpp.
SubIter
template<typename Container > template<typename ContainerT> using iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::SubIter = IteratorWrapper<SubContainer> private
Definition at line 199 of file chain.hpp.
value_type
template<typename Container > template<typename ContainerT> using iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::value_type = iterator_traits_deref<iterator_deref<ContainerT> >
Definition at line 233 of file chain.hpp.
Constructor & Destructor Documentation
Iterator()
template<typename Container > template<typename ContainerT> iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::Iterator (IteratorWrapper< ContainerT > && top_iter, IteratorWrapper< ContainerT > && top_end) inline
Definition at line 238 of file chain.hpp.
Member Function Documentation
advance_while_empty_sub_iterable()
template<typename Container > template<typename ContainerT> void iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::advance_while_empty_sub_iterable () inline private
Definition at line 207 of file chain.hpp.
next_sub_iterable()
template<typename Container > template<typename ContainerT> void iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::next_sub_iterable () inline private
Definition at line 226 of file chain.hpp.
operator!=()
template<typename Container > template<typename ContainerT> template<typename T > bool iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::operator!= (const Iterator< T > & other) const inline
Definition at line 261 of file chain.hpp.
References iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::sub_iter_p_, and iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::top_level_iter_.
operator*()
template<typename Container > template<typename ContainerT> iterator_deref<iterator_deref<ContainerT> > iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::operator* () inline
Definition at line 271 of file chain.hpp.
operator++() [1/2]
template<typename Container > template<typename ContainerT> Iterator& iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::operator++ () inline
Definition at line 245 of file chain.hpp.
operator++() [2/2]
template<typename Container > template<typename ContainerT> Iterator iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::operator++ (int) inline
Definition at line 254 of file chain.hpp.
operator->()
template<typename Container > template<typename ContainerT> iterator_arrow<iterator_deref<ContainerT> > iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::operator-> () inline
Definition at line 275 of file chain.hpp.
References iter::impl::apply_arrow().
operator==()
template<typename Container > template<typename ContainerT> template<typename T > bool iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::operator== (const Iterator< T > & other) const inline
Definition at line 267 of file chain.hpp.
update_sub_iterable()
template<typename Container > template<typename ContainerT> void iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::update_sub_iterable () inline private
Definition at line 214 of file chain.hpp.
References iter::impl::DerefHolder< T >::get(), iter::impl::get_iters::get_begin(), iter::impl::get_iters::get_end(), and iter::impl::DerefHolder< T >::reset().
Friends And Related Function Documentation
Iterator
template<typename Container > template<typename ContainerT> template<typename > friend class Iterator friend
Definition at line 197 of file chain.hpp.
Member Data Documentation
sub_end_p_
template<typename Container > template<typename ContainerT> std::optional<SubIter> iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::sub_end_p_ private
Definition at line 205 of file chain.hpp.
sub_iter_p_
template<typename Container > template<typename ContainerT> std::optional<SubIter> iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::sub_iter_p_ private
Definition at line 204 of file chain.hpp.
Referenced by iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::operator!=().
sub_iterable_
template<typename Container > template<typename ContainerT> DerefHolder<SubContainer> iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::sub_iterable_ private
Definition at line 203 of file chain.hpp.
top_level_end_
template<typename Container > template<typename ContainerT> IteratorWrapper<ContainerT> iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::top_level_end_ private
Definition at line 202 of file chain.hpp.
top_level_iter_
template<typename Container > template<typename ContainerT> IteratorWrapper<ContainerT> iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::top_level_iter_ private
Definition at line 201 of file chain.hpp.
Referenced by iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::operator!=().
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/chain.hpp