CkPttnCpp: PartMgrBase< GainMgr, ConstrMgr, Derived > Class Template Reference
PartMgrBase< GainMgr, ConstrMgr, Derived > Class Template Reference
Partition Manager Base.
#include <PartMgrBase.hpp>
Public Types
using GainCalc_ = typename GainMgr::GainCalc_
using GainMgr_ = GainMgr
using ConstrMgr_ = ConstrMgr
using Der = Derived< GainMgr, ConstrMgr >
Public Member Functions
PartMgrBase (SimpleNetlist &H, GainMgr &gainMgr, ConstrMgr &constrMgr)
Construct a new FDPartMgr object.
void init (std::vector< uint8_t > &part)
size_t legalize (std::vector< uint8_t > &part)
void optimize (std::vector< uint8_t > &part)
Public Attributes
Der & self = *static_cast<Der*>(this)
int totalcost {0}
Protected Attributes
SimpleNetlist & H
GainMgr & gainMgr
ConstrMgr & validator
uint8_t K
Private Member Functions
void __optimize_1pass (std::vector< uint8_t > &part)
Detailed Description
template<typename GainMgr, typename ConstrMgr, template< typename _GainMgr, typename _ConstrMgr > class Derived>
class PartMgrBase< GainMgr, ConstrMgr, Derived >
Partition Manager Base.
Template Parameters
GainMgr
ConstrMgr
Derived Iterative Improvement Partitioning Base Class. In this partitioning method, the next solution $s'$ considered after solution $s$ is dervied by first applying a sequence of $t$ changes (moves) to $s$ (with $t$ dependent from $s$ and from the specific heuristic method), thus obtaining a sequence of solution $s,...,s_t$ and by successively choosing the best among these solutions.
In order to do that, heuristics refer to a measure of the gain (and balance condition) associated to any sequence of changes performed on the current solution. Moreover, the length of the sequence generated is determined by evaluting a suitably defined $stopping rule$ at each iteration.
Reference: G. Ausiello et al., Complexity and Approximation: Combinatorial Optimization Problems and Their Approximability Properties, Section 10.3.2.
Definition at line 41 of file PartMgrBase.hpp.
Member Typedef Documentation
ConstrMgr_
template<typename GainMgr, typename ConstrMgr, template< typename _GainMgr, typename _ConstrMgr > class Derived> using PartMgrBase< GainMgr, ConstrMgr, Derived >::ConstrMgr_ = ConstrMgr
Definition at line 47 of file PartMgrBase.hpp.
Der
template<typename GainMgr, typename ConstrMgr, template< typename _GainMgr, typename _ConstrMgr > class Derived> using PartMgrBase< GainMgr, ConstrMgr, Derived >::Der = Derived<GainMgr, ConstrMgr>
Definition at line 49 of file PartMgrBase.hpp.
GainCalc_
template<typename GainMgr, typename ConstrMgr, template< typename _GainMgr, typename _ConstrMgr > class Derived> using PartMgrBase< GainMgr, ConstrMgr, Derived >::GainCalc_ = typename GainMgr::GainCalc_
Definition at line 45 of file PartMgrBase.hpp.
GainMgr_
template<typename GainMgr, typename ConstrMgr, template< typename _GainMgr, typename _ConstrMgr > class Derived> using PartMgrBase< GainMgr, ConstrMgr, Derived >::GainMgr_ = GainMgr
Definition at line 46 of file PartMgrBase.hpp.
Constructor & Destructor Documentation
PartMgrBase()
template<typename GainMgr, typename ConstrMgr, template< typename _GainMgr, typename _ConstrMgr > class Derived> PartMgrBase< GainMgr, ConstrMgr, Derived >::PartMgrBase (SimpleNetlist & H, GainMgr & gainMgr, ConstrMgr & constrMgr) inline
Construct a new FDPartMgr object.
Parameters
H
gainMgr
constrMgr
Definition at line 70 of file PartMgrBase.hpp.
Member Function Documentation
__optimize_1pass()
template<typename GainMgr , typename ConstrMgr , template< typename _GainMgr, typename _ConstrMgr > class Derived> auto PartMgrBase< GainMgr, ConstrMgr, Derived >::__optimize_1pass (std::vector< uint8_t > & part) private
Parameters
part
Template Parameters
GainMgr
ConstrMgr
Parameters
part
Definition at line 75 of file PartMgrBase.cpp.
Referenced by PartMgrBase< GainMgr, ConstrMgr, FMPartMgr >::PartMgrBase().
init()
template<typename GainMgr , typename ConstrMgr , template< typename _GainMgr, typename _ConstrMgr > class Derived> auto PartMgrBase< GainMgr, ConstrMgr, Derived >::init (std::vector< uint8_t > & part)
Parameters
part
Template Parameters
GainMgr
ConstrMgr
Parameters
part
Definition at line 12 of file PartMgrBase.cpp.
Referenced by PartMgrBase< GainMgr, ConstrMgr, FMPartMgr >::PartMgrBase().
legalize()
template<typename GainMgr , typename ConstrMgr , template< typename _GainMgr, typename _ConstrMgr > class Derived> auto PartMgrBase< GainMgr, ConstrMgr, Derived >::legalize (std::vector< uint8_t > & part)
Parameters
part
Definition at line 19 of file PartMgrBase.cpp.
Referenced by PartMgrBase< GainMgr, ConstrMgr, FMPartMgr >::PartMgrBase().
optimize()
template<typename GainMgr , typename ConstrMgr , template< typename _GainMgr, typename _ConstrMgr > class Derived> auto PartMgrBase< GainMgr, ConstrMgr, Derived >::optimize (std::vector< uint8_t > & part)
Parameters
part
Template Parameters
GainMgr
ConstrMgr
Parameters
part
Definition at line 136 of file PartMgrBase.cpp.
Referenced by PartMgrBase< GainMgr, ConstrMgr, FMPartMgr >::PartMgrBase().
Member Data Documentation
gainMgr
template<typename GainMgr, typename ConstrMgr, template< typename _GainMgr, typename _ConstrMgr > class Derived> GainMgr& PartMgrBase< GainMgr, ConstrMgr, Derived >::gainMgr protected
Definition at line 54 of file PartMgrBase.hpp.
H
template<typename GainMgr, typename ConstrMgr, template< typename _GainMgr, typename _ConstrMgr > class Derived> SimpleNetlist& PartMgrBase< GainMgr, ConstrMgr, Derived >::H protected
Definition at line 53 of file PartMgrBase.hpp.
K
template<typename GainMgr, typename ConstrMgr, template< typename _GainMgr, typename _ConstrMgr > class Derived> uint8_t PartMgrBase< GainMgr, ConstrMgr, Derived >::K protected
Definition at line 56 of file PartMgrBase.hpp.
self
template<typename GainMgr, typename ConstrMgr, template< typename _GainMgr, typename _ConstrMgr > class Derived> Der& PartMgrBase< GainMgr, ConstrMgr, Derived >::self = *static_cast<Der*>(this)
Definition at line 50 of file PartMgrBase.hpp.
totalcost
template<typename GainMgr, typename ConstrMgr, template< typename _GainMgr, typename _ConstrMgr > class Derived> int PartMgrBase< GainMgr, ConstrMgr, Derived >::totalcost {0}
Definition at line 61 of file PartMgrBase.hpp.
Referenced by TEST_CASE().
validator
template<typename GainMgr, typename ConstrMgr, template< typename _GainMgr, typename _ConstrMgr > class Derived> ConstrMgr& PartMgrBase< GainMgr, ConstrMgr, Derived >::validator protected
Definition at line 55 of file PartMgrBase.hpp.
The documentation for this class was generated from the following files:
lib/include/ckpttncpp/PartMgrBase.hpp
lib/src/PartMgrBase.cpp