CkPttnCpp: FMKWayGainCalc Class Reference
FMKWayGainCalc Class Reference
FMKWayGainCalc.
#include <FMKWayGainCalc.hpp>
Public Types
using ret_2pin_info = std::tuple< index_t, std::vector< int > >
using ret_info = std::tuple< std::vector< node_t >, std::vector< std::vector< int > >>
Public Member Functions
FMKWayGainCalc (SimpleNetlist &H, uint8_t K)
Construct a new FMKWayGainCalc object.
auto start_ptr (uint8_t toPart) -> dllink< node_t > *
auto init (gsl::span< const uint8_t > part) -> int
auto update_move_init () -> void
auto update_move_2pin_net (gsl::span< const uint8_t > part, const MoveInfo &move_info) -> ret_2pin_info
auto update_move_3pin_net (gsl::span< const uint8_t > part, const MoveInfo &move_info) -> ret_info
auto update_move_general_net (gsl::span< const uint8_t > part, const MoveInfo &move_info) -> ret_info
Public Attributes
int totalcost {0}
Private Types
using index_t = typename SimpleNetlist::index_t
Private Member Functions
auto __modify_gain (node_t v, uint8_t part_v, int weight) -> void
auto __init_gain (node_t net, gsl::span< const uint8_t > part) -> void
auto __init_gain_2pin_net (node_t net, gsl::span< const uint8_t > part) -> void
auto __init_gain_3pin_net (node_t net, gsl::span< const uint8_t > part) -> void
auto __init_gain_general_net (node_t net, gsl::span< const uint8_t > part) -> void
Private Attributes
SimpleNetlist & H
uint8_t K
robin< uint8_t > RR
size_t num_modules
std::vector< std::vector< dllink< node_t > > > vertex_list
std::vector< int > deltaGainV
Friends
class FMKWayGainMgr
Detailed Description
FMKWayGainCalc.
Definition at line 14 of file FMKWayGainCalc.hpp.
Member Typedef Documentation
index_t
using FMKWayGainCalc::index_t = typename SimpleNetlist::index_t private
Definition at line 17 of file FMKWayGainCalc.hpp.
ret_2pin_info
using FMKWayGainCalc::ret_2pin_info = std::tuple<index_t, std::vector<int> >
Definition at line 92 of file FMKWayGainCalc.hpp.
ret_info
using FMKWayGainCalc::ret_info = std::tuple<std::vector<node_t>, std::vector<std::vector<int> >>
Definition at line 105 of file FMKWayGainCalc.hpp.
Constructor & Destructor Documentation
FMKWayGainCalc()
FMKWayGainCalc::FMKWayGainCalc (SimpleNetlist & H, uint8_t K) inline
Construct a new FMKWayGainCalc object.
Parameters
H Netlist
K number of partitions
Definition at line 36 of file FMKWayGainCalc.hpp.
References deltaGainV, k, K, and Netlist< nodeview_t, nodemap_t >::number_of_modules().
Member Function Documentation
__init_gain()
void FMKWayGainCalc::__init_gain (node_t net, gsl::span< const uint8_t > part) -> void private
Parameters
net
part
net
part
vertex_list
Definition at line 10 of file FMKWayGainCalc.cpp.
References __init_gain_2pin_net(), __init_gain_3pin_net(), __init_gain_general_net(), xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::degree(), Netlist< nodeview_t, nodemap_t >::G, and H.
Referenced by __modify_gain(), and init().
__init_gain_2pin_net()
void FMKWayGainCalc::__init_gain_2pin_net (node_t net, gsl::span< const uint8_t > part) -> void private
Parameters
net
part
Definition at line 36 of file FMKWayGainCalc.cpp.
References __modify_gain(), xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::begin(), Netlist< nodeview_t, nodemap_t >::G, Netlist< nodeview_t, nodemap_t >::get_net_weight(), H, totalcost, and vertex_list.
Referenced by __init_gain(), and __modify_gain().
__init_gain_3pin_net()
void FMKWayGainCalc::__init_gain_3pin_net (node_t net, gsl::span< const uint8_t > part) -> void private
Parameters
net
part
Definition at line 64 of file FMKWayGainCalc.cpp.
References __modify_gain(), b, xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::begin(), Netlist< nodeview_t, nodemap_t >::G, Netlist< nodeview_t, nodemap_t >::get_net_weight(), H, totalcost, and vertex_list.
Referenced by __init_gain(), and __modify_gain().
__init_gain_general_net()
void FMKWayGainCalc::__init_gain_general_net (node_t net, gsl::span< const uint8_t > part) -> void private
Parameters
net
part
Definition at line 127 of file FMKWayGainCalc.cpp.
References __modify_gain(), Netlist< nodeview_t, nodemap_t >::G, Netlist< nodeview_t, nodemap_t >::get_net_weight(), H, k, K, totalcost, and vertex_list.
Referenced by __init_gain(), and __modify_gain().
__modify_gain()
auto FMKWayGainCalc::__modify_gain (node_t v, uint8_t part_v, int weight) -> void inline private
Parameters
v
weight
Definition at line 134 of file FMKWayGainCalc.hpp.
References __init_gain(), __init_gain_2pin_net(), __init_gain_3pin_net(), __init_gain_general_net(), robin< T >::exclude(), and k.
Referenced by __init_gain_2pin_net(), __init_gain_3pin_net(), and __init_gain_general_net().
init()
auto FMKWayGainCalc::init (gsl::span< const uint8_t > part) -> int inline
Parameters
part
Definition at line 66 of file FMKWayGainCalc.hpp.
References __init_gain(), k, K, Netlist< nodeview_t, nodemap_t >::nets, and totalcost.
start_ptr()
auto FMKWayGainCalc::start_ptr (uint8_t toPart) -> dllink<node_t>* inline
Parameters
toPart
Returns
dllink*
Definition at line 56 of file FMKWayGainCalc.hpp.
update_move_2pin_net()
FMKWayGainCalc::ret_2pin_info FMKWayGainCalc::update_move_2pin_net (gsl::span< const uint8_t > part, const MoveInfo & move_info) -> ret_2pin_info
Parameters
part
move_info
Returns
ret_2pin_info
Definition at line 177 of file FMKWayGainCalc.cpp.
References xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::begin(), deltaGainV, Netlist< nodeview_t, nodemap_t >::G, Netlist< nodeview_t, nodemap_t >::get_net_weight(), H, k, and K.
update_move_3pin_net()
FMKWayGainCalc::ret_info FMKWayGainCalc::update_move_3pin_net (gsl::span< const uint8_t > part, const MoveInfo & move_info) -> ret_info
Parameters
part
move_info
Returns
ret_info
Definition at line 210 of file FMKWayGainCalc.cpp.
References deltaGainV, Netlist< nodeview_t, nodemap_t >::G, Netlist< nodeview_t, nodemap_t >::get_net_weight(), H, k, and K.
update_move_general_net()
FMKWayGainCalc::ret_info FMKWayGainCalc::update_move_general_net (gsl::span< const uint8_t > part, const MoveInfo & move_info) -> ret_info
Parameters
part
move_info
Returns
ret_info
Definition at line 296 of file FMKWayGainCalc.cpp.
References deltaGainV, Netlist< nodeview_t, nodemap_t >::G, Netlist< nodeview_t, nodemap_t >::get_net_weight(), H, k, and K.
update_move_init()
auto FMKWayGainCalc::update_move_init () -> void inline
Definition at line 87 of file FMKWayGainCalc.hpp.
References K.
Friends And Related Function Documentation
FMKWayGainMgr
friend class FMKWayGainMgr friend
Definition at line 16 of file FMKWayGainCalc.hpp.
Member Data Documentation
deltaGainV
std::vector<int> FMKWayGainCalc::deltaGainV private
Definition at line 25 of file FMKWayGainCalc.hpp.
Referenced by FMKWayGainCalc(), update_move_2pin_net(), update_move_3pin_net(), and update_move_general_net().
H
SimpleNetlist& FMKWayGainCalc::H private
Definition at line 20 of file FMKWayGainCalc.hpp.
Referenced by __init_gain(), __init_gain_2pin_net(), __init_gain_3pin_net(), __init_gain_general_net(), update_move_2pin_net(), update_move_3pin_net(), and update_move_general_net().
K
uint8_t FMKWayGainCalc::K private
Definition at line 21 of file FMKWayGainCalc.hpp.
Referenced by __init_gain_general_net(), FMKWayGainCalc(), init(), update_move_2pin_net(), update_move_3pin_net(), update_move_general_net(), and update_move_init().
num_modules
size_t FMKWayGainCalc::num_modules private
Definition at line 23 of file FMKWayGainCalc.hpp.
RR
robin<uint8_t> FMKWayGainCalc::RR private
Definition at line 22 of file FMKWayGainCalc.hpp.
totalcost
int FMKWayGainCalc::totalcost {0}
Definition at line 28 of file FMKWayGainCalc.hpp.
Referenced by __init_gain_2pin_net(), __init_gain_3pin_net(), __init_gain_general_net(), and init().
vertex_list
std::vector<std::vector<dllink<node_t> > > FMKWayGainCalc::vertex_list private
Definition at line 24 of file FMKWayGainCalc.hpp.
Referenced by __init_gain_2pin_net(), __init_gain_3pin_net(), __init_gain_general_net(), FMKWayGainMgr::__set_key(), FMKWayGainMgr::init(), FMKWayGainMgr::lock(), FMKWayGainMgr::modify_key(), and FMKWayGainMgr::update_move_v().
The documentation for this class was generated from the following files:
lib/include/ckpttncpp/FMKWayGainCalc.hpp
lib/src/FMKWayGainCalc.cpp