CkPttnCpp: iter::impl::Chained< TupType, Is > Class Template Reference
iter::impl::Chained< TupType, Is > Class Template Reference
#include <chain.hpp>
Classes
class Iterator
class IteratorData
Public Member Functions
Chained (Chained &&)=default
Iterator< TupType > begin ()
Iterator< TupType > end ()
Iterator< AsConst< TupType > > begin () const
Iterator< AsConst< TupType > > end () const
Private Member Functions
Chained (TupType &&t)
Private Attributes
friend ChainMaker
TupType tup_
Detailed Description
template<typename TupType, std::size_t... Is>
class iter::impl::Chained< TupType, Is >
Definition at line 18 of file chain.hpp.
Constructor & Destructor Documentation
Chained() [1/2]
template<typename TupType , std::size_t... Is> iter::impl::Chained< TupType, Is >::Chained (TupType && t) inline private
Definition at line 96 of file chain.hpp.
Chained() [2/2]
template<typename TupType , std::size_t... Is> iter::impl::Chained< TupType, Is >::Chained (Chained< TupType, Is > &&) default
Member Function Documentation
begin() [1/2]
template<typename TupType , std::size_t... Is> Iterator<TupType> iter::impl::Chained< TupType, Is >::begin () inline
Definition at line 162 of file chain.hpp.
References iter::impl::get_iters::get_begin(), and iter::impl::get_iters::get_end().
begin() [2/2]
template<typename TupType , std::size_t... Is> Iterator<AsConst<TupType> > iter::impl::Chained< TupType, Is >::begin () const inline
Definition at line 172 of file chain.hpp.
References iter::impl::get_iters::get_begin(), and iter::impl::get_iters::get_end().
end() [1/2]
template<typename TupType , std::size_t... Is> Iterator<TupType> iter::impl::Chained< TupType, Is >::end () inline
Definition at line 167 of file chain.hpp.
References iter::impl::get_iters::get_end().
end() [2/2]
template<typename TupType , std::size_t... Is> Iterator<AsConst<TupType> > iter::impl::Chained< TupType, Is >::end () const inline
Definition at line 177 of file chain.hpp.
References iter::impl::get_iters::get_end().
Member Data Documentation
ChainMaker
template<typename TupType , std::size_t... Is> friend iter::impl::Chained< TupType, Is >::ChainMaker private
Definition at line 34 of file chain.hpp.
tup_
template<typename TupType , std::size_t... Is> TupType iter::impl::Chained< TupType, Is >::tup_ private
Definition at line 97 of file chain.hpp.
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/chain.hpp