CkPttnCpp: iter::impl::Enumerable< Container, Index > Class Template Reference
iter::impl::Enumerable< Container, Index > Class Template Reference
#include <enumerate.hpp>
Classes
class Iterator
Public Types
template<typename T >
using IterYield = EnumIterYield< Index, iterator_deref< T > >
Public Member Functions
Enumerable (Enumerable &&)=default
Iterator< Container > begin ()
Iterator< Container > end ()
Iterator< AsConst< Container > > begin () const
Iterator< AsConst< Container > > end () const
Private Member Functions
Enumerable (Container &&container, Index start)
Private Attributes
Container container_
const Index start_
friend EnumerateFn
Detailed Description
template<typename Container, typename Index>
class iter::impl::Enumerable< Container, Index >
Definition at line 32 of file enumerate.hpp.
Member Typedef Documentation
IterYield
template<typename Container , typename Index > template<typename T > using iter::impl::Enumerable< Container, Index >::IterYield = EnumIterYield<Index, iterator_deref<T> >
Definition at line 65 of file enumerate.hpp.
Constructor & Destructor Documentation
Enumerable() [1/2]
template<typename Container , typename Index > iter::impl::Enumerable< Container, Index >::Enumerable (Container && container, Index start) inline private
Definition at line 58 of file enumerate.hpp.
Enumerable() [2/2]
template<typename Container , typename Index > iter::impl::Enumerable< Container, Index >::Enumerable (Enumerable< Container, Index > &&) default
Member Function Documentation
begin() [1/2]
template<typename Container , typename Index > Iterator<Container> iter::impl::Enumerable< Container, Index >::begin () inline
Definition at line 119 of file enumerate.hpp.
References iter::impl::get_iters::get_begin().
begin() [2/2]
template<typename Container , typename Index > Iterator<AsConst<Container> > iter::impl::Enumerable< Container, Index >::begin () const inline
Definition at line 127 of file enumerate.hpp.
References iter::impl::get_iters::get_begin().
end() [1/2]
template<typename Container , typename Index > Iterator<Container> iter::impl::Enumerable< Container, Index >::end () inline
Definition at line 123 of file enumerate.hpp.
References iter::impl::get_iters::get_end().
end() [2/2]
template<typename Container , typename Index > Iterator<AsConst<Container> > iter::impl::Enumerable< Container, Index >::end () const inline
Definition at line 131 of file enumerate.hpp.
References iter::impl::get_iters::get_end().
Member Data Documentation
container_
template<typename Container , typename Index > Container iter::impl::Enumerable< Container, Index >::container_ private
Definition at line 52 of file enumerate.hpp.
EnumerateFn
template<typename Container , typename Index > friend iter::impl::Enumerable< Container, Index >::EnumerateFn private
Definition at line 55 of file enumerate.hpp.
start_
template<typename Container , typename Index > const Index iter::impl::Enumerable< Container, Index >::start_ private
Definition at line 53 of file enumerate.hpp.
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/enumerate.hpp