CkPttnCpp: bpqueue< T > Class Template Reference
bpqueue< T > Class Template Reference
bounded priority queue
#include <bpqueue.hpp>
Public Types
using coro_t = boost::coroutines2::coroutine< dllink< T > & >
iterator point to begin
using pull_t = typename coro_t::pull_type
Public Member Functions
bpqueue (T a, T b)
Construct a new bpqueue object.
auto set_key (dllink< T > &it, T gain) -> void
Set the key object.
auto get_max () const -> T
Get the max value.
auto is_empty () const -> bool
whether empty
auto clear () -> void
clear reset the PQ
auto append_direct (dllink< T > &it) -> void
append item with internal key
auto append (dllink< T > &it, T k) -> void
append item with external key
auto appendfrom (std::vector< dllink< T >> &nodes) -> void
append from list
auto popleft () -> dllink< T > &
pop node with the highest key
auto decrease_key (dllink< T > &it, T delta) -> void
decrease key by delta
auto increase_key (dllink< T > &it, T delta) -> void
increase key by delta
auto modify_key (dllink< T > &it, T delta) -> void
modify key by delta
auto detach (dllink< T > &it) -> void
detach the item from bpqueue
auto items () -> pull_t
item generator
Private Attributes
T max {0}
T offset
T high
std::vector< dllink< T > > bucket
Static Private Attributes
static dllink< T > sentinel {}
sentinel
Detailed Description
template<typename T>
class bpqueue< T >
bounded priority queue
Bounded Priority Queue with integer keys in [a..b]. Implemented by array (bucket) of doubly-linked lists. Efficient if key is bounded by a small integer value.
Note that this class does not own the PQ nodes. This feature makes the nodes sharable between doubly linked list class and this class. In the FM algorithm, the node either attached to the gain buckets (PQ) or in the waitinglist (doubly linked list), but not in both of them in the same time.
Another improvement is to make the array size one element bigger i.e. (b - a + 2). The extra dummy array element (which is called sentinel) is used to reduce the boundary checking during updating.
All the member functions assume that the keys are within the bound.
Definition at line 28 of file bpqueue.hpp.
Member Typedef Documentation
coro_t
template<typename T> using bpqueue< T >::coro_t = boost::coroutines2::coroutine<dllink<T>&>
iterator point to begin
Returns
bpq_iterator
iterator point to end
Returns
bpq_iterator
Definition at line 268 of file bpqueue.hpp.
pull_t
template<typename T> using bpqueue< T >::pull_t = typename coro_t::pull_type
Definition at line 269 of file bpqueue.hpp.
Constructor & Destructor Documentation
bpqueue()
template<typename T> bpqueue< T >::bpqueue (T a, T b) inline
Construct a new bpqueue object.
Parameters
a lower bound
b upper bound
Definition at line 45 of file bpqueue.hpp.
Member Function Documentation
append()
template<typename T> auto bpqueue< T >::append (dllink< T > & it, T k) -> void inline
append item with external key
Parameters
it the item
k the key
Definition at line 116 of file bpqueue.hpp.
Referenced by bpqueue< int >::append_direct().
append_direct()
template<typename T> auto bpqueue< T >::append_direct (dllink< T > & it) -> void inline
append item with internal key
Parameters
it the item
Definition at line 104 of file bpqueue.hpp.
appendfrom()
template<typename T> auto bpqueue< T >::appendfrom (std::vector< dllink< T >> & nodes) -> void inline
append from list
Parameters
nodes
keys
Definition at line 133 of file bpqueue.hpp.
clear()
template<typename T> auto bpqueue< T >::clear () -> void inline
clear reset the PQ
Definition at line 90 of file bpqueue.hpp.
decrease_key()
template<typename T> auto bpqueue< T >::decrease_key (dllink< T > & it, T delta) -> void inline
decrease key by delta
Parameters
it the item
delta the change of the key
Note that the order of items with same key will not be preserved. For FM algorithm, this is a prefered behavior.
Definition at line 172 of file bpqueue.hpp.
Referenced by bpqueue< int >::modify_key().
detach()
template<typename T> auto bpqueue< T >::detach (dllink< T > & it) -> void inline
detach the item from bpqueue
Parameters
it the item
Definition at line 244 of file bpqueue.hpp.
get_max()
template<typename T> auto bpqueue< T >::get_max () const -> T inline
Get the max value.
Returns
T maximum value
Definition at line 71 of file bpqueue.hpp.
increase_key()
template<typename T> auto bpqueue< T >::increase_key (dllink< T > & it, T delta) -> void inline
increase key by delta
Parameters
it the item
delta the change of the key
Note that the order of items with same key will not be preserved. For FM algorithm, this is a prefered behavior.
Definition at line 200 of file bpqueue.hpp.
Referenced by bpqueue< int >::modify_key().
is_empty()
template<typename T> auto bpqueue< T >::is_empty () const -> bool inline
whether empty
Returns
true
false
Definition at line 82 of file bpqueue.hpp.
Referenced by bpqueue< int >::appendfrom(), bpqueue< int >::decrease_key(), bpqueue< int >::detach(), and bpqueue< int >::popleft().
items()
template<typename T> auto bpqueue< T >::items () -> pull_t inline
item generator
Returns
pull_t
Definition at line 276 of file bpqueue.hpp.
Referenced by bpqueue< int >::items().
modify_key()
template<typename T> auto bpqueue< T >::modify_key (dllink< T > & it, T delta) -> void inline
modify key by delta
Parameters
it the item
delta the change of the key
Note that the order of items with same key will not be preserved. For FM algorithm, this is a prefered behavior.
Definition at line 223 of file bpqueue.hpp.
popleft()
template<typename T> auto bpqueue< T >::popleft () -> dllink<T>& inline
pop node with the highest key
Returns
dllink&
Definition at line 153 of file bpqueue.hpp.
set_key()
template<typename T> auto bpqueue< T >::set_key (dllink< T > & it, T gain) -> void inline
Set the key object.
Parameters
it the item
gain the key of it
Definition at line 61 of file bpqueue.hpp.
Member Data Documentation
bucket
template<typename T> std::vector<dllink<T> > bpqueue< T >::bucket private
bucket, array of lists
Definition at line 36 of file bpqueue.hpp.
Referenced by bpqueue< int >::bpqueue().
high
template<typename T> T bpqueue< T >::high private
b - a + 1
Definition at line 35 of file bpqueue.hpp.
Referenced by bpqueue< int >::appendfrom().
max
template<typename T> T bpqueue< T >::max {0} private
max value
Definition at line 33 of file bpqueue.hpp.
Referenced by bpqueue< int >::append(), bpqueue< int >::appendfrom(), bpqueue< int >::clear(), bpqueue< int >::decrease_key(), bpqueue< int >::detach(), bpqueue< int >::get_max(), bpqueue< int >::increase_key(), bpqueue< int >::is_empty(), bpqueue< int >::items(), and bpqueue< int >::popleft().
offset
template<typename T> T bpqueue< T >::offset private
a - 1
Definition at line 34 of file bpqueue.hpp.
Referenced by bpqueue< int >::append(), bpqueue< int >::appendfrom(), bpqueue< int >::get_max(), and bpqueue< int >::set_key().
sentinel
template<typename T> dllink< T > bpqueue< T >::sentinel {} inline static private
sentinel
sentinel
Template Parameters
T
Definition at line 30 of file bpqueue.hpp.
The documentation for this class was generated from the following file:
lib/include/ckpttncpp/bpqueue.hpp