CkPttnCpp: FMConstrMgr Class Reference
FMConstrMgr Class Reference
FM Partition Constraint Manager.
#include <FMConstrMgr.hpp>
Public Member Functions
auto init (gsl::span< const uint8_t > part) -> void
auto check_legal (const MoveInfoV &move_info_v) -> size_t
auto check_constraints (const MoveInfoV &move_info_v) -> bool
auto update_move (const MoveInfoV &move_info_v) -> void
Protected Member Functions
FMConstrMgr (SimpleNetlist &H, double BalTol, uint8_t K=2)
Construct a new FMConstrMgr object.
Protected Attributes
SimpleNetlist & H
double BalTol
uint8_t K
std::vector< int > diff
int lowerbound {0}
int totalweight {0}
Private Attributes
int weight
Detailed Description
FM Partition Constraint Manager.
Definition at line 16 of file FMConstrMgr.hpp.
Constructor & Destructor Documentation
FMConstrMgr()
FMConstrMgr::FMConstrMgr (SimpleNetlist & H, double BalTol, uint8_t K = 2) inline protected
Construct a new FMConstrMgr object.
Parameters
H
K
BalTol
Definition at line 35 of file FMConstrMgr.hpp.
References check_constraints(), check_legal(), diff, Netlist< nodeview_t, nodemap_t >::get_module_weight(), init(), K, lowerbound, Netlist< nodeview_t, nodemap_t >::modules, totalweight, update_move(), and weight.
Member Function Documentation
check_constraints()
bool FMConstrMgr::check_constraints (const MoveInfoV & move_info_v) -> bool
Parameters
move_info_v
Returns
true
false
Definition at line 50 of file FMConstMgr.cpp.
References diff, Netlist< nodeview_t, nodemap_t >::get_module_weight(), H, lowerbound, and weight.
Referenced by FMConstrMgr().
check_legal()
size_t FMConstrMgr::check_legal (const MoveInfoV & move_info_v) -> size_t
Parameters
move_info_v
Returns
size_t
Definition at line 25 of file FMConstMgr.cpp.
References diff, Netlist< nodeview_t, nodemap_t >::get_module_weight(), H, lowerbound, and weight.
Referenced by FMKWayConstrMgr::check_legal(), and FMConstrMgr().
init()
void FMConstrMgr::init (gsl::span< const uint8_t > part) -> void
Parameters
part
Definition at line 9 of file FMConstMgr.cpp.
References diff, Netlist< nodeview_t, nodemap_t >::get_module_weight(), H, K, and Netlist< nodeview_t, nodemap_t >::modules.
Referenced by FMConstrMgr(), and FMKWayConstrMgr::init().
update_move()
void FMConstrMgr::update_move (const MoveInfoV & move_info_v) -> void
Parameters
move_info_v
Definition at line 65 of file FMConstMgr.cpp.
References diff, MoveInfoV::fromPart, MoveInfoV::toPart, and weight.
Referenced by FMConstrMgr().
Member Data Documentation
BalTol
double FMConstrMgr::BalTol protected
Definition at line 22 of file FMConstrMgr.hpp.
Referenced by FMBiConstrMgr::FMBiConstrMgr(), and FMKWayConstrMgr::FMKWayConstrMgr().
diff
std::vector<int> FMConstrMgr::diff protected
Definition at line 24 of file FMConstrMgr.hpp.
Referenced by check_constraints(), check_legal(), FMConstrMgr(), FMKWayConstrMgr::init(), init(), FMKWayConstrMgr::select_togo(), FMBiConstrMgr::select_togo(), and update_move().
H
SimpleNetlist& FMConstrMgr::H protected
Definition at line 21 of file FMConstrMgr.hpp.
Referenced by check_constraints(), check_legal(), FMBiConstrMgr::FMBiConstrMgr(), FMKWayConstrMgr::FMKWayConstrMgr(), and init().
K
uint8_t FMConstrMgr::K protected
Definition at line 23 of file FMConstrMgr.hpp.
Referenced by FMConstrMgr(), FMKWayConstrMgr::init(), and init().
lowerbound
int FMConstrMgr::lowerbound {0} protected
Definition at line 25 of file FMConstrMgr.hpp.
Referenced by check_constraints(), check_legal(), FMConstrMgr(), and FMKWayConstrMgr::init().
totalweight
int FMConstrMgr::totalweight {0} protected
Definition at line 26 of file FMConstrMgr.hpp.
Referenced by FMConstrMgr().
weight
int FMConstrMgr::weight private
Definition at line 18 of file FMConstrMgr.hpp.
Referenced by check_constraints(), check_legal(), FMConstrMgr(), and update_move().
The documentation for this class was generated from the following files:
lib/include/ckpttncpp/FMConstrMgr.hpp
lib/src/FMConstMgr.cpp