CkPttnCpp: iter::impl::ChainedFromIterable< Container > Class Template Reference
iter::impl::ChainedFromIterable< Container > Class Template Reference
#include <chain.hpp>
Classes
class Iterator
Public Member Functions
ChainedFromIterable (ChainedFromIterable &&)=default
Iterator< Container > begin ()
Iterator< Container > end ()
Iterator< AsConst< Container > > begin () const
Iterator< AsConst< Container > > end () const
Private Member Functions
ChainedFromIterable (Container &&container)
Private Attributes
friend ChainFromIterableFn
Container container_
Detailed Description
template<typename Container>
class iter::impl::ChainedFromIterable< Container >
Definition at line 21 of file chain.hpp.
Constructor & Destructor Documentation
ChainedFromIterable() [1/2]
template<typename Container > iter::impl::ChainedFromIterable< Container >::ChainedFromIterable (Container && container) inline private
Definition at line 188 of file chain.hpp.
ChainedFromIterable() [2/2]
template<typename Container > iter::impl::ChainedFromIterable< Container >::ChainedFromIterable (ChainedFromIterable< Container > &&) default
Member Function Documentation
begin() [1/2]
template<typename Container > Iterator<Container> iter::impl::ChainedFromIterable< Container >::begin () inline
Definition at line 280 of file chain.hpp.
References iter::impl::get_iters::get_begin(), and iter::impl::get_iters::get_end().
begin() [2/2]
template<typename Container > Iterator<AsConst<Container> > iter::impl::ChainedFromIterable< Container >::begin () const inline
Definition at line 288 of file chain.hpp.
References iter::impl::get_iters::get_begin(), and iter::impl::get_iters::get_end().
end() [1/2]
template<typename Container > Iterator<Container> iter::impl::ChainedFromIterable< Container >::end () inline
Definition at line 284 of file chain.hpp.
References iter::impl::get_iters::get_end().
end() [2/2]
template<typename Container > Iterator<AsConst<Container> > iter::impl::ChainedFromIterable< Container >::end () const inline
Definition at line 293 of file chain.hpp.
References iter::impl::get_iters::get_end().
Member Data Documentation
ChainFromIterableFn
template<typename Container > friend iter::impl::ChainedFromIterable< Container >::ChainFromIterableFn private
Definition at line 186 of file chain.hpp.
container_
template<typename Container > Container iter::impl::ChainedFromIterable< Container >::container_ private
Definition at line 187 of file chain.hpp.
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/chain.hpp