CkPttnCpp: FMGainMgr< GainCalc, Derived > Class Template Reference
FMGainMgr< GainCalc, Derived > Class Template Reference
#include <FMGainMgr.hpp>
Public Member Functions
FMGainMgr (SimpleNetlist &H, uint8_t K)
Construct a new FMGainMgr object.
auto init (gsl::span< const uint8_t > part) -> int
auto is_empty_togo (uint8_t toPart) const -> bool
auto is_empty () const -> bool
auto select (gsl::span< const uint8_t > part) -> std::tuple< MoveInfoV, int >
auto select_togo (uint8_t toPart) -> std::tuple< index_t, int >
auto update_move (gsl::span< const uint8_t > part, const MoveInfoV &move_info_v) -> void
Public Attributes
uint8_t K
Protected Attributes
dllink< node_t > waitinglist {}
SimpleNetlist & H
GainCalc gainCalc
size_t pmax
std::vector< bpqueue< int > > gainbucket
Private Types
using index_t = typename SimpleNetlist::index_t
Private Member Functions
auto __update_move_2pin_net (gsl::span< const uint8_t > part, const MoveInfo &move_info) -> void
auto __update_move_3pin_net (gsl::span< const uint8_t > part, const MoveInfo &move_info) -> void
auto __update_move_general_net (gsl::span< const uint8_t > part, const MoveInfo &move_info) -> void
Private Attributes
Derived & self = *static_cast<Derived*>(this)
Detailed Description
template<typename GainCalc, class Derived>
class FMGainMgr< GainCalc, Derived >
Template Parameters
GainCalc
Derived
Definition at line 19 of file FMGainMgr.hpp.
Member Typedef Documentation
index_t
template<typename GainCalc, class Derived> using FMGainMgr< GainCalc, Derived >::index_t = typename SimpleNetlist::index_t private
Definition at line 22 of file FMGainMgr.hpp.
Constructor & Destructor Documentation
FMGainMgr()
template<typename GainCalc , class Derived > FMGainMgr< GainCalc, Derived >::FMGainMgr (SimpleNetlist & H, uint8_t K) explicit
Construct a new FMGainMgr object.
Parameters
H
K
Definition at line 10 of file FMGainMgr.cpp.
Member Function Documentation
__update_move_2pin_net()
template<typename GainCalc , class Derived > void FMGainMgr< GainCalc, Derived >::__update_move_2pin_net (gsl::span< const uint8_t > part, const MoveInfo & move_info) -> void private
Parameters
part
move_info
Definition at line 126 of file FMGainMgr.cpp.
Referenced by FMGainMgr< FMBiGainCalc, FMBiGainMgr >::is_empty(), and FMGainMgr< FMBiGainCalc, FMBiGainMgr >::update_move().
__update_move_3pin_net()
template<typename GainCalc , class Derived > void FMGainMgr< GainCalc, Derived >::__update_move_3pin_net (gsl::span< const uint8_t > part, const MoveInfo & move_info) -> void private
Parameters
part
move_info
Definition at line 140 of file FMGainMgr.cpp.
Referenced by FMGainMgr< FMBiGainCalc, FMBiGainMgr >::is_empty(), and FMGainMgr< FMBiGainCalc, FMBiGainMgr >::update_move().
__update_move_general_net()
template<typename GainCalc , class Derived > void FMGainMgr< GainCalc, Derived >::__update_move_general_net (gsl::span< const uint8_t > part, const MoveInfo & move_info) -> void private
Parameters
part
move_info
Definition at line 160 of file FMGainMgr.cpp.
Referenced by FMGainMgr< FMBiGainCalc, FMBiGainMgr >::is_empty(), and FMGainMgr< FMBiGainCalc, FMBiGainMgr >::update_move().
init()
template<typename GainCalc , class Derived > int FMGainMgr< GainCalc, Derived >::init (gsl::span< const uint8_t > part) -> int
Parameters
part
Definition at line 30 of file FMGainMgr.cpp.
is_empty()
template<typename GainCalc, class Derived> auto FMGainMgr< GainCalc, Derived >::is_empty () const -> bool inline
Returns
true
false
Definition at line 69 of file FMGainMgr.hpp.
Referenced by FMGainMgr< FMBiGainCalc, FMBiGainMgr >::is_empty().
is_empty_togo()
template<typename GainCalc, class Derived> auto FMGainMgr< GainCalc, Derived >::is_empty_togo (uint8_t toPart) const -> bool inline
Parameters
toPart
Returns
true
false
Definition at line 58 of file FMGainMgr.hpp.
select()
template<typename GainCalc , class Derived > std::tuple< MoveInfoV, int > FMGainMgr< GainCalc, Derived >::select (gsl::span< const uint8_t > part) -> std::tuple<MoveInfoV, int>
Parameters
part
Returns
std::tuple<MoveInfoV, int>
Definition at line 45 of file FMGainMgr.cpp.
Referenced by FMGainMgr< FMBiGainCalc, FMBiGainMgr >::is_empty().
select_togo()
template<typename GainCalc , class Derived > std::tuple< index_t, int > FMGainMgr< GainCalc, Derived >::select_togo (uint8_t toPart) -> std::tuple<index_t, int>
Parameters
toPart
Returns
std::tuple<index_t, int>
Definition at line 71 of file FMGainMgr.cpp.
Referenced by FMGainMgr< FMBiGainCalc, FMBiGainMgr >::is_empty().
update_move()
template<typename GainCalc , class Derived > void FMGainMgr< GainCalc, Derived >::update_move (gsl::span< const uint8_t > part, const MoveInfoV & move_info_v) -> void
Parameters
part
move_info_v
part
move_info_v
gain
Definition at line 89 of file FMGainMgr.cpp.
Referenced by FMGainMgr< FMBiGainCalc, FMBiGainMgr >::is_empty().
Member Data Documentation
gainbucket
template<typename GainCalc, class Derived> std::vector<bpqueue<int> > FMGainMgr< GainCalc, Derived >::gainbucket protected
Definition at line 30 of file FMGainMgr.hpp.
Referenced by FMGainMgr< FMBiGainCalc, FMBiGainMgr >::FMGainMgr(), FMGainMgr< FMBiGainCalc, FMBiGainMgr >::select(), and FMGainMgr< FMBiGainCalc, FMBiGainMgr >::select_togo().
gainCalc
template<typename GainCalc, class Derived> GainCalc FMGainMgr< GainCalc, Derived >::gainCalc protected
Definition at line 28 of file FMGainMgr.hpp.
Referenced by FMGainMgr< FMBiGainCalc, FMBiGainMgr >::__update_move_2pin_net(), FMGainMgr< FMBiGainCalc, FMBiGainMgr >::__update_move_3pin_net(), FMGainMgr< FMBiGainCalc, FMBiGainMgr >::__update_move_general_net(), FMGainMgr< FMBiGainCalc, FMBiGainMgr >::FMGainMgr(), FMGainMgr< FMBiGainCalc, FMBiGainMgr >::init(), FMGainMgr< FMBiGainCalc, FMBiGainMgr >::select(), FMGainMgr< FMBiGainCalc, FMBiGainMgr >::select_togo(), and FMGainMgr< FMBiGainCalc, FMBiGainMgr >::update_move().
H
template<typename GainCalc, class Derived> SimpleNetlist& FMGainMgr< GainCalc, Derived >::H protected
Definition at line 27 of file FMGainMgr.hpp.
Referenced by FMGainMgr< FMBiGainCalc, FMBiGainMgr >::FMGainMgr(), and FMGainMgr< FMBiGainCalc, FMBiGainMgr >::update_move().
K
template<typename GainCalc, class Derived> uint8_t FMGainMgr< GainCalc, Derived >::K
Definition at line 33 of file FMGainMgr.hpp.
Referenced by FMGainMgr< FMBiGainCalc, FMBiGainMgr >::FMGainMgr(), FMGainMgr< FMBiGainCalc, FMBiGainMgr >::is_empty(), and FMGainMgr< FMBiGainCalc, FMBiGainMgr >::select().
pmax
template<typename GainCalc, class Derived> size_t FMGainMgr< GainCalc, Derived >::pmax protected
Definition at line 29 of file FMGainMgr.hpp.
Referenced by FMGainMgr< FMBiGainCalc, FMBiGainMgr >::FMGainMgr().
self
template<typename GainCalc, class Derived> Derived& FMGainMgr< GainCalc, Derived >::self = *static_cast<Derived*>(this) private
Definition at line 21 of file FMGainMgr.hpp.
waitinglist
template<typename GainCalc, class Derived> dllink<node_t> FMGainMgr< GainCalc, Derived >::waitinglist {} protected
Definition at line 25 of file FMGainMgr.hpp.
Referenced by FMGainMgr< FMBiGainCalc, FMBiGainMgr >::init(), FMGainMgr< FMBiGainCalc, FMBiGainMgr >::select(), and FMGainMgr< FMBiGainCalc, FMBiGainMgr >::select_togo().
The documentation for this class was generated from the following files:
lib/include/ckpttncpp/FMGainMgr.hpp
lib/src/FMGainMgr.cpp