CkPttnCpp: xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory > Class Template Reference
xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory > Class Template Reference
#include <graph.hpp>
Public Types
using Node = typename nodeview_t::value_type
using dict = py::dict< const char *, boost::any >
using graph_attr_dict_factory = dict
using adjlist_outer_dict_factory = std::vector< adjlist_inner_dict_factory >
using key_type = typename adjlist_inner_dict_factory::key_type
using value_type = typename adjlist_inner_dict_factory::value_type
Public Types inherited from py::dict< const char *, boost::any >
using value_type = std::pair< const const char *, boost::any >
Public Member Functions
Graph (const nodeview_t &Nodes, const nodemap_t &node_map)
Initialize a graph with edges, name, or graph attributes.
Graph (int num_nodes)
auto adj () const
Graph adjacency object holding the neighbors of each node.
auto get_name ()
auto set_name (const char *s)
auto begin () const
Iterate over the nodes.
auto end () const
bool contains (const Node &n)
Return true if (n is a node, false otherwise.
auto operator[] (const Node &n) const
Return a dict of neighbors of node n.
auto nodes ()
auto number_of_nodes () const
Return the number of nodes : the graph.
auto order ()
Return the number of nodes : the graph.
auto has_node (const Node &n)
Return true if (the graph contains the node n.
auto add_edge (const Node &u, const Node &v)
auto has_edge (const Node &u, const Node &v) -> bool
auto degree (const Node &n)
auto clear ()
An EdgeView of the Graph as G.edges || G.edges().
auto is_multigraph ()
auto is_directed ()
Public Member Functions inherited from py::dict< const char *, boost::any >
dict ()
Construct a new dict object.
dict (_Self &&)=default
Move Constructor (default)
_Self & operator= (_Self &&)=default
Public Attributes
nodeview_t _node
nodemap_t _node_map
graph_attr_dict_factory graph {}
adjlist_outer_dict_factory _adj
Detailed Description
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>>
class xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >
Definition at line 201 of file graph.hpp.
Member Typedef Documentation
adjlist_outer_dict_factory
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> using xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::adjlist_outer_dict_factory = std::vector<adjlist_inner_dict_factory>
Definition at line 212 of file graph.hpp.
dict
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> using xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::dict = py::dict<const char *, boost::any>
Definition at line 204 of file graph.hpp.
graph_attr_dict_factory
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> using xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::graph_attr_dict_factory = dict
Definition at line 205 of file graph.hpp.
key_type
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> using xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::key_type = typename adjlist_inner_dict_factory::key_type
Definition at line 213 of file graph.hpp.
Node
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> using xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::Node = typename nodeview_t::value_type
Definition at line 203 of file graph.hpp.
value_type
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> using xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::value_type = typename adjlist_inner_dict_factory::value_type
Definition at line 214 of file graph.hpp.
Constructor & Destructor Documentation
Graph() [1/2]
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::Graph (const nodeview_t & Nodes, const nodemap_t & node_map) inline
Initialize a graph with edges, name, or graph attributes.
Parameters
node_container : input nodes
Examples
v = std::vector{5, 3, 2}; G = xn::Graph(v); // or DiGraph, MultiGraph, MultiDiGraph, etc
r = py::range(100); G = xn::Graph(r); // or DiGraph, MultiGraph, MultiDiGraph, etc
Definition at line 253 of file graph.hpp.
Graph() [2/2]
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::Graph (int num_nodes) inline
Definition at line 256 of file graph.hpp.
Member Function Documentation
add_edge()
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> auto xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::add_edge (const Node & u, const Node & v) inline
Add an edge between u && v.
The nodes u && v will be automatically added if (they are not already : the graph.
Edge attributes can be specified with keywords || by directly accessing the edge"s attribute dictionary. See examples below.
Parameters
u, v : nodes Nodes can be, for example, strings || numbers. Nodes must be hashable (and not None) C++ objects.
See Also
add_edges_from : add a collection of edges
Notes
Adding an edge that already exists updates the edge data.
Many XNetwork algorithms designed for weighted graphs use an edge attribute (by default weight) to hold a numerical value.
Examples
The following all add the edge e=(1, 2) to graph G) {
G = xn::Graph() // or DiGraph, MultiGraph, MultiDiGraph, etc e = (1, 2); G.add_edge(1, 2) // explicit two-node form G.add_edges_from([(1, 2)]); // add edges from iterable container
Associate data to edges using keywords) {
G.add_edge(1, 2);
For non-string attribute keys, use subscript notation.
G.add_edge(1, 2); G[1][2].update({0: 5}); G.edges[1, 2].update({0: 5});
Definition at line 476 of file graph.hpp.
Referenced by xn::grAdaptor< Graph >::grAdaptor().
adj()
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> auto xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::adj () const inline
Graph adjacency object holding the neighbors of each node.
This object is a read-only dict-like structure with node keys and neighbor-dict values. The neighbor-dict is keyed by neighbor to the edge-data-dict. So `G.adj[3][2]['color'] = 'blue'sets the color of the edge(3, 2)to"blue"`.
Iterating over G.adj behaves like a dict. Useful idioms include for nbr, datadict in G.adj[n].items():.
The neighbor information is also provided by subscripting the graph. So `for nbr, foovalue in G[node].data('foo', default=1):` works.
For directed graphs, G.adj holds outgoing (successor) info.
Definition at line 276 of file graph.hpp.
begin()
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> auto xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::begin () const inline
Iterate over the nodes.
Use: "for (auto n : G)".
Returns
niter : iterator An iterator over all nodes : the graph.
Examples
G = xn::path_graph(4); // or DiGraph, MultiGraph, MultiDiGraph, etc [n for n : G];
[0, 1, 2, 3];
list(G);
[0, 1, 2, 3];
Definition at line 309 of file graph.hpp.
Referenced by FMBiGainCalc::__init_gain_2pin_net(), FMBiGainCalc::__init_gain_3pin_net(), create_contraction_subgraph(), and FMBiGainCalc::update_move_2pin_net().
clear()
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> auto xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::clear () inline
An EdgeView of the Graph as G.edges || G.edges().
edges(nbunch=None, data=false, default=None);
The EdgeView provides set-like operations on the edge-tuples as well as edge attribute lookup. When called, it also provides an EdgeDataView object which allows control of access to edge attributes (but does not provide set-like operations). Hence, G.edges[u, v]["color"] provides the value of the color attribute for edge (u, v) while for (auto u, v, c] : G.edges.data("color", default="red") { iterates through all the edges yielding the color attribute with default "red" if (no color attribute exists.
Parameters
nbunch : single node, container, || all nodes (default= all nodes); The view will only report edges incident to these nodes. data : string || bool, optional (default=false); The edge attribute returned : 3-tuple (u, v, ddict[data]). If true, return edge attribute dict : 3-tuple (u, v, ddict). If false, return 2-tuple (u, v). default : value, optional (default=None); Value used for edges that don"t have the requested attribute. Only relevant if (data is not true || false.
Returns
edges : EdgeView A view of edge attributes, usually it iterates over (u, v); || (u, v, d) tuples of edges, but can also be used for attribute lookup as edges[u, v]["foo"].
Notes
Nodes : nbunch that are not : the graph will be (quietly) ignored. For directed graphs this returns the out-edges.
Examples
G = xn::path_graph(3) // or MultiGraph, etc G.add_edge(2, 3, weight=5); [e for e : G.edges];
[(0, 1), (1, 2), (2, 3)];
G.edges.data(); // default data is {} (empty dict);
EdgeDataView([(0, 1, {}), (1, 2, {}), (2, 3, {"weight": 5})]);
G.edges.data("weight", default=1);
EdgeDataView([(0, 1, 1), (1, 2, 1), (2, 3, 5)]);
G.edges([0, 3]); // only edges incident to these nodes
EdgeDataView([(0, 1), (3, 2)]);
G.edges(0); // only edges incident to a single node (use
G.adj[0]?); EdgeDataView([(0, 1)]); A DegreeView for the Graph as G.degree || G.degree().
The node degree is the number of edges adjacent to the node. The weighted node degree is the sum of the edge weights for edges incident to that node.
This object provides an iterator for (auto node, degree) as well as lookup for the degree for a single node.
Parameters
nbunch : single node, container, || all nodes (default= all nodes); The view will only report edges incident to these nodes.
weight : string || None, optional (default=None); The name of an edge attribute that holds the numerical value used as a weight. If None, then each edge has weight 1. The degree is the sum of the edge weights adjacent to the node.
Returns
If a single node is requested deg : int Degree of the node
OR if (multiple nodes are requested nd_view : A DegreeView object capable of iterating (node, degree) pairs
Examples
G = xn::path_graph(4); // or DiGraph, MultiGraph, MultiDiGraph,
etc
G.degree[0]; // node 0 has degree 1
1
list(G.degree([0, 1, 2]));
[(0, 1), (1, 2), (2, 2)];
Remove all nodes && edges from the graph.
This also removes the name, && all graph, node, && edge attributes.
Examples
G = xn::path_graph(4); // or DiGraph, MultiGraph, MultiDiGraph, etc G.clear(); list(G.nodes);
[];
list(G.edges);
[];
Definition at line 687 of file graph.hpp.
contains()
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> bool xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::contains (const Node & n) inline
Return true if (n is a node, false otherwise.
Use: "n : G".
Examples
G = xn::path_graph(4); // or DiGraph, MultiGraph, MultiDiGraph, etc 1 : G
true
Definition at line 321 of file graph.hpp.
degree()
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> auto xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::degree (const Node & n) inline
Definition at line 580 of file graph.hpp.
Referenced by FMBiGainCalc::__init_gain(), xn::grAdaptor< Graph >::grAdaptor(), max_independent_net(), Netlist< nodeview_t, nodemap_t >::Netlist(), and FMGainMgr< FMBiGainCalc, FMBiGainMgr >::update_move().
end()
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> auto xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::end () const inline
Definition at line 311 of file graph.hpp.
get_name()
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> auto xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::get_name () inline
String identifier of the graph.
This graph attribute appears : the attribute dict G.graph keyed by the string "name". as well as an attribute (technically a property) G.name. This is entirely user controlled.
Definition at line 279 of file graph.hpp.
has_edge()
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> auto xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::has_edge (const Node & u, const Node & v) -> bool inline
Return true if (the edge (u, v) is : the graph.
This is the same as v : G[u] without KeyError exceptions.
Parameters
u, v : nodes Nodes can be, for example, strings || numbers. Nodes must be hashable (and not None) C++ objects.
Returns
edge_ind : bool true if (edge is : the graph, false otherwise.
Examples
G = xn::path_graph(4); // or DiGraph, MultiGraph, MultiDiGraph, etc G.has_edge(0, 1); // using two nodes
true
e = (0, 1); G.has_edge(*e); // e is a 2-tuple (u, v);
true
e = (0, 1, {"weight":7}); G.has_edge(*e[:2]); // e is a 3-tuple (u, v, data_dictionary);
true
The following syntax are equivalent) {
G.has_edge(0, 1);
true
1 : G[0]; // though this gives KeyError if (0 not : G
true
Definition at line 541 of file graph.hpp.
has_node()
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> auto xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::has_node (const Node & n) inline
Return true if (the graph contains the node n.
Identical to n : G
Parameters
n : node
Examples
G = xn::path_graph(3); // or DiGraph, MultiGraph, MultiDiGraph, etc G.has_node(0);
true
Definition at line 474 of file graph.hpp.
is_directed()
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> auto xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::is_directed () inline
Return true if (graph is directed, false otherwise.
Definition at line 712 of file graph.hpp.
is_multigraph()
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> auto xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::is_multigraph () inline
Return true if (graph is a multigraph, false otherwise.
Definition at line 707 of file graph.hpp.
nodes()
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> auto xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::nodes () inline
A NodeView of the Graph as G.nodes().
Returns
NodeView Allows set-like operations over the nodes as well as node attribute dict lookup && calling to get a NodeDataView. A NodeDataView iterates over (n, data) && has no set operations. A NodeView iterates over n && includes set operations.
When called, if (data == false, an iterator over nodes. Otherwise an iterator of 2-tuples (node, attribute value); where the attribute is specified : data. If data is true then the attribute becomes the entire data dictionary.
Notes
If your node data is not needed, it is simpler and equivalent to use the expression for n : G, or list(G).
Examples
There are two simple ways of getting a list of all nodes : the graph) {
G = xn::path_graph(3); list(G.nodes);
[0, 1, 2];
list(G);
[0, 1, 2];
To get the node data along with the nodes) {
G.add_node(1, time="5pm"); G.nodes[0]["foo"] = "bar"; list(G.nodes(data=true));
[(0, {"foo": "bar"}), (1, {"time": "5pm"}), (2, {})];
list(G.nodes.data());
[(0, {"foo": "bar"}), (1, {"time": "5pm"}), (2, {})];
list(G.nodes(data="foo"));
[(0, "bar"), (1, None), (2, None)];
list(G.nodes.data("foo"));
[(0, "bar"), (1, None), (2, None)];
list(G.nodes(data="time"));
[(0, None), (1, "5pm"), (2, None)];
list(G.nodes.data("time"));
[(0, None), (1, "5pm"), (2, None)];
list(G.nodes(data="time", default="Not Available"));
[(0, "Not Available"), (1, "5pm"), (2, "Not Available")];
list(G.nodes.data("time", default="Not Available"));
[(0, "Not Available"), (1, "5pm"), (2, "Not Available")];
If some of your nodes have an attribute && the rest are assumed to have a default attribute value you can create a dictionary from node/attribute pairs using the default keyword argument to guarantee the value is never None:) {
>>> G = xn::Graph();
>>> G.add_node(0);
>>> G.add_node(1, weight=2);
>>> G.add_node(2, weight=3);
>>> dict(G.nodes(data="weight", default=1));
{0: 1, 1: 2, 2: 3}
Definition at line 351 of file graph.hpp.
number_of_nodes()
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> auto xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::number_of_nodes () const inline
Return the number of nodes : the graph.
Returns
nnodes : int The number of nodes : the graph.
See Also
order, len which are identical
Examples
G = xn::path_graph(3); // or DiGraph, MultiGraph, MultiDiGraph, etc len(G);
3
Definition at line 445 of file graph.hpp.
Referenced by xn::grAdaptor< Graph >::grAdaptor(), and Netlist< nodeview_t, nodemap_t >::number_of_nodes().
operator[]()
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> auto xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::operator[] (const Node & n) const inline
Return a dict of neighbors of node n.
Use: "G[n]".
Parameters
n : node A node in the graph.
Returns
adj_dict : dictionary The adjacency dictionary for nodes connected to n.
Notes
G[n] is the same as G.adj[n] && similar to G.neighbors(n); (which is an iterator over G.adj[n]);
Examples
G = xn::path_graph(4); // or DiGraph, MultiGraph, MultiDiGraph, etc G[0];
AtlasView({1: {}});
Definition at line 346 of file graph.hpp.
Referenced by xn::grAdaptor< Graph >::grAdaptor().
order()
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> auto xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::order () inline
Return the number of nodes : the graph.
Returns
nnodes : int The number of nodes : the graph.
See Also
number_of_nodes, len which are identical
Definition at line 458 of file graph.hpp.
set_name()
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> auto xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::set_name (const char * s) inline
Definition at line 292 of file graph.hpp.
Member Data Documentation
_adj
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> adjlist_outer_dict_factory xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::_adj
Definition at line 222 of file graph.hpp.
_node
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> nodeview_t xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::_node
Definition at line 218 of file graph.hpp.
_node_map
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> nodemap_t xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::_node_map
Definition at line 219 of file graph.hpp.
graph
template<typename nodeview_t, typename nodemap_t, typename adjlist_inner_dict_factory = py::set<typename nodeview_t::value_type>> graph_attr_dict_factory xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::graph {}
Definition at line 220 of file graph.hpp.
The documentation for this class was generated from the following file:
lib/include/xnetwork/classes/graph.hpp