CkPttnCpp: set_partition_ Class Reference
set_partition_ Class Reference
#include <set_partition.hpp>
Public Member Functions
set_partition_ (Fun yield_)
Construct object.
void run (int n, int k)
run
Private Types
using ret_t = std::tuple< int, int >
using Fun = std::function< void(ret_t)>
Private Member Functions
void __Move (int x, int y)
Move.
void __GEN0_even (int n, int k)
S(n,k,0) even k.
void __NEG0_even (int n, int k)
S'(n,k,0) even k.
void __GEN1_even (int n, int k)
S(n,k,1) even k.
void __NEG1_even (int n, int k)
S'(n,k,1) even k.
void __GEN0_odd (int n, int k)
S(n,k,0) odd k.
void __NEG0_odd (int n, int k)
S'(n,k,0) odd k.
void __GEN1_odd (int n, int k)
S(n,k,1) odd k.
void __NEG1_odd (int n, int k)
S'(n,k,1) odd k.
Private Attributes
Fun yield
Detailed Description
Definition at line 58 of file set_partition.hpp.
Member Typedef Documentation
Fun
using set_partition_::Fun = std::function<void(ret_t)> private
Definition at line 61 of file set_partition.hpp.
ret_t
using set_partition_::ret_t = std::tuple<int, int> private
Definition at line 60 of file set_partition.hpp.
Constructor & Destructor Documentation
set_partition_()
set_partition_::set_partition_ (Fun yield_) inline explicit
Construct object.
Parameters
n_
k_
yield_
Definition at line 76 of file set_partition.hpp.
Member Function Documentation
__GEN0_even()
void set_partition_::__GEN0_even (int n, int k) private
S(n,k,0) even k.
Parameters
n
k
Definition at line 16 of file set_partition.cpp.
References __GEN0_odd(), __GEN1_even(), __Move(), and __NEG1_even().
Referenced by __GEN1_odd(), __Move(), and run().
__GEN0_odd()
void set_partition_::__GEN0_odd (int n, int k) private
S(n,k,0) odd k.
Parameters
n
k
Definition at line 128 of file set_partition.cpp.
References __GEN1_even(), __GEN1_odd(), __Move(), and __NEG1_odd().
Referenced by __GEN0_even(), __Move(), and run().
__GEN1_even()
void set_partition_::__GEN1_even (int n, int k) private
S(n,k,1) even k.
Parameters
n
k
Definition at line 72 of file set_partition.cpp.
References __GEN1_odd(), __Move(), and __NEG1_even().
Referenced by __GEN0_even(), __GEN0_odd(), __Move(), __NEG0_even(), and __NEG1_even().
__GEN1_odd()
void set_partition_::__GEN1_odd (int n, int k) private
S(n,k,1) odd k.
Parameters
n
k
Definition at line 180 of file set_partition.cpp.
References __GEN0_even(), __Move(), and __NEG1_odd().
Referenced by __GEN0_odd(), __GEN1_even(), __Move(), __NEG0_odd(), and __NEG1_odd().
__Move()
void set_partition_::__Move (int x, int y) inline private
Move.
Parameters
x
y
Definition at line 100 of file set_partition.hpp.
References __GEN0_even(), __GEN0_odd(), __GEN1_even(), __GEN1_odd(), __NEG0_even(), __NEG0_odd(), __NEG1_even(), __NEG1_odd(), k, and yield.
Referenced by __GEN0_even(), __GEN0_odd(), __GEN1_even(), __GEN1_odd(), __NEG0_even(), __NEG0_odd(), __NEG1_even(), and __NEG1_odd().
__NEG0_even()
void set_partition_::__NEG0_even (int n, int k) private
S'(n,k,0) even k.
Parameters
n
k
Definition at line 44 of file set_partition.cpp.
References __GEN1_even(), __Move(), __NEG0_odd(), and __NEG1_even().
Referenced by __Move(), and __NEG1_odd().
__NEG0_odd()
void set_partition_::__NEG0_odd (int n, int k) private
S'(n,k,0) odd k.
Parameters
n
k
Definition at line 154 of file set_partition.cpp.
References __GEN1_odd(), __Move(), __NEG1_even(), and __NEG1_odd().
Referenced by __Move(), and __NEG0_even().
__NEG1_even()
void set_partition_::__NEG1_even (int n, int k) private
S'(n,k,1) even k.
Parameters
n
k
Definition at line 100 of file set_partition.cpp.
References __GEN1_even(), __Move(), and __NEG1_odd().
Referenced by __GEN0_even(), __GEN1_even(), __Move(), __NEG0_even(), and __NEG0_odd().
__NEG1_odd()
void set_partition_::__NEG1_odd (int n, int k) private
S'(n,k,1) odd k.
Parameters
n
k
Definition at line 206 of file set_partition.cpp.
References __GEN1_odd(), __Move(), and __NEG0_even().
Referenced by __GEN0_odd(), __GEN1_odd(), __Move(), __NEG0_odd(), and __NEG1_even().
run()
void set_partition_::run (int n, int k) inline
run
Definition at line 85 of file set_partition.hpp.
References __GEN0_even(), and __GEN0_odd().
Referenced by set_partition().
Member Data Documentation
yield
Fun set_partition_::yield private
Definition at line 66 of file set_partition.hpp.
Referenced by __Move().
The documentation for this class was generated from the following files:
lib/include/ckpttncpp/set_partition.hpp
lib/src/set_partition.cpp