CkPttnCpp: iter::impl::Dropper< FilterFunc, Container > Class Template Reference
iter::impl::Dropper< FilterFunc, Container > Class Template Reference
#include <dropwhile.hpp>
Classes
class Iterator
Public Member Functions
Dropper (Dropper &&)=default
Iterator< Container > begin ()
Iterator< Container > end ()
Iterator< AsConst< Container > > begin () const
Iterator< AsConst< Container > > end () const
Private Member Functions
Dropper (FilterFunc filter_func, Container &&container)
Private Attributes
Container container_
FilterFunc filter_func_
friend DropWhileFn
Detailed Description
template<typename FilterFunc, typename Container>
class iter::impl::Dropper< FilterFunc, Container >
Definition at line 15 of file dropwhile.hpp.
Constructor & Destructor Documentation
Dropper() [1/2]
template<typename FilterFunc , typename Container > iter::impl::Dropper< FilterFunc, Container >::Dropper (FilterFunc filter_func, Container && container) inline private
Definition at line 30 of file dropwhile.hpp.
Dropper() [2/2]
template<typename FilterFunc , typename Container > iter::impl::Dropper< FilterFunc, Container >::Dropper (Dropper< FilterFunc, Container > &&) default
Member Function Documentation
begin() [1/2]
template<typename FilterFunc , typename Container > Iterator<Container> iter::impl::Dropper< FilterFunc, Container >::begin () inline
Definition at line 109 of file dropwhile.hpp.
References iter::impl::get_iters::get_begin(), and iter::impl::get_iters::get_end().
begin() [2/2]
template<typename FilterFunc , typename Container > Iterator<AsConst<Container> > iter::impl::Dropper< FilterFunc, Container >::begin () const inline
Definition at line 117 of file dropwhile.hpp.
References iter::impl::get_iters::get_begin(), and iter::impl::get_iters::get_end().
end() [1/2]
template<typename FilterFunc , typename Container > Iterator<Container> iter::impl::Dropper< FilterFunc, Container >::end () inline
Definition at line 113 of file dropwhile.hpp.
References iter::impl::get_iters::get_end().
end() [2/2]
template<typename FilterFunc , typename Container > Iterator<AsConst<Container> > iter::impl::Dropper< FilterFunc, Container >::end () const inline
Definition at line 122 of file dropwhile.hpp.
References iter::impl::get_iters::get_end().
Member Data Documentation
container_
template<typename FilterFunc , typename Container > Container iter::impl::Dropper< FilterFunc, Container >::container_ private
Definition at line 25 of file dropwhile.hpp.
DropWhileFn
template<typename FilterFunc , typename Container > friend iter::impl::Dropper< FilterFunc, Container >::DropWhileFn private
Definition at line 28 of file dropwhile.hpp.
filter_func_
template<typename FilterFunc , typename Container > FilterFunc iter::impl::Dropper< FilterFunc, Container >::filter_func_ mutable private
Definition at line 26 of file dropwhile.hpp.
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/dropwhile.hpp