CkPttnCpp: iter::impl::SortedView< Container, CompareFunc > Class Template Reference
iter::impl::SortedView< Container, CompareFunc > Class Template Reference
#include <sorted.hpp>
Classes
class SortedItersHolder
class SortedItersHolder< ContainerT, std::void_t< decltype(std::begin(std::declval< AsConst< ContainerT > & >()))> >
Public Member Functions
SortedView (SortedView &&)=default
SortedItersHolder< Container >::ItIt begin ()
SortedItersHolder< Container >::ItIt end ()
SortedItersHolder< Container >::ConstItIt begin () const
SortedItersHolder< Container >::ConstItIt end () const
Private Member Functions
SortedView (Container &&container, CompareFunc compare_func)
Private Attributes
friend SortedFn
SortedItersHolder< Container > sorted_iters_holder_
Detailed Description
template<typename Container, typename CompareFunc>
class iter::impl::SortedView< Container, CompareFunc >
Definition at line 15 of file sorted.hpp.
Constructor & Destructor Documentation
SortedView() [1/2]
template<typename Container , typename CompareFunc > iter::impl::SortedView< Container, CompareFunc >::SortedView (Container && container, CompareFunc compare_func) inline private
Definition at line 149 of file sorted.hpp.
SortedView() [2/2]
template<typename Container , typename CompareFunc > iter::impl::SortedView< Container, CompareFunc >::SortedView (SortedView< Container, CompareFunc > &&) default
Member Function Documentation
begin() [1/2]
template<typename Container , typename CompareFunc > SortedItersHolder<Container>::ItIt iter::impl::SortedView< Container, CompareFunc >::begin () inline
Definition at line 156 of file sorted.hpp.
References iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, typename >::begin().
begin() [2/2]
template<typename Container , typename CompareFunc > SortedItersHolder<Container>::ConstItIt iter::impl::SortedView< Container, CompareFunc >::begin () const inline
Definition at line 164 of file sorted.hpp.
References iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, typename >::begin().
end() [1/2]
template<typename Container , typename CompareFunc > SortedItersHolder<Container>::ItIt iter::impl::SortedView< Container, CompareFunc >::end () inline
Definition at line 160 of file sorted.hpp.
References iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, typename >::end().
end() [2/2]
template<typename Container , typename CompareFunc > SortedItersHolder<Container>::ConstItIt iter::impl::SortedView< Container, CompareFunc >::end () const inline
Definition at line 168 of file sorted.hpp.
References iter::impl::SortedView< Container, CompareFunc >::SortedItersHolder< ContainerT, typename >::end().
Member Data Documentation
sorted_iters_holder_
template<typename Container , typename CompareFunc > SortedItersHolder<Container> iter::impl::SortedView< Container, CompareFunc >::sorted_iters_holder_ private
Definition at line 147 of file sorted.hpp.
SortedFn
template<typename Container , typename CompareFunc > friend iter::impl::SortedView< Container, CompareFunc >::SortedFn private
Definition at line 145 of file sorted.hpp.
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/sorted.hpp