CkPttnCpp: iter Namespace Reference
iter Namespace Reference
Namespaces
detail
impl
Functions
template<typename Container , typename Selector >
impl::Compressed< Container, Selector > compress (Container &&, Selector &&)
template<typename T >
constexpr auto count (T start, T step) noexcept
template<typename T = long>
constexpr auto count (T start=T(0)) noexcept
template<typename... Containers>
decltype(auto) product (Containers &&... containers)
constexpr std::array< std::tuple<>, 1 > product ()
template<std::size_t N, typename Container >
decltype(auto) product (Container &&container)
template<typename T >
constexpr impl::Range< T > range (T) noexcept
template<typename T >
constexpr impl::Range< T > range (T, T) noexcept
template<typename T >
constexpr impl::Range< T > range (T, T, T) noexcept
template<typename T >
constexpr impl::RepeaterWithCount< T > repeat (T &&, int)
template<typename T >
constexpr impl::Repeater< T > repeat (T &&)
template<typename... Containers>
auto zip (Containers &&... containers)
template<typename... Containers>
auto zip_longest (Containers &&... containers)
Variables
constexpr impl::AccumulateFn accumulate {}
constexpr impl::ChunkedFn chunked {}
constexpr impl::CombinationsFn combinations {}
constexpr impl::CombinationsWithReplacementFn combinations_with_replacement {}
constexpr impl::CycleFn cycle {}
constexpr impl::DropWhileFn dropwhile {}
constexpr impl::EnumerateFn enumerate {}
constexpr impl::FilterFn filter {}
constexpr impl::FilterFalseFn filterfalse {}
constexpr impl::GroupByFn groupby {}
constexpr impl::IMapFn imap {}
constexpr impl::PermutationsFn permutations {}
constexpr impl::PowersetFn powerset {}
constexpr impl::ReversedFn reversed {}
constexpr impl::SliceFn slice {}
constexpr impl::SlidingWindowFn sliding_window {}
constexpr impl::SortedFn sorted {}
constexpr impl::StarMapFn starmap {}
constexpr impl::TakeWhileFn takewhile {}
constexpr impl::UniqueEverseenFn unique_everseen {}
constexpr impl::UniqueJustseenFn unique_justseen {}
Function Documentation
compress()
template<typename Container , typename Selector > impl::Compressed<Container, Selector> iter::compress (Container && , Selector &&)
Referenced by iter::impl::Compressed< Container, Selector >::end(), main(), TEST_CASE(), and testcase().
count() [1/2]
template<typename T > constexpr auto iter::count (T start, T step) noexcept
Definition at line 10 of file count.hpp.
References range().
Referenced by count(), and main().
count() [2/2]
template<typename T = long> constexpr auto iter::count (T start = T(0)) noexcept
Definition at line 18 of file count.hpp.
References count().
product() [1/3]
template<typename... Containers> decltype(auto) iter::product (Containers &&... containers)
Definition at line 193 of file product.hpp.
References iter::impl::product_impl().
Referenced by main(), iter::impl::product_repeat(), and TEST_CASE().
product() [2/3]
constexpr std::array<std::tuple<>, 1> iter::product ()
Definition at line 199 of file product.hpp.
product() [3/3]
template<std::size_t N, typename Container > decltype(auto) iter::product (Container && container)
Definition at line 227 of file product.hpp.
References iter::impl::product_repeat().
range() [1/3]
template<typename T > constexpr impl::Range<T> iter::range (T) inline noexcept
Definition at line 112 of file py2cpp.hpp.
References py::range().
Referenced by count(), iter::impl::Range< T >::end(), main(), iter::detail::RangeIterData< T, true >::operator!=(), and TEST_CASE().
range() [2/3]
template<typename T > constexpr impl::Range<T> iter::range (T , T) inline noexcept
Definition at line 75 of file py2cpp.hpp.
References NS1::begin(), NS1::end(), and i.
Referenced by py::range(), and TEST_CASE().
range() [3/3]
template<typename T > constexpr impl::Range<T> iter::range (T , T , T) noexcept
repeat() [1/2]
template<typename T > constexpr impl::RepeaterWithCount<T> iter::repeat (T && , int)
Referenced by iter::impl::RepeaterWithCount< T >::end(), iter::impl::Repeater< T >::end(), main(), and TEST_CASE().
repeat() [2/2]
template<typename T > constexpr impl::Repeater<T> iter::repeat (T &&)
zip()
template<typename... Containers> auto iter::zip (Containers &&... containers)
Definition at line 127 of file zip.hpp.
References iter::impl::zip_impl().
Referenced by main(), iter::impl::IMapFn::operator()(), and TEST_CASE().
zip_longest()
template<typename... Containers> auto iter::zip_longest (Containers &&... containers)
Definition at line 141 of file zip_longest.hpp.
References iter::impl::zip_longest_impl().
Referenced by main(), and TEST_CASE().
Variable Documentation
accumulate
constexpr impl::AccumulateFn iter::accumulate {}
Definition at line 20 of file accumulate.hpp.
Referenced by main(), and TEST_CASE().
chunked
constexpr impl::ChunkedFn iter::chunked {}
Definition at line 22 of file chunked.hpp.
Referenced by main(), and TEST_CASE().
combinations
constexpr impl::CombinationsFn iter::combinations {}
Definition at line 18 of file combinations.hpp.
Referenced by iter::impl::Powersetter< Container >::Iterator< ContainerT >::Iterator(), main(), iter::impl::Powersetter< Container >::Iterator< ContainerT >::operator++(), and TEST_CASE().
combinations_with_replacement
constexpr impl::CombinationsWithReplacementFn iter::combinations_with_replacement {}
Definition at line 18 of file combinations_with_replacement.hpp.
Referenced by main(), and TEST_CASE().
cycle
constexpr impl::CycleFn iter::cycle {}
Definition at line 18 of file cycle.hpp.
Referenced by main(), and TEST_CASE().
dropwhile
constexpr impl::DropWhileFn iter::dropwhile {}
Definition at line 19 of file dropwhile.hpp.
Referenced by main(), and TEST_CASE().
enumerate
constexpr impl::EnumerateFn iter::enumerate {}
Definition at line 36 of file enumerate.hpp.
Referenced by main(), and TEST_CASE().
filter
constexpr impl::FilterFn iter::filter {}
Definition at line 27 of file filter.hpp.
Referenced by main(), iter::impl::UniqueEverseenFn::operator()(), and TEST_CASE().
filterfalse
constexpr impl::FilterFalseFn iter::filterfalse {}
Definition at line 41 of file filterfalse.hpp.
Referenced by main(), and TEST_CASE().
groupby
constexpr impl::GroupByFn iter::groupby {}
Definition at line 30 of file groupby.hpp.
Referenced by main(), iter::impl::UniqueJustseenFn::operator()(), and TEST_CASE().
imap
constexpr impl::IMapFn iter::imap {}
Definition at line 20 of file imap.hpp.
Referenced by main(), iter::impl::UniqueJustseenFn::operator()(), and TEST_CASE().
permutations
constexpr impl::PermutationsFn iter::permutations {}
Definition at line 20 of file permutations.hpp.
Referenced by main(), and TEST_CASE().
powerset
constexpr impl::PowersetFn iter::powerset {}
Definition at line 21 of file powerset.hpp.
Referenced by main(), and TEST_CASE().
reversed
constexpr impl::ReversedFn iter::reversed {}
Definition at line 48 of file reversed.hpp.
Referenced by main(), and TEST_CASE().
slice
constexpr impl::SliceFn iter::slice {}
Definition at line 176 of file slice.hpp.
Referenced by main(), and TEST_CASE().
sliding_window
constexpr impl::SlidingWindowFn iter::sliding_window {}
Definition at line 18 of file sliding_window.hpp.
Referenced by main(), and TEST_CASE().
sorted
constexpr impl::SortedFn iter::sorted {}
Definition at line 18 of file sorted.hpp.
Referenced by main(), and TEST_CASE().
starmap
constexpr impl::StarMapFn iter::starmap {}
Definition at line 248 of file starmap.hpp.
Referenced by main(), iter::impl::IMapFn::operator()(), and TEST_CASE().
takewhile
constexpr impl::TakeWhileFn iter::takewhile {}
Definition at line 19 of file takewhile.hpp.
Referenced by main(), and TEST_CASE().
unique_everseen
constexpr impl::UniqueEverseenFn iter::unique_everseen {}
Definition at line 28 of file unique_everseen.hpp.
Referenced by main(), and TEST_CASE().
unique_justseen
constexpr impl::UniqueJustseenFn iter::unique_justseen {}
Definition at line 22 of file unique_justseen.hpp.
Referenced by main(), and TEST_CASE().