CkPttnCpp: iter::impl Namespace Reference
iter::impl Namespace Reference
Namespaces
detail
get_iters
Classes
class Accumulator
struct are_same
struct are_same< T, U, Ts... >
class ArrowProxy
struct BoolTester
class Chained
class ChainedFromIterable
class ChainMaker
class Chunker
class Combinator
class CombinatorWithReplacement
class Compressed
class Cycler
class DerefHolder
class DerefHolder< T & >
class Dropper
class Enumerable
class EnumIterYield
class Filtered
class FilterFalsed
class GroupProducer
struct HasConstDeref
struct HasConstDeref< T, std::void_t< decltype(*std::declval< const T & >())> >
struct Identity
struct IMapFn
struct is_random_access_iter
struct is_random_access_iter< T, std::enable_if_t< std::is_same< typename std::iterator_traits< T >::iterator_category, std::random_access_iterator_tag >::value > >
struct IsIterable
struct IsIterable< T, std::void_t< iterator_type< T > > >
class IteratorIterator
class IteratorWrapperImpl
struct IteratorWrapperImplType
struct IteratorWrapperImplType< Container, false >
struct IteratorWrapperImplType< Container, true >
class IterIterWrapper
struct IterToolFn
struct IterToolFnBindSizeTSecond
struct IterToolFnOptionalBindFirst
struct IterToolFnOptionalBindSecond
class Permuter
struct Pipeable
struct PipeableAndBindFirst
class Powersetter
class PredicateFlipper
class Productor
class Range
class Repeater
class RepeaterWithCount
struct ReverseIteratorWrapperImplType
struct ReverseIteratorWrapperImplType< Container, false >
struct ReverseIteratorWrapperImplType< Container, true >
class Reverser
class Sliced
struct SliceFn
class SortedView
struct StarMapFn
class StarMapper
class Taker
class TupleStarMapper
struct type_is
struct UniqueEverseenFn
struct UniqueJustseenFn
class WindowSlider
class Zipped
class ZippedLongest
Typedefs
using AccumulateFn = IterToolFnOptionalBindSecond< Accumulator, std::plus<> >
using ChainFromIterableFn = IterToolFn< ChainedFromIterable >
using ChunkedFn = IterToolFnBindSizeTSecond< Chunker >
using CombinationsFn = IterToolFnBindSizeTSecond< Combinator >
using CombinationsWithReplacementFn = IterToolFnBindSizeTSecond< CombinatorWithReplacement >
using CycleFn = IterToolFn< Cycler >
using DropWhileFn = IterToolFnOptionalBindFirst< Dropper, BoolTester >
template<typename Index , typename Elem >
using EnumBasePair = std::pair< Index, Elem >
using EnumerateFn = IterToolFnOptionalBindSecond< Enumerable, std::size_t >
using FilterFn = IterToolFnOptionalBindFirst< Filtered, BoolTester >
using FilterFalseFn = IterToolFnOptionalBindFirst< FilterFalsed, BoolTester >
using GroupByFn = IterToolFnOptionalBindSecond< GroupProducer, Identity >
template<typename TupleType >
using iterator_tuple_type = decltype(detail::iterator_tuple_type_helper(std::declval< TupleType >()))
template<typename TupleType >
using const_iterator_tuple_type = decltype(detail::const_iterator_tuple_type_helper(std::declval< TupleType >()))
template<typename TupleType >
using iterator_deref_tuple = decltype(detail::iterator_tuple_deref_helper(std::declval< TupleType >()))
template<typename TupleType >
using const_iterator_deref_tuple = decltype(detail::const_iterator_tuple_deref_helper(std::declval< TupleType >()))
template<typename Container >
using iterator_end_type = decltype(get_end(std::declval< Container & >()))
template<typename Container >
using IteratorWrapper = typename IteratorWrapperImplType< Container, std::is_same_v< impl::iterator_type< Container >, impl::iterator_end_type< Container > >>::type
template<typename T >
using AsConst = decltype(std::as_const(std::declval< T & >()))
template<typename T >
using iterator_type = decltype(get_begin(std::declval< T & >()))
template<typename Container >
using const_iterator_type = decltype(get_begin(std::declval< const std::remove_reference_t< Container > & >()))
template<typename Container >
using iterator_deref = decltype(*std::declval< iterator_type< Container > & >())
template<typename Container >
using const_iterator_deref = decltype(*std::declval< const iterator_type< Container > & >())
template<typename Container >
using const_iterator_type_deref = decltype(*std::declval< const_iterator_type< Container > & >())
template<typename Container >
using iterator_traits_deref = std::remove_reference_t< iterator_deref< Container > >
template<typename C >
using iterator_arrow = detail::arrow< iterator_type< C > >
template<typename T >
using has_random_access_iter = is_random_access_iter< iterator_type< T > >
using PermutationsFn = IterToolFn< Permuter >
using PowersetFn = IterToolFn< Powersetter >
template<typename Container >
using reverse_iterator_type = decltype(std::rbegin(std::declval< Container & >()))
template<typename Container >
using reverse_iterator_end_type = decltype(std::rend(std::declval< Container & >()))
template<typename Container >
using ReverseIteratorWrapper = typename ReverseIteratorWrapperImplType< Container, std::is_same_v< impl::reverse_iterator_type< Container >, impl::reverse_iterator_end_type< Container > >>::type
using ReversedFn = IterToolFn< Reverser >
using SlidingWindowFn = IterToolFnBindSizeTSecond< WindowSlider >
using SortedFn = IterToolFnOptionalBindSecond< SortedView, std::less<> >
using TakeWhileFn = IterToolFnOptionalBindFirst< Taker, BoolTester >
Functions
template<typename... Ts>
void absorb (Ts &&...)
template<typename T >
detail::arrow< T > apply_arrow (T &t)
template<typename InputIt , typename Distance = std::size_t>
void dumb_advance_unsafe (InputIt &iter, Distance distance)
template<typename Iter , typename EndIter , typename Distance >
void dumb_advance_impl (Iter &iter, const EndIter &end, Distance distance, std::false_type)
template<typename Iter , typename EndIter , typename Distance >
void dumb_advance_impl (Iter &iter, const EndIter &end, Distance distance, std::true_type)
template<typename Iter , typename EndIter , typename Distance = std::size_t>
void dumb_advance (Iter &iter, const EndIter &end, Distance distance)
template<typename ForwardIt , typename Distance = std::size_t>
ForwardIt dumb_next (ForwardIt it, Distance distance=1)
template<typename ForwardIt , typename Distance = std::size_t>
ForwardIt dumb_next (ForwardIt it, const ForwardIt &end, Distance distance=1)
template<typename Container , typename Distance = std::size_t>
Distance dumb_size (Container &&container)
template<typename TupleType , std::size_t... Is>
Productor< TupleType, Is... > product_impl (TupleType &&containers, std::index_sequence< Is... >)
template<std::size_t... Is, typename Container >
decltype(auto) product_repeat (std::index_sequence< Is... >, Container &&container)
template<std::size_t... Is, typename Container >
decltype(auto) product_repeat (std::index_sequence< Is... >, Container &container)
template<std::size_t... Is, typename Container >
decltype(auto) product_repeat (std::index_sequence< Is... >, const Container &container)
template<typename TupleType , std::size_t... Is>
Zipped< TupleType, Is... > zip_impl (TupleType &&, std::index_sequence< Is... >)
template<typename TupleType , std::size_t... Is>
ZippedLongest< TupleType, Is... > zip_longest_impl (TupleType &&, std::index_sequence< Is... >)
Variables
template<typename T >
constexpr bool is_iterable = IsIterable<T>::value
Typedef Documentation
AccumulateFn
using iter::impl::AccumulateFn = typedef IterToolFnOptionalBindSecond<Accumulator, std::plus<> >
Definition at line 18 of file accumulate.hpp.
AsConst
template<typename T > using iter::impl::AsConst = typedef decltype(std::as_const(std::declval<T&>()))
Definition at line 84 of file iterbase.hpp.
ChainFromIterableFn
using iter::impl::ChainFromIterableFn = typedef IterToolFn<ChainedFromIterable>
Definition at line 23 of file chain.hpp.
ChunkedFn
using iter::impl::ChunkedFn = typedef IterToolFnBindSizeTSecond<Chunker>
Definition at line 20 of file chunked.hpp.
CombinationsFn
using iter::impl::CombinationsFn = typedef IterToolFnBindSizeTSecond<Combinator>
Definition at line 16 of file combinations.hpp.
CombinationsWithReplacementFn
using iter::impl::CombinationsWithReplacementFn = typedef IterToolFnBindSizeTSecond<CombinatorWithReplacement>
Definition at line 16 of file combinations_with_replacement.hpp.
const_iterator_deref
template<typename Container > using iter::impl::const_iterator_deref = typedef decltype(*std::declval<const iterator_type<Container>&>())
Definition at line 110 of file iterbase.hpp.
const_iterator_deref_tuple
template<typename TupleType > using iter::impl::const_iterator_deref_tuple = typedef decltype(detail::const_iterator_tuple_deref_helper(std::declval<TupleType>()))
Definition at line 47 of file iter_tuples.hpp.
const_iterator_tuple_type
template<typename TupleType > using iter::impl::const_iterator_tuple_type = typedef decltype(detail::const_iterator_tuple_type_helper(std::declval<TupleType>()))
Definition at line 36 of file iter_tuples.hpp.
const_iterator_type
template<typename Container > using iter::impl::const_iterator_type = typedef decltype(get_begin(std::declval<const std::remove_reference_t<Container>&>()))
Definition at line 98 of file iterbase.hpp.
const_iterator_type_deref
template<typename Container > using iter::impl::const_iterator_type_deref = typedef decltype(*std::declval<const_iterator_type<Container>&>())
Definition at line 115 of file iterbase.hpp.
CycleFn
using iter::impl::CycleFn = typedef IterToolFn<Cycler>
Definition at line 16 of file cycle.hpp.
DropWhileFn
using iter::impl::DropWhileFn = typedef IterToolFnOptionalBindFirst<Dropper, BoolTester>
Definition at line 17 of file dropwhile.hpp.
EnumBasePair
template<typename Index , typename Elem > using iter::impl::EnumBasePair = typedef std::pair<Index, Elem>
Definition at line 17 of file enumerate.hpp.
EnumerateFn
using iter::impl::EnumerateFn = typedef IterToolFnOptionalBindSecond<Enumerable, std::size_t>
Definition at line 34 of file enumerate.hpp.
FilterFalseFn
using iter::impl::FilterFalseFn = typedef IterToolFnOptionalBindFirst<FilterFalsed, BoolTester>
Definition at line 39 of file filterfalse.hpp.
FilterFn
using iter::impl::FilterFn = typedef IterToolFnOptionalBindFirst<Filtered, BoolTester>
Definition at line 24 of file filter.hpp.
GroupByFn
using iter::impl::GroupByFn = typedef IterToolFnOptionalBindSecond<GroupProducer, Identity>
Definition at line 28 of file groupby.hpp.
has_random_access_iter
template<typename T > using iter::impl::has_random_access_iter = typedef is_random_access_iter<iterator_type<T> >
Definition at line 198 of file iterbase.hpp.
iterator_arrow
template<typename C > using iter::impl::iterator_arrow = typedef detail::arrow<iterator_type<C> >
Definition at line 162 of file iterbase.hpp.
iterator_deref
template<typename Container > using iter::impl::iterator_deref = typedef decltype(*std::declval<iterator_type<Container>&>())
Definition at line 103 of file iterbase.hpp.
iterator_deref_tuple
template<typename TupleType > using iter::impl::iterator_deref_tuple = typedef decltype(detail::iterator_tuple_deref_helper(std::declval<TupleType>()))
Definition at line 43 of file iter_tuples.hpp.
iterator_end_type
template<typename Container > using iter::impl::iterator_end_type = typedef decltype(get_end(std::declval<Container&>()))
Definition at line 13 of file iterator_wrapper.hpp.
iterator_traits_deref
template<typename Container > using iter::impl::iterator_traits_deref = typedef std::remove_reference_t<iterator_deref<Container> >
Definition at line 119 of file iterbase.hpp.
iterator_tuple_type
template<typename TupleType > using iter::impl::iterator_tuple_type = typedef decltype(detail::iterator_tuple_type_helper(std::declval<TupleType>()))
Definition at line 32 of file iter_tuples.hpp.
iterator_type
template<typename T > using iter::impl::iterator_type = typedef decltype(get_begin(std::declval<T&>()))
Definition at line 93 of file iterbase.hpp.
IteratorWrapper
template<typename Container > using iter::impl::IteratorWrapper = typedef typename IteratorWrapperImplType<Container, std::is_same_v<impl::iterator_type<Container>, impl::iterator_end_type<Container> >>::type
Definition at line 36 of file iterator_wrapper.hpp.
PermutationsFn
using iter::impl::PermutationsFn = typedef IterToolFn<Permuter>
Definition at line 18 of file permutations.hpp.
PowersetFn
using iter::impl::PowersetFn = typedef IterToolFn<Powersetter>
Definition at line 19 of file powerset.hpp.
reverse_iterator_end_type
template<typename Container > using iter::impl::reverse_iterator_end_type = typedef decltype(std::rend(std::declval<Container&>()))
Definition at line 17 of file reversed.hpp.
reverse_iterator_type
template<typename Container > using iter::impl::reverse_iterator_type = typedef decltype(std::rbegin(std::declval<Container&>()))
Definition at line 14 of file reversed.hpp.
ReversedFn
using iter::impl::ReversedFn = typedef IterToolFn<Reverser>
Definition at line 46 of file reversed.hpp.
ReverseIteratorWrapper
template<typename Container > using iter::impl::ReverseIteratorWrapper = typedef typename ReverseIteratorWrapperImplType<Container, std::is_same_v<impl::reverse_iterator_type<Container>, impl:: reverse_iterator_end_type<Container> >>:: type
Definition at line 41 of file reversed.hpp.
SlidingWindowFn
using iter::impl::SlidingWindowFn = typedef IterToolFnBindSizeTSecond<WindowSlider>
Definition at line 16 of file sliding_window.hpp.
SortedFn
using iter::impl::SortedFn = typedef IterToolFnOptionalBindSecond<SortedView, std::less<> >
Definition at line 16 of file sorted.hpp.
TakeWhileFn
using iter::impl::TakeWhileFn = typedef IterToolFnOptionalBindFirst<Taker, BoolTester>
Definition at line 17 of file takewhile.hpp.
Function Documentation
absorb()
template<typename... Ts> void iter::impl::absorb (Ts && ...)
Definition at line 53 of file iter_tuples.hpp.
Referenced by iter::impl::Zipped< TupleType, Is >::Iterator< TupleTypeT, IteratorTuple, TupleDeref >::operator++(), and iter::impl::ZippedLongest< TupleType, Is >::Iterator< TupleTypeT, IterTuple, OptTempl >::operator++().
apply_arrow()
template<typename T > detail::arrow<T> iter::impl::apply_arrow (T & t)
Definition at line 167 of file iterbase.hpp.
Referenced by iter::impl::Chained< TupType, Is >::IteratorData< TupTypeT >::get_and_arrow(), iter::impl::Cycler< Container >::Iterator< ContainerT >::operator->(), iter::impl::Sliced< Container, DifferenceType >::Iterator< ContainerT >::operator->(), iter::impl::IteratorWrapperImpl< SubIter, SubEnd >::operator->(), iter::impl::Compressed< Container, Selector >::Iterator< ContainerT, SelectorT >::operator->(), iter::impl::Powersetter< Container >::Iterator< ContainerT >::operator->(), iter::impl::Reverser< Container >::Iterator< ContainerT >::operator->(), iter::impl::ChainedFromIterable< Container >::Iterator< ContainerT >::operator->(), and TEST_CASE().
dumb_advance()
template<typename Iter , typename EndIter , typename Distance = std::size_t> void iter::impl::dumb_advance (Iter & iter, const EndIter & end, Distance distance)
Definition at line 229 of file iterbase.hpp.
References dumb_advance_impl().
Referenced by iter::impl::Sliced< Container, DifferenceType >::begin(), dumb_next(), iter::impl::Combinator< Container >::Iterator< ContainerT >::Iterator(), and iter::impl::Sliced< Container, DifferenceType >::Iterator< ContainerT >::operator++().
dumb_advance_impl() [1/2]
template<typename Iter , typename EndIter , typename Distance > void iter::impl::dumb_advance_impl (Iter & iter, const EndIter & end, Distance distance, std::false_type)
Definition at line 210 of file iterbase.hpp.
References NS1::end(), and i.
Referenced by dumb_advance().
dumb_advance_impl() [2/2]
template<typename Iter , typename EndIter , typename Distance > void iter::impl::dumb_advance_impl (Iter & iter, const EndIter & end, Distance distance, std::true_type)
Definition at line 218 of file iterbase.hpp.
References NS1::end().
dumb_advance_unsafe()
template<typename InputIt , typename Distance = std::size_t> void iter::impl::dumb_advance_unsafe (InputIt & iter, Distance distance)
Definition at line 203 of file iterbase.hpp.
References i.
Referenced by dumb_next(), and TEST_CASE().
dumb_next() [1/2]
template<typename ForwardIt , typename Distance = std::size_t> ForwardIt iter::impl::dumb_next (ForwardIt it, Distance distance = 1)
Definition at line 234 of file iterbase.hpp.
References dumb_advance_unsafe().
Referenced by iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::operator++(), iter::impl::Combinator< Container >::Iterator< ContainerT >::operator++(), and TEST_CASE().
dumb_next() [2/2]
template<typename ForwardIt , typename Distance = std::size_t> ForwardIt iter::impl::dumb_next (ForwardIt it, const ForwardIt & end, Distance distance = 1)
Definition at line 240 of file iterbase.hpp.
References dumb_advance().
dumb_size()
template<typename Container , typename Distance = std::size_t> Distance iter::impl::dumb_size (Container && container)
Definition at line 247 of file iterbase.hpp.
References iter::impl::get_iters::get_begin(), and iter::impl::get_iters::get_end().
Referenced by iter::impl::Powersetter< Container >::end(), and TEST_CASE().
product_impl()
template<typename TupleType , std::size_t... Is> Productor< TupleType, Is... > iter::impl::product_impl (TupleType && containers, std::index_sequence< Is... >)
Definition at line 185 of file product.hpp.
Referenced by iter::product().
product_repeat() [1/3]
template<std::size_t... Is, typename Container > decltype(auto) iter::impl::product_repeat (std::index_sequence< Is... > , Container && container)
Definition at line 207 of file product.hpp.
References iter::product().
Referenced by iter::product().
product_repeat() [2/3]
template<std::size_t... Is, typename Container > decltype(auto) iter::impl::product_repeat (std::index_sequence< Is... > , Container & container)
Definition at line 213 of file product.hpp.
References iter::product().
product_repeat() [3/3]
template<std::size_t... Is, typename Container > decltype(auto) iter::impl::product_repeat (std::index_sequence< Is... > , const Container & container)
Definition at line 219 of file product.hpp.
References iter::product().
zip_impl()
template<typename TupleType , std::size_t... Is> Zipped<TupleType, Is...> iter::impl::zip_impl (TupleType && , std::index_sequence< Is... >)
Referenced by iter::impl::Zipped< TupleType, Is >::end(), and iter::zip().
zip_longest_impl()
template<typename TupleType , std::size_t... Is> ZippedLongest<TupleType, Is...> iter::impl::zip_longest_impl (TupleType && , std::index_sequence< Is... >)
Referenced by iter::impl::ZippedLongest< TupleType, Is >::end(), and iter::zip_longest().
Variable Documentation
is_iterable
template<typename T > constexpr bool iter::impl::is_iterable = IsIterable<T>::value
Definition at line 129 of file iterbase.hpp.
Referenced by TEST_CASE().