CkPttnCpp: lib/bench/one_example.cpp File Reference
one_example.cpp File Reference
#include "benchmark/benchmark.h"
#include <set>
#include <vector>
Functions
static void BM_VectorInsert (benchmark::State &state)
BENCHMARK (BM_VectorInsert) -> Range(2, 2<< 3)
static void BM_SetInsert (benchmark::State &state)
BENCHMARK (BM_SetInsert) -> Range(2, 2<< 3)
BENCHMARK_MAIN ()
Function Documentation
BENCHMARK() [1/2]
BENCHMARK (BM_VectorInsert) -> Range(2, 2<< 3)
Referenced by BM_SetInsert(), and BM_VectorInsert().
BENCHMARK() [2/2]
BENCHMARK (BM_SetInsert) -> Range(2, 2<< 3)
BENCHMARK_MAIN()
BENCHMARK_MAIN ()
Referenced by BM_SetInsert().
BM_SetInsert()
static void BM_SetInsert (benchmark::State & state) static
Definition at line 23 of file one_example.cpp.
References BENCHMARK(), and BENCHMARK_MAIN().
BM_VectorInsert()
static void BM_VectorInsert (benchmark::State & state) static
Definition at line 5 of file one_example.cpp.
References BENCHMARK().