CkPttnCpp: lib/src/readwrite.cpp File Reference
readwrite.cpp File Reference
#include <ckpttncpp/netlist.hpp>
#include <climits>
#include <fstream>
#include <iostream>
#include <py2cpp/py2cpp.hpp>
#include <utility>
#include <vector>
Functions
void writeJSON (const char *jsonFileName, const SimpleNetlist &H)
SimpleNetlist readNetD (const char *netDFileName)
void readAre (SimpleNetlist &H, const char *areFileName)
Function Documentation
readAre()
void readAre (SimpleNetlist & H, const char * areFileName)
Definition at line 173 of file readwrite.cpp.
References Netlist< nodeview_t, nodemap_t >::module_weight, Netlist< nodeview_t, nodemap_t >::num_pads, and Netlist< nodeview_t, nodemap_t >::number_of_modules().
Referenced by TEST_CASE().
readNetD()
SimpleNetlist readNetD (const char * netDFileName)
Definition at line 63 of file readwrite.cpp.
References Netlist< nodeview_t, nodemap_t >::num_pads, and R.
Referenced by TEST_CASE().
writeJSON()
void writeJSON (const char * jsonFileName, const SimpleNetlist & H)
Definition at line 18 of file readwrite.cpp.
References Netlist< nodeview_t, nodemap_t >::G, Netlist< nodeview_t, nodemap_t >::modules, Netlist< nodeview_t, nodemap_t >::num_pads, Netlist< nodeview_t, nodemap_t >::number_of_modules(), and Netlist< nodeview_t, nodemap_t >::number_of_nets().
Referenced by TEST_CASE().