CkPttnCpp: FMBiGainMgr Struct Reference
FMBiGainMgr Struct Reference
FMBiGainMgr.
#include <FMBiGainMgr.hpp>
Public Types
using Base = FMGainMgr< FMBiGainCalc, FMBiGainMgr >
using GainCalc_ = FMBiGainCalc
using index_t = typename SimpleNetlist::index_t
Public Member Functions
FMBiGainMgr (SimpleNetlist &H)
FMBiGainMgr (SimpleNetlist &H, uint8_t)
Construct a new FMBiGainMgr object.
auto init (const std::vector< uint8_t > &part) -> int
auto modify_key (index_t i_w, uint8_t part_w, int key) -> void
(needed by base class)
auto update_move_v (const MoveInfoV &move_info_v, int gain) -> void
auto lock (uint8_t whichPart, index_t i_v) -> void
lock
auto lock_all (uint8_t fromPart, index_t i_v) -> void
lock_all
Public Member Functions inherited from FMGainMgr< FMBiGainCalc, FMBiGainMgr >
FMGainMgr (SimpleNetlist &H, uint8_t K)
Construct a new FMGainMgr object.
auto init (const std::vector< uint8_t > &part) -> int
auto is_empty_togo (uint8_t toPart) const -> bool
auto is_empty () const -> bool
auto select (const std::vector< uint8_t > &part) -> std::tuple< MoveInfoV, int >
auto select_togo (uint8_t toPart) -> std::tuple< index_t, int >
auto update_move (const std::vector< uint8_t > &part, const MoveInfoV &move_info_v) -> void
Private Member Functions
auto __set_key (uint8_t whichPart, index_t i_v, int key) -> void
Set the key object.
Additional Inherited Members
Public Attributes inherited from FMGainMgr< FMBiGainCalc, FMBiGainMgr >
uint8_t K
Protected Attributes inherited from FMGainMgr< FMBiGainCalc, FMBiGainMgr >
dllink< index_t > waitinglist
SimpleNetlist & H
FMBiGainCalc gainCalc
size_t pmax
std::vector< bpqueue< int > > gainbucket
Detailed Description
FMBiGainMgr.
Definition at line 12 of file FMBiGainMgr.hpp.
Member Typedef Documentation
Base
using FMBiGainMgr::Base = FMGainMgr<FMBiGainCalc, FMBiGainMgr>
Definition at line 14 of file FMBiGainMgr.hpp.
GainCalc_
using FMBiGainMgr::GainCalc_ = FMBiGainCalc
Definition at line 15 of file FMBiGainMgr.hpp.
index_t
using FMBiGainMgr::index_t = typename SimpleNetlist::index_t
Definition at line 16 of file FMBiGainMgr.hpp.
Constructor & Destructor Documentation
FMBiGainMgr() [1/2]
FMBiGainMgr::FMBiGainMgr (SimpleNetlist & H) inline
Definition at line 18 of file FMBiGainMgr.hpp.
References FMGainMgr< FMBiGainCalc, FMBiGainMgr >::H.
FMBiGainMgr() [2/2]
FMBiGainMgr::FMBiGainMgr (SimpleNetlist & H, uint8_t) inline explicit
Construct a new FMBiGainMgr object.
Parameters
H
Definition at line 25 of file FMBiGainMgr.hpp.
References FMGainMgr< FMBiGainCalc, FMBiGainMgr >::H, and init().
Member Function Documentation
__set_key()
auto FMBiGainMgr::__set_key (uint8_t whichPart, index_t i_v, int key) -> void inline private
Set the key object.
Parameters
whichPart
v
key
Definition at line 94 of file FMBiGainMgr.hpp.
References FMGainMgr< FMBiGainCalc, FMBiGainMgr >::gainbucket, FMGainMgr< FMBiGainCalc, FMBiGainMgr >::gainCalc, and FMBiGainCalc::vertex_list.
Referenced by update_move_v().
init()
auto FMBiGainMgr::init (const std::vector< uint8_t > & part) -> int
Parameters
part
Returns
int
Parameters
part
Definition at line 9 of file FMBiGainMgr2.cpp.
Referenced by FMBiGainMgr().
lock()
auto FMBiGainMgr::lock (uint8_t whichPart, index_t i_v) -> void inline
lock
Parameters
whichPart
v
Definition at line 67 of file FMBiGainMgr.hpp.
References FMGainMgr< FMBiGainCalc, FMBiGainMgr >::gainbucket, FMGainMgr< FMBiGainCalc, FMBiGainMgr >::gainCalc, and FMBiGainCalc::vertex_list.
Referenced by lock_all().
lock_all()
auto FMBiGainMgr::lock_all (uint8_t fromPart, index_t i_v) -> void inline
lock_all
Parameters
fromPart
v
Definition at line 80 of file FMBiGainMgr.hpp.
References lock().
modify_key()
auto FMBiGainMgr::modify_key (index_t i_w, uint8_t part_w, int key) -> void inline
(needed by base class)
Parameters
part
w
key
Definition at line 42 of file FMBiGainMgr.hpp.
References FMGainMgr< FMBiGainCalc, FMBiGainMgr >::gainbucket, FMGainMgr< FMBiGainCalc, FMBiGainMgr >::gainCalc, and FMBiGainCalc::vertex_list.
update_move_v()
auto FMBiGainMgr::update_move_v (const MoveInfoV & move_info_v, int gain) -> void inline
Parameters
part
move_info_v
gain
Definition at line 54 of file FMBiGainMgr.hpp.
References __set_key().
The documentation for this struct was generated from the following files:
lib/include/ckpttncpp/FMBiGainMgr.hpp
lib/src/FMBiGainMgr2.cpp