CkPttnCpp: lib/test/src/test_range.cpp File Reference
test_range.cpp File Reference
#include <array>
#include <catch2/catch.hpp>
#include <py2cpp/py2cpp.hpp>
Functions
TEST_CASE ("Test Range", "[range]")
TEST_CASE ("Test Range2", "[range]")
CHECK (!R.empty())
CHECK (R.contains('B'))
CHECK (R[3]=='D')
for (auto a :R)
CHECK (count==R.size())
CHECK (R.contains(&A+2))
CHECK (R[1]==&A+1)
for ([[maybe_unused]] auto _ :R)
Variables
auto count = 0
auto R = py::range(&A, &A + 4)
Function Documentation
CHECK() [1/6]
CHECK (!R. empty())
Referenced by for(), run_FMBiPartMgr(), run_FMKWayPartMgr(), and TEST_CASE().
CHECK() [2/6]
CHECK (R. contains 'B')
CHECK() [3/6]
CHECK (R [3] = ='D')
CHECK() [4/6]
CHECK (count = =R.size())
CHECK() [5/6]
CHECK (R.contains &+ 2A)
CHECK() [6/6]
CHECK (R [1] = =&A+1)
for() [1/2]
for (auto a :R)
Definition at line 46 of file test_range.cpp.
References CHECK(), count, and TEST_CASE().
for() [2/2]
for ([[maybe_unused] ] auto _ :R)
Definition at line 63 of file test_range.cpp.
References CHECK(), and count.
TEST_CASE() [1/2]
TEST_CASE ("Test Range" , "" [range])
Definition at line 5 of file test_range.cpp.
References CHECK(), count, R, and py::range().
Referenced by for(), and TEST_CASE().
TEST_CASE() [2/2]
TEST_CASE ("Test Range2" , "" [range])
Definition at line 21 of file test_range.cpp.
References CHECK(), count, R, py::range(), and TEST_CASE().
Variable Documentation
count
auto count = 0
Definition at line 45 of file test_range.cpp.
Referenced by for(), and TEST_CASE().
R
auto R = py::range(&A, &A + 4)
Definition at line 56 of file test_range.cpp.
Referenced by create_contraction_subgraph(), create_test_netlist(), readNetD(), and TEST_CASE().