CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_groupby.cpp File Reference
test_groupby.cpp File Reference
#include <groupby.hpp>
#include "helpers.hpp"
#include <iterator>
#include <string>
#include <vector>
#include "catch.hpp"
Typedefs
template<typename T , typename U >
using ImpT = decltype(groupby(std::declval< T >(), std::declval< U >()))
Functions
TEST_CASE ("groupby: works with lambda, callable, and function pointer")
TEST_CASE ("groupby: handles pointer to member function", "[groupby]")
TEST_CASE ("groupby: handles pointer to data member", "[groupby]")
TEST_CASE ("groupby: const iteration", "[groupby][const]")
TEST_CASE ("groupby: iterators compare equal to non-const iterators", "[groupby][const]")
TEST_CASE ("groupby: Works with different begin and end types", "[groupby]")
TEST_CASE ("groupby: groups can be skipped completely", "[groupby]")
TEST_CASE ("groupby: groups can be skipped partially", "[groupby]")
TEST_CASE ("groupby: single argument uses elements as keys", "[groupby]")
TEST_CASE ("groupby: empty iterable yields nothing", "[groupby]")
TEST_CASE ("groupby: inner iterator (group) not used", "[groupby]")
TEST_CASE ("groupby: doesn't double dereference", "[groupby]")
TEST_CASE ("grouby: iterator doesn't need to be dereferenced before advanced", "[groupby]")
TEST_CASE ("groupby: iterator can be dereferenced multiple times", "[groupby]")
TEST_CASE ("groupby: copy constructed iterators behave as expected", "[groupby]")
TEST_CASE ("groupby: operator-> on both iterator types", "[groupby]")
TEST_CASE ("groupby: iterator and groupiterator are correct", "[groupby]")
TEST_CASE ("groupby: has correct ctor and assign ops", "[groupby]")
Typedef Documentation
ImpT
template<typename T , typename U > using ImpT = decltype(groupby(std::declval<T>(), std::declval<U>()))
Definition at line 364 of file test_groupby.cpp.
Function Documentation
TEST_CASE() [1/18]
TEST_CASE ("groupby: works with lambda, callable , and function pointer")
Definition at line 28 of file test_groupby.cpp.
References NS1::begin(), NS1::end(), and iter::groupby.
TEST_CASE() [2/18]
TEST_CASE ("groupby: handles pointer to member function" , "" [groupby])
Definition at line 74 of file test_groupby.cpp.
References NS1::begin(), NS1::end(), iter::groupby, and itertest::Integer::is_positive().
TEST_CASE() [3/18]
TEST_CASE ("groupby: handles pointer to data member" , "" [groupby])
Definition at line 91 of file test_groupby.cpp.
References NS1::begin(), NS1::end(), and iter::groupby.
TEST_CASE() [4/18]
TEST_CASE ("groupby: const iteration" , "" [groupby][const ])
Definition at line 124 of file test_groupby.cpp.
References NS1::begin(), NS1::end(), and iter::groupby.
TEST_CASE() [5/18]
TEST_CASE ("groupby: iterators compare equal to non-const iterators" , "" [groupby][const ])
Definition at line 174 of file test_groupby.cpp.
References NS1::begin(), NS1::end(), and iter::groupby.
TEST_CASE() [6/18]
TEST_CASE ("groupby: Works with different begin and end types" , "" [groupby])
Definition at line 191 of file test_groupby.cpp.
References NS1::begin(), NS1::end(), and iter::groupby.
TEST_CASE() [7/18]
TEST_CASE ("groupby: groups can be skipped completely" , "" [groupby])
Definition at line 205 of file test_groupby.cpp.
References NS1::begin(), NS1::end(), and iter::groupby.
TEST_CASE() [8/18]
TEST_CASE ("groupby: groups can be skipped partially" , "" [groupby])
Definition at line 227 of file test_groupby.cpp.
References NS1::begin(), NS1::end(), and iter::groupby.
TEST_CASE() [9/18]
TEST_CASE ("groupby: single argument uses elements as keys" , "" [groupby])
Definition at line 252 of file test_groupby.cpp.
References NS1::begin(), NS1::end(), and iter::groupby.
TEST_CASE() [10/18]
TEST_CASE ("groupby: empty iterable yields nothing" , "" [groupby])
Definition at line 284 of file test_groupby.cpp.
References NS1::begin(), NS1::end(), and iter::groupby.
TEST_CASE() [11/18]
TEST_CASE ("groupby: inner iterator (group) not used" , "" [groupby])
Definition at line 290 of file test_groupby.cpp.
References iter::groupby.
TEST_CASE() [12/18]
TEST_CASE ("groupby: doesn't double dereference" , "" [groupby])
Definition at line 300 of file test_groupby.cpp.
References iter::groupby, and i.
TEST_CASE() [13/18]
TEST_CASE ("grouby: iterator doesn't need to be dereferenced before advanced" , "" [groupby])
Definition at line 309 of file test_groupby.cpp.
References NS1::begin(), and iter::groupby.
TEST_CASE() [14/18]
TEST_CASE ("groupby: iterator can be dereferenced multiple times" , "" [groupby])
Definition at line 318 of file test_groupby.cpp.
References NS1::begin(), and iter::groupby.
TEST_CASE() [15/18]
TEST_CASE ("groupby: copy constructed iterators behave as expected" , "" [groupby])
Definition at line 327 of file test_groupby.cpp.
References NS1::begin(), and iter::groupby.
TEST_CASE() [16/18]
TEST_CASE ("groupby: operator-> on both iterator types" , "" [groupby])
Definition at line 344 of file test_groupby.cpp.
References NS1::begin(), and iter::groupby.
TEST_CASE() [17/18]
TEST_CASE ("groupby: iterator and groupiterator are correct" , "" [groupby])
Definition at line 353 of file test_groupby.cpp.
References NS1::begin(), and iter::groupby.
TEST_CASE() [18/18]
TEST_CASE ("groupby: has correct ctor and assign ops" , "" [groupby])
Definition at line 365 of file test_groupby.cpp.