CkPttnCpp: lib/test/src/test_FMBiGainMgr.cpp File Reference
test_FMBiGainMgr.cpp File Reference
#include <catch2/catch.hpp>
#include <ckpttncpp/FMBiGainMgr.hpp>
#include <ckpttncpp/netlist.hpp>
Functions
SimpleNetlist create_test_netlist ()
Create a test netlist object.
SimpleNetlist create_dwarf ()
Create a test netlist object.
void run_FMBiGainMgr (SimpleNetlist &H, gsl::span< uint8_t > part)
TEST_CASE ("Test FMBiGainMgr", "[test_FMBiGainMgr]")
TEST_CASE ("Test FMBiGainMgr 2", "[test_FMBiGainMgr2]")
Function Documentation
create_dwarf()
SimpleNetlist create_dwarf () -> SimpleNetlist
Create a test netlist object.
Returns
Netlist
Definition at line 18 of file test_netlist.cpp.
Referenced by TEST_CASE().
create_test_netlist()
SimpleNetlist create_test_netlist () -> SimpleNetlist
Create a test netlist object.
Returns
Netlist
Definition at line 79 of file test_netlist.cpp.
Referenced by TEST_CASE().
run_FMBiGainMgr()
void run_FMBiGainMgr (SimpleNetlist & H, gsl::span< uint8_t > part)
Parameters
H
part_test
Definition at line 14 of file test_FMBiGainMgr.cpp.
Referenced by TEST_CASE().
TEST_CASE() [1/2]
TEST_CASE ("Test FMBiGainMgr" , "" [test_FMBiGainMgr])
Definition at line 34 of file test_FMBiGainMgr.cpp.
References create_test_netlist(), and run_FMBiGainMgr().
TEST_CASE() [2/2]
TEST_CASE ("Test FMBiGainMgr 2" , "" [test_FMBiGainMgr2])
Definition at line 41 of file test_FMBiGainMgr.cpp.
References create_dwarf(), and run_FMBiGainMgr().