CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_slice.cpp File Reference
test_slice.cpp File Reference
#include <slice.hpp>
#include <string>
#include <utility>
#include <vector>
#include "catch.hpp"
#include "helpers.hpp"
Typedefs
using Vec = const std::vector< int >
template<typename T >
using ImpT = decltype(slice(std::declval< T >(), 1))
Functions
TEST_CASE ("slice: take from beginning", "[slice]")
TEST_CASE ("slice: const iteration", "[slice][const]")
TEST_CASE ("slice: const iterator can be compared to non-const iterator", "[slice][const]")
TEST_CASE ("slice: start and stop", "[slice]")
TEST_CASE ("slice: Works with different begin and end types", "[slice]")
TEST_CASE ("slice: start, stop, step", "[slice]")
TEST_CASE ("slice: empty iterable", "[slice]")
TEST_CASE ("slice: stop is beyond end of iterable", "[slice]")
TEST_CASE ("slice: start is beyond end of iterable", "[slice]")
TEST_CASE ("slice: (stop - start) % step != 0", "[slice]")
TEST_CASE ("slice: invalid ranges give 0 size slices", "[slice]")
TEST_CASE ("slice: moves rvalues and binds to lvalues", "[slice]")
TEST_CASE ("slice: with iterable doesn't move or copy elems", "[slice]")
TEST_CASE ("slice: iterator meets requirements", "[slice]")
TEST_CASE ("slice: has correct ctor and assign ops", "[slice]")
Typedef Documentation
ImpT
template<typename T > using ImpT = decltype(slice(std::declval<T>(), 1))
Definition at line 157 of file test_slice.cpp.
Vec
using Vec = const std::vector<int>
Definition at line 11 of file test_slice.cpp.
Function Documentation
TEST_CASE() [1/15]
TEST_CASE ("slice: take from beginning" , "" [slice])
Definition at line 13 of file test_slice.cpp.
References NS1::begin(), NS1::end(), and iter::slice.
TEST_CASE() [2/15]
TEST_CASE ("slice: const iteration" , "" [slice][const ])
Definition at line 30 of file test_slice.cpp.
References NS1::begin(), NS1::end(), and iter::slice.
TEST_CASE() [3/15]
TEST_CASE ("slice: const iterator can be compared to non-const iterator" , "" [slice][const ])
Definition at line 40 of file test_slice.cpp.
References NS1::begin(), NS1::end(), and iter::slice.
TEST_CASE() [4/15]
TEST_CASE ("slice: start and stop" , "" [slice])
Definition at line 47 of file test_slice.cpp.
References NS1::begin(), NS1::end(), and iter::slice.
TEST_CASE() [5/15]
TEST_CASE ("slice: Works with different begin and end types" , "" [slice])
Definition at line 64 of file test_slice.cpp.
References NS1::begin(), NS1::end(), and iter::slice.
TEST_CASE() [6/15]
TEST_CASE ("slice: start, stop , step" , "" [slice])
Definition at line 72 of file test_slice.cpp.
References NS1::begin(), NS1::end(), and iter::slice.
TEST_CASE() [7/15]
TEST_CASE ("slice: empty iterable" , "" [slice])
Definition at line 89 of file test_slice.cpp.
References NS1::begin(), NS1::end(), and iter::slice.
TEST_CASE() [8/15]
TEST_CASE ("slice: stop is beyond end of iterable" , "" [slice])
Definition at line 95 of file test_slice.cpp.
References NS1::begin(), NS1::end(), and iter::slice.
TEST_CASE() [9/15]
TEST_CASE ("slice: start is beyond end of iterable" , "" [slice])
Definition at line 103 of file test_slice.cpp.
References NS1::begin(), NS1::end(), and iter::slice.
TEST_CASE() [10/15]
TEST_CASE ()
Definition at line 109 of file test_slice.cpp.
References NS1::begin(), NS1::end(), and iter::slice.
TEST_CASE() [11/15]
TEST_CASE ("slice: invalid ranges give 0 size slices" , "" [slice])
Definition at line 118 of file test_slice.cpp.
References NS1::begin(), NS1::end(), and iter::slice.
TEST_CASE() [12/15]
TEST_CASE ("slice: moves rvalues and binds to lvalues" , "" [slice])
Definition at line 130 of file test_slice.cpp.
References NS1::begin(), NS1::end(), and iter::slice.
TEST_CASE() [13/15]
TEST_CASE ("slice: with iterable doesn't move or copy elems" , "" [slice])
Definition at line 143 of file test_slice.cpp.
References i, and iter::slice.
TEST_CASE() [14/15]
TEST_CASE ("slice: iterator meets requirements" , "" [slice])
Definition at line 150 of file test_slice.cpp.
References NS1::begin(), and iter::slice.
TEST_CASE() [15/15]
TEST_CASE ("slice: has correct ctor and assign ops" , "" [slice])
Definition at line 158 of file test_slice.cpp.