CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_dropwhile.cpp File Reference
test_dropwhile.cpp File Reference
#include <dropwhile.hpp>
#include "helpers.hpp"
#include <iterator>
#include <string>
#include <vector>
#include "catch.hpp"
Typedefs
using Vec = const std::vector< int >
template<typename T , typename U >
using ImpT = decltype(dropwhile(std::declval< T >(), std::declval< U >()))
Functions
TEST_CASE ("dropwhile: skips initial elements", "[dropwhile]")
TEST_CASE ("dropwhile: handles pointer to member", "[dropwhile]")
TEST_CASE ("dropwhile: drop zeros from front", "[dropwhile]")
TEST_CASE ("dropwhile: const iteration", "[dropwhile][const]")
TEST_CASE ("dropwhile: const iterators can be compared to non-const iterators", "[dropwhile][const]")
TEST_CASE ("dropwhile: Works with different begin and end types", "[dropwhile]")
TEST_CASE ("dropwhile: doesn't skip anything if it shouldn't", "[dropwhile]")
TEST_CASE ("dropwhile: skips all elements when all are true under predicate", "[dropwhile]")
TEST_CASE ("dropwhile: identity", "[dropwhile]")
TEST_CASE ("dropwhile: empty case is empty", "[dropwhile]")
TEST_CASE ("dropwhile: only drops from beginning", "[dropwhile]")
TEST_CASE ("dropwhile: operator->", "[dropwhile]")
TEST_CASE ("dropwhile: works with function pointer", "[dropwhile]")
TEST_CASE ("dropwhile: binds to lvalues, moves rvalues", "[dropwhile]")
TEST_CASE ("dropwhile: doesn't move or copy elements of iterable", "[dropwhile]")
TEST_CASE ("dropwhile: iterator meets requirements", "[dropwhile]")
TEST_CASE ("dropwhile: has correct ctor and assign ops", "[dropwhile]")
Typedef Documentation
ImpT
template<typename T , typename U > using ImpT = decltype(dropwhile(std::declval<T>(), std::declval<U>()))
Definition at line 182 of file test_dropwhile.cpp.
Vec
using Vec = const std::vector<int>
Definition at line 13 of file test_dropwhile.cpp.
Function Documentation
TEST_CASE() [1/17]
TEST_CASE ("dropwhile: skips initial elements" , "" [dropwhile])
Definition at line 29 of file test_dropwhile.cpp.
References NS1::begin(), iter::dropwhile, NS1::end(), and i.
TEST_CASE() [2/17]
TEST_CASE ("dropwhile: handles pointer to member" , "" [dropwhile])
Definition at line 44 of file test_dropwhile.cpp.
References NS1::begin(), iter::dropwhile, and NS1::end().
TEST_CASE() [3/17]
TEST_CASE ("dropwhile: drop zeros from front" , "" [dropwhile])
Definition at line 63 of file test_dropwhile.cpp.
References NS1::begin(), iter::dropwhile, and NS1::end().
TEST_CASE() [4/17]
TEST_CASE ("dropwhile: const iteration" , "" [dropwhile][const ])
Definition at line 72 of file test_dropwhile.cpp.
References NS1::begin(), iter::dropwhile, and NS1::end().
TEST_CASE() [5/17]
TEST_CASE ("dropwhile: const iterators can be compared to non-const iterators" , "" [dropwhile][const ])
Definition at line 80 of file test_dropwhile.cpp.
References NS1::begin(), iter::dropwhile, and NS1::end().
TEST_CASE() [6/17]
TEST_CASE ("dropwhile: Works with different begin and end types" , "" [dropwhile])
Definition at line 87 of file test_dropwhile.cpp.
References iter::dropwhile.
TEST_CASE() [7/17]
TEST_CASE ("dropwhile: doesn't skip anything if it shouldn't" , "" [dropwhile])
Definition at line 96 of file test_dropwhile.cpp.
References NS1::begin(), iter::dropwhile, NS1::end(), and i.
TEST_CASE() [8/17]
TEST_CASE ("dropwhile: skips all elements when all are true under predicate" , "" [dropwhile])
Definition at line 104 of file test_dropwhile.cpp.
References NS1::begin(), iter::dropwhile, NS1::end(), and i.
TEST_CASE() [9/17]
TEST_CASE ("dropwhile: identity" , "" [dropwhile])
Definition at line 111 of file test_dropwhile.cpp.
References NS1::begin(), iter::dropwhile, and NS1::end().
TEST_CASE() [10/17]
TEST_CASE ("dropwhile: empty case is empty" , "" [dropwhile])
Definition at line 119 of file test_dropwhile.cpp.
References NS1::begin(), iter::dropwhile, NS1::end(), and i.
TEST_CASE() [11/17]
TEST_CASE ("dropwhile: only drops from beginning" , "" [dropwhile])
Definition at line 125 of file test_dropwhile.cpp.
References NS1::begin(), iter::dropwhile, NS1::end(), and i.
TEST_CASE() [12/17]
TEST_CASE ("dropwhile: operator->" , "" [dropwhile])
Definition at line 133 of file test_dropwhile.cpp.
References NS1::begin(), iter::dropwhile, and i.
TEST_CASE() [13/17]
TEST_CASE ("dropwhile: works with function pointer" , "" [dropwhile])
Definition at line 146 of file test_dropwhile.cpp.
References NS1::begin(), iter::dropwhile, and NS1::end().
TEST_CASE() [14/17]
TEST_CASE ("dropwhile: binds to lvalues, moves rvalues" , "" [dropwhile])
Definition at line 154 of file test_dropwhile.cpp.
References iter::dropwhile.
TEST_CASE() [15/17]
TEST_CASE ("dropwhile: doesn't move or copy elements of iterable" , "" [dropwhile])
Definition at line 166 of file test_dropwhile.cpp.
References iter::dropwhile, and i.
TEST_CASE() [16/17]
TEST_CASE ("dropwhile: iterator meets requirements" , "" [dropwhile])
Definition at line 175 of file test_dropwhile.cpp.
References NS1::begin(), and iter::dropwhile.
TEST_CASE() [17/17]
TEST_CASE ("dropwhile: has correct ctor and assign ops" , "" [dropwhile])
Definition at line 183 of file test_dropwhile.cpp.