CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_zip.cpp File Reference
test_zip.cpp File Reference
#include <zip.hpp>
#include "helpers.hpp"
#include <iterator>
#include <sstream>
#include <string>
#include <tuple>
#include <utility>
#include <vector>
#include "catch.hpp"
Typedefs
template<typename... Ts>
using ImpT = decltype(zip(std::declval< Ts >()...))
Functions
TEST_CASE ("zip: Simple case, same length", "[zip]")
TEST_CASE ("zip: const iteration", "[zip][const]")
TEST_CASE ("zip: const iterators can be compared to non-const iterators", "[zip][const]")
TEST_CASE ("zip: three sequences, one sequence has different begin and end", "[zip]")
TEST_CASE ("zip: One empty, all empty", "[zip]")
TEST_CASE ("zip: terminates on shortest sequence", "[zip]")
TEST_CASE ("zip: Empty", "[zip]")
TEST_CASE ("zip: Modify sequence through zip", "[zip]")
TEST_CASE ("zip: binds reference when it should", "[zip]")
TEST_CASE ("zip: moves rvalues", "[zip]")
TEST_CASE ("zip: Can bind ref and move in single zip", "[zip]")
TEST_CASE ("zip: doesn't move or copy elements of iterable", "[zip]")
TEST_CASE ("zip: postfix ++", "[zip]")
TEST_CASE ("zip: iterator meets requirements", "[zip]")
TEST_CASE ("zip: has correct ctor and assign ops", "[zip]")
Typedef Documentation
ImpT
template<typename... Ts> using ImpT = decltype(zip(std::declval<Ts>()...))
Definition at line 148 of file test_zip.cpp.
Function Documentation
TEST_CASE() [1/15]
TEST_CASE ("zip: Simple case, same length" , "" [zip])
Definition at line 18 of file test_zip.cpp.
References NS1::begin(), NS1::end(), and iter::zip().
TEST_CASE() [2/15]
TEST_CASE ("zip: const iteration" , "" [zip][const ])
Definition at line 31 of file test_zip.cpp.
References NS1::begin(), NS1::end(), and iter::zip().
TEST_CASE() [3/15]
TEST_CASE ("zip: const iterators can be compared to non-const iterators" , "" [zip][const ])
Definition at line 45 of file test_zip.cpp.
References NS1::begin(), NS1::end(), and iter::zip().
TEST_CASE() [4/15]
TEST_CASE ("zip: three sequences, one sequence has different begin and end" , "" [zip])
Definition at line 54 of file test_zip.cpp.
References NS1::begin(), NS1::end(), and iter::zip().
TEST_CASE() [5/15]
TEST_CASE ("zip: One empty, all empty" , "" [zip])
Definition at line 68 of file test_zip.cpp.
References NS1::begin(), NS1::end(), and iter::zip().
TEST_CASE() [6/15]
TEST_CASE ("zip: terminates on shortest sequence" , "" [zip])
Definition at line 77 of file test_zip.cpp.
References NS1::begin(), NS1::end(), and iter::zip().
TEST_CASE() [7/15]
TEST_CASE ("zip: Empty" , "" [zip])
Definition at line 85 of file test_zip.cpp.
References NS1::begin(), NS1::end(), and iter::zip().
TEST_CASE() [8/15]
TEST_CASE ("zip: Modify sequence through zip" , "" [zip])
Definition at line 90 of file test_zip.cpp.
References iter::zip().
TEST_CASE() [9/15]
TEST_CASE ("zip: binds reference when it should" , "" [zip])
Definition at line 104 of file test_zip.cpp.
References iter::zip().
TEST_CASE() [10/15]
TEST_CASE ("zip: moves rvalues" , "" [zip])
Definition at line 110 of file test_zip.cpp.
References iter::zip().
TEST_CASE() [11/15]
TEST_CASE ("zip: Can bind ref and move in single zip" , "" [zip])
Definition at line 116 of file test_zip.cpp.
References iter::zip().
TEST_CASE() [12/15]
TEST_CASE ("zip: doesn't move or copy elements of iterable" , "" [zip])
Definition at line 124 of file test_zip.cpp.
References iter::zip().
TEST_CASE() [13/15]
TEST_CASE ("zip: postfix ++" , "" [zip])
Definition at line 131 of file test_zip.cpp.
References NS1::begin(), NS1::end(), and iter::zip().
TEST_CASE() [14/15]
TEST_CASE ("zip: iterator meets requirements" , "" [zip])
Definition at line 139 of file test_zip.cpp.
References NS1::begin(), and iter::zip().
TEST_CASE() [15/15]
TEST_CASE ("zip: has correct ctor and assign ops" , "" [zip])
Definition at line 149 of file test_zip.cpp.