CkPttnCpp: lib/test/src/test_readwrite.cpp File Reference
test_readwrite.cpp File Reference
#include <catch2/catch.hpp>
#include <ckpttncpp/netlist.hpp>
Functions
SimpleNetlist readNetD (const char *netDFileName)
void readAre (SimpleNetlist &H, const char *areFileName)
void writeJSON (const char *jsonFileName, const SimpleNetlist &H)
TEST_CASE ("Test Read Dwarf", "[test_readwrite]")
TEST_CASE ("Test Read p1", "[test_readwrite]")
TEST_CASE ("Test Write Dwarf", "[test_readwrite]")
TEST_CASE ("Test Write p1", "[test_readwrite]")
Function Documentation
readAre()
void readAre (SimpleNetlist & H, const char * areFileName)
Definition at line 173 of file readwrite.cpp.
References Netlist< nodeview_t, nodemap_t >::module_weight, Netlist< nodeview_t, nodemap_t >::num_pads, and Netlist< nodeview_t, nodemap_t >::number_of_modules().
Referenced by TEST_CASE().
readNetD()
SimpleNetlist readNetD (const char * netDFileName)
Definition at line 63 of file readwrite.cpp.
References Netlist< nodeview_t, nodemap_t >::num_pads, and R.
Referenced by TEST_CASE().
TEST_CASE() [1/4]
TEST_CASE ("Test Read Dwarf" , "" [test_readwrite])
Definition at line 9 of file test_readwrite.cpp.
References CHECK(), readAre(), and readNetD().
TEST_CASE() [2/4]
TEST_CASE ("Test Read p1" , "" [test_readwrite])
Definition at line 23 of file test_readwrite.cpp.
References CHECK(), and readNetD().
TEST_CASE() [3/4]
TEST_CASE ("Test Write Dwarf" , "" [test_readwrite])
Definition at line 36 of file test_readwrite.cpp.
References CHECK(), readAre(), readNetD(), and writeJSON().
TEST_CASE() [4/4]
TEST_CASE ("Test Write p1" , "" [test_readwrite])
Definition at line 47 of file test_readwrite.cpp.
References readNetD(), and writeJSON().
writeJSON()
void writeJSON (const char * jsonFileName, const SimpleNetlist & H)
Definition at line 18 of file readwrite.cpp.
References Netlist< nodeview_t, nodemap_t >::G, Netlist< nodeview_t, nodemap_t >::modules, Netlist< nodeview_t, nodemap_t >::num_pads, Netlist< nodeview_t, nodemap_t >::number_of_modules(), and Netlist< nodeview_t, nodemap_t >::number_of_nets().
Referenced by TEST_CASE().