CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_repeat.cpp File Reference
test_repeat.cpp File Reference
#include <repeat.hpp>
#include "helpers.hpp"
#include <iterator>
#include <string>
#include <vector>
#include "catch.hpp"
Typedefs
template<typename T >
using ImpT = decltype(repeat(std::declval< T >()))
template<typename T >
using ImpT2 = decltype(repeat(std::declval< T >(), 1))
Functions
TEST_CASE ("repeat: one argument keeps giving value back", "[repeat]")
TEST_CASE ("repeat: can be used as constexpr", "[repeat]")
TEST_CASE ("repeat: iterators compare to const iterators", "[repeat]")
TEST_CASE ("repeat: two argument repeats a number of times", "[repeat]")
TEST_CASE ("repeat: 0 count gives empty sequence", "[repeat]")
TEST_CASE ("repeat: negative count gives empty sequence", "[repeat]")
TEST_CASE ("repeat: doesn't duplicate item", "[repeat]")
TEST_CASE ("repeat: iterator meets requirements", "[repeat]")
TEST_CASE ("repeat: has correct ctor and assign ops", "[repeat]")
Typedef Documentation
ImpT
template<typename T > using ImpT = decltype(repeat(std::declval<T>()))
Definition at line 90 of file test_repeat.cpp.
ImpT2
template<typename T > using ImpT2 = decltype(repeat(std::declval<T>(), 1))
Definition at line 93 of file test_repeat.cpp.
Function Documentation
TEST_CASE() [1/9]
TEST_CASE ("repeat: one argument keeps giving value back" , "" [repeat])
Definition at line 13 of file test_repeat.cpp.
References NS1::begin(), and iter::repeat().
TEST_CASE() [2/9]
TEST_CASE ("repeat: can be used as constexpr" , "" [repeat])
Definition at line 27 of file test_repeat.cpp.
References i, and iter::repeat().
TEST_CASE() [3/9]
TEST_CASE ("repeat: iterators compare to const iterators" , "" [repeat])
Definition at line 53 of file test_repeat.cpp.
References NS1::begin(), NS1::end(), and iter::repeat().
TEST_CASE() [4/9]
TEST_CASE ("repeat: two argument repeats a number of times" , "" [repeat])
Definition at line 59 of file test_repeat.cpp.
References NS1::begin(), NS1::end(), and iter::repeat().
TEST_CASE() [5/9]
TEST_CASE ("repeat: 0 count gives empty sequence" , "" [repeat])
Definition at line 65 of file test_repeat.cpp.
References NS1::begin(), NS1::end(), and iter::repeat().
TEST_CASE() [6/9]
TEST_CASE ("repeat: negative count gives empty sequence" , "" [repeat])
Definition at line 70 of file test_repeat.cpp.
References NS1::begin(), NS1::end(), and iter::repeat().
TEST_CASE() [7/9]
TEST_CASE ("repeat: doesn't duplicate item" , "" [repeat])
Definition at line 77 of file test_repeat.cpp.
References NS1::begin(), and iter::repeat().
TEST_CASE() [8/9]
TEST_CASE ("repeat: iterator meets requirements" , "" [repeat])
Definition at line 84 of file test_repeat.cpp.
References NS1::begin(), and iter::repeat().
TEST_CASE() [9/9]
TEST_CASE ("repeat: has correct ctor and assign ops" , "" [repeat])
Definition at line 95 of file test_repeat.cpp.