CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_filterfalse.cpp File Reference
test_filterfalse.cpp File Reference
#include <filterfalse.hpp>
#include "helpers.hpp"
#include <iterator>
#include <string>
#include <vector>
#include "catch.hpp"
Typedefs
using Vec = const std::vector< int >
template<typename T , typename U >
using ImpT = decltype(filterfalse(std::declval< T >(), std::declval< U >()))
Functions
TEST_CASE ("filterfalse: handles different callable types", "[filterfalse]")
TEST_CASE ("filterfalse: handles pointer to member", "[filterfalse]")
TEST_CASE ("filterfalse: const iteration", "[filterfalse][const]")
TEST_CASE ("filterfalse: const iterator and non-const iterator can be compared", "[filterfalse][const]")
TEST_CASE ("filterfalse: Works with different begin and end types", "[filterfalse]")
TEST_CASE ("filterfalse: using identity", "[filterfalse]")
TEST_CASE ("filterfalse: binds to lvalues, moves rvales", "[filterfalse]")
TEST_CASE ("filterfalse: all elements pass predicate", "[filterfalse]")
TEST_CASE ("filterfalse: iterator meets requirements", "[filterfalse]")
TEST_CASE ("filterfalse: has correct ctor and assign ops", "[filterfalse]")
Typedef Documentation
ImpT
template<typename T , typename U > using ImpT = decltype(filterfalse(std::declval<T>(), std::declval<U>()))
Definition at line 160 of file test_filterfalse.cpp.
Vec
using Vec = const std::vector<int>
Definition at line 13 of file test_filterfalse.cpp.
Function Documentation
TEST_CASE() [1/10]
TEST_CASE ("filterfalse: handles different callable types" , "" [filterfalse])
Definition at line 33 of file test_filterfalse.cpp.
References NS1::begin(), NS1::end(), iter::filterfalse, and i.
TEST_CASE() [2/10]
TEST_CASE ("filterfalse: handles pointer to member" , "" [filterfalse])
Definition at line 63 of file test_filterfalse.cpp.
References NS1::begin(), NS1::end(), and iter::filterfalse.
TEST_CASE() [3/10]
TEST_CASE ("filterfalse: const iteration" , "" [filterfalse][const ])
Definition at line 81 of file test_filterfalse.cpp.
References NS1::begin(), NS1::end(), and iter::filterfalse.
TEST_CASE() [4/10]
TEST_CASE ("filterfalse: const iterator and non-const iterator can be compared" , "" [filterfalse][const ])
Definition at line 89 of file test_filterfalse.cpp.
References NS1::begin(), NS1::end(), and iter::filterfalse.
TEST_CASE() [5/10]
TEST_CASE ("filterfalse: Works with different begin and end types" , "" [filterfalse])
Definition at line 96 of file test_filterfalse.cpp.
References iter::filterfalse.
TEST_CASE() [6/10]
TEST_CASE ("filterfalse: using identity" , "" [filterfalse])
Definition at line 105 of file test_filterfalse.cpp.
References NS1::begin(), NS1::end(), and iter::filterfalse.
TEST_CASE() [7/10]
TEST_CASE ("filterfalse: binds to lvalues, moves rvales" , "" [filterfalse])
Definition at line 122 of file test_filterfalse.cpp.
References iter::filterfalse.
TEST_CASE() [8/10]
TEST_CASE ("filterfalse: all elements pass predicate" , "" [filterfalse])
Definition at line 146 of file test_filterfalse.cpp.
References NS1::begin(), NS1::end(), and iter::filterfalse.
TEST_CASE() [9/10]
TEST_CASE ("filterfalse: iterator meets requirements" , "" [filterfalse])
Definition at line 153 of file test_filterfalse.cpp.
References NS1::begin(), and iter::filterfalse.
TEST_CASE() [10/10]
TEST_CASE ("filterfalse: has correct ctor and assign ops" , "" [filterfalse])
Definition at line 161 of file test_filterfalse.cpp.