CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_iterator_wrapper.cpp File Reference
test_iterator_wrapper.cpp File Reference
#include "catch.hpp"
#include "internal/iterator_wrapper.hpp"
Classes
struct SameTypes
struct SameTypes::iterator
struct DifferentTypes
struct DifferentTypes::iterator
struct DifferentTypes::end_iterator
Functions
TEST_CASE ("ensure test type iterators are totally comparable", "[test_util")
TEST_CASE ("Operations on IteratorWrappers with SameTypes work", "[base_iterator]")
TEST_CASE ("Operations on IteratorWrappers with DifferentTypes work", "[base_iterator]")
TEST_CASE ("Can copy construct a IteratorWrapper with SameTypes", "[base_iterator]")
TEST_CASE ("Can copy assign a IteratorWrapper with SameTypes", "[base_iterator]")
TEST_CASE ("Can copy construct a IteratorWrapper with DifferentTypes", "[base_iterator]")
TEST_CASE ("Can copy construct a IteratorWrapper with DifferenTypes", "[base_iterator]")
Function Documentation
TEST_CASE() [1/7]
TEST_CASE ("ensure test type iterators are totally comparable" , "[test_util")
Definition at line 107 of file test_iterator_wrapper.cpp.
References DifferentTypes::begin().
TEST_CASE() [2/7]
TEST_CASE ("Operations on IteratorWrappers with SameTypes work" , "" [base_iterator])
Definition at line 125 of file test_iterator_wrapper.cpp.
References SameTypes::begin().
TEST_CASE() [3/7]
TEST_CASE ("Operations on IteratorWrappers with DifferentTypes work" , "" [base_iterator])
Definition at line 136 of file test_iterator_wrapper.cpp.
References DifferentTypes::begin(), and DifferentTypes::end().
TEST_CASE() [4/7]
TEST_CASE ("Can copy construct a IteratorWrapper with SameTypes" , "" [base_iterator])
Definition at line 166 of file test_iterator_wrapper.cpp.
References SameTypes::begin().
TEST_CASE() [5/7]
TEST_CASE ("Can copy assign a IteratorWrapper with SameTypes" , "" [base_iterator])
Definition at line 177 of file test_iterator_wrapper.cpp.
References SameTypes::begin().
TEST_CASE() [6/7]
TEST_CASE ("Can copy construct a IteratorWrapper with DifferentTypes" , "" [base_iterator])
Definition at line 190 of file test_iterator_wrapper.cpp.
References DifferentTypes::begin().
TEST_CASE() [7/7]
TEST_CASE ("Can copy construct a IteratorWrapper with DifferenTypes" , "" [base_iterator])
Definition at line 201 of file test_iterator_wrapper.cpp.
References DifferentTypes::begin(), and DifferentTypes::end().