CkPttnCpp: lib/test/src/test_MLPartMgr.cpp File Reference
test_MLPartMgr.cpp File Reference
#include <catch.hpp>
#include <chrono>
#include <ckpttncpp/FMBiConstrMgr.hpp>
#include <ckpttncpp/FMBiGainMgr.hpp>
#include <ckpttncpp/FMKWayConstrMgr.hpp>
#include <ckpttncpp/FMKWayGainMgr.hpp>
#include <ckpttncpp/FMPartMgr.hpp>
#include <ckpttncpp/MLPartMgr.hpp>
#include <experimental/random>
#include <iostream>
Functions
SimpleNetlist create_test_netlist ()
Create a test netlist object.
SimpleNetlist create_dwarf ()
Create a test netlist object.
SimpleNetlist readNetD (const char *netDFileName)
void readAre (SimpleNetlist &H, const char *areFileName)
TEST_CASE ("Test MLBiPartMgr dwarf", "[test_MLBiPartMgr]")
TEST_CASE ("Test MLKWayPartMgr dwarf", "[test_MLKWayPartMgr]")
TEST_CASE ("Test MLBiPartMgr p1", "[test_MLBiPartMgr]")
TEST_CASE ("Test MLBiPartMgr ibm01", "[test_MLBiPartMgr]")
TEST_CASE ("Test MLBiPartMgr ibm03", "[test_MLBiPartMgr]")
Function Documentation
create_dwarf()
SimpleNetlist create_dwarf () -> SimpleNetlist
Create a test netlist object.
Returns
Netlist
Definition at line 18 of file test_netlist.cpp.
References Netlist< nodeview_t, nodemap_t >::module_weight.
Referenced by TEST_CASE().
create_test_netlist()
SimpleNetlist create_test_netlist () -> SimpleNetlist
Create a test netlist object.
Returns
Netlist
Definition at line 78 of file test_netlist.cpp.
References Netlist< nodeview_t, nodemap_t >::module_weight, and R.
Referenced by TEST_CASE().
readAre()
void readAre (SimpleNetlist & H, const char * areFileName)
Definition at line 162 of file readwrite.cpp.
Referenced by TEST_CASE().
readNetD()
SimpleNetlist readNetD (const char * netDFileName)
Definition at line 64 of file readwrite.cpp.
Referenced by TEST_CASE().
TEST_CASE() [1/5]
TEST_CASE ("Test MLBiPartMgr dwarf" , "" [test_MLBiPartMgr])
Definition at line 19 of file test_MLPartMgr.cpp.
References CHECK(), create_dwarf(), and MLPartMgr::run_FMPartition().
TEST_CASE() [2/5]
TEST_CASE ("Test MLKWayPartMgr dwarf" , "" [test_MLKWayPartMgr])
Definition at line 28 of file test_MLPartMgr.cpp.
References CHECK(), create_dwarf(), and MLPartMgr::run_FMPartition().
TEST_CASE() [3/5]
TEST_CASE ("Test MLBiPartMgr p1" , "" [test_MLBiPartMgr])
Definition at line 37 of file test_MLPartMgr.cpp.
References CHECK(), i, readNetD(), and PartMgrBase< GainMgr, ConstrMgr, Derived >::totalcost.
TEST_CASE() [4/5]
TEST_CASE ("Test MLBiPartMgr ibm01" , "" [test_MLBiPartMgr])
Definition at line 59 of file test_MLPartMgr.cpp.
References CHECK(), i, readAre(), readNetD(), and PartMgrBase< GainMgr, ConstrMgr, Derived >::totalcost.
TEST_CASE() [5/5]
TEST_CASE ("Test MLBiPartMgr ibm03" , "" [test_MLBiPartMgr])
Definition at line 81 of file test_MLPartMgr.cpp.
References NS1::begin(), CHECK(), readAre(), and readNetD().