PgCpp: fun::pg_object< _K, _dual > Class Template Reference
fun::pg_object< _K, _dual > Class Template Reference
Projective object.
#include <pg_object.hpp>
Public Types
using value_type = _K
using dual = _dual
Public Member Functions
constexpr pg_object (const _Base &a)
Construct a new pg object object.
constexpr bool operator== (const _Self &rhs) const
Equal to.
constexpr bool operator!= (const _Self &rhs) const
Not equal to.
constexpr bool is_NaN () const
Equal to.
constexpr _K dot (const dual &l) const
the dot product
constexpr dual operator* (const _Self &rhs) const
Join or meet.
constexpr dual aux () const
Generate a new line not incident with p.
Private Types
using _Base = std::array< _K, 3 >
Value typedef.
using _Self = pg_object< _K, _dual >
Detailed Description
template<CommutativeRing _K, typename _dual>
class fun::pg_object< _K, _dual >
Projective object.
Template Parameters
_K Type of object elements
_dual
Definition at line 23 of file pg_object.hpp.
Member Typedef Documentation
_Base
template<CommutativeRing _K, typename _dual> using fun::pg_object< _K, _dual >::_Base = std::array<_K, 3> private
Value typedef.
Definition at line 26 of file pg_object.hpp.
_Self
template<CommutativeRing _K, typename _dual> using fun::pg_object< _K, _dual >::_Self = pg_object<_K, _dual> private
Definition at line 27 of file pg_object.hpp.
dual
template<CommutativeRing _K, typename _dual> using fun::pg_object< _K, _dual >::dual = _dual
Definition at line 31 of file pg_object.hpp.
value_type
template<CommutativeRing _K, typename _dual> using fun::pg_object< _K, _dual >::value_type = _K
Definition at line 30 of file pg_object.hpp.
Constructor & Destructor Documentation
pg_object()
template<CommutativeRing _K, typename _dual> constexpr fun::pg_object< _K, _dual >::pg_object (const _Base & a) inline explicit
Construct a new pg object object.
Parameters
a array of coordinates
Definition at line 40 of file pg_object.hpp.
Member Function Documentation
aux()
template<CommutativeRing _K, typename _dual> constexpr dual fun::pg_object< _K, _dual >::aux () const inline
Generate a new line not incident with p.
Returns
dual
Definition at line 117 of file pg_object.hpp.
dot()
template<CommutativeRing _K, typename _dual> constexpr _K fun::pg_object< _K, _dual >::dot (const dual & l) const inline
the dot product
Parameters
l
Returns
_K
Definition at line 95 of file pg_object.hpp.
Referenced by fun::persp_euclid_plane< P, L >::midpoint(), fun::persp_euclid_plane< P, L >::perp(), and fun::ratio_ratio().
is_NaN()
template<CommutativeRing _K, typename _dual> constexpr bool fun::pg_object< _K, _dual >::is_NaN () const inline
Equal to.
Parameters
rhs
Returns
true if this object is equivalent to the rhs
false otherwise
Definition at line 82 of file pg_object.hpp.
operator!=()
template<CommutativeRing _K, typename _dual> constexpr bool fun::pg_object< _K, _dual >::operator!= (const _Self & rhs) const inline
Not equal to.
Parameters
rhs
Returns
true if this object is not equivalent to the rhs
false otherwise
Definition at line 70 of file pg_object.hpp.
operator*()
template<CommutativeRing _K, typename _dual> constexpr dual fun::pg_object< _K, _dual >::operator* (const _Self & rhs) const inline
Join or meet.
Parameters
rhs
Returns
true if this point is equivalent to the rhs
false otherwise
Definition at line 107 of file pg_object.hpp.
operator==()
template<CommutativeRing _K, typename _dual> constexpr bool fun::pg_object< _K, _dual >::operator== (const _Self & rhs) const inline
Equal to.
Parameters
rhs
Returns
true if this object is equivalent to the rhs
false otherwise
Definition at line 54 of file pg_object.hpp.
The documentation for this class was generated from the following file:
lib/include/pgcpp/pg_object.hpp