PgCpp: fun::persp_euclid_plane< P, L > Class Template Reference
fun::persp_euclid_plane< P, L > Class Template Reference
#include <persp_plane.hpp>
Public Member Functions
constexpr persp_euclid_plane (P &&Ire, P &&Iim, L &&l_infty)
Construct a new persp euclid plane object.
constexpr const L & l_infty () const
Construct a new persp euclid plane object.
constexpr auto perp (const L &v) const -> P
constexpr auto is_parallel (const L &l, const L &m) const -> bool
constexpr auto midpoint (const P &a, const P &b) const -> P
constexpr auto tri_midpoint (const Triple< P > &tri) const
constexpr auto omega (const P &x) const -> K
constexpr auto omega (const L &x) const -> K
template<Projective_plane2 _P>
constexpr auto measure (const _P &a1, const _P &a2) const
Public Member Functions inherited from fun::ck< P, L, persp_euclid_plane >
constexpr ck ()
construct ck object
constexpr auto is_perpendicular (const L &l, const L &m) const -> bool
is perpendicular
requires Projective_plane_prim< P, L > constexpr auto altitude (const P &p, const L &l) const -> L
altitude
constexpr auto tri_altitude (const Triple< Projective_plane_prim2 > &tri) const
altitudes of triangle
constexpr auto orthocenter (const Triple< Projective_plane_prim2 > &tri) const
ortho-center
auto reflect (const Projective_plane2 &m) const
reflect
constexpr auto tri_measure (const Triple< Projective_plane2 > &tri) const
measure of triangle
constexpr auto quadrance (const P &p, const P &q) const
quadrance between two points
constexpr auto spread (const L &l, const L &m) const
spread between two lines
constexpr auto tri_quadrance (const Triple< P > &triangle) const
quadrances of triangle
constexpr auto tri_spread (const Triple< L > &trilateral) const
spreads of triangle
Private Types
using K = Value_type< P >
Private Attributes
P _Ire
P _Iim
L _l_infty
Additional Inherited Members
Public Types inherited from fun::ck< P, L, persp_euclid_plane >
using point_t = P
using line_t = L
using cDer = const persp_euclid_plane< P, L >
Public Attributes inherited from fun::ck< P, L, persp_euclid_plane >
cDer & self
Detailed Description
template<typename P, typename L = typename P::dual>
class fun::persp_euclid_plane< P, L >
Template Parameters
P
P::dual
Definition at line 19 of file persp_plane.hpp.
Member Typedef Documentation
K
template<typename P , typename L = typename P::dual> using fun::persp_euclid_plane< P, L >::K = Value_type<P> private
Definition at line 21 of file persp_plane.hpp.
Constructor & Destructor Documentation
persp_euclid_plane()
template<typename P , typename L = typename P::dual> constexpr fun::persp_euclid_plane< P, L >::persp_euclid_plane (P && Ire, P && Iim, L && l_infty) inline
Construct a new persp euclid plane object.
Parameters
Ire
Iim
l_infty
Definition at line 36 of file persp_plane.hpp.
References Iim, Ire, and fun::persp_euclid_plane< P, L >::l_infty().
Member Function Documentation
is_parallel()
template<typename P , typename L = typename P::dual> constexpr auto fun::persp_euclid_plane< P, L >::is_parallel (const L & l, const L & m) const -> bool inline
Parameters
l
m
Returns
true
false
Definition at line 93 of file persp_plane.hpp.
References l.
l_infty()
template<typename P , typename L = typename P::dual> constexpr const L& fun::persp_euclid_plane< P, L >::l_infty () const inline
Construct a new persp euclid plane object.
Parameters
Ire
Iim
l_infty
x
Returns
const L&
const L&
Definition at line 67 of file persp_plane.hpp.
References fun::persp_euclid_plane< P, L >::_l_infty.
Referenced by fun::persp_euclid_plane< P, L >::persp_euclid_plane().
measure()
template<typename P , typename L = typename P::dual> template<Projective_plane2 _P> constexpr auto fun::persp_euclid_plane< P, L >::measure (const _P & a1, const _P & a2) const inline
Parameters
a1
a2
Returns
auto
Definition at line 158 of file persp_plane.hpp.
References fun::persp_euclid_plane< P, L >::omega().
midpoint()
template<typename P , typename L = typename P::dual> constexpr auto fun::persp_euclid_plane< P, L >::midpoint (const P & a, const P & b) const -> P inline
Parameters
a
b
Returns
P
Definition at line 105 of file persp_plane.hpp.
References fun::pg_object< _K, _dual >::dot(), and fun::plucker().
Referenced by fun::persp_euclid_plane< P, L >::tri_midpoint().
omega() [1/2]
template<typename P , typename L = typename P::dual> constexpr auto fun::persp_euclid_plane< P, L >::omega (const P & x) const -> K inline
Parameters
x
Returns
K
Definition at line 134 of file persp_plane.hpp.
References fun::sq().
Referenced by fun::persp_euclid_plane< P, L >::measure().
omega() [2/2]
template<typename P , typename L = typename P::dual> constexpr auto fun::persp_euclid_plane< P, L >::omega (const L & x) const -> K inline
Parameters
x
Returns
K
Definition at line 145 of file persp_plane.hpp.
References fun::sq().
perp()
template<typename P , typename L = typename P::dual> constexpr auto fun::persp_euclid_plane< P, L >::perp (const L & v) const -> P inline
Parameters
x
Returns
P
Definition at line 78 of file persp_plane.hpp.
References fun::pg_object< _K, _dual >::dot(), and fun::plucker().
tri_midpoint()
template<typename P , typename L = typename P::dual> constexpr auto fun::persp_euclid_plane< P, L >::tri_midpoint (const Triple< P > & tri) const inline
Parameters
tri
Returns
auto
Definition at line 118 of file persp_plane.hpp.
References a1, a2, a3, and fun::persp_euclid_plane< P, L >::midpoint().
Member Data Documentation
_Iim
template<typename P , typename L = typename P::dual> P fun::persp_euclid_plane< P, L >::_Iim private
Definition at line 25 of file persp_plane.hpp.
_Ire
template<typename P , typename L = typename P::dual> P fun::persp_euclid_plane< P, L >::_Ire private
Definition at line 24 of file persp_plane.hpp.
_l_infty
template<typename P , typename L = typename P::dual> L fun::persp_euclid_plane< P, L >::_l_infty private
Definition at line 26 of file persp_plane.hpp.
Referenced by fun::persp_euclid_plane< P, L >::l_infty().
The documentation for this class was generated from the following file:
lib/include/pgcpp/persp_plane.hpp