PgCpp: fun Namespace Reference
fun Namespace Reference
Classes
struct ck
struct ellck
Elliptic Plane.
struct Fraction
struct hyck
Hyperbolic Plane.
class persp_euclid_plane
class pg_line
Projective line: two dimensional subspace of K^3.
class pg_object
Projective object.
struct pg_point
Typedefs
template<typename T >
using Value_type = typename T::value_type
template<typename T >
using Element_type = decltype(back(std::declval< T >()))
template<typename T >
using Iterator_type = decltype(begin(std::declval< T >()))
Functions
template<CommutativeRing Q_t>
constexpr bool check_sine_law (const Triple< Q_t > &Q, const Triple< Q_t > &S)
check sine law
template<CommutativeRing K>
constexpr auto check_cross_TQF (const Triple< K > &Q)
template<CommutativeRing K>
constexpr auto check_cross_law (const Triple< K > &S, const K &q3)
template<typename P , typename... Args>
concept bool Predicate ()
template<Projective_plane_coord2 L>
constexpr auto fB (const L &l) -> typename L::dual
template<Projective_plane_coord2 L>
constexpr auto is_perpendicular (const L &l, const L &m) -> bool
template<Projective_plane_coord2 L>
constexpr auto is_parallel (const L &l, const L &m) -> bool
template<Integral _Mn>
constexpr _Mn gcd (_Mn __m, _Mn __n)
Greatest common divider.
template<Integral _Mn>
constexpr _Mn lcm (_Mn __m, _Mn __n)
Least common multiple.
template<Integral Z>
constexpr Fraction< Z > operator+ (const Z &c, const Fraction< Z > &frac)
template<Integral Z>
constexpr Fraction< Z > operator- (const Z &c, const Fraction< Z > &frac)
template<Integral Z>
constexpr Fraction< Z > operator* (const Z &c, const Fraction< Z > &frac)
template<Integral Z>
constexpr Fraction< Z > operator+ (int &&c, const Fraction< Z > &frac)
template<Integral Z>
constexpr Fraction< Z > operator- (int &&c, const Fraction< Z > &frac)
template<Integral Z>
constexpr Fraction< Z > operator* (int &&c, const Fraction< Z > &frac)
template<typename _Stream , Integral Z>
_Stream & operator<< (_Stream &os, const Fraction< Z > &frac)
template<CommutativeRing _K>
auto cross0 (const std::array< _K, 3 > &v, const std::array< _K, 3 > &w) -> _K
1st term of Cross product
template<CommutativeRing _K>
auto cross1 (const std::array< _K, 3 > &v, const std::array< _K, 3 > &w) -> _K
2nd term of Cross product
template<CommutativeRing _K>
auto cross2 (const std::array< _K, 3 > &v, const std::array< _K, 3 > &w) -> _K
3rd term of Cross product
template<typename P >
requires CommutativeRing< Value_type< P > > auto cross (const P &v, const P &w) -> std::array< Value_type< P >, 3 >
Cross product.
template<CommutativeRing _K>
auto dot_c (const std::array< _K, 3 > &v, const std::array< _K, 3 > &w) -> _K
Dot product.
template<CommutativeRing _T, CommutativeRing _K>
auto plucker_c (const _T &ld, const std::array< _K, 3 > &v1, const _T &mu, const std::array< _K, 3 > &v2) -> std::array< _K, 3 >
generic Plucker function
template<CommutativeRing _K>
auto dot1 (const std::array< _K, 3 > &v, const std::array< _K, 3 > &w) -> _K
dot product of the (0,1)-component of two vectors
template<CommutativeRing _K>
auto dot2 (const std::array< _K, 3 > &v, const std::array< _K, 3 > &w) -> _K
dot product of the (0,2)-component of two vectors
template<typename T >
constexpr auto sq (const T &a)
Square function.
template<CommutativeRing _K>
constexpr pg_point< _K > meet (const pg_line< _K > &l, const pg_line< _K > &m)
Return meet of two lines.
template<typename P , CommutativeRing _K = Value_type<P>>
constexpr P plucker (const _K &lda1, const P &p, const _K &mu1, const P &q)
template<CommutativeRing _K, typename _dual , class _Stream >
_Stream & operator<< (_Stream &os, const pg_object< _K, _dual > &p)
template<CommutativeRing _K>
constexpr pg_line< _K > join (const pg_point< _K > &p, const pg_point< _K > &q)
Return join of two points.
template<Projective_plane_prim2 P>
constexpr bool coincident (const P &p, const P &q, const P &r)
Coincident.
template<Projective_plane_prim2 P>
constexpr auto tri_dual (const Triple< P > &tri)
template<Projective_plane_prim2 P>
constexpr auto tri_func (auto func, const Triple< P > &tri)
template<Projective_plane_prim2 P>
constexpr bool persp (const Triple< P > &tri1, const Triple< P > &tri2)
template<CommutativeRing K>
constexpr auto ratio_ratio (const K &a, const K &b, const K &c, const K &d)
Variables
template<typename I >
concept bool Input_iter
Input iterator concept.
template<typename T >
concept bool Sequence
Sequence.
template<typename T >
concept bool Range
template<typename T >
concept bool Equality_comparable
template<Equality_comparable K>
concept bool CommutativeRing
template<CommutativeRing Z>
concept bool Integral
Projective_plane_prim
Coincident.
Projective_plane
Projective plane Concept (full)
template<class P , class L >
concept bool Projective_plane_prim_h
Projective plane Concept (half)
template<class P >
concept bool Projective_plane_prim2
Shorthand Notation of Projective_plane.
template<class P , class L >
concept bool Projective_plane_h
Projective plane Concept (half)
template<class P >
concept bool Projective_plane2
Shorthand Notation of Projective_plane.
template<class P , class L >
concept bool Projective_plane_coord_h
Projective plane Concept (half)
template<class P , class L = typename P::dual>
concept bool Projective_plane_coord
Projective plane Concept (full)
template<class P >
concept bool Projective_plane_coord2
Shorthand Notation of Projective_plane.
Detailed Description
Todo:
: projectivity >=
Todo:
: projectivity >=
Typedef Documentation
Element_type
template<typename T > using fun::Element_type = typedef decltype(back(std::declval<T>()))
Definition at line 12 of file common_concepts.h.
Iterator_type
template<typename T > using fun::Iterator_type = typedef decltype(begin(std::declval<T>()))
Definition at line 15 of file common_concepts.h.
Value_type
template<typename T > using fun::Value_type = typedef typename T::value_type
Definition at line 9 of file common_concepts.h.
Function Documentation
check_cross_law()
template<CommutativeRing K> constexpr auto fun::check_cross_law (const Triple< K > & S, const K & q3)
Template Parameters
K
Parameters
S
q3
Returns
constexpr auto
Definition at line 309 of file ck_plane.hpp.
References sq().
Referenced by chk_tri().
check_cross_TQF()
template<CommutativeRing K> constexpr auto fun::check_cross_TQF (const Triple< K > & Q)
Template Parameters
K
Parameters
Q
Returns
constexpr auto
Definition at line 293 of file ck_plane.hpp.
References sq().
Referenced by chk_tri().
check_sine_law()
template<CommutativeRing Q_t> constexpr bool fun::check_sine_law (const Triple< Q_t > & Q, const Triple< Q_t > & S)
check sine law
Template Parameters
Q_t
S_t
Parameters
Q
S
Returns
true
false
Definition at line 184 of file ck_plane.hpp.
Referenced by chk_ck(), and chk_euclid().
coincident()
template<Projective_plane_prim2 P> constexpr bool fun::coincident (const P & p, const P & q, const P & r)
Coincident.
Template Parameters
P Point
L Line
Parameters
p p
q q
r r
Returns
true if three points are conincident
false otherwise
Definition at line 31 of file proj_plane.hpp.
References Projective_plane_prim.
Referenced by chk_ck(), chk_degenerate(), chk_euclid(), and ratio_ratio().
cross()
template<typename P > requires CommutativeRing<Value_type<P> > auto fun::cross (const P & v, const P & w) -> std::array<Value_type<P>, 3>
Cross product.
Template Parameters
_K
Parameters
v
w
Returns
Cross product
Definition at line 65 of file pg_common.hpp.
References cross0(), cross1(), and cross2().
Referenced by chk_ck(), chk_euclid(), chk_tri(), fun::pg_object< _K, pg_line< _K > >::operator*(), and fun::pg_object< _K, pg_line< _K > >::operator==().
cross0()
template<CommutativeRing _K> auto fun::cross0 (const std::array< _K, 3 > & v, const std::array< _K, 3 > & w) -> _K
1st term of Cross product
Template Parameters
_K
Parameters
v
w
Returns
1st term of Cross product
Definition at line 23 of file pg_common.hpp.
Referenced by cross(), and ratio_ratio().
cross1()
template<CommutativeRing _K> auto fun::cross1 (const std::array< _K, 3 > & v, const std::array< _K, 3 > & w) -> _K
2nd term of Cross product
Template Parameters
_K
Parameters
v
w
Returns
2nd term of Cross product
Definition at line 37 of file pg_common.hpp.
Referenced by cross(), and ratio_ratio().
cross2()
template<CommutativeRing _K> auto fun::cross2 (const std::array< _K, 3 > & v, const std::array< _K, 3 > & w) -> _K
3rd term of Cross product
Template Parameters
_K
Parameters
v
w
Returns
3rd term of Cross product
Definition at line 51 of file pg_common.hpp.
Referenced by chk_euclid(), cross(), and is_parallel().
dot1()
template<CommutativeRing _K> auto fun::dot1 (const std::array< _K, 3 > & v, const std::array< _K, 3 > & w) -> _K
dot product of the (0,1)-component of two vectors
Template Parameters
_K
Parameters
v
w
Returns
auto
Definition at line 115 of file pg_common.hpp.
Referenced by chk_euclid(), is_parallel(), and is_perpendicular().
dot2()
template<CommutativeRing _K> auto fun::dot2 (const std::array< _K, 3 > & v, const std::array< _K, 3 > & w) -> _K
dot product of the (0,2)-component of two vectors
Template Parameters
_K
Parameters
v
w
Returns
auto
Definition at line 129 of file pg_common.hpp.
dot_c()
template<CommutativeRing _K> auto fun::dot_c (const std::array< _K, 3 > & v, const std::array< _K, 3 > & w) -> _K
Dot product.
Template Parameters
_K
Parameters
v
w
Returns
auto
Definition at line 80 of file pg_common.hpp.
Referenced by fun::pg_object< _K, pg_line< _K > >::dot().
fB()
template<Projective_plane_coord2 L> constexpr auto fun::fB (const L & l) -> typename L::dual
Parameters
l
Returns
auto
Definition at line 19 of file euclid_plane.hpp.
References l.
Referenced by is_parallel().
gcd()
template<Integral _Mn> constexpr _Mn fun::gcd (_Mn __m, _Mn __n)
Greatest common divider.
Template Parameters
_Mn
Parameters
__m
__n
Returns
_Mn
Definition at line 28 of file fractions.hpp.
Referenced by fun::Fraction< Z >::Fraction(), and lcm().
is_parallel()
template<Projective_plane_coord2 L> constexpr auto fun::is_parallel (const L & l, const L & m) -> bool
Parameters
l
m
Returns
true
false
Definition at line 47 of file euclid_plane.hpp.
References a1, a2, a3, cross2(), dot1(), fB(), l, plucker(), Projective_plane_coord, sq(), and triangle.
Referenced by chk_euclid().
is_perpendicular()
template<Projective_plane_coord2 L> constexpr auto fun::is_perpendicular (const L & l, const L & m) -> bool
Parameters
l
m
Returns
true
false
Definition at line 33 of file euclid_plane.hpp.
References dot1(), and l.
Referenced by chk_euclid().
join()
template<CommutativeRing _K> constexpr pg_line<_K> fun::join (const pg_point< _K > & p, const pg_point< _K > & q)
Return join of two points.
Parameters
p
q
Returns
pg_line<_K>
Definition at line 86 of file pg_point.hpp.
lcm()
template<Integral _Mn> constexpr _Mn fun::lcm (_Mn __m, _Mn __n)
Least common multiple.
Template Parameters
_Mn
Parameters
__m
__n
Returns
_Mn
Definition at line 42 of file fractions.hpp.
References gcd().
Referenced by fun::Fraction< Z >::operator+().
meet()
template<CommutativeRing _K> constexpr pg_point<_K> fun::meet (const pg_line< _K > & l, const pg_line< _K > & m)
Return meet of two lines.
Definition at line 63 of file pg_line.hpp.
Referenced by chk_euclid().
operator*() [1/2]
template<Integral Z> constexpr Fraction<Z> fun::operator* (const Z & c, const Fraction< Z > & frac)
Parameters
c
frac
Returns
Fraction<Z>
Definition at line 561 of file fractions.hpp.
operator*() [2/2]
template<Integral Z> constexpr Fraction<Z> fun::operator* (int && c, const Fraction< Z > & frac)
Parameters
c
frac
Returns
Fraction<Z>
Definition at line 600 of file fractions.hpp.
operator+() [1/2]
template<Integral Z> constexpr Fraction<Z> fun::operator+ (const Z & c, const Fraction< Z > & frac)
Parameters
c
frac
Returns
Fraction<Z>
Definition at line 535 of file fractions.hpp.
operator+() [2/2]
template<Integral Z> constexpr Fraction<Z> fun::operator+ (int && c, const Fraction< Z > & frac)
Parameters
c
frac
Returns
Fraction<Z>
Definition at line 574 of file fractions.hpp.
operator-() [1/2]
template<Integral Z> constexpr Fraction<Z> fun::operator- (const Z & c, const Fraction< Z > & frac)
Parameters
c
frac
Returns
Fraction<Z>
Definition at line 548 of file fractions.hpp.
operator-() [2/2]
template<Integral Z> constexpr Fraction<Z> fun::operator- (int && c, const Fraction< Z > & frac)
Parameters
c
frac
Returns
Fraction<Z>
Definition at line 587 of file fractions.hpp.
operator<<() [1/2]
template<CommutativeRing _K, typename _dual , class _Stream > _Stream& fun::operator<< (_Stream & os, const pg_object< _K, _dual > & p)
Template Parameters
_K
_dual
_Stream
Parameters
os
p
Returns
_Stream&
Definition at line 151 of file pg_object.hpp.
operator<<() [2/2]
template<typename _Stream , Integral Z> _Stream& fun::operator<< (_Stream & os, const Fraction< Z > & frac)
Template Parameters
_Stream
Z
Parameters
os
frac
Returns
_Stream&
Definition at line 615 of file fractions.hpp.
References fun::Fraction< Z >::numerator().
persp()
template<Projective_plane_prim2 P> constexpr bool fun::persp (const Triple< P > & tri1, const Triple< P > & tri2)
Parameters
tri1
tri2
Returns
true
false
Definition at line 103 of file proj_plane.hpp.
References Projective_plane.
Referenced by ratio_ratio().
plucker()
template<typename P , CommutativeRing _K = Value_type<P>> constexpr P fun::plucker (const _K & lda1, const P & p, const _K & mu1, const P & q)
Template Parameters
P
Value_type<P>
Parameters
lda1
p
mu1
q
Returns
P
Definition at line 135 of file pg_object.hpp.
References plucker_c().
Referenced by chk_degenerate(), chk_euclid(), chk_tri(), is_parallel(), fun::persp_euclid_plane< P, L >::midpoint(), fun::persp_euclid_plane< P, L >::perp(), and TEST_CASE().
plucker_c()
template<CommutativeRing _T, CommutativeRing _K> auto fun::plucker_c (const _T & ld, const std::array< _K, 3 > & v1, const _T & mu, const std::array< _K, 3 > & v2) -> std::array<_K, 3>
generic Plucker function
Template Parameters
_K data type
Parameters
ld lamda
v
mu
w
Returns
lamda*v + mu*w
Definition at line 98 of file pg_common.hpp.
Referenced by plucker().
Predicate()
template<typename P , typename... Args> concept bool fun::Predicate ()
Definition at line 51 of file common_concepts.h.
ratio_ratio()
template<CommutativeRing K> constexpr auto fun::ratio_ratio (const K & a, const K & b, const K & c, const K & d)
Template Parameters
K
Parameters
a
b
c
d
Returns
auto
Definition at line 209 of file proj_plane.hpp.
References coincident(), cross0(), cross1(), fun::pg_object< _K, _dual >::dot(), persp(), Projective_plane, and tri_dual().
sq()
template<typename T > constexpr auto fun::sq (const T & a) inline
Square function.
Template Parameters
T data type
Parameters
a input value
Returns
a^2
Definition at line 142 of file pg_common.hpp.
Referenced by check_cross_law(), check_cross_TQF(), chk_degenerate(), chk_euclid(), is_parallel(), and fun::persp_euclid_plane< P, L >::omega().
tri_dual()
template<Projective_plane_prim2 P> constexpr auto fun::tri_dual (const Triple< P > & tri)
Parameters
tri
Returns
auto
Definition at line 70 of file proj_plane.hpp.
References a1, a2, and a3.
Referenced by chk_ck(), chk_degenerate(), chk_euclid(), chk_tri(), ratio_ratio(), and fun::ck< P, L, myck >::tri_altitude().
tri_func()
template<Projective_plane_prim2 P> constexpr auto fun::tri_func (auto func, const Triple< P > & tri)
Parameters
func
tri
Returns
auto
Definition at line 84 of file proj_plane.hpp.
References a1, a2, and a3.
Variable Documentation
CommutativeRing
template<Equality_comparable K> concept bool fun::CommutativeRing
Initial value:
= requires(K a, K b)
{
    { a + b } -> K;
    { a - b } -> K;
    { a * b } -> K;
    { -a } -> K;
    { K(a) } -> K;
    { K(0) } -> K;
}
Definition at line 68 of file common_concepts.h.
Equality_comparable
template<typename T > concept bool fun::Equality_comparable
Initial value:
= requires(T a, T b)
{
    { a == b } -> bool;
    { a != b } -> bool;
}
Definition at line 60 of file common_concepts.h.
Input_iter
template<typename I > concept bool fun::Input_iter
Initial value:
= requires(I iter)
{
    ++iter;
}
Input iterator concept.
Template Parameters
I
Definition at line 23 of file common_concepts.h.
Integral
template<CommutativeRing Z> concept bool fun::Integral
Initial value:
= requires(Z a, Z b)
{
    { a % b } -> Z;
    { a / b } -> Z;
}
Definition at line 79 of file common_concepts.h.
Projective_plane
concept bool fun::Projective_plane
Projective plane Concept (full)
Parameters
p
l
Returns
true
false
Template Parameters
P Point
L Line
Definition at line 121 of file proj_plane.hpp.
Referenced by persp(), and ratio_ratio().
Projective_plane2
template<class P > concept bool fun::Projective_plane2
Initial value:
=
    Projective_plane<std::remove_reference_t<P>>
Shorthand Notation of Projective_plane.
Template Parameters
P Point
Definition at line 116 of file proj_plane_concepts.h.
Projective_plane_coord
template<class P , class L = typename P::dual> concept bool fun::Projective_plane_coord
Initial value:
=
    Projective_plane_coord_h<P, L>&& Projective_plane_coord_h<L, P>
Projective plane Concept (full)
Template Parameters
P Point
L Line
Definition at line 142 of file proj_plane_concepts.h.
Referenced by is_parallel().
Projective_plane_coord2
template<class P > concept bool fun::Projective_plane_coord2
Initial value:
=
    Projective_plane_coord<std::remove_reference_t<P>>
Shorthand Notation of Projective_plane.
Template Parameters
P Point
Definition at line 151 of file proj_plane_concepts.h.
Projective_plane_coord_h
template<class P , class L > concept bool fun::Projective_plane_coord_h
Initial value:
= Projective_plane_h<P, L>&& requires(
    P& p, size_t idx)
{
    {
        p[idx]
    }
    ->Value_type<P>;
}
Projective plane Concept (half)
Template Parameters
P Point
L Line
Definition at line 126 of file proj_plane_concepts.h.
Projective_plane_h
template<class P , class L > concept bool fun::Projective_plane_h
Initial value:
= Equality_comparable<P>&& requires(
    P& p, P& q, L& l, Value_type<P> a)
{
    typename Value_type<P>;
    {
        p* q
    }
    ->L;
    {
        p.aux()
    }
    ->L;
    {
        p.dot(l)
    }
    ->Value_type<P>;
    {
        plucker(a, p, a, q)
    }
    ->P;
}
Projective plane Concept (half)
Template Parameters
P Point
L Line
Definition at line 69 of file proj_plane_concepts.h.
Projective_plane_prim
concept bool fun::Projective_plane_prim
Initial value:
{
    P, L
}
constexpr bool coincident(const L& l, const Sequence& seq)
{
    for (auto const& p : seq)
    {
        if (!incident(l, p))
            return false;
    }
    return true;
}
template <typename P>
using Triple = std::tuple<P, P, P>
Coincident.
Projective plane Concept (full)
Template Parameters
P Point
L Line
Parameters
l line
seq Sequence of points
Returns
true if all points are incident with l
false otherwise
Template Parameters
P Point
L Line
Definition at line 47 of file proj_plane.hpp.
Referenced by coincident().
Projective_plane_prim2
template<class P > concept bool fun::Projective_plane_prim2
Initial value:
=
    Projective_plane_prim<std::remove_reference_t<P>>
Shorthand Notation of Projective_plane.
Template Parameters
P Point
Definition at line 58 of file proj_plane_concepts.h.
Projective_plane_prim_h
template<class P , class L > concept bool fun::Projective_plane_prim_h
Initial value:
= Equality_comparable<P>&& requires(
    P& p, P& q, L& l)
{
    {
        incident(p, l)
    }
    ->bool;
    {
        p* q
    }
    ->L;
    {
        p.aux()
    }
    ->L;
}
Projective plane Concept (half)
Template Parameters
P Point
L Line
Definition at line 23 of file proj_plane_concepts.h.
Range
template<typename T > concept bool fun::Range
Initial value:
= requires(T range)
{
    typename Iterator_type<T>;
    { std::begin(range) } -> Iterator_type<T>;
    { std::end(range) } -> Iterator_type<T>;
}
Definition at line 43 of file common_concepts.h.
Sequence
template<typename T > concept bool fun::Sequence
Initial value:
= requires(T t, Element_type<T> x)
{
    { t.size() } -> int;
    { t.empty() } -> bool;
    { t.back() } -> Element_type<T>;
    { t.push_back(x) }
}
Sequence.
Template Parameters
T
Definition at line 34 of file common_concepts.h.