PgCpp: fun::ck< _P, _L, Derived > Struct Template Reference
fun::ck< _P, _L, Derived > Struct Template Reference
#include <ck_plane.hpp>
Public Types
using point_t = _P
using line_t = _L
using cDer = const Derived< _P, _L >
Public Member Functions
constexpr ck ()
construct ck object
template<Projective_plane_prim2 L>
constexpr auto is_perpendicular (const L &l, const L &m) const -> bool
is perpendicular
template<typename P , typename L = typename P::dual>
requires Projective_plane_prim< P, L > constexpr auto altitude (const P &p, const L &l) const -> L
altitude
constexpr auto tri_altitude (const Triple< Projective_plane_prim2 > &tri) const
altitudes of triangle
constexpr auto orthocenter (const Triple< Projective_plane_prim2 > &tri) const
ortho-center
auto reflect (const Projective_plane2 &m) const
reflect
constexpr auto tri_measure (const Triple< Projective_plane2 > &tri) const
measure of triangle
constexpr auto quadrance (const _P &p, const _P &q) const
quadrance between two points
constexpr auto spread (const _L &l, const _L &m) const
spread between two lines
constexpr auto tri_quadrance (const Triple< _P > &triangle) const
quadrances of triangle
constexpr auto tri_spread (const Triple< _L > &trilateral) const
spreads of triangle
Public Attributes
cDer & self = *static_cast<cDer*>(this)
Detailed Description
template<typename _P, typename _L, template< typename P, typename L > class Derived>
struct fun::ck< _P, _L, Derived >
Template Parameters
_P
_L
Derived
Definition at line 21 of file ck_plane.hpp.
Member Typedef Documentation
cDer
template<typename _P, typename _L, template< typename P, typename L > class Derived> using fun::ck< _P, _L, Derived >::cDer = const Derived<_P, _L>
Definition at line 26 of file ck_plane.hpp.
line_t
template<typename _P, typename _L, template< typename P, typename L > class Derived> using fun::ck< _P, _L, Derived >::line_t = _L
Definition at line 24 of file ck_plane.hpp.
point_t
template<typename _P, typename _L, template< typename P, typename L > class Derived> using fun::ck< _P, _L, Derived >::point_t = _P
Definition at line 23 of file ck_plane.hpp.
Constructor & Destructor Documentation
ck()
template<typename _P, typename _L, template< typename P, typename L > class Derived> constexpr fun::ck< _P, _L, Derived >::ck () inline explicit
construct ck object
Definition at line 33 of file ck_plane.hpp.
Member Function Documentation
altitude()
template<typename _P, typename _L, template< typename P, typename L > class Derived> template<typename P , typename L = typename P::dual> requires Projective_plane_prim<P, L> constexpr auto fun::ck< _P, _L, Derived >::altitude (const P & p, const L & l) const -> L inline
altitude
Parameters
p
l
Returns
L
Definition at line 62 of file ck_plane.hpp.
Referenced by fun::ck< P, L, myck >::orthocenter(), and fun::ck< P, L, myck >::tri_altitude().
is_perpendicular()
template<typename _P, typename _L, template< typename P, typename L > class Derived> template<Projective_plane_prim2 L> constexpr auto fun::ck< _P, _L, Derived >::is_perpendicular (const L & l, const L & m) const -> bool inline
is perpendicular
Template Parameters
L
Parameters
l
m
Returns
true
false
Definition at line 48 of file ck_plane.hpp.
orthocenter()
template<typename _P, typename _L, template< typename P, typename L > class Derived> constexpr auto fun::ck< _P, _L, Derived >::orthocenter (const Triple< Projective_plane_prim2 > & tri) const inline
ortho-center
Parameters
tri
Returns
P
Definition at line 90 of file ck_plane.hpp.
quadrance()
template<typename _P, typename _L, template< typename P, typename L > class Derived> constexpr auto fun::ck< _P, _L, Derived >::quadrance (const _P & p, const _P & q) const inline
quadrance between two points
Parameters
p
q
Returns
constexpr auto
Definition at line 133 of file ck_plane.hpp.
reflect()
template<typename _P, typename _L, template< typename P, typename L > class Derived> auto fun::ck< _P, _L, Derived >::reflect (const Projective_plane2 & m) const inline
reflect
Parameters
m
Returns
auto
Definition at line 105 of file ck_plane.hpp.
spread()
template<typename _P, typename _L, template< typename P, typename L > class Derived> constexpr auto fun::ck< _P, _L, Derived >::spread (const _L & l, const _L & m) const inline
spread between two lines
Parameters
l
m
Returns
constexpr auto
Definition at line 145 of file ck_plane.hpp.
tri_altitude()
template<typename _P, typename _L, template< typename P, typename L > class Derived> constexpr auto fun::ck< _P, _L, Derived >::tri_altitude (const Triple< Projective_plane_prim2 > & tri) const inline
altitudes of triangle
Parameters
tri
Returns
std::tuple
Definition at line 73 of file ck_plane.hpp.
tri_measure()
template<typename _P, typename _L, template< typename P, typename L > class Derived> constexpr auto fun::ck< _P, _L, Derived >::tri_measure (const Triple< Projective_plane2 > & tri) const inline
measure of triangle
Parameters
tri
Returns
constexpr auto
Definition at line 116 of file ck_plane.hpp.
Referenced by fun::ck< P, L, myck >::tri_quadrance(), and fun::ck< P, L, myck >::tri_spread().
tri_quadrance()
template<typename _P, typename _L, template< typename P, typename L > class Derived> constexpr auto fun::ck< _P, _L, Derived >::tri_quadrance (const Triple< _P > & triangle) const inline
quadrances of triangle
Parameters
triangle
Returns
constexpr auto
Definition at line 156 of file ck_plane.hpp.
tri_spread()
template<typename _P, typename _L, template< typename P, typename L > class Derived> constexpr auto fun::ck< _P, _L, Derived >::tri_spread (const Triple< _L > & trilateral) const inline
spreads of triangle
Parameters
trilateral
Returns
constexpr auto
Definition at line 167 of file ck_plane.hpp.
Member Data Documentation
self
template<typename _P, typename _L, template< typename P, typename L > class Derived> cDer& fun::ck< _P, _L, Derived >::self = *static_cast<cDer*>(this)
Definition at line 27 of file ck_plane.hpp.
The documentation for this struct was generated from the following file:
lib/include/pgcpp/ck_plane.hpp