PgCpp: lib/test/src/test_persp_plane.cpp File Reference
test_persp_plane.cpp File Reference
#include "pgcpp/euclid_plane.hpp"
#include "pgcpp/persp_plane.hpp"
#include "pgcpp/pg_line.hpp"
#include "pgcpp/pg_point.hpp"
#include <boost/multiprecision/cpp_int.hpp>
#include <catch2/catch.hpp>
#include <iostream>
Functions
template<typename PG >
void chk_degenerate (const PG &myck)
chk_degenerate (P)
Variables
static auto Zero = Approx(0).margin(0.01)
auto Ire = pg_point<cpp_int>(0, 1, 1)
auto Iim = pg_point<cpp_int>(1, 0, 0)
auto l_inf = pg_line<cpp_int>(0, -1, 1)
auto P
Function Documentation
chk_degenerate() [1/2]
template<typename PG > void chk_degenerate (const PG & myck)
Template Parameters
PG
Parameters
myck
Definition at line 23 of file test_persp_plane.cpp.
References a1, a2, a3, CHECK(), fun::coincident(), fun::plucker(), fun::sq(), TEST_CASE(), fun::tri_dual(), triangle, and Zero.
chk_degenerate() [2/2]
chk_degenerate (P)
Variable Documentation
Iim
auto Iim = pg_point<cpp_int>(1, 0, 0)
Definition at line 84 of file test_persp_plane.cpp.
Ire
auto Ire = pg_point<cpp_int>(0, 1, 1)
Definition at line 83 of file test_persp_plane.cpp.
l_inf
auto l_inf = pg_line<cpp_int>(0, -1, 1)
Definition at line 85 of file test_persp_plane.cpp.
P
auto P
Initial value:
=
        persp_euclid_plane {std::move(Ire), std::move(Iim), std::move(l_inf)}
Definition at line 87 of file test_persp_plane.cpp.
Zero
auto Zero = Approx(0).margin(0.01) static
Definition at line 14 of file test_persp_plane.cpp.
Referenced by chk_degenerate().