PgCpp: lib/test/src/test_euclid.cpp File Reference
test_euclid.cpp File Reference
#include "pgcpp/ck_plane.hpp"
#include "pgcpp/euclid_plane.hpp"
#include "pgcpp/pg_line.hpp"
#include "pgcpp/pg_point.hpp"
#include <boost/multiprecision/cpp_int.hpp>
#include <catch2/catch.hpp>
#include <iostream>
Typedefs
using P = pg_point< cpp_int >
Functions
auto ApproxZero (const auto &a) -> bool
template<Projective_plane_prim2 P>
void chk_euclid (Triple< P > &triangle)
template<typename T >
void chk_cyclic (const T &quadangle)
chk_euclid (triangle)
chk_cyclic (quadangle)
Variables
static auto Zero = Approx(0).margin(0.01)
auto a1 = pg_point<cpp_int> {1, 3, 1}
auto a2 = pg_point<cpp_int> {4, 2, 1}
auto a3 = pg_point<cpp_int> {4, -3, 1}
auto triangle = std::tuple {std::move(a1), std::move(a2), std::move(a3)}
auto u1 = uc_point<P>(1, 0)
auto u2 = uc_point<P>(3, 4)
auto u3 = uc_point<P>(-1, 2)
auto u4 = uc_point<P>(0, 1)
auto quadangle
Typedef Documentation
P
auto P
Initial value:
{
    using boost::multiprecision::cpp_int
Definition at line 181 of file test_euclid.cpp.
Function Documentation
ApproxZero()
auto ApproxZero (const auto & a) -> bool inline
Parameters
a
Returns
true
false
Definition at line 23 of file test_euclid.cpp.
References Zero.
Referenced by chk_euclid().
chk_cyclic() [1/2]
template<typename T > void chk_cyclic (const T & quadangle)
Definition at line 129 of file test_euclid.cpp.
References CHECK(), quadangle, TEST_CASE(), u1, u2, u3, u4, and Zero.
chk_cyclic() [2/2]
chk_cyclic (quadangle)
chk_euclid() [1/2]
template<Projective_plane_prim2 P> void chk_euclid (Triple< P > & triangle)
Template Parameters
T
Parameters
triangle
Definition at line 35 of file test_euclid.cpp.
References a1, a2, a3, ApproxZero(), CHECK(), fun::check_sine_law(), fun::coincident(), fun::cross(), fun::cross2(), fun::dot1(), fun::is_parallel(), fun::is_perpendicular(), fun::meet(), fun::plucker(), fun::sq(), fun::tri_dual(), triangle, and Zero.
chk_euclid() [2/2]
chk_euclid (triangle)
Variable Documentation
a1
auto a1 = pg_point<cpp_int> {1, 3, 1}
Definition at line 160 of file test_euclid.cpp.
Referenced by chk_ck(), chk_degenerate(), chk_euclid(), chk_tri(), fun::is_parallel(), fun::ck< P, L, myck >::orthocenter(), fun::ck< P, L, myck >::tri_altitude(), fun::tri_dual(), fun::tri_func(), fun::ck< P, L, myck >::tri_measure(), and fun::persp_euclid_plane< P, L >::tri_midpoint().
a2
auto a2 = pg_point<cpp_int> {4, 2, 1}
Definition at line 161 of file test_euclid.cpp.
Referenced by chk_ck(), chk_degenerate(), chk_euclid(), chk_tri(), fun::is_parallel(), fun::ck< P, L, myck >::orthocenter(), fun::ck< P, L, myck >::tri_altitude(), fun::tri_dual(), fun::tri_func(), fun::ck< P, L, myck >::tri_measure(), and fun::persp_euclid_plane< P, L >::tri_midpoint().
a3
auto a3 = pg_point<cpp_int> {4, -3, 1}
Definition at line 162 of file test_euclid.cpp.
Referenced by chk_ck(), chk_degenerate(), chk_euclid(), chk_tri(), fun::is_parallel(), fun::ck< P, L, myck >::orthocenter(), fun::ck< P, L, myck >::tri_altitude(), fun::tri_dual(), fun::tri_func(), fun::ck< P, L, myck >::tri_measure(), and fun::persp_euclid_plane< P, L >::tri_midpoint().
quadangle
auto quadangle
Initial value:
=
        std::tuple {std::move(u1), std::move(u2), std::move(u3), std::move(u4)}
Definition at line 188 of file test_euclid.cpp.
Referenced by chk_cyclic().
triangle
auto triangle = std::tuple {std::move(a1), std::move(a2), std::move(a3)}
Definition at line 164 of file test_euclid.cpp.
Referenced by chk_ck(), chk_degenerate(), chk_euclid(), chk_tri(), and fun::is_parallel().
u1
auto u1 = uc_point<P>(1, 0)
Definition at line 183 of file test_euclid.cpp.
Referenced by chk_cyclic().
u2
auto u2 = uc_point<P>(3, 4)
Definition at line 184 of file test_euclid.cpp.
Referenced by chk_cyclic().
u3
auto u3 = uc_point<P>(-1, 2)
Definition at line 185 of file test_euclid.cpp.
Referenced by chk_cyclic().
u4
auto u4 = uc_point<P>(0, 1)
Definition at line 186 of file test_euclid.cpp.
Referenced by chk_cyclic().
Zero
auto Zero = Approx(0).margin(0.01) static
Definition at line 14 of file test_euclid.cpp.
Referenced by ApproxZero(), chk_cyclic(), and chk_euclid().