NetOptimCpp: fun::Fraction< Z > Struct Template Reference
fun::Fraction< Z > Struct Template Reference
#include <fractions.hpp>
Public Types
using _Self = Fraction< Z >
Public Member Functions
constexpr Fraction (const Z &numerator, const Z &denominator)
Construct a new Fraction object.
constexpr Fraction (const Z &numerator)
Construct a new Fraction object.
constexpr Fraction ()=default
Construct a new Fraction object.
constexpr const Z & numerator () const
constexpr const Z & denominator () const
constexpr _Self abs () const
constexpr void reciprocal ()
constexpr _Self operator- () const
constexpr _Self operator+ (const _Self &frac) const
constexpr _Self operator- (const _Self &frac) const
constexpr _Self operator* (const _Self &frac) const
constexpr _Self operator/ (_Self frac) const
constexpr _Self operator+ (const Z &i) const
constexpr _Self operator- (const Z &i) const
constexpr _Self operator* (const Z &i) const
constexpr _Self operator/ (const Z &i) const
constexpr _Self operator+= (const _Self &frac)
constexpr _Self operator-= (const _Self &frac)
constexpr _Self operator*= (const _Self &frac)
constexpr _Self operator/= (const _Self &frac)
constexpr _Self operator+= (const Z &i)
constexpr _Self operator-= (const Z &i)
constexpr _Self operator*= (const Z &i)
constexpr _Self operator/= (const Z &i)
template<typename U >
constexpr auto cmp (const Fraction< U > &frac) const
Three way comparison.
template<typename U >
constexpr bool operator== (const Fraction< U > &frac) const
template<typename U >
constexpr bool operator!= (const Fraction< U > &frac) const
template<typename U >
constexpr bool operator< (const Fraction< U > &frac) const
template<typename U >
constexpr bool operator> (const Fraction< U > &frac) const
template<typename U >
constexpr bool operator<= (const Fraction< U > &frac) const
template<typename U >
constexpr bool operator>= (const Fraction< U > &frac) const
constexpr auto cmp (const Z &c) const
constexpr bool operator== (const Z &c) const
constexpr bool operator!= (const Z &c) const
constexpr bool operator< (const Z &c) const
constexpr bool operator> (const Z &c) const
constexpr bool operator<= (const Z &c) const
constexpr bool operator>= (const Z &c) const
constexpr operator double ()
Public Attributes
Z _numerator
Z _denominator
Detailed Description
template<typename Z>
struct fun::Fraction< Z >
Definition at line 40 of file fractions.hpp.
Member Typedef Documentation
_Self
template<typename Z> using fun::Fraction< Z >::_Self = Fraction<Z>
Definition at line 41 of file fractions.hpp.
Constructor & Destructor Documentation
Fraction() [1/3]
template<typename Z> constexpr fun::Fraction< Z >::Fraction (const Z & numerator, const Z & denominator) inline
Construct a new Fraction object.
Parameters
numerator
denominator
Definition at line 52 of file fractions.hpp.
References fun::gcd().
Fraction() [2/3]
template<typename Z> constexpr fun::Fraction< Z >::Fraction (const Z & numerator) inline explicit
Construct a new Fraction object.
Parameters
numerator
Definition at line 63 of file fractions.hpp.
References fun::Fraction< Z >::Fraction().
Fraction() [3/3]
template<typename Z> constexpr fun::Fraction< Z >::Fraction () default
Construct a new Fraction object.
Referenced by fun::Fraction< Z >::Fraction().
Member Function Documentation
abs()
template<typename Z> constexpr _Self fun::Fraction< Z >::abs () const inline
Returns
_Self
Definition at line 93 of file fractions.hpp.
cmp() [1/2]
template<typename Z> template<typename U > constexpr auto fun::Fraction< Z >::cmp (const Fraction< U > & frac) const inline
Three way comparison.
Parameters
frac
Returns
auto
Definition at line 280 of file fractions.hpp.
References fun::Fraction< Z >::_denominator, and fun::Fraction< Z >::_numerator.
Referenced by fun::Fraction< Z >::operator!=(), fun::Fraction< Z >::operator<(), fun::Fraction< Z >::operator<=(), fun::Fraction< Z >::operator==(), fun::Fraction< Z >::operator>(), and fun::Fraction< Z >::operator>=().
cmp() [2/2]
template<typename Z> constexpr auto fun::Fraction< Z >::cmp (const Z & c) const inline
Parameters
c
Returns
auto
Definition at line 377 of file fractions.hpp.
denominator()
template<typename Z> constexpr const Z& fun::Fraction< Z >::denominator () const inline
Returns
const Z&
Definition at line 86 of file fractions.hpp.
References fun::Fraction< Z >::_denominator.
numerator()
template<typename Z> constexpr const Z& fun::Fraction< Z >::numerator () const inline
Returns
const Z&
Definition at line 79 of file fractions.hpp.
References fun::Fraction< Z >::_numerator.
Referenced by fun::operator<<().
operator double()
template<typename Z> constexpr fun::Fraction< Z >::operator double () inline explicit
Returns
double
Definition at line 440 of file fractions.hpp.
References fun::Fraction< Z >::_denominator.
operator!=() [1/2]
template<typename Z> template<typename U > constexpr bool fun::Fraction< Z >::operator!= (const Fraction< U > & frac) const inline
Template Parameters
U
Parameters
frac
Returns
true
false
Definition at line 312 of file fractions.hpp.
operator!=() [2/2]
template<typename Z> constexpr bool fun::Fraction< Z >::operator!= (const Z & c) const inline
Parameters
c
Returns
true
false
Definition at line 397 of file fractions.hpp.
References fun::Fraction< Z >::cmp().
operator*() [1/2]
template<typename Z> constexpr _Self fun::Fraction< Z >::operator* (const _Self & frac) const inline
Parameters
frac
Returns
_Self
Definition at line 144 of file fractions.hpp.
References fun::Fraction< Z >::_denominator, and fun::Fraction< Z >::_numerator.
operator*() [2/2]
template<typename Z> constexpr _Self fun::Fraction< Z >::operator* (const Z & i) const inline
Parameters
i
Returns
_Self
Definition at line 186 of file fractions.hpp.
operator*=() [1/2]
template<typename Z> constexpr _Self fun::Fraction< Z >::operator*= (const _Self & frac) inline
Parameters
frac
Returns
_Self
Definition at line 228 of file fractions.hpp.
operator*=() [2/2]
template<typename Z> constexpr _Self fun::Fraction< Z >::operator*= (const Z & i) inline
Parameters
i
Returns
_Self
Definition at line 264 of file fractions.hpp.
operator+() [1/2]
template<typename Z> constexpr _Self fun::Fraction< Z >::operator+ (const _Self & frac) const inline
Parameters
frac
Returns
_Self
Definition at line 118 of file fractions.hpp.
References fun::Fraction< Z >::_denominator, fun::Fraction< Z >::_numerator, and fun::lcm().
operator+() [2/2]
template<typename Z> constexpr _Self fun::Fraction< Z >::operator+ (const Z & i) const inline
Parameters
i
Returns
_Self
Definition at line 167 of file fractions.hpp.
operator+=() [1/2]
template<typename Z> constexpr _Self fun::Fraction< Z >::operator+= (const _Self & frac) inline
Parameters
frac
Returns
_Self
Definition at line 208 of file fractions.hpp.
operator+=() [2/2]
template<typename Z> constexpr _Self fun::Fraction< Z >::operator+= (const Z & i) inline
Parameters
i
Returns
_Self
Definition at line 248 of file fractions.hpp.
operator-() [1/3]
template<typename Z> constexpr _Self fun::Fraction< Z >::operator- () const inline
Returns
_Self
Definition at line 108 of file fractions.hpp.
operator-() [2/3]
template<typename Z> constexpr _Self fun::Fraction< Z >::operator- (const _Self & frac) const inline
Parameters
frac
Returns
_Self
Definition at line 134 of file fractions.hpp.
operator-() [3/3]
template<typename Z> constexpr _Self fun::Fraction< Z >::operator- (const Z & i) const inline
Parameters
i
Returns
_Self
Definition at line 178 of file fractions.hpp.
operator-=() [1/2]
template<typename Z> constexpr _Self fun::Fraction< Z >::operator-= (const _Self & frac) inline
Parameters
frac
Returns
_Self
Definition at line 218 of file fractions.hpp.
operator-=() [2/2]
template<typename Z> constexpr _Self fun::Fraction< Z >::operator-= (const Z & i) inline
Parameters
i
Returns
_Self
Definition at line 256 of file fractions.hpp.
operator/() [1/2]
template<typename Z> constexpr _Self fun::Fraction< Z >::operator/ (_Self frac) const inline
Parameters
frac
Returns
_Self
Definition at line 156 of file fractions.hpp.
References fun::Fraction< Z >::reciprocal().
operator/() [2/2]
template<typename Z> constexpr _Self fun::Fraction< Z >::operator/ (const Z & i) const inline
Parameters
i
Returns
_Self
Definition at line 197 of file fractions.hpp.
operator/=() [1/2]
template<typename Z> constexpr _Self fun::Fraction< Z >::operator/= (const _Self & frac) inline
Parameters
frac
Returns
_Self
Definition at line 238 of file fractions.hpp.
operator/=() [2/2]
template<typename Z> constexpr _Self fun::Fraction< Z >::operator/= (const Z & i) inline
Parameters
i
Returns
_Self
Definition at line 272 of file fractions.hpp.
operator<() [1/2]
template<typename Z> template<typename U > constexpr bool fun::Fraction< Z >::operator< (const Fraction< U > & frac) const inline
Template Parameters
U
Parameters
frac
Returns
true
false
Definition at line 325 of file fractions.hpp.
References fun::Fraction< Z >::cmp().
operator<() [2/2]
template<typename Z> constexpr bool fun::Fraction< Z >::operator< (const Z & c) const inline
Parameters
c
Returns
true
false
Definition at line 406 of file fractions.hpp.
References fun::Fraction< Z >::cmp().
operator<=() [1/2]
template<typename Z> template<typename U > constexpr bool fun::Fraction< Z >::operator<= (const Fraction< U > & frac) const inline
Template Parameters
U
Parameters
frac
Returns
true
false
Definition at line 354 of file fractions.hpp.
operator<=() [2/2]
template<typename Z> constexpr bool fun::Fraction< Z >::operator<= (const Z & c) const inline
Parameters
c
Returns
true
false
Definition at line 424 of file fractions.hpp.
References fun::Fraction< Z >::cmp().
operator==() [1/2]
template<typename Z> template<typename U > constexpr bool fun::Fraction< Z >::operator== (const Fraction< U > & frac) const inline
Template Parameters
U
Parameters
frac
Returns
true
false
Definition at line 296 of file fractions.hpp.
References fun::Fraction< Z >::_denominator, fun::Fraction< Z >::_numerator, and fun::Fraction< Z >::cmp().
operator==() [2/2]
template<typename Z> constexpr bool fun::Fraction< Z >::operator== (const Z & c) const inline
Parameters
c
Returns
true
false
Definition at line 388 of file fractions.hpp.
References fun::Fraction< Z >::cmp().
operator>() [1/2]
template<typename Z> template<typename U > constexpr bool fun::Fraction< Z >::operator> (const Fraction< U > & frac) const inline
Template Parameters
U
Parameters
frac
Returns
true
false
Definition at line 341 of file fractions.hpp.
operator>() [2/2]
template<typename Z> constexpr bool fun::Fraction< Z >::operator> (const Z & c) const inline
Parameters
c
Returns
true
false
Definition at line 415 of file fractions.hpp.
References fun::Fraction< Z >::cmp().
operator>=() [1/2]
template<typename Z> template<typename U > constexpr bool fun::Fraction< Z >::operator>= (const Fraction< U > & frac) const inline
Template Parameters
U
Parameters
frac
Returns
true
false
Definition at line 367 of file fractions.hpp.
operator>=() [2/2]
template<typename Z> constexpr bool fun::Fraction< Z >::operator>= (const Z & c) const inline
Parameters
c
Returns
true
false
Definition at line 433 of file fractions.hpp.
References fun::Fraction< Z >::cmp().
reciprocal()
template<typename Z> constexpr void fun::Fraction< Z >::reciprocal () inline
Definition at line 101 of file fractions.hpp.
Referenced by fun::Fraction< Z >::operator/().
Member Data Documentation
_denominator
template<typename Z> Z fun::Fraction< Z >::_denominator
Definition at line 44 of file fractions.hpp.
Referenced by fun::Fraction< Z >::cmp(), fun::Fraction< Z >::denominator(), fun::Fraction< Z >::operator double(), fun::Fraction< Z >::operator*(), fun::Fraction< Z >::operator+(), and fun::Fraction< Z >::operator==().
_numerator
template<typename Z> Z fun::Fraction< Z >::_numerator
Definition at line 43 of file fractions.hpp.
Referenced by fun::Fraction< Z >::cmp(), fun::Fraction< Z >::numerator(), fun::Fraction< Z >::operator*(), fun::Fraction< Z >::operator+(), and fun::Fraction< Z >::operator==().
The documentation for this struct was generated from the following file:
lib/include/py2cpp/fractions.hpp