NetOptimCpp: lib/test/src/test_cycle_ratio_boost.cpp File Reference
test_cycle_ratio_boost.cpp File Reference
#include <boost/graph/adjacency_list.hpp>
#include <boost/graph/graph_traits.hpp>
#include <boost/graph/properties.hpp>
#include <boost/property_map/property_map.hpp>
#include <catch.hpp>
#include <netoptim/min_cycle_ratio.hpp>
#include <py2cpp/fractions.hpp>
#include <py2cpp/nx2bgl.hpp>
#include <utility>
#include <vector>
Namespaces
boost
Typedefs
using graph_t = boost::adjacency_list< boost::vecS, boost::vecS, boost::directedS, boost::no_property, boost::property< boost::edge_id_tag_t, std::size_t > >
using Vertex = typename boost::graph_traits< graph_t >::vertex_descriptor
using edge_t = typename boost::graph_traits< graph_t >::edge_iterator
using IterMap = boost::iterator_property_map< int *, EdgeIndexMap, int, int & >
Enumerations
enum boost::edge_id_tag_t { boost::id_tag }
Functions
boost::BOOST_INSTALL_PROPERTY (edge, id_tag)
static auto create_test_case1 ()
static auto create_test_case_timing ()
IterMap cost_pa (cost, edge_id)
CHECK (!c.empty())
CHECK (c.size()==5)
CHECK (r==fun::Fraction< int >(9, 5))
Variables
auto G = create_test_case1()
int cost [] = {5, 1, 1, 1, 1}
EdgeIndexMap edge_id = boost::get(boost::id_tag, G)
auto get_cost
auto get_time = [&](const xn::grAdaptor<graph_t>& G, const auto& e) -> int { return 1; }
auto [r, c] = min_cycle_ratio(G, get_cost, get_time, fun::Fraction<int>{})
Typedef Documentation
edge_t
using edge_t = typename boost::graph_traits<graph_t>::edge_iterator
Definition at line 29 of file test_cycle_ratio_boost.cpp.
graph_t
using graph_t = boost::adjacency_list<boost::vecS, boost::vecS, boost::directedS, boost::no_property, boost::property<boost::edge_id_tag_t, std::size_t> >
Definition at line 27 of file test_cycle_ratio_boost.cpp.
IterMap
typedef boost::iterator_property_map< int *, EdgeIndexMap, int, int & > IterMap
Initial value:
{
    using EdgeIndexMap = typename boost::property_map<graph_t, boost::edge_id_tag_t>::type
Definition at line 74 of file test_cycle_ratio_boost.cpp.
Vertex
using Vertex = typename boost::graph_traits<graph_t>::vertex_descriptor
Definition at line 28 of file test_cycle_ratio_boost.cpp.
Function Documentation
CHECK() [1/3]
CHECK (!c. empty())
Referenced by TEST_CASE().
CHECK() [2/3]
CHECK (c. size() = =5)
CHECK() [3/3]
CHECK (r = =fun::Fraction< int >(9, 5))
cost_pa()
IterMap cost_pa (cost , edge_id)
create_test_case1()
static auto create_test_case1 () static
Definition at line 31 of file test_cycle_ratio_boost.cpp.
create_test_case_timing()
static auto create_test_case_timing () static
Definition at line 51 of file test_cycle_ratio_boost.cpp.
References TEST_CASE().
Variable Documentation
auto
auto[r, c] = min_cycle_ratio(G, get_cost, get_time, fun::Fraction<int>{})
Definition at line 86 of file test_cycle_ratio_boost.cpp.
cost
int cost = {5, 1, 1, 1, 1}
Definition at line 77 of file test_cycle_ratio_boost.cpp.
Referenced by TEST_CASE().
edge_id
EdgeIndexMap edge_id = boost::get(boost::id_tag, G)
Definition at line 78 of file test_cycle_ratio_boost.cpp.
G
auto G = create_test_case1()
Definition at line 76 of file test_cycle_ratio_boost.cpp.
Referenced by xn::AtlasView< Vertex, Graph >::AtlasView(), do_case(), max_parametric(), min_cycle_ratio(), and TEST_CASE().
get_cost
auto get_cost
Initial value:
= [&](const xn::grAdaptor<graph_t>& G, const auto& e) -> int {
        return boost::get(cost_pa, e);
    }
Definition at line 81 of file test_cycle_ratio_boost.cpp.
Referenced by min_cycle_ratio(), and TEST_CASE().
get_time
auto get_time = [&](const xn::grAdaptor<graph_t>& G, const auto& e) -> int { return 1; }
Definition at line 84 of file test_cycle_ratio_boost.cpp.
Referenced by min_cycle_ratio(), and TEST_CASE().