--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#2E3440"
foreground="#E5E9F0"
cursor="#E5E9F0"

-- Colors
color0="#2E3440"
color1="#88C0D0"
color2="#BF616A"
color3="#5E81AC"
color4="#EBCB8B"
color5="#A3BE8C"
color6="#D08770"
color7="#E5E9F0"
color8="#4C566A"
color9="#88C0D0"
color10="#BF616A"
color11="#5E81AC"
color12="#EBCB8B"
color13="#A3BE8C"
color14="#D08770"
color15="#8FBCBB"
