CkPttnCpp: iter::impl::WindowSlider< Container > Class Template Reference
iter::impl::WindowSlider< Container > Class Template Reference
#include <sliding_window.hpp>
Classes
class Iterator
Public Member Functions
WindowSlider (WindowSlider &&)=default
Iterator< Container > begin ()
Iterator< Container > end ()
Iterator< AsConst< Container > > begin () const
Iterator< AsConst< Container > > end () const
Private Types
template<typename T >
using IndexVector = std::deque< IteratorWrapper< T > >
template<typename T >
using DerefVec = IterIterWrapper< IndexVector< T > >
Private Member Functions
WindowSlider (Container &&container, std::size_t win_sz)
Private Attributes
Container container_
std::size_t window_size_
friend SlidingWindowFn
Detailed Description
template<typename Container>
class iter::impl::WindowSlider< Container >
Definition at line 15 of file sliding_window.hpp.
Member Typedef Documentation
DerefVec
template<typename Container > template<typename T > using iter::impl::WindowSlider< Container >::DerefVec = IterIterWrapper<IndexVector<T> > private
Definition at line 35 of file sliding_window.hpp.
IndexVector
template<typename Container > template<typename T > using iter::impl::WindowSlider< Container >::IndexVector = std::deque<IteratorWrapper<T> > private
Definition at line 33 of file sliding_window.hpp.
Constructor & Destructor Documentation
WindowSlider() [1/2]
template<typename Container > iter::impl::WindowSlider< Container >::WindowSlider (Container && container, std::size_t win_sz) inline private
Definition at line 29 of file sliding_window.hpp.
WindowSlider() [2/2]
template<typename Container > iter::impl::WindowSlider< Container >::WindowSlider (WindowSlider< Container > &&) default
Member Function Documentation
begin() [1/2]
template<typename Container > Iterator<Container> iter::impl::WindowSlider< Container >::begin () inline
Definition at line 99 of file sliding_window.hpp.
References iter::impl::get_iters::get_begin(), and iter::impl::get_iters::get_end().
begin() [2/2]
template<typename Container > Iterator<AsConst<Container> > iter::impl::WindowSlider< Container >::begin () const inline
Definition at line 110 of file sliding_window.hpp.
References iter::impl::get_iters::get_begin(), and iter::impl::get_iters::get_end().
end() [1/2]
template<typename Container > Iterator<Container> iter::impl::WindowSlider< Container >::end () inline
Definition at line 106 of file sliding_window.hpp.
References iter::impl::get_iters::get_end().
end() [2/2]
template<typename Container > Iterator<AsConst<Container> > iter::impl::WindowSlider< Container >::end () const inline
Definition at line 118 of file sliding_window.hpp.
References iter::impl::get_iters::get_end().
Member Data Documentation
container_
template<typename Container > Container iter::impl::WindowSlider< Container >::container_ private
Definition at line 24 of file sliding_window.hpp.
SlidingWindowFn
template<typename Container > friend iter::impl::WindowSlider< Container >::SlidingWindowFn private
Definition at line 27 of file sliding_window.hpp.
window_size_
template<typename Container > std::size_t iter::impl::WindowSlider< Container >::window_size_ private
Definition at line 25 of file sliding_window.hpp.
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/sliding_window.hpp