CkPttnCpp: iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT > Class Template Reference
iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT > Class Template Reference
#include <combinations_with_replacement.hpp>
Public Types
using iterator_category = std::input_iterator_tag
using value_type = CombIteratorDeref< ContainerT >
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
Public Member Functions
Iterator (ContainerT &in_container, std::size_t n)
CombIteratorDeref< ContainerT > & operator* ()
CombIteratorDeref< ContainerT > * operator-> ()
Iterator & operator++ ()
Iterator operator++ (int)
template<typename T >
bool operator!= (const Iterator< T > &other) const
template<typename T >
bool operator== (const Iterator< T > &other) const
Private Attributes
std::remove_reference_t< ContainerT > * container_p_
CombIteratorDeref< ContainerT > indices_
int steps_
Static Private Attributes
static constexpr const int COMPLETE = -1
Friends
template<typename >
class Iterator
Detailed Description
template<typename Container>
template<typename ContainerT>
class iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >
Definition at line 40 of file combinations_with_replacement.hpp.
Member Typedef Documentation
difference_type
template<typename Container > template<typename ContainerT> using iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::difference_type = std::ptrdiff_t
Definition at line 52 of file combinations_with_replacement.hpp.
iterator_category
template<typename Container > template<typename ContainerT> using iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::iterator_category = std::input_iterator_tag
Definition at line 50 of file combinations_with_replacement.hpp.
pointer
template<typename Container > template<typename ContainerT> using iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::pointer = value_type*
Definition at line 53 of file combinations_with_replacement.hpp.
reference
template<typename Container > template<typename ContainerT> using iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::reference = value_type&
Definition at line 54 of file combinations_with_replacement.hpp.
value_type
template<typename Container > template<typename ContainerT> using iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::value_type = CombIteratorDeref<ContainerT>
Definition at line 51 of file combinations_with_replacement.hpp.
Constructor & Destructor Documentation
Iterator()
template<typename Container > template<typename ContainerT> iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::Iterator (ContainerT & in_container, std::size_t n) inline
Definition at line 56 of file combinations_with_replacement.hpp.
References iter::impl::get_iters::get_begin(), iter::impl::get_iters::get_end(), and iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::indices_.
Member Function Documentation
operator!=()
template<typename Container > template<typename ContainerT> template<typename T > bool iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::operator!= (const Iterator< T > & other) const inline
Definition at line 105 of file combinations_with_replacement.hpp.
operator*()
template<typename Container > template<typename ContainerT> CombIteratorDeref<ContainerT>& iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::operator* () inline
Definition at line 63 of file combinations_with_replacement.hpp.
References iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::indices_.
operator++() [1/2]
template<typename Container > template<typename ContainerT> Iterator& iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::operator++ () inline
Definition at line 71 of file combinations_with_replacement.hpp.
References iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::COMPLETE, iter::impl::dumb_next(), iter::impl::IterIterWrapper< Container >::get(), iter::impl::get_iters::get_end(), and iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::steps_.
operator++() [2/2]
template<typename Container > template<typename ContainerT> Iterator iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::operator++ (int) inline
Definition at line 98 of file combinations_with_replacement.hpp.
operator->()
template<typename Container > template<typename ContainerT> CombIteratorDeref<ContainerT>* iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::operator-> () inline
Definition at line 67 of file combinations_with_replacement.hpp.
References iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::indices_.
operator==()
template<typename Container > template<typename ContainerT> template<typename T > bool iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::operator== (const Iterator< T > & other) const inline
Definition at line 110 of file combinations_with_replacement.hpp.
References iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::steps_.
Friends And Related Function Documentation
Iterator
template<typename Container > template<typename ContainerT> template<typename > friend class Iterator friend
Definition at line 43 of file combinations_with_replacement.hpp.
Member Data Documentation
COMPLETE
template<typename Container > template<typename ContainerT> constexpr const int iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::COMPLETE = -1 static private
Definition at line 44 of file combinations_with_replacement.hpp.
Referenced by iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::operator++().
container_p_
template<typename Container > template<typename ContainerT> std::remove_reference_t<ContainerT>* iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::container_p_ private
Definition at line 45 of file combinations_with_replacement.hpp.
indices_
template<typename Container > template<typename ContainerT> CombIteratorDeref<ContainerT> iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::indices_ private
Definition at line 46 of file combinations_with_replacement.hpp.
Referenced by iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::Iterator(), iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::operator*(), and iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::operator->().
steps_
template<typename Container > template<typename ContainerT> int iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::steps_ private
Definition at line 47 of file combinations_with_replacement.hpp.
Referenced by iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::operator++(), and iter::impl::CombinatorWithReplacement< Container >::Iterator< ContainerT >::operator==().
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/combinations_with_replacement.hpp