CkPttnCpp: iter::impl::Permuter< Container >::Iterator< ContainerT > Class Template Reference
iter::impl::Permuter< Container >::Iterator< ContainerT > Class Template Reference
#include <permutations.hpp>
Public Types
using iterator_category = std::input_iterator_tag
using value_type = Permutable< ContainerT >
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
Public Member Functions
Iterator (IteratorWrapper< ContainerT > &&sub_iter, IteratorWrapper< ContainerT > &&sub_end)
Permutable< ContainerT > & operator* ()
Permutable< ContainerT > * operator-> ()
Iterator & operator++ ()
Iterator operator++ (int)
template<typename T >
bool operator!= (const Iterator< T > &other) const
template<typename T >
bool operator== (const Iterator< T > &other) const
Static Private Member Functions
static bool cmp_iters (IteratorWrapper< ContainerT > lhs, IteratorWrapper< ContainerT > rhs) noexcept
Private Attributes
Permutable< ContainerT > working_set_
int steps_ {}
Static Private Attributes
static constexpr const int COMPLETE = -1
Friends
template<typename >
class Iterator
Detailed Description
template<typename Container>
template<typename ContainerT>
class iter::impl::Permuter< Container >::Iterator< ContainerT >
Definition at line 41 of file permutations.hpp.
Member Typedef Documentation
difference_type
template<typename Container > template<typename ContainerT> using iter::impl::Permuter< Container >::Iterator< ContainerT >::difference_type = std::ptrdiff_t
Definition at line 57 of file permutations.hpp.
iterator_category
template<typename Container > template<typename ContainerT> using iter::impl::Permuter< Container >::Iterator< ContainerT >::iterator_category = std::input_iterator_tag
Definition at line 55 of file permutations.hpp.
pointer
template<typename Container > template<typename ContainerT> using iter::impl::Permuter< Container >::Iterator< ContainerT >::pointer = value_type*
Definition at line 58 of file permutations.hpp.
reference
template<typename Container > template<typename ContainerT> using iter::impl::Permuter< Container >::Iterator< ContainerT >::reference = value_type&
Definition at line 59 of file permutations.hpp.
value_type
template<typename Container > template<typename ContainerT> using iter::impl::Permuter< Container >::Iterator< ContainerT >::value_type = Permutable<ContainerT>
Definition at line 56 of file permutations.hpp.
Constructor & Destructor Documentation
Iterator()
template<typename Container > template<typename ContainerT> iter::impl::Permuter< Container >::Iterator< ContainerT >::Iterator (IteratorWrapper< ContainerT > && sub_iter, IteratorWrapper< ContainerT > && sub_end) inline
Definition at line 61 of file permutations.hpp.
References iter::impl::Permuter< Container >::Iterator< ContainerT >::cmp_iters(), iter::impl::IterIterWrapper< Container >::get(), iter::impl::get_iters::get_begin(), and iter::impl::get_iters::get_end().
Member Function Documentation
cmp_iters()
template<typename Container > template<typename ContainerT> static bool iter::impl::Permuter< Container >::Iterator< ContainerT >::cmp_iters (IteratorWrapper< ContainerT > lhs, IteratorWrapper< ContainerT > rhs) inline static private noexcept
Definition at line 46 of file permutations.hpp.
Referenced by iter::impl::Permuter< Container >::Iterator< ContainerT >::Iterator(), and iter::impl::Permuter< Container >::Iterator< ContainerT >::operator++().
operator!=()
template<typename Container > template<typename ContainerT> template<typename T > bool iter::impl::Permuter< Container >::Iterator< ContainerT >::operator!= (const Iterator< T > & other) const inline
Definition at line 99 of file permutations.hpp.
operator*()
template<typename Container > template<typename ContainerT> Permutable<ContainerT>& iter::impl::Permuter< Container >::Iterator< ContainerT >::operator* () inline
Definition at line 75 of file permutations.hpp.
References iter::impl::Permuter< Container >::Iterator< ContainerT >::working_set_.
operator++() [1/2]
template<typename Container > template<typename ContainerT> Iterator& iter::impl::Permuter< Container >::Iterator< ContainerT >::operator++ () inline
Definition at line 83 of file permutations.hpp.
References iter::impl::Permuter< Container >::Iterator< ContainerT >::cmp_iters(), iter::impl::Permuter< Container >::Iterator< ContainerT >::COMPLETE, iter::impl::IterIterWrapper< Container >::get(), iter::impl::get_iters::get_begin(), iter::impl::get_iters::get_end(), and iter::impl::Permuter< Container >::Iterator< ContainerT >::steps_.
operator++() [2/2]
template<typename Container > template<typename ContainerT> Iterator iter::impl::Permuter< Container >::Iterator< ContainerT >::operator++ (int) inline
Definition at line 92 of file permutations.hpp.
operator->()
template<typename Container > template<typename ContainerT> Permutable<ContainerT>* iter::impl::Permuter< Container >::Iterator< ContainerT >::operator-> () inline
Definition at line 79 of file permutations.hpp.
References iter::impl::Permuter< Container >::Iterator< ContainerT >::working_set_.
operator==()
template<typename Container > template<typename ContainerT> template<typename T > bool iter::impl::Permuter< Container >::Iterator< ContainerT >::operator== (const Iterator< T > & other) const inline
Definition at line 104 of file permutations.hpp.
References iter::impl::Permuter< Container >::Iterator< ContainerT >::steps_.
Friends And Related Function Documentation
Iterator
template<typename Container > template<typename ContainerT> template<typename > friend class Iterator friend
Definition at line 44 of file permutations.hpp.
Member Data Documentation
COMPLETE
template<typename Container > template<typename ContainerT> constexpr const int iter::impl::Permuter< Container >::Iterator< ContainerT >::COMPLETE = -1 static private
Definition at line 45 of file permutations.hpp.
Referenced by iter::impl::Permuter< Container >::Iterator< ContainerT >::operator++().
steps_
template<typename Container > template<typename ContainerT> int iter::impl::Permuter< Container >::Iterator< ContainerT >::steps_ {} private
Definition at line 52 of file permutations.hpp.
Referenced by iter::impl::Permuter< Container >::Iterator< ContainerT >::operator++(), and iter::impl::Permuter< Container >::Iterator< ContainerT >::operator==().
working_set_
template<typename Container > template<typename ContainerT> Permutable<ContainerT> iter::impl::Permuter< Container >::Iterator< ContainerT >::working_set_ private
Definition at line 51 of file permutations.hpp.
Referenced by iter::impl::Permuter< Container >::Iterator< ContainerT >::operator*(), and iter::impl::Permuter< Container >::Iterator< ContainerT >::operator->().
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/permutations.hpp