CkPttnCpp: iter::impl::ZippedLongest< TupleType, Is > Class Template Reference
iter::impl::ZippedLongest< TupleType, Is > Class Template Reference
#include <zip_longest.hpp>
Classes
class Iterator
Public Member Functions
ZippedLongest (ZippedLongest &&)=default
Iterator< TupleType, iterator_tuple_type, OptType > begin ()
Iterator< TupleType, iterator_tuple_type, OptType > end ()
Iterator< AsConst< TupleType >, const_iterator_tuple_type, ConstOptType > begin () const
Iterator< AsConst< TupleType >, const_iterator_tuple_type, ConstOptType > end () const
Private Types
template<std::size_t I, typename TupleTypeT >
using OptType = boost::optional< iterator_deref< std::tuple_element_t< I, std::remove_reference_t< TupleTypeT > >> >
template<std::size_t I, typename TupleTypeT >
using ConstOptType = boost::optional< const_iterator_type_deref< std::tuple_element_t< I, std::remove_reference_t< TupleTypeT > >> >
template<typename TupleTypeT , template< std::size_t, typename > class OptTempl>
using ZipIterDeref = std::tuple< OptTempl< Is, TupleTypeT >... >
Private Member Functions
ZippedLongest (TupleType &&containers)
Private Attributes
TupleType containers_
Friends
ZippedLongest zip_longest_impl (TupleType &&, std::index_sequence< Is... >)
Detailed Description
template<typename TupleType, std::size_t... Is>
class iter::impl::ZippedLongest< TupleType, Is >
Definition at line 15 of file zip_longest.hpp.
Member Typedef Documentation
ConstOptType
template<typename TupleType , std::size_t... Is> template<std::size_t I, typename TupleTypeT > using iter::impl::ZippedLongest< TupleType, Is >::ConstOptType = boost::optional<const_iterator_type_deref< std::tuple_element_t<I, std::remove_reference_t<TupleTypeT> >> > private
Definition at line 39 of file zip_longest.hpp.
OptType
template<typename TupleType , std::size_t... Is> template<std::size_t I, typename TupleTypeT > using iter::impl::ZippedLongest< TupleType, Is >::OptType = boost::optional<iterator_deref< std::tuple_element_t<I, std::remove_reference_t<TupleTypeT> >> > private
Definition at line 35 of file zip_longest.hpp.
ZipIterDeref
template<typename TupleType , std::size_t... Is> template<typename TupleTypeT , template< std::size_t, typename > class OptTempl> using iter::impl::ZippedLongest< TupleType, Is >::ZipIterDeref = std::tuple<OptTempl<Is, TupleTypeT>...> private
Definition at line 43 of file zip_longest.hpp.
Constructor & Destructor Documentation
ZippedLongest() [1/2]
template<typename TupleType , std::size_t... Is> iter::impl::ZippedLongest< TupleType, Is >::ZippedLongest (TupleType && containers) inline private
Definition at line 45 of file zip_longest.hpp.
ZippedLongest() [2/2]
template<typename TupleType , std::size_t... Is> iter::impl::ZippedLongest< TupleType, Is >::ZippedLongest (ZippedLongest< TupleType, Is > &&) default
Member Function Documentation
begin() [1/2]
template<typename TupleType , std::size_t... Is> Iterator<TupleType, iterator_tuple_type, OptType> iter::impl::ZippedLongest< TupleType, Is >::begin () inline
Definition at line 111 of file zip_longest.hpp.
References iter::impl::get_iters::get_begin(), and iter::impl::get_iters::get_end().
begin() [2/2]
template<typename TupleType , std::size_t... Is> Iterator<AsConst<TupleType>, const_iterator_tuple_type, ConstOptType> iter::impl::ZippedLongest< TupleType, Is >::begin () const inline
Definition at line 121 of file zip_longest.hpp.
References iter::impl::get_iters::get_begin(), and iter::impl::get_iters::get_end().
end() [1/2]
template<typename TupleType , std::size_t... Is> Iterator<TupleType, iterator_tuple_type, OptType> iter::impl::ZippedLongest< TupleType, Is >::end () inline
Definition at line 116 of file zip_longest.hpp.
References iter::impl::get_iters::get_end().
end() [2/2]
template<typename TupleType , std::size_t... Is> Iterator<AsConst<TupleType>, const_iterator_tuple_type, ConstOptType> iter::impl::ZippedLongest< TupleType, Is >::end () const inline
Definition at line 127 of file zip_longest.hpp.
References iter::impl::get_iters::get_end(), and iter::impl::zip_longest_impl().
Friends And Related Function Documentation
zip_longest_impl
template<typename TupleType , std::size_t... Is> ZippedLongest zip_longest_impl (TupleType && , std::index_sequence< Is... >) friend
Member Data Documentation
containers_
template<typename TupleType , std::size_t... Is> TupleType iter::impl::ZippedLongest< TupleType, Is >::containers_ private
Definition at line 29 of file zip_longest.hpp.
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/zip_longest.hpp