CkPttnCpp: MyUnMovable Class Reference
MyUnMovable Class Reference
Public Member Functions
constexpr MyUnMovable (int val)
MyUnMovable (const MyUnMovable &)=delete
MyUnMovable & operator= (const MyUnMovable &)=delete
MyUnMovable (MyUnMovable &&other)
constexpr int get_val () const
void set_val (int new_val)
bool operator== (const MyUnMovable &other) const
bool operator!= (const MyUnMovable &other) const
Private Attributes
int val
Detailed Description
Definition at line 10 of file test_mixed.cpp.
Constructor & Destructor Documentation
MyUnMovable() [1/3]
constexpr MyUnMovable::MyUnMovable (int val) inline
Definition at line 14 of file test_mixed.cpp.
References operator=().
MyUnMovable() [2/3]
MyUnMovable::MyUnMovable (const MyUnMovable &) delete
MyUnMovable() [3/3]
MyUnMovable::MyUnMovable (MyUnMovable && other) inline
Definition at line 19 of file test_mixed.cpp.
Member Function Documentation
get_val()
constexpr int MyUnMovable::get_val () const inline
Definition at line 21 of file test_mixed.cpp.
References val.
Referenced by operator!=(), and TEST_CASE().
operator!=()
bool MyUnMovable::operator!= (const MyUnMovable & other) const inline
Definition at line 32 of file test_mixed.cpp.
References get_val().
operator=()
MyUnMovable& MyUnMovable::operator= (const MyUnMovable &) delete
Referenced by MyUnMovable().
operator==()
bool MyUnMovable::operator== (const MyUnMovable & other) const inline
Definition at line 28 of file test_mixed.cpp.
References val.
set_val()
void MyUnMovable::set_val (int new_val) inline
Definition at line 24 of file test_mixed.cpp.
Member Data Documentation
val
int MyUnMovable::val private
Definition at line 11 of file test_mixed.cpp.
Referenced by get_val(), and operator==().
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_mixed.cpp