CkPttnCpp: FMBiGainCalc Class Reference
FMBiGainCalc Class Reference
FMBiGainCalc.
#include <FMBiGainCalc.hpp>
Public Types
using ret_2pin_info = std::tuple< index_t, int >
using ret_info = std::tuple< std::vector< index_t >, std::vector< int > >
Public Member Functions
FMBiGainCalc (SimpleNetlist &H, uint8_t)
Construct a new FMBiGainCalc object.
auto init (const std::vector< uint8_t > &part) -> int
auto start_ptr (uint8_t) -> dllink< index_t > *
auto update_move_init () -> void
auto update_move_2pin_net (const std::vector< uint8_t > &part, const MoveInfo &move_info) -> ret_2pin_info
auto update_move_3pin_net (const std::vector< uint8_t > &part, const MoveInfo &move_info) -> ret_info
auto update_move_general_net (const std::vector< uint8_t > &part, const MoveInfo &move_info) -> ret_info
Public Attributes
int totalcost
Private Types
using index_t = typename SimpleNetlist::index_t
Private Member Functions
auto __modify_gain (index_t i_w, int weight) -> void
auto __init_gain (node_t net, const std::vector< uint8_t > &part) -> void
auto __init_gain_2pin_net (node_t net, const std::vector< uint8_t > &part) -> void
auto __init_gain_3pin_net (node_t net, const std::vector< uint8_t > &part) -> void
auto __init_gain_general_net (node_t net, const std::vector< uint8_t > &part) -> void
Private Attributes
friend FMBiGainMgr
SimpleNetlist & H
size_t num_modules {}
std::vector< dllink< index_t > > vertex_list
Detailed Description
FMBiGainCalc.
Definition at line 12 of file FMBiGainCalc.hpp.
Member Typedef Documentation
index_t
using FMBiGainCalc::index_t = typename SimpleNetlist::index_t private
Definition at line 15 of file FMBiGainCalc.hpp.
ret_2pin_info
using FMBiGainCalc::ret_2pin_info = std::tuple<index_t, int>
Definition at line 73 of file FMBiGainCalc.hpp.
ret_info
using FMBiGainCalc::ret_info = std::tuple<std::vector<index_t>, std::vector<int> >
Definition at line 85 of file FMBiGainCalc.hpp.
Constructor & Destructor Documentation
FMBiGainCalc()
FMBiGainCalc::FMBiGainCalc (SimpleNetlist & H, uint8_t) inline explicit
Construct a new FMBiGainCalc object.
Parameters
H
K
Definition at line 32 of file FMBiGainCalc.hpp.
References Netlist< nodeview_t, nodemap_t >::number_of_modules(), and vertex_list.
Member Function Documentation
__init_gain()
void FMBiGainCalc::__init_gain (node_t net, const std::vector< uint8_t > & part) -> void private
Parameters
net
part
Definition at line 13 of file FMBiGainCalc.cpp.
References __init_gain_2pin_net(), __init_gain_3pin_net(), __init_gain_general_net(), xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::degree(), Netlist< nodeview_t, nodemap_t >::G, H, and unlikely.
Referenced by __modify_gain(), and init().
__init_gain_2pin_net()
void FMBiGainCalc::__init_gain_2pin_net (node_t net, const std::vector< uint8_t > & part) -> void private
Parameters
net
part
Definition at line 35 of file FMBiGainCalc.cpp.
References __modify_gain(), xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::begin(), Netlist< nodeview_t, nodemap_t >::G, Netlist< nodeview_t, nodemap_t >::get_net_weight(), H, Netlist< nodeview_t, nodemap_t >::module_map, and totalcost.
Referenced by __init_gain(), and __modify_gain().
__init_gain_3pin_net()
void FMBiGainCalc::__init_gain_3pin_net (node_t net, const std::vector< uint8_t > & part) -> void private
Parameters
net
part
Definition at line 60 of file FMBiGainCalc.cpp.
References __modify_gain(), xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::begin(), Netlist< nodeview_t, nodemap_t >::G, Netlist< nodeview_t, nodemap_t >::get_net_weight(), H, Netlist< nodeview_t, nodemap_t >::module_map, and totalcost.
Referenced by __init_gain(), and __modify_gain().
__init_gain_general_net()
void FMBiGainCalc::__init_gain_general_net (node_t net, const std::vector< uint8_t > & part) -> void private
Parameters
net
part
Definition at line 100 of file FMBiGainCalc.cpp.
References __modify_gain(), Netlist< nodeview_t, nodemap_t >::G, Netlist< nodeview_t, nodemap_t >::get_net_weight(), H, Netlist< nodeview_t, nodemap_t >::module_map, and totalcost.
Referenced by __init_gain(), and __modify_gain().
__modify_gain()
auto FMBiGainCalc::__modify_gain (index_t i_w, int weight) -> void inline private
Parameters
w
weight
Definition at line 115 of file FMBiGainCalc.hpp.
References __init_gain(), __init_gain_2pin_net(), __init_gain_3pin_net(), and __init_gain_general_net().
Referenced by __init_gain_2pin_net(), __init_gain_3pin_net(), and __init_gain_general_net().
init()
auto FMBiGainCalc::init (const std::vector< uint8_t > & part) -> int inline
Parameters
part
Definition at line 42 of file FMBiGainCalc.hpp.
References __init_gain(), Netlist< nodeview_t, nodemap_t >::nets, and totalcost.
start_ptr()
auto FMBiGainCalc::start_ptr (uint8_t) -> dllink<index_t>* inline
Parameters
toPart
Returns
dllink*
Definition at line 62 of file FMBiGainCalc.hpp.
update_move_2pin_net()
auto FMBiGainCalc::update_move_2pin_net (const std::vector< uint8_t > & part, const MoveInfo & move_info) -> ret_2pin_info
Parameters
part
move_info
Returns
ret_2pin_info
Definition at line 144 of file FMBiGainCalc.cpp.
References xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::begin(), Netlist< nodeview_t, nodemap_t >::G, Netlist< nodeview_t, nodemap_t >::get_net_weight(), H, and Netlist< nodeview_t, nodemap_t >::module_map.
update_move_3pin_net()
auto FMBiGainCalc::update_move_3pin_net (const std::vector< uint8_t > & part, const MoveInfo & move_info) -> ret_info
Parameters
net
part
fromPart
v
part
move_info
Returns
ret_info
Definition at line 164 of file FMBiGainCalc.cpp.
References Netlist< nodeview_t, nodemap_t >::G, Netlist< nodeview_t, nodemap_t >::get_net_weight(), H, and Netlist< nodeview_t, nodemap_t >::module_map.
update_move_general_net()
auto FMBiGainCalc::update_move_general_net (const std::vector< uint8_t > & part, const MoveInfo & move_info) -> ret_info
Parameters
net
part
fromPart
v
part
move_info
Returns
ret_info
Definition at line 204 of file FMBiGainCalc.cpp.
References Netlist< nodeview_t, nodemap_t >::G, Netlist< nodeview_t, nodemap_t >::get_net_weight(), H, and Netlist< nodeview_t, nodemap_t >::module_map.
update_move_init()
auto FMBiGainCalc::update_move_init () -> void inline
Definition at line 68 of file FMBiGainCalc.hpp.
Member Data Documentation
FMBiGainMgr
friend FMBiGainCalc::FMBiGainMgr private
Definition at line 14 of file FMBiGainCalc.hpp.
H
SimpleNetlist& FMBiGainCalc::H private
Definition at line 18 of file FMBiGainCalc.hpp.
Referenced by __init_gain(), __init_gain_2pin_net(), __init_gain_3pin_net(), __init_gain_general_net(), update_move_2pin_net(), update_move_3pin_net(), and update_move_general_net().
num_modules
size_t FMBiGainCalc::num_modules {} private
Definition at line 19 of file FMBiGainCalc.hpp.
totalcost
int FMBiGainCalc::totalcost
Definition at line 24 of file FMBiGainCalc.hpp.
Referenced by __init_gain_2pin_net(), __init_gain_3pin_net(), __init_gain_general_net(), and init().
vertex_list
std::vector<dllink<index_t> > FMBiGainCalc::vertex_list private
Definition at line 21 of file FMBiGainCalc.hpp.
Referenced by FMBiGainMgr::__set_key(), FMBiGainCalc(), FMBiGainMgr::lock(), and FMBiGainMgr::modify_key().
The documentation for this class was generated from the following files:
lib/include/ckpttncpp/FMBiGainCalc.hpp
lib/src/FMBiGainCalc.cpp