CkPttnCpp: iter::impl::Sliced< Container, DifferenceType > Class Template Reference
iter::impl::Sliced< Container, DifferenceType > Class Template Reference
#include <slice.hpp>
Classes
class Iterator
Public Member Functions
Sliced (Sliced &&)=default
Iterator< Container > begin ()
Iterator< Container > end ()
Iterator< AsConst< Container > > begin () const
Iterator< AsConst< Container > > end () const
Private Member Functions
Sliced (Container &&container, DifferenceType start, DifferenceType stop, DifferenceType step)
Private Attributes
Container container_
DifferenceType start_
DifferenceType stop_
DifferenceType step_
friend SliceFn
Detailed Description
template<typename Container, typename DifferenceType>
class iter::impl::Sliced< Container, DifferenceType >
Definition at line 13 of file slice.hpp.
Constructor & Destructor Documentation
Sliced() [1/2]
template<typename Container , typename DifferenceType > iter::impl::Sliced< Container, DifferenceType >::Sliced (Container && container, DifferenceType start, DifferenceType stop, DifferenceType step) inline private
Definition at line 29 of file slice.hpp.
Sliced() [2/2]
template<typename Container , typename DifferenceType > iter::impl::Sliced< Container, DifferenceType >::Sliced (Sliced< Container, DifferenceType > &&) default
Member Function Documentation
begin() [1/2]
template<typename Container , typename DifferenceType > Iterator<Container> iter::impl::Sliced< Container, DifferenceType >::begin () inline
Definition at line 99 of file slice.hpp.
References iter::impl::dumb_advance(), iter::impl::get_iters::get_begin(), iter::impl::get_iters::get_end(), iter::impl::Sliced< Container, DifferenceType >::start_, and iter::impl::Sliced< Container, DifferenceType >::Iterator< ContainerT >::stop_.
begin() [2/2]
template<typename Container , typename DifferenceType > Iterator<AsConst<Container> > iter::impl::Sliced< Container, DifferenceType >::begin () const inline
Definition at line 109 of file slice.hpp.
References iter::impl::dumb_advance(), iter::impl::get_iters::get_begin(), iter::impl::get_iters::get_end(), iter::impl::Sliced< Container, DifferenceType >::start_, and iter::impl::Sliced< Container, DifferenceType >::Iterator< ContainerT >::stop_.
end() [1/2]
template<typename Container , typename DifferenceType > Iterator<Container> iter::impl::Sliced< Container, DifferenceType >::end () inline
Definition at line 105 of file slice.hpp.
References iter::impl::get_iters::get_end(), and iter::impl::Sliced< Container, DifferenceType >::Iterator< ContainerT >::stop_.
end() [2/2]
template<typename Container , typename DifferenceType > Iterator<AsConst<Container> > iter::impl::Sliced< Container, DifferenceType >::end () const inline
Definition at line 116 of file slice.hpp.
References iter::impl::get_iters::get_end(), and iter::impl::Sliced< Container, DifferenceType >::Iterator< ContainerT >::stop_.
Member Data Documentation
container_
template<typename Container , typename DifferenceType > Container iter::impl::Sliced< Container, DifferenceType >::container_ private
Definition at line 22 of file slice.hpp.
SliceFn
template<typename Container , typename DifferenceType > friend iter::impl::Sliced< Container, DifferenceType >::SliceFn private
Definition at line 27 of file slice.hpp.
start_
template<typename Container , typename DifferenceType > DifferenceType iter::impl::Sliced< Container, DifferenceType >::start_ private
Definition at line 23 of file slice.hpp.
Referenced by iter::impl::Sliced< Container, DifferenceType >::begin(), and iter::impl::SliceFn::FnPartial< DifferenceType >::operator()().
step_
template<typename Container , typename DifferenceType > DifferenceType iter::impl::Sliced< Container, DifferenceType >::step_ private
Definition at line 25 of file slice.hpp.
stop_
template<typename Container , typename DifferenceType > DifferenceType iter::impl::Sliced< Container, DifferenceType >::stop_ private
Definition at line 24 of file slice.hpp.
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/slice.hpp