CkPttnCpp: iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT > Class Template Reference
iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT > Class Template Reference
#include <groupby.hpp>
Public Types
using iterator_category = std::input_iterator_tag
using value_type = KeyGroupPair< ContainerT >
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
Public Member Functions
Iterator (IteratorWrapper< ContainerT > &&sub_iter, IteratorWrapper< ContainerT > &&sub_end, KeyFunc &key_func)
Iterator (const Iterator &other)
Iterator & operator= (const Iterator &other)
~Iterator ()=default
KeyGroupPair< ContainerT > & operator* ()
KeyGroupPair< ContainerT > * operator-> ()
Iterator & operator++ ()
Iterator operator++ (int)
template<typename T >
bool operator!= (const Iterator< T > &other) const
template<typename T >
bool operator== (const Iterator< T > &other) const
void increment_iterator ()
bool exhausted () const
Holder< ContainerT >::reference get ()
Holder< ContainerT >::pointer get_ptr ()
key_func_ret< ContainerT > next_key ()
void set_key_group_pair ()
Private Attributes
IteratorWrapper< ContainerT > sub_iter_
IteratorWrapper< ContainerT > sub_end_
Holder< ContainerT > item_
KeyFunc * key_func_
std::optional< KeyGroupPair< ContainerT > > current_key_group_pair_
Friends
template<typename >
class Iterator
Detailed Description
template<typename Container, typename KeyFunc>
template<typename ContainerT>
class iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >
Definition at line 51 of file groupby.hpp.
Member Typedef Documentation
difference_type
template<typename Container , typename KeyFunc > template<typename ContainerT> using iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::difference_type = std::ptrdiff_t
Definition at line 76 of file groupby.hpp.
iterator_category
template<typename Container , typename KeyFunc > template<typename ContainerT> using iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::iterator_category = std::input_iterator_tag
Definition at line 74 of file groupby.hpp.
pointer
template<typename Container , typename KeyFunc > template<typename ContainerT> using iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::pointer = value_type*
Definition at line 77 of file groupby.hpp.
reference
template<typename Container , typename KeyFunc > template<typename ContainerT> using iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::reference = value_type&
Definition at line 78 of file groupby.hpp.
value_type
template<typename Container , typename KeyFunc > template<typename ContainerT> using iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::value_type = KeyGroupPair<ContainerT>
Definition at line 75 of file groupby.hpp.
Constructor & Destructor Documentation
Iterator() [1/2]
template<typename Container , typename KeyFunc > template<typename ContainerT> iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::Iterator (IteratorWrapper< ContainerT > && sub_iter, IteratorWrapper< ContainerT > && sub_end, KeyFunc & key_func) inline
Definition at line 80 of file groupby.hpp.
References iter::impl::DerefHolder< T >::reset().
Iterator() [2/2]
template<typename Container , typename KeyFunc > template<typename ContainerT> iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::Iterator (const Iterator< ContainerT > & other) inline
Definition at line 90 of file groupby.hpp.
References iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::sub_iter_.
~Iterator()
template<typename Container , typename KeyFunc > template<typename ContainerT> iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::~Iterator () default
Member Function Documentation
exhausted()
template<typename Container , typename KeyFunc > template<typename ContainerT> bool iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::exhausted () const inline
Definition at line 156 of file groupby.hpp.
get()
template<typename Container , typename KeyFunc > template<typename ContainerT> Holder<ContainerT>::reference iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::get () inline
Definition at line 160 of file groupby.hpp.
References iter::impl::DerefHolder< T >::get().
get_ptr()
template<typename Container , typename KeyFunc > template<typename ContainerT> Holder<ContainerT>::pointer iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::get_ptr () inline
Definition at line 164 of file groupby.hpp.
References iter::impl::DerefHolder< T >::get_ptr().
increment_iterator()
template<typename Container , typename KeyFunc > template<typename ContainerT> void iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::increment_iterator () inline
Definition at line 147 of file groupby.hpp.
References iter::impl::DerefHolder< T >::reset().
next_key()
template<typename Container , typename KeyFunc > template<typename ContainerT> key_func_ret<ContainerT> iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::next_key () inline
Definition at line 168 of file groupby.hpp.
References iter::impl::DerefHolder< T >::get().
operator!=()
template<typename Container , typename KeyFunc > template<typename ContainerT> template<typename T > bool iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::operator!= (const Iterator< T > & other) const inline
Definition at line 138 of file groupby.hpp.
References iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::sub_iter_.
operator*()
template<typename Container , typename KeyFunc > template<typename ContainerT> KeyGroupPair<ContainerT>& iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::operator* () inline
Definition at line 113 of file groupby.hpp.
operator++() [1/2]
template<typename Container , typename KeyFunc > template<typename ContainerT> Iterator& iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::operator++ () inline
Definition at line 123 of file groupby.hpp.
operator++() [2/2]
template<typename Container , typename KeyFunc > template<typename ContainerT> Iterator iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::operator++ (int) inline
Definition at line 131 of file groupby.hpp.
operator->()
template<typename Container , typename KeyFunc > template<typename ContainerT> KeyGroupPair<ContainerT>* iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::operator-> () inline
Definition at line 118 of file groupby.hpp.
operator=()
template<typename Container , typename KeyFunc > template<typename ContainerT> Iterator& iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::operator= (const Iterator< ContainerT > & other) inline
Definition at line 96 of file groupby.hpp.
References iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::item_, iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::key_func_, iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::sub_end_, and iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::sub_iter_.
operator==()
template<typename Container , typename KeyFunc > template<typename ContainerT> template<typename T > bool iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::operator== (const Iterator< T > & other) const inline
Definition at line 143 of file groupby.hpp.
set_key_group_pair()
template<typename Container , typename KeyFunc > template<typename ContainerT> void iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::set_key_group_pair () inline
Definition at line 172 of file groupby.hpp.
References iter::impl::DerefHolder< T >::get().
Friends And Related Function Documentation
Iterator
template<typename Container , typename KeyFunc > template<typename ContainerT> template<typename > friend class Iterator friend
Definition at line 66 of file groupby.hpp.
Member Data Documentation
current_key_group_pair_
template<typename Container , typename KeyFunc > template<typename ContainerT> std::optional<KeyGroupPair<ContainerT> > iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::current_key_group_pair_ private
Definition at line 71 of file groupby.hpp.
item_
template<typename Container , typename KeyFunc > template<typename ContainerT> Holder<ContainerT> iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::item_ private
Definition at line 69 of file groupby.hpp.
Referenced by iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::operator=().
key_func_
template<typename Container , typename KeyFunc > template<typename ContainerT> KeyFunc* iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::key_func_ private
Definition at line 70 of file groupby.hpp.
Referenced by iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::operator=().
sub_end_
template<typename Container , typename KeyFunc > template<typename ContainerT> IteratorWrapper<ContainerT> iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::sub_end_ private
Definition at line 68 of file groupby.hpp.
Referenced by iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::operator=().
sub_iter_
template<typename Container , typename KeyFunc > template<typename ContainerT> IteratorWrapper<ContainerT> iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::sub_iter_ private
Definition at line 67 of file groupby.hpp.
Referenced by iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::Iterator(), iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::operator!=(), and iter::impl::GroupProducer< Container, KeyFunc >::Iterator< ContainerT >::operator=().
The documentation for this class was generated from the following file:
/media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/groupby.hpp