CkPttnCpp: Netlist< nodeview_t, nodemap_t > Struct Template Reference
Netlist< nodeview_t, nodemap_t > Struct Template Reference
Netlist.
#include <netlist.hpp>
Public Types
using node_t = typename nodeview_t::value_type
using index_t = typename nodemap_t::value_type
using graph_t = xn::Graph< nodeview_t, nodemap_t >
Public Member Functions
Netlist (graph_t &&G, const nodeview_t &modules, const nodeview_t &nets, const nodemap_t &module_map, const nodemap_t &net_map)
Construct a new Netlist object.
Netlist (graph_t &&G, size_t num_modules, size_t num_nets)
Construct a new Netlist object.
auto number_of_modules () const -> size_t
auto number_of_nets () const -> size_t
auto number_of_nodes () const -> size_t
auto get_max_degree () const -> size_t
Get the max degree.
auto get_max_net_degree () const -> size_t
Get the max net degree.
auto get_module_weight (node_t v) const -> int
auto get_module_weight_by_id (index_t i_v) const -> int
auto get_net_weight (node_t) const -> index_t
void projection_down (const std::vector< uint8_t > &part, std::vector< uint8_t > &part_down)
projection down
void projection_up (const std::vector< uint8_t > &part, std::vector< uint8_t > &part_up)
projection up
Public Attributes
graph_t G
nodeview_t modules
nodeview_t nets
nodemap_t module_map
nodemap_t net_map
size_t num_modules
size_t num_nets
size_t num_pads = 0U
size_t max_degree {}
size_t max_net_degree {}
bool has_fixed_modules {}
uint8_t cost_model = 0
std::vector< int > module_weight
std::vector< int > net_weight
py::set< node_t > module_fixed
Netlist< nodeview_t, nodemap_t > * parent
py::dict< node_t, index_t > node_up_map
py::dict< index_t, node_t > node_down_map
py::dict< index_t, node_t > cluster_down_map
Detailed Description
template<typename nodeview_t, typename nodemap_t>
struct Netlist< nodeview_t, nodemap_t >
Netlist.
Netlist is implemented by xn::Graph, which is a networkx-like graph.
Definition at line 26 of file netlist.hpp.
Member Typedef Documentation
graph_t
template<typename nodeview_t, typename nodemap_t> using Netlist< nodeview_t, nodemap_t >::graph_t = xn::Graph<nodeview_t, nodemap_t>
Definition at line 30 of file netlist.hpp.
index_t
template<typename nodeview_t, typename nodemap_t> using Netlist< nodeview_t, nodemap_t >::index_t = typename nodemap_t::value_type
Definition at line 29 of file netlist.hpp.
node_t
template<typename nodeview_t, typename nodemap_t> using Netlist< nodeview_t, nodemap_t >::node_t = typename nodeview_t::value_type
Definition at line 28 of file netlist.hpp.
Constructor & Destructor Documentation
Netlist() [1/2]
template<typename nodeview_t , typename nodemap_t > Netlist< nodeview_t, nodemap_t >::Netlist (graph_t && G, const nodeview_t & modules, const nodeview_t & nets, const nodemap_t & module_map, const nodemap_t & net_map)
Construct a new Netlist object.
Parameters
G
module_list
net_list
module_fixed
Definition at line 193 of file netlist.hpp.
References xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::degree(), Netlist< nodeview_t, nodemap_t >::G, Netlist< nodeview_t, nodemap_t >::has_fixed_modules, Netlist< nodeview_t, nodemap_t >::max_degree, Netlist< nodeview_t, nodemap_t >::max_net_degree, Netlist< nodeview_t, nodemap_t >::module_fixed, Netlist< nodeview_t, nodemap_t >::module_map, Netlist< nodeview_t, nodemap_t >::modules, Netlist< nodeview_t, nodemap_t >::net_map, Netlist< nodeview_t, nodemap_t >::nets, Netlist< nodeview_t, nodemap_t >::num_modules, and Netlist< nodeview_t, nodemap_t >::num_nets.
Netlist() [2/2]
template<typename nodeview_t , typename nodemap_t > Netlist< nodeview_t, nodemap_t >::Netlist (graph_t && G, size_t num_modules, size_t num_nets)
Construct a new Netlist object.
Parameters
G
module_list
net_list
module_fixed
Definition at line 215 of file netlist.hpp.
References Netlist< nodeview_t, nodemap_t >::G.
Member Function Documentation
get_max_degree()
template<typename nodeview_t, typename nodemap_t> auto Netlist< nodeview_t, nodemap_t >::get_max_degree () const -> size_t inline
Get the max degree.
Returns
index_t
index_t
Definition at line 109 of file netlist.hpp.
Referenced by FMGainMgr< FMBiGainCalc, FMBiGainMgr >::FMGainMgr().
get_max_net_degree()
template<typename nodeview_t, typename nodemap_t> auto Netlist< nodeview_t, nodemap_t >::get_max_net_degree () const -> size_t inline
Get the max net degree.
Returns
index_t
Definition at line 116 of file netlist.hpp.
Referenced by max_independent_net().
get_module_weight()
template<typename nodeview_t, typename nodemap_t> auto Netlist< nodeview_t, nodemap_t >::get_module_weight (node_t v) const -> int inline
Definition at line 118 of file netlist.hpp.
Referenced by create_contraction_subgraph().
get_module_weight_by_id()
template<typename nodeview_t, typename nodemap_t> auto Netlist< nodeview_t, nodemap_t >::get_module_weight_by_id (index_t i_v) const -> int inline
Definition at line 125 of file netlist.hpp.
Referenced by FMConstrMgr::FMConstrMgr().
get_net_weight()
template<typename nodeview_t, typename nodemap_t> auto Netlist< nodeview_t, nodemap_t >::get_net_weight (node_t) const -> index_t inline
Definition at line 130 of file netlist.hpp.
References PartInfo::part.
Referenced by FMBiGainCalc::__init_gain_2pin_net(), FMBiGainCalc::__init_gain_3pin_net(), FMBiGainCalc::__init_gain_general_net(), max_independent_net(), FMBiGainCalc::update_move_2pin_net(), FMBiGainCalc::update_move_3pin_net(), and FMBiGainCalc::update_move_general_net().
number_of_modules()
template<typename nodeview_t, typename nodemap_t> auto Netlist< nodeview_t, nodemap_t >::number_of_modules () const -> size_t inline
Returns
index_t
Definition at line 80 of file netlist.hpp.
Referenced by create_contraction_subgraph(), FMBiGainCalc::FMBiGainCalc(), FMConstrMgr::FMConstrMgr(), FMKWayGainCalc::FMKWayGainCalc(), readAre(), run_FMBiPartMgr(), and run_FMKWayPartMgr().
number_of_nets()
template<typename nodeview_t, typename nodemap_t> auto Netlist< nodeview_t, nodemap_t >::number_of_nets () const -> size_t inline
Returns
index_t
Definition at line 87 of file netlist.hpp.
number_of_nodes()
template<typename nodeview_t, typename nodemap_t> auto Netlist< nodeview_t, nodemap_t >::number_of_nodes () const -> size_t inline
Returns
index_t
Definition at line 94 of file netlist.hpp.
References xn::Graph< nodeview_t, nodemap_t, adjlist_inner_dict_factory >::number_of_nodes().
projection_down()
template<typename nodeview_t , typename nodemap_t > auto Netlist< nodeview_t, nodemap_t >::projection_down (const std::vector< uint8_t > & part, std::vector< uint8_t > & part_down)
projection down
Parameters
part
part_down
Definition at line 26 of file netlist.cpp.
projection_up()
template<typename nodeview_t , typename nodemap_t > auto Netlist< nodeview_t, nodemap_t >::projection_up (const std::vector< uint8_t > & part, std::vector< uint8_t > & part_up)
projection up
Parameters
part
part_up
Definition at line 5 of file netlist.cpp.
Member Data Documentation
cluster_down_map
template<typename nodeview_t, typename nodemap_t> py::dict<index_t, node_t> Netlist< nodeview_t, nodemap_t >::cluster_down_map
Definition at line 52 of file netlist.hpp.
cost_model
template<typename nodeview_t, typename nodemap_t> uint8_t Netlist< nodeview_t, nodemap_t >::cost_model = 0
Definition at line 43 of file netlist.hpp.
G
template<typename nodeview_t, typename nodemap_t> graph_t Netlist< nodeview_t, nodemap_t >::G
Definition at line 32 of file netlist.hpp.
Referenced by FMBiGainCalc::__init_gain(), FMBiGainCalc::__init_gain_2pin_net(), FMBiGainCalc::__init_gain_3pin_net(), FMBiGainCalc::__init_gain_general_net(), create_contraction_subgraph(), max_independent_net(), Netlist< nodeview_t, nodemap_t >::Netlist(), FMGainMgr< FMBiGainCalc, FMBiGainMgr >::update_move(), FMBiGainCalc::update_move_2pin_net(), FMBiGainCalc::update_move_3pin_net(), and FMBiGainCalc::update_move_general_net().
has_fixed_modules
template<typename nodeview_t, typename nodemap_t> bool Netlist< nodeview_t, nodemap_t >::has_fixed_modules {}
Definition at line 42 of file netlist.hpp.
Referenced by Netlist< nodeview_t, nodemap_t >::Netlist().
max_degree
template<typename nodeview_t, typename nodemap_t> size_t Netlist< nodeview_t, nodemap_t >::max_degree {}
Definition at line 40 of file netlist.hpp.
Referenced by Netlist< nodeview_t, nodemap_t >::Netlist().
max_net_degree
template<typename nodeview_t, typename nodemap_t> size_t Netlist< nodeview_t, nodemap_t >::max_net_degree {}
Definition at line 41 of file netlist.hpp.
Referenced by Netlist< nodeview_t, nodemap_t >::Netlist().
module_fixed
template<typename nodeview_t, typename nodemap_t> py::set<node_t> Netlist< nodeview_t, nodemap_t >::module_fixed
Definition at line 46 of file netlist.hpp.
Referenced by Netlist< nodeview_t, nodemap_t >::Netlist().
module_map
template<typename nodeview_t, typename nodemap_t> nodemap_t Netlist< nodeview_t, nodemap_t >::module_map
Definition at line 35 of file netlist.hpp.
Referenced by FMBiGainCalc::__init_gain_2pin_net(), FMBiGainCalc::__init_gain_3pin_net(), FMBiGainCalc::__init_gain_general_net(), Netlist< nodeview_t, nodemap_t >::Netlist(), FMBiGainCalc::update_move_2pin_net(), FMBiGainCalc::update_move_3pin_net(), and FMBiGainCalc::update_move_general_net().
module_weight
template<typename nodeview_t, typename nodemap_t> std::vector<int> Netlist< nodeview_t, nodemap_t >::module_weight
Definition at line 44 of file netlist.hpp.
Referenced by create_contraction_subgraph(), create_dwarf(), create_test_netlist(), and readAre().
modules
template<typename nodeview_t, typename nodemap_t> nodeview_t Netlist< nodeview_t, nodemap_t >::modules
Definition at line 33 of file netlist.hpp.
Referenced by create_contraction_subgraph(), Netlist< nodeview_t, nodemap_t >::Netlist(), and FMGainMgr< FMBiGainCalc, FMBiGainMgr >::update_move().
net_map
template<typename nodeview_t, typename nodemap_t> nodemap_t Netlist< nodeview_t, nodemap_t >::net_map
Definition at line 36 of file netlist.hpp.
Referenced by max_independent_net(), and Netlist< nodeview_t, nodemap_t >::Netlist().
net_weight
template<typename nodeview_t, typename nodemap_t> std::vector<int> Netlist< nodeview_t, nodemap_t >::net_weight
Definition at line 45 of file netlist.hpp.
nets
template<typename nodeview_t, typename nodemap_t> nodeview_t Netlist< nodeview_t, nodemap_t >::nets
Definition at line 34 of file netlist.hpp.
Referenced by create_contraction_subgraph(), FMBiGainCalc::init(), FMKWayGainCalc::init(), max_independent_net(), and Netlist< nodeview_t, nodemap_t >::Netlist().
node_down_map
template<typename nodeview_t, typename nodemap_t> py::dict<index_t, node_t> Netlist< nodeview_t, nodemap_t >::node_down_map
Definition at line 51 of file netlist.hpp.
node_up_map
template<typename nodeview_t, typename nodemap_t> py::dict<node_t, index_t> Netlist< nodeview_t, nodemap_t >::node_up_map
Definition at line 50 of file netlist.hpp.
num_modules
template<typename nodeview_t, typename nodemap_t> size_t Netlist< nodeview_t, nodemap_t >::num_modules
Definition at line 37 of file netlist.hpp.
Referenced by Netlist< nodeview_t, nodemap_t >::Netlist().
num_nets
template<typename nodeview_t, typename nodemap_t> size_t Netlist< nodeview_t, nodemap_t >::num_nets
Definition at line 38 of file netlist.hpp.
Referenced by Netlist< nodeview_t, nodemap_t >::Netlist().
num_pads
template<typename nodeview_t, typename nodemap_t> size_t Netlist< nodeview_t, nodemap_t >::num_pads = 0U
Definition at line 39 of file netlist.hpp.
Referenced by readAre(), and readNetD().
parent
template<typename nodeview_t, typename nodemap_t> Netlist<nodeview_t, nodemap_t>* Netlist< nodeview_t, nodemap_t >::parent
Definition at line 49 of file netlist.hpp.
The documentation for this struct was generated from the following files:
lib/include/ckpttncpp/netlist.hpp
lib/src/netlist.cpp