CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_imap.cpp File Reference
test_imap.cpp File Reference
#include <imap.hpp>
#include "helpers.hpp"
#include <cctype>
#include <iterator>
#include <string>
#include <vector>
#include "catch.hpp"
Typedefs
using Vec = const std::vector< int >
template<typename T , typename U >
using ImpT = decltype(imap(std::declval< T >(), std::declval< U >()))
Functions
TEST_CASE ("imap: works with lambda, callable, and function", "[imap]")
TEST_CASE ("imap: works with pointer to member", "[imap]")
TEST_CASE ("imap: works with pointer to member function taking argument")
TEST_CASE ("imap: Works with different begin and end types", "[imap]")
TEST_CASE ("imap: works with multiple sequences", "[imap]")
TEST_CASE ("imap: terminates on shortest squence", "[imap]")
TEST_CASE ("imap: operator->", "[imap]")
TEST_CASE ("imap: empty sequence gives nothing", "[imap]")
TEST_CASE ("imap: binds to lvalues, moves rvalues", "[imap]")
TEST_CASE ("imap: doesn't move or copy elements of iterable", "[imap]")
TEST_CASE ("imap: postfix ++", "[imap]")
TEST_CASE ("imap: iterator meets requirements", "[imap]")
TEST_CASE ("imap: has correct ctor and assign ops", "[imap]")
Typedef Documentation
ImpT
template<typename T , typename U > using ImpT = decltype(imap(std::declval<T>(), std::declval<U>()))
Definition at line 207 of file test_imap.cpp.
Vec
using Vec = const std::vector<int>
Definition at line 13 of file test_imap.cpp.
Function Documentation
TEST_CASE() [1/13]
TEST_CASE ("imap: works with lambda, callable , and function" , "" [imap])
Definition at line 36 of file test_imap.cpp.
References NS1::begin(), NS1::end(), i, and iter::imap.
Referenced by TEST_CASE().
TEST_CASE() [2/13]
TEST_CASE ("imap: works with pointer to member" , "" [imap])
Definition at line 64 of file test_imap.cpp.
References NS1::begin(), NS1::end(), and iter::imap.
TEST_CASE() [3/13]
TEST_CASE ("imap: works with pointer to member function taking argument")
Definition at line 82 of file test_imap.cpp.
References NS1::begin(), NS1::end(), iter::imap, and TEST_CASE().
TEST_CASE() [4/13]
TEST_CASE ("imap: Works with different begin and end types" , "" [imap])
Definition at line 113 of file test_imap.cpp.
References iter::imap.
TEST_CASE() [5/13]
TEST_CASE ("imap: works with multiple sequences" , "" [imap])
Definition at line 121 of file test_imap.cpp.
References NS1::begin(), NS1::end(), and iter::imap.
TEST_CASE() [6/13]
TEST_CASE ("imap: terminates on shortest squence" , "" [imap])
Definition at line 132 of file test_imap.cpp.
References NS1::begin(), NS1::end(), and iter::imap.
TEST_CASE() [7/13]
TEST_CASE ("imap: operator->" , "" [imap])
Definition at line 148 of file test_imap.cpp.
References NS1::begin(), and iter::imap.
TEST_CASE() [8/13]
TEST_CASE ("imap: empty sequence gives nothing" , "" [imap])
Definition at line 163 of file test_imap.cpp.
References NS1::begin(), NS1::end(), and iter::imap.
TEST_CASE() [9/13]
TEST_CASE ("imap: binds to lvalues, moves rvalues" , "" [imap])
Definition at line 169 of file test_imap.cpp.
References iter::imap.
TEST_CASE() [10/13]
TEST_CASE ("imap: doesn't move or copy elements of iterable" , "" [imap])
Definition at line 182 of file test_imap.cpp.
References itertest::SolidInt::getint(), i, and iter::imap.
TEST_CASE() [11/13]
TEST_CASE ("imap: postfix ++" , "" [imap])
Definition at line 190 of file test_imap.cpp.
References NS1::begin(), NS1::end(), and iter::imap.
TEST_CASE() [12/13]
TEST_CASE ("imap: iterator meets requirements" , "" [imap])
Definition at line 200 of file test_imap.cpp.
References NS1::begin(), and iter::imap.
TEST_CASE() [13/13]
TEST_CASE ("imap: has correct ctor and assign ops" , "" [imap])
Definition at line 208 of file test_imap.cpp.