CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_starmap.cpp File Reference
test_starmap.cpp File Reference
#include <starmap.hpp>
#include "helpers.hpp"
#include <iterator>
#include <list>
#include <string>
#include <vector>
#include "catch.hpp"
Functions
TEST_CASE ("starmap: works with function pointer and lambda", "[starmap]")
TEST_CASE ("starmap: works with pointer to member function", "[starmap]")
TEST_CASE ("starmap: vector of pairs const iteration", "[starmap][const]")
TEST_CASE ("starmap: vector of pairs const iterators can be compared to non-const " "iterators", "[starmap][const]")
TEST_CASE ("starmap: Works with different begin and end types", "[starmap]")
TEST_CASE ("starmap: tuple of tuples const iteration", "[starmap][const]")
TEST_CASE ("starmap: tuple of tuples const iterators can be compared to non-const " "iterator", "[starmap][const]")
TEST_CASE ("starmap: list of tuples", "[starmap]")
TEST_CASE ("starmap: tuple of tuples", "[starmap]")
TEST_CASE ("starmap: tuple of pairs", "[starmap]")
TEST_CASE ("starmap: moves rvalues, binds to lvalues", "[starmap]")
TEST_CASE ("starmap: iterator meets requirements", "[starmap]")
TEST_CASE ("starmap: tuple of tuples iterator meets requirements", "[starmap]")
Function Documentation
TEST_CASE() [1/13]
TEST_CASE ("starmap: works with function pointer and lambda" , "" [starmap])
Definition at line 40 of file test_starmap.cpp.
References NS1::begin(), NS1::end(), and iter::starmap.
TEST_CASE() [2/13]
TEST_CASE ("starmap: works with pointer to member function" , "" [starmap])
Definition at line 64 of file test_starmap.cpp.
References NS1::begin(), NS1::end(), and iter::starmap.
TEST_CASE() [3/13]
TEST_CASE ("starmap: vector of pairs const iteration" , "" [starmap][const ])
Definition at line 75 of file test_starmap.cpp.
References NS1::begin(), NS1::end(), and iter::starmap.
TEST_CASE() [4/13]
TEST_CASE ("starmap: vector of pairs const iterators can be compared to non-const " "iterators" , "" [starmap][const ])
Definition at line 85 of file test_starmap.cpp.
References NS1::begin(), NS1::end(), and iter::starmap.
TEST_CASE() [5/13]
TEST_CASE ("starmap: Works with different begin and end types" , "" [starmap])
Definition at line 95 of file test_starmap.cpp.
References i, and iter::starmap.
TEST_CASE() [6/13]
TEST_CASE ("starmap: tuple of tuples const iteration" , "" [starmap][const ])
Definition at line 104 of file test_starmap.cpp.
References NS1::begin(), NS1::end(), and iter::starmap.
TEST_CASE() [7/13]
TEST_CASE ("starmap: tuple of tuples const iterators can be compared to non-const " "iterator" , "" [starmap][const ])
Definition at line 111 of file test_starmap.cpp.
References NS1::begin(), NS1::end(), and iter::starmap.
TEST_CASE() [8/13]
TEST_CASE ("starmap: list of tuples" , "" [starmap])
Definition at line 122 of file test_starmap.cpp.
References NS1::begin(), NS1::end(), and iter::starmap.
TEST_CASE() [9/13]
TEST_CASE ("starmap: tuple of tuples" , "" [starmap])
Definition at line 134 of file test_starmap.cpp.
References NS1::begin(), NS1::end(), and iter::starmap.
TEST_CASE() [10/13]
TEST_CASE ("starmap: tuple of pairs" , "" [starmap])
Definition at line 151 of file test_starmap.cpp.
References NS1::begin(), NS1::end(), and iter::starmap.
TEST_CASE() [11/13]
TEST_CASE ("starmap: moves rvalues, binds to lvalues" , "" [starmap])
Definition at line 164 of file test_starmap.cpp.
References iter::starmap.
TEST_CASE() [12/13]
TEST_CASE ("starmap: iterator meets requirements" , "" [starmap])
Definition at line 172 of file test_starmap.cpp.
References NS1::begin(), and iter::starmap.
TEST_CASE() [13/13]
TEST_CASE ("starmap: tuple of tuples iterator meets requirements" , "" [starmap])
Definition at line 179 of file test_starmap.cpp.
References NS1::begin(), and iter::starmap.