CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_filter.cpp File Reference
test_filter.cpp File Reference
#include <filter.hpp>
#include "helpers.hpp"
#include <iterator>
#include <string>
#include <vector>
#include "catch.hpp"
Typedefs
using Vec = const std::vector< int >
template<typename T , typename U >
using ImpT = decltype(filter(std::declval< T >(), std::declval< U >()))
Functions
TEST_CASE ("filter: handles different callable types", "[filter]")
TEST_CASE ("filter: handles pointer to member", "[filter]")
TEST_CASE ("filter: const iteration", "[filter][const]")
TEST_CASE ("filter: const iterator can be compared to non-const iterator", "[filter][const]")
TEST_CASE ("filter: iterator with lambda can be assigned", "[filter]")
TEST_CASE ("filter: using identity", "[filter]")
TEST_CASE ("filter: skips null pointers", "[filter]")
TEST_CASE ("filter: binds to lvalues, moves rvales", "[filter]")
TEST_CASE ("filter: operator->", "[filter]")
TEST_CASE ("filter: all elements fail predicate", "[filter]")
TEST_CASE ("filter: doesn't move or copy elements of iterable", "[filter]")
TEST_CASE ("filter: works with pipe", "[filter]")
TEST_CASE ("filter: using identity and pipe", "[filter]")
TEST_CASE ("filter: Works with different begin and end types", "[filter]")
TEST_CASE ("filter: iterator meets requirements", "[filter]")
TEST_CASE ("filter: has correct ctor and assign ops", "[filter]")
Typedef Documentation
ImpT
template<typename T , typename U > using ImpT = decltype(filter(std::declval<T>(), std::declval<U>()))
Definition at line 196 of file test_filter.cpp.
Vec
using Vec = const std::vector<int>
Definition at line 13 of file test_filter.cpp.
Function Documentation
TEST_CASE() [1/16]
TEST_CASE ("filter: handles different callable types" , "" [filter])
Definition at line 33 of file test_filter.cpp.
References NS1::begin(), NS1::end(), iter::filter, and i.
TEST_CASE() [2/16]
TEST_CASE ("filter: handles pointer to member" , "" [filter])
Definition at line 56 of file test_filter.cpp.
References NS1::begin(), NS1::end(), and iter::filter.
TEST_CASE() [3/16]
TEST_CASE ("filter: const iteration" , "" [filter][const ])
Definition at line 74 of file test_filter.cpp.
References NS1::begin(), NS1::end(), and iter::filter.
TEST_CASE() [4/16]
TEST_CASE ("filter: const iterator can be compared to non-const iterator" , "" [filter][const ])
Definition at line 82 of file test_filter.cpp.
References NS1::begin(), NS1::end(), and iter::filter.
TEST_CASE() [5/16]
TEST_CASE ("filter: iterator with lambda can be assigned" , "" [filter])
Definition at line 89 of file test_filter.cpp.
References NS1::begin(), iter::filter, and i.
TEST_CASE() [6/16]
TEST_CASE ("filter: using identity" , "" [filter])
Definition at line 97 of file test_filter.cpp.
References NS1::begin(), NS1::end(), and iter::filter.
TEST_CASE() [7/16]
TEST_CASE ("filter: skips null pointers" , "" [filter])
Definition at line 106 of file test_filter.cpp.
References NS1::begin(), NS1::end(), and iter::filter.
TEST_CASE() [8/16]
TEST_CASE ("filter: binds to lvalues, moves rvales" , "" [filter])
Definition at line 117 of file test_filter.cpp.
References iter::filter.
TEST_CASE() [9/16]
TEST_CASE ("filter: operator->" , "" [filter])
Definition at line 141 of file test_filter.cpp.
References NS1::begin(), and iter::filter.
TEST_CASE() [10/16]
TEST_CASE ("filter: all elements fail predicate" , "" [filter])
Definition at line 148 of file test_filter.cpp.
References NS1::begin(), NS1::end(), and iter::filter.
TEST_CASE() [11/16]
TEST_CASE ("filter: doesn't move or copy elements of iterable" , "" [filter])
Definition at line 155 of file test_filter.cpp.
References iter::filter, itertest::SolidInt::getint(), and i.
TEST_CASE() [12/16]
TEST_CASE ("filter: works with pipe" , "" [filter])
Definition at line 163 of file test_filter.cpp.
References NS1::begin(), NS1::end(), and iter::filter.
TEST_CASE() [13/16]
TEST_CASE ("filter: using identity and pipe" , "" [filter])
Definition at line 172 of file test_filter.cpp.
References NS1::begin(), NS1::end(), and iter::filter.
TEST_CASE() [14/16]
TEST_CASE ("filter: Works with different begin and end types" , "" [filter])
Definition at line 181 of file test_filter.cpp.
References iter::filter.
TEST_CASE() [15/16]
TEST_CASE ("filter: iterator meets requirements" , "" [filter])
Definition at line 189 of file test_filter.cpp.
References NS1::begin(), and iter::filter.
TEST_CASE() [16/16]
TEST_CASE ("filter: has correct ctor and assign ops" , "" [filter])
Definition at line 197 of file test_filter.cpp.