CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_product.cpp File Reference
test_product.cpp File Reference
#include <product.hpp>
#include "helpers.hpp"
#include <iterator>
#include <string>
#include <vector>
#include "catch.hpp"
Macros
#define DEFINE_BASIC_ITERABLE_COPY_CTOR
#define DEFINE_BASIC_ITERABLE_CONST_BEGIN_AND_END
Typedefs
using Vec = const std::vector< int >
template<typename... Ts>
using ImpT = decltype(product(std::declval< Ts >()...))
Functions
TEST_CASE ("product: basic test, two sequences", "[product]")
TEST_CASE ("product: const iteration", "[product][const]")
TEST_CASE ("product: const iterators can be compared to non-const iterators", "[product][const]")
TEST_CASE ("product: two sequences where one has different begin and end", "[product]")
TEST_CASE ("product: three sequences", "[product]")
TEST_CASE ("product: with repeat", "[product]")
TEST_CASE ("product: empty when any iterable is empty", "[product]")
TEST_CASE ("product: single iterable", "[product]")
TEST_CASE ("product: no arguments gives one empty tuple", "[product")
TEST_CASE ("product: binds to lvalues and moves rvalues", "[product]")
TEST_CASE ("product: handles a lot of containers values", "[product]")
TEST_CASE ("product: doesn't move or copy elements of iterable", "[product]")
TEST_CASE ("product: iterator meets requirements", "[product]")
TEST_CASE ("product: has correct ctor and assign ops", "[product]")
Macro Definition Documentation
DEFINE_BASIC_ITERABLE_CONST_BEGIN_AND_END
#define DEFINE_BASIC_ITERABLE_CONST_BEGIN_AND_END
Definition at line 4 of file test_product.cpp.
DEFINE_BASIC_ITERABLE_COPY_CTOR
#define DEFINE_BASIC_ITERABLE_COPY_CTOR
Definition at line 3 of file test_product.cpp.
Typedef Documentation
ImpT
template<typename... Ts> using ImpT = decltype(product(std::declval<Ts>()...))
Definition at line 227 of file test_product.cpp.
Vec
using Vec = const std::vector<int>
Definition at line 16 of file test_product.cpp.
Function Documentation
TEST_CASE() [1/14]
TEST_CASE ("product: basic test, two sequences" , "" [product])
Definition at line 18 of file test_product.cpp.
References NS1::begin(), NS1::end(), and iter::product().
TEST_CASE() [2/14]
TEST_CASE ("product: const iteration" , "" [product][const ])
Definition at line 33 of file test_product.cpp.
References NS1::begin(), NS1::end(), and iter::product().
TEST_CASE() [3/14]
TEST_CASE ("product: const iterators can be compared to non-const iterators" , "" [product][const ])
Definition at line 48 of file test_product.cpp.
References NS1::begin(), NS1::end(), and iter::product().
TEST_CASE() [4/14]
TEST_CASE ("product: two sequences where one has different begin and end" , "" [product])
Definition at line 56 of file test_product.cpp.
References NS1::begin(), NS1::end(), and iter::product().
TEST_CASE() [5/14]
TEST_CASE ("product: three sequences" , "" [product])
Definition at line 72 of file test_product.cpp.
References NS1::begin(), NS1::end(), and iter::product().
TEST_CASE() [6/14]
TEST_CASE ("product: with repeat" , "" [product])
Definition at line 88 of file test_product.cpp.
References NS1::begin(), and NS1::end().
TEST_CASE() [7/14]
TEST_CASE ("product: empty when any iterable is empty" , "" [product])
Definition at line 127 of file test_product.cpp.
References NS1::begin(), NS1::end(), and iter::product().
TEST_CASE() [8/14]
TEST_CASE ("product: single iterable" , "" [product])
Definition at line 148 of file test_product.cpp.
References NS1::begin(), NS1::end(), and iter::product().
TEST_CASE() [9/14]
TEST_CASE ("product: no arguments gives one empty tuple" , "[product")
Definition at line 160 of file test_product.cpp.
References NS1::begin(), NS1::end(), and iter::product().
TEST_CASE() [10/14]
TEST_CASE ("product: binds to lvalues and moves rvalues" , "" [product])
Definition at line 169 of file test_product.cpp.
References iter::product().
TEST_CASE() [11/14]
TEST_CASE ("product: handles a lot of containers values" , "" [product])
Definition at line 207 of file test_product.cpp.
TEST_CASE() [12/14]
TEST_CASE ("product: doesn't move or copy elements of iterable" , "" [product])
Definition at line 213 of file test_product.cpp.
References iter::product().
TEST_CASE() [13/14]
TEST_CASE ("product: iterator meets requirements" , "" [product])
Definition at line 220 of file test_product.cpp.
References NS1::begin(), and iter::product().
TEST_CASE() [14/14]
TEST_CASE ("product: has correct ctor and assign ops" , "" [product])
Definition at line 228 of file test_product.cpp.