CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_accumulate.cpp File Reference
test_accumulate.cpp File Reference
#include <accumulate.hpp>
#include "helpers.hpp"
#include <iterator>
#include <string>
#include <vector>
#include "catch.hpp"
Classes
struct Integer
Typedefs
using Vec = const std::vector< int >
template<typename T >
using ImpT = decltype(accumulate(std::declval< T >()))
Functions
TEST_CASE ("Simple sum", "[accumulate]")
TEST_CASE ("accumulate: With subtraction lambda", "[accumulate]")
TEST_CASE ("accumulate: handles pointer to member function", "[accumulate]")
TEST_CASE ("accumulate: const iterators", "[accumulate][const]")
TEST_CASE ("accumulate: const iterators can be compared", "[accumulate][const]")
TEST_CASE ("accumulate: intermidate type need not be default constructible", "[accumulate]")
TEST_CASE ("accumulate: binds reference when it should", "[accumulate]")
TEST_CASE ("accumulate: moves rvalues when it should", "[accumulate]")
TEST_CASE ("accumulate: operator==", "[accumulate]")
TEST_CASE ("accumulate: postfix ++", "[accumulate]")
TEST_CASE ("accumulate: operator->", "[accumulate]")
TEST_CASE ("accumulate: iterator meets requirements", "[accumulate]")
TEST_CASE ("accumulate: Works with different begin and end types", "[accumulate]")
TEST_CASE ("accumulate: has correct ctor and assign ops", "[accumulate]")
Typedef Documentation
ImpT
template<typename T > using ImpT = decltype(accumulate(std::declval<T>()))
Definition at line 151 of file test_accumulate.cpp.
Vec
using Vec = const std::vector<int>
Definition at line 13 of file test_accumulate.cpp.
Function Documentation
TEST_CASE() [1/14]
TEST_CASE ("Simple sum" , "" [accumulate])
Definition at line 14 of file test_accumulate.cpp.
References iter::accumulate, NS1::begin(), and NS1::end().
TEST_CASE() [2/14]
TEST_CASE ("accumulate: With subtraction lambda" , "" [accumulate])
Definition at line 31 of file test_accumulate.cpp.
References iter::accumulate, NS1::begin(), and NS1::end().
TEST_CASE() [3/14]
TEST_CASE ("accumulate: handles pointer to member function" , "" [accumulate])
Definition at line 48 of file test_accumulate.cpp.
References iter::accumulate, NS1::begin(), and NS1::end().
TEST_CASE() [4/14]
TEST_CASE ("accumulate: const iterators" , "" [accumulate][const ])
Definition at line 57 of file test_accumulate.cpp.
References iter::accumulate, NS1::begin(), and NS1::end().
TEST_CASE() [5/14]
TEST_CASE ("accumulate: const iterators can be compared" , "" [accumulate][const ])
Definition at line 77 of file test_accumulate.cpp.
References iter::accumulate, NS1::begin(), and NS1::end().
TEST_CASE() [6/14]
TEST_CASE ("accumulate: intermidate type need not be default constructible" , "" [accumulate])
Definition at line 92 of file test_accumulate.cpp.
References iter::accumulate, and NS1::begin().
TEST_CASE() [7/14]
TEST_CASE ("accumulate: binds reference when it should" , "" [accumulate])
Definition at line 99 of file test_accumulate.cpp.
References iter::accumulate.
TEST_CASE() [8/14]
TEST_CASE ("accumulate: moves rvalues when it should" , "" [accumulate])
Definition at line 105 of file test_accumulate.cpp.
References iter::accumulate.
TEST_CASE() [9/14]
TEST_CASE ()
Definition at line 111 of file test_accumulate.cpp.
References iter::accumulate, NS1::begin(), and NS1::end().
TEST_CASE() [10/14]
TEST_CASE ("accumulate: postfix ++" , "" [accumulate])
Definition at line 117 of file test_accumulate.cpp.
References iter::accumulate, and NS1::begin().
TEST_CASE() [11/14]
TEST_CASE ("accumulate: operator->" , "" [accumulate])
Definition at line 125 of file test_accumulate.cpp.
References iter::accumulate, and NS1::begin().
TEST_CASE() [12/14]
TEST_CASE ("accumulate: iterator meets requirements" , "" [accumulate])
Definition at line 133 of file test_accumulate.cpp.
References iter::accumulate, NS1::begin(), and Integer::value.
TEST_CASE() [13/14]
TEST_CASE ("accumulate: Works with different begin and end types" , "" [accumulate])
Definition at line 141 of file test_accumulate.cpp.
References iter::accumulate.
TEST_CASE() [14/14]
TEST_CASE ("accumulate: has correct ctor and assign ops" , "" [accumulate])
Definition at line 152 of file test_accumulate.cpp.
References Integer::value.