CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_combinations_with_replacement.cpp File Reference
test_combinations_with_replacement.cpp File Reference
#include <combinations_with_replacement.hpp>
#include <iterator>
#include <set>
#include <string>
#include <vector>
#include "helpers.hpp"
#include "catch.hpp"
Macros
#define CHAR_RANGE_DEFAULT_CONSTRUCTIBLE
Typedefs
using CharCombSet = std::vector< std::vector< char > >
template<typename T >
using ImpT = decltype(combinations_with_replacement(std::declval< T >(), 1))
Functions
TEST_CASE ("combinations_with_replacement: Simple combination", "[combinations_with_replacement]")
TEST_CASE ("combinations_with_replacement: const iteration", "[combinations_with_replacement]")
TEST_CASE ("combinations_with_replacement: const iterators can be compared to " "non-const iterators", "[combinations_with_replacement][const]")
TEST_CASE ("combinations_with_replacement: Works with different begin and end types", "[combinations_with_replacement]")
TEST_CASE ("combinations_with_replacement: iterators can be compared", "[combinations_with_replacement]")
TEST_CASE ("combinations_with_replacement: big size is no problem", "[combinations_with_replacement]")
TEST_CASE ("combinations_with_replacement: 0 size is empty", "[combinations_with_replacement]")
TEST_CASE ("combinations_with_replacement: operator->", "[combinations_with_replacement]")
TEST_CASE ("combinations_with_replacement: binds to lvalues, moves rvalues", "[combinations_with_replacement]")
TEST_CASE ("combinations_with_replacement: " "doesn't move or copy elements of iterable", "[combinations_with_replacement]")
TEST_CASE ("combinations_with_replacement: iterator meets requirements", "[combinations_with_replacement]")
TEST_CASE ("combinations_with_replacement: has correct ctor and assign ops", "[combinations_with_replacement]")
Macro Definition Documentation
CHAR_RANGE_DEFAULT_CONSTRUCTIBLE
#define CHAR_RANGE_DEFAULT_CONSTRUCTIBLE
Definition at line 8 of file test_combinations_with_replacement.cpp.
Typedef Documentation
CharCombSet
using CharCombSet = std::vector<std::vector<char> >
Definition at line 15 of file test_combinations_with_replacement.cpp.
ImpT
template<typename T > using ImpT = decltype(combinations_with_replacement(std::declval<T>(), 1))
Definition at line 144 of file test_combinations_with_replacement.cpp.
Function Documentation
TEST_CASE() [1/12]
TEST_CASE ("combinations_with_replacement: Simple combination" , "" [combinations_with_replacement])
Definition at line 17 of file test_combinations_with_replacement.cpp.
References NS1::begin(), iter::combinations_with_replacement, and NS1::end().
TEST_CASE() [2/12]
TEST_CASE ("combinations_with_replacement: const iteration" , "" [combinations_with_replacement])
Definition at line 36 of file test_combinations_with_replacement.cpp.
References NS1::begin(), iter::combinations_with_replacement, and NS1::end().
TEST_CASE() [3/12]
TEST_CASE ("combinations_with_replacement: const iterators can be compared to " "non-const iterators" , "" [combinations_with_replacement][const ])
Definition at line 49 of file test_combinations_with_replacement.cpp.
References NS1::begin(), iter::combinations_with_replacement, and NS1::end().
TEST_CASE() [4/12]
TEST_CASE ("combinations_with_replacement: Works with different begin and end types" , "" [combinations_with_replacement])
Definition at line 59 of file test_combinations_with_replacement.cpp.
References NS1::begin(), iter::combinations_with_replacement, and NS1::end().
TEST_CASE() [5/12]
TEST_CASE ("combinations_with_replacement: iterators can be compared" , "" [combinations_with_replacement])
Definition at line 72 of file test_combinations_with_replacement.cpp.
References NS1::begin(), and iter::combinations_with_replacement.
TEST_CASE() [6/12]
TEST_CASE ("combinations_with_replacement: big size is no problem" , "" [combinations_with_replacement])
Definition at line 84 of file test_combinations_with_replacement.cpp.
References NS1::begin(), iter::combinations_with_replacement, and NS1::end().
TEST_CASE() [7/12]
TEST_CASE ("combinations_with_replacement: 0 size is empty" , "" [combinations_with_replacement])
Definition at line 96 of file test_combinations_with_replacement.cpp.
References NS1::begin(), iter::combinations_with_replacement, and NS1::end().
TEST_CASE() [8/12]
TEST_CASE ("combinations_with_replacement: operator->" , "" [combinations_with_replacement])
Definition at line 103 of file test_combinations_with_replacement.cpp.
References NS1::begin(), and iter::combinations_with_replacement.
TEST_CASE() [9/12]
TEST_CASE ("combinations_with_replacement: binds to lvalues, moves rvalues" , "" [combinations_with_replacement])
Definition at line 111 of file test_combinations_with_replacement.cpp.
References iter::combinations_with_replacement.
TEST_CASE() [10/12]
TEST_CASE ("combinations_with_replacement: " "doesn't move or copy elements of iterable" , "" [combinations_with_replacement])
Definition at line 124 of file test_combinations_with_replacement.cpp.
References iter::combinations_with_replacement, and i.
TEST_CASE() [11/12]
TEST_CASE ("combinations_with_replacement: iterator meets requirements" , "" [combinations_with_replacement])
Definition at line 134 of file test_combinations_with_replacement.cpp.
References NS1::begin(), and iter::combinations_with_replacement.
TEST_CASE() [12/12]
TEST_CASE ("combinations_with_replacement: has correct ctor and assign ops" , "" [combinations_with_replacement])
Definition at line 145 of file test_combinations_with_replacement.cpp.