CkPttnCpp: /media/lubuntu/USBDISK/github/ckpttncpp/third_party/cppitertools/test/test_takewhile.cpp File Reference
test_takewhile.cpp File Reference
#include <takewhile.hpp>
#include <array>
#include <string>
#include <utility>
#include <vector>
#include "catch.hpp"
#include "helpers.hpp"
Typedefs
using Vec = const std::vector< int >
template<typename T , typename U >
using ImpT = decltype(takewhile(std::declval< T >(), std::declval< U >()))
Functions
TEST_CASE ("takewhile: works with lambda, callable, and function pointer", "[takewhile]")
TEST_CASE ("takewhile: handles pointer to member", "[takewhile]")
TEST_CASE ("takewhile: supports const iteration", "[takewhile][const]")
TEST_CASE ("takewhile: const iterator and non-const iterator are comparable", "[takewhile][const]")
TEST_CASE ("takewhile: Works with different begin and end types", "[takewhile]")
TEST_CASE ("takewhile: identity", "[takewhile]")
TEST_CASE ("takewhile: everything passes predicate", "[takewhile]")
TEST_CASE ("takewhile: empty iterable is empty", "[takewhile]")
TEST_CASE ("takewhile: when first element fails predicate, it's empty" "[takewhile]")
TEST_CASE ("takewhile: moves rvalues, binds to lvalues", "[takewhile]")
TEST_CASE ("takewhile: with iterable doesn't move or copy elements", "[takewhile]")
TEST_CASE ("takewhile: iterator meets requirements", "[takewhile]")
TEST_CASE ("takewhile: has correct ctor and assign ops", "[takewhile]")
Typedef Documentation
ImpT
template<typename T , typename U > using ImpT = decltype(takewhile(std::declval<T>(), std::declval<U>()))
Definition at line 172 of file test_takewhile.cpp.
Vec
using Vec = const std::vector<int>
Definition at line 12 of file test_takewhile.cpp.
Function Documentation
TEST_CASE() [1/13]
TEST_CASE ("takewhile: works with lambda, callable , and function pointer" , "" [takewhile])
Definition at line 26 of file test_takewhile.cpp.
References NS1::begin(), NS1::end(), i, and iter::takewhile.
TEST_CASE() [2/13]
TEST_CASE ("takewhile: handles pointer to member" , "" [takewhile])
Definition at line 60 of file test_takewhile.cpp.
References NS1::begin(), NS1::end(), and iter::takewhile.
TEST_CASE() [3/13]
TEST_CASE ("takewhile: supports const iteration" , "" [takewhile][const ])
Definition at line 79 of file test_takewhile.cpp.
References NS1::begin(), NS1::end(), and iter::takewhile.
TEST_CASE() [4/13]
TEST_CASE ("takewhile: const iterator and non-const iterator are comparable" , "" [takewhile][const ])
Definition at line 87 of file test_takewhile.cpp.
References NS1::begin(), NS1::end(), and iter::takewhile.
TEST_CASE() [5/13]
TEST_CASE ("takewhile: Works with different begin and end types" , "" [takewhile])
Definition at line 94 of file test_takewhile.cpp.
References iter::takewhile.
TEST_CASE() [6/13]
TEST_CASE ("takewhile: identity" , "" [takewhile])
Definition at line 103 of file test_takewhile.cpp.
References NS1::begin(), NS1::end(), and iter::takewhile.
TEST_CASE() [7/13]
TEST_CASE ("takewhile: everything passes predicate" , "" [takewhile])
Definition at line 118 of file test_takewhile.cpp.
References NS1::begin(), NS1::end(), and iter::takewhile.
TEST_CASE() [8/13]
TEST_CASE ("takewhile: empty iterable is empty" , "" [takewhile])
Definition at line 125 of file test_takewhile.cpp.
References NS1::begin(), NS1::end(), and iter::takewhile.
TEST_CASE() [9/13]
TEST_CASE ("takewhile: when first element fails predicate, it 's empty" "" [takewhile])
Definition at line 131 of file test_takewhile.cpp.
References NS1::begin(), NS1::end(), and iter::takewhile.
TEST_CASE() [10/13]
TEST_CASE ("takewhile: moves rvalues, binds to lvalues" , "" [takewhile])
Definition at line 147 of file test_takewhile.cpp.
References iter::takewhile.
TEST_CASE() [11/13]
TEST_CASE ("takewhile: with iterable doesn't move or copy elements" , "" [takewhile])
Definition at line 156 of file test_takewhile.cpp.
References i, and iter::takewhile.
TEST_CASE() [12/13]
TEST_CASE ("takewhile: iterator meets requirements" , "" [takewhile])
Definition at line 165 of file test_takewhile.cpp.
References NS1::begin(), and iter::takewhile.
TEST_CASE() [13/13]
TEST_CASE ("takewhile: has correct ctor and assign ops" , "" [takewhile])
Definition at line 173 of file test_takewhile.cpp.